import type { PhonemeCategory, PhonemeData } from "@/types/phoneme";

export const PHONEMES: PhonemeData[] = [
  // ===== Vowels (16) =====
  {
    ipa: "/iː/",
    symbol: "iː",
    slug: "ee",
    name: "close front unrounded",
    category: "vowel",
    example: "see",
    chartWord: "green",
    chartImage: "green",
    chartIpa: "/gɹin/",
    chartIpaHighlight: "i",
    keywords: [
      { word: "see", ipa: "/siː/" },
      { word: "tree", ipa: "/triː/" },
      { word: "beach", ipa: "/biːtʃ/" },
      { word: "green", ipa: "/ɡriːn/" },
      { word: "eat", ipa: "/iːt/" },
      { word: "deep", ipa: "/diːp/" },
      { word: "sleep", ipa: "/sliːp/" },
      { word: "free", ipa: "/friː/" },
    ],
    difficulty: "easy",
    description: "舌尖抵下齿，舌前部尽量抬高，嘴角向两侧微展，发长音",
  },
  {
    ipa: "/ɪ/",
    symbol: "ɪ",
    slug: "ih",
    name: "near-close near-front unrounded",
    category: "vowel",
    example: "sit",
    chartWord: "pink",
    chartImage: "pink",
    chartIpa: "/pɪnk/",
    chartIpaHighlight: "ɪ",
    keywords: [
      { word: "sit", ipa: "/sɪt/" },
      { word: "big", ipa: "/bɪɡ/" },
      { word: "fish", ipa: "/fɪʃ/" },
      { word: "milk", ipa: "/mɪlk/" },
      { word: "ship", ipa: "/ʃɪp/" },
      { word: "trip", ipa: "/trɪp/" },
      { word: "quick", ipa: "/kwɪk/" },
      { word: "gift", ipa: "/ɡɪft/" },
    ],
    difficulty: "medium",
    description: "舌位比 /iː/ 略低略后，嘴巴微张，短促有力",
  },
  {
    ipa: "/eɪ/",
    symbol: "eɪ",
    slug: "ey",
    name: "diphthong",
    category: "vowel",
    example: "say",
    chartWord: "jade",
    chartImage: "jade",
    chartIpa: "/dʒeɪd/",
    chartIpaHighlight: "eɪ",
    keywords: [
      { word: "say", ipa: "/seɪ/" },
      { word: "play", ipa: "/pleɪ/" },
      { word: "rain", ipa: "/reɪn/" },
      { word: "make", ipa: "/meɪk/" },
      { word: "cake", ipa: "/keɪk/" },
      { word: "name", ipa: "/neɪm/" },
      { word: "late", ipa: "/leɪt/" },
      { word: "wait", ipa: "/weɪt/" },
    ],
    difficulty: "easy",
    description: "由 /e/ 滑向 /ɪ/，嘴巴由半开到接近合拢",
  },
  {
    ipa: "/e/",
    symbol: "e",
    slug: "eh",
    name: "open-mid front unrounded",
    category: "vowel",
    example: "bed",
    chartWord: "red",
    chartImage: "red",
    chartIpa: "/ɹɛd/",
    chartIpaHighlight: "ɛ",
    keywords: [
      { word: "bed", ipa: "/bed/" },
      { word: "red", ipa: "/red/" },
      { word: "head", ipa: "/hed/" },
      { word: "dress", ipa: "/dres/" },
      { word: "help", ipa: "/help/" },
      { word: "best", ipa: "/best/" },
      { word: "left", ipa: "/left/" },
      { word: "step", ipa: "/step/" },
    ],
    difficulty: "easy",
    description: "嘴巴半开，舌尖抵下齿，舌前部稍抬",
  },
  {
    ipa: "/æ/",
    symbol: "æ",
    slug: "ae",
    name: "near-open front unrounded",
    category: "vowel",
    example: "cat",
    chartWord: "sand",
    chartImage: "sand",
    chartIpa: "/sænd/",
    chartIpaHighlight: "æ",
    keywords: [
      { word: "cat", ipa: "/kæt/" },
      { word: "bad", ipa: "/bæd/" },
      { word: "hand", ipa: "/hænd/" },
      { word: "trap", ipa: "/træp/" },
      { word: "black", ipa: "/blæk/" },
      { word: "plan", ipa: "/plæn/" },
      { word: "fast", ipa: "/fæst/" },
      { word: "map", ipa: "/mæp/" },
    ],
    difficulty: "high",
    description: "嘴巴大张，舌尖抵下齿，舌前部低平，嘴角向两侧拉开",
  },
  {
    ipa: "/ɑː/",
    symbol: "ɑː",
    slug: "ah",
    name: "open back unrounded",
    category: "vowel",
    example: "car",
    chartWord: "coffee",
    chartImage: "coffee",
    chartIpa: "/ˈkɑ·fi/",
    chartIpaHighlight: "ɑ",
    keywords: [
      { word: "car", ipa: "/kɑːr/" },
      { word: "father", ipa: "/ˈfɑːðər/" },
      { word: "hot", ipa: "/hɑːt/" },
      { word: "stop", ipa: "/stɑːp/" },
      { word: "heart", ipa: "/hɑːrt/" },
      { word: "dark", ipa: "/dɑːrk/" },
      { word: "start", ipa: "/stɑːrt/" },
      { word: "park", ipa: "/pɑːrk/" },
    ],
    difficulty: "easy",
    description: "嘴巴张到最大，舌身后缩放平，发长音",
  },
  {
    ipa: "/ɔː/",
    symbol: "ɔː",
    slug: "aw",
    name: "open-mid back rounded",
    category: "vowel",
    example: "law",
    chartWord: "mauve",
    chartImage: "mauve",
    chartIpa: "/mɔv/",
    chartIpaHighlight: "ɔ",
    keywords: [
      { word: "law", ipa: "/lɔː/" },
      { word: "call", ipa: "/kɔːl/" },
      { word: "thought", ipa: "/θɔːt/" },
      { word: "walk", ipa: "/wɔːk/" },
      { word: "tall", ipa: "/tɔːl/" },
      { word: "fall", ipa: "/fɔːl/" },
      { word: "small", ipa: "/smɔːl/" },
      { word: "draw", ipa: "/drɔː/" },
    ],
    difficulty: "easy",
    description: "双唇收圆并略前突，舌身后缩，舌后部抬起",
  },
  {
    ipa: "/oʊ/",
    symbol: "oʊ",
    slug: "oh",
    name: "diphthong",
    category: "vowel",
    example: "go",
    chartWord: "gold",
    chartImage: "gold",
    chartIpa: "/goʊɫd/",
    chartIpaHighlight: "oʊ",
    keywords: [
      { word: "go", ipa: "/ɡoʊ/" },
      { word: "home", ipa: "/hoʊm/" },
      { word: "boat", ipa: "/boʊt/" },
      { word: "show", ipa: "/ʃoʊ/" },
      { word: "nose", ipa: "/noʊz/" },
      { word: "cold", ipa: "/koʊld/" },
      { word: "road", ipa: "/roʊd/" },
      { word: "slow", ipa: "/sloʊ/" },
    ],
    difficulty: "easy",
    description: "由 /o/ 滑向 /ʊ/，嘴巴由半圆逐渐收小",
  },
  {
    ipa: "/ʊ/",
    symbol: "ʊ",
    slug: "uh",
    name: "near-close near-back rounded",
    category: "vowel",
    example: "book",
    chartWord: "wood",
    chartImage: "wood",
    chartIpa: "/wʊd/",
    chartIpaHighlight: "ʊ",
    keywords: [
      { word: "book", ipa: "/bʊk/" },
      { word: "put", ipa: "/pʊt/" },
      { word: "good", ipa: "/ɡʊd/" },
      { word: "look", ipa: "/lʊk/" },
      { word: "cook", ipa: "/kʊk/" },
      { word: "push", ipa: "/pʊʃ/" },
      { word: "foot", ipa: "/fʊt/" },
      { word: "wood", ipa: "/wʊd/" },
    ],
    difficulty: "medium",
    description: "双唇略收圆，舌后部抬高，发音短促",
  },
  {
    ipa: "/uː/",
    symbol: "uː",
    slug: "oo",
    name: "close back rounded",
    category: "vowel",
    example: "too",
    chartWord: "blue",
    chartImage: "blue",
    chartIpa: "/bɫu/",
    chartIpaHighlight: "u",
    keywords: [
      { word: "too", ipa: "/tuː/" },
      { word: "blue", ipa: "/bluː/" },
      { word: "food", ipa: "/fuːd/" },
      { word: "moon", ipa: "/muːn/" },
      { word: "cool", ipa: "/kuːl/" },
      { word: "school", ipa: "/skuːl/" },
      { word: "true", ipa: "/truː/" },
      { word: "juice", ipa: "/dʒuːs/" },
    ],
    difficulty: "medium",
    description: "双唇收成小圆形并前突，舌后部尽量抬高，发长音",
  },
  {
    ipa: "/ʌ/",
    symbol: "ʌ",
    slug: "uh2",
    name: "open-mid back unrounded",
    category: "vowel",
    example: "cup",
    chartWord: "cup",
    chartImage: "cup",
    chartIpa: "/kʌp/",
    chartIpaHighlight: "ʌ",
    keywords: [
      { word: "cup", ipa: "/kʌp/" },
      { word: "but", ipa: "/bʌt/" },
      { word: "love", ipa: "/lʌv/" },
      { word: "run", ipa: "/rʌn/" },
      { word: "much", ipa: "/mʌtʃ/" },
      { word: "luck", ipa: "/lʌk/" },
      { word: "fun", ipa: "/fʌn/" },
      { word: "truck", ipa: "/trʌk/" },
    ],
    difficulty: "easy",
    description: "嘴巴半开，舌身放平略后缩，类似中文啊但更短",
  },
  {
    ipa: "/ə/",
    symbol: "ə",
    slug: "schwa",
    name: "mid central (schwa)",
    category: "vowel",
    example: "about",
    chartWord: "dust",
    chartImage: "dust",
    chartIpa: "/dəst/",
    chartIpaHighlight: "ə",
    keywords: [
      { word: "about", ipa: "/əˈbaʊt/" },
      { word: "banana", ipa: "/bəˈnænə/" },
      { word: "sofa", ipa: "/ˈsoʊfə/" },
      { word: "open", ipa: "/ˈoʊpən/" },
      { word: "problem", ipa: "/ˈprɑːbləm/" },
      { word: "again", ipa: "/əˈɡen/" },
      { word: "animal", ipa: "/ˈænɪml/" },
      { word: "camera", ipa: "/ˈkæmrə/" },
    ],
    difficulty: "easy",
    description: "嘴巴自然微张，全身放松，最轻最短的元音",
  },
  {
    ipa: "/ɜːr/",
    symbol: "ɜːr",
    slug: "er",
    name: "rhotacized mid central",
    category: "vowel",
    example: "bird",
    chartWord: "purple",
    chartImage: "purple",
    chartIpa: "/ˈpɝ·pəɫ/",
    chartIpaHighlight: "ɝ",
    keywords: [
      { word: "bird", ipa: "/bɜːrd/" },
      { word: "word", ipa: "/wɜːrd/" },
      { word: "nurse", ipa: "/nɜːrs/" },
      { word: "turn", ipa: "/tɜːrn/" },
      { word: "first", ipa: "/fɜːrst/" },
      { word: "learn", ipa: "/lɜːrn/" },
      { word: "earth", ipa: "/ɜːrθ/" },
      { word: "serve", ipa: "/sɜːrv/" },
    ],
    difficulty: "high",
    description: "嘴巴半开，舌身中部抬起，舌尖卷起指向硬腭",
  },
  {
    ipa: "/aɪ/",
    symbol: "aɪ",
    slug: "ai",
    name: "diphthong",
    category: "vowel",
    example: "my",
    chartWord: "lime",
    chartImage: "lime",
    chartIpa: "/ɫaɪm/",
    chartIpaHighlight: "aɪ",
    keywords: [
      { word: "my", ipa: "/maɪ/" },
      { word: "time", ipa: "/taɪm/" },
      { word: "fly", ipa: "/flaɪ/" },
      { word: "nice", ipa: "/naɪs/" },
      { word: "drive", ipa: "/draɪv/" },
      { word: "light", ipa: "/laɪt/" },
      { word: "smile", ipa: "/smaɪl/" },
      { word: "side", ipa: "/saɪd/" },
    ],
    difficulty: "easy",
    description: "由 /a/ 滑向 /ɪ/，嘴巴由大张到接近合拢",
  },
  {
    ipa: "/aʊ/",
    symbol: "aʊ",
    slug: "au",
    name: "diphthong",
    category: "vowel",
    example: "how",
    chartWord: "brown",
    chartImage: "brown",
    chartIpa: "/bɹaʊn/",
    chartIpaHighlight: "aʊ",
    keywords: [
      { word: "how", ipa: "/haʊ/" },
      { word: "out", ipa: "/aʊt/" },
      { word: "town", ipa: "/taʊn/" },
      { word: "house", ipa: "/haʊs/" },
      { word: "loud", ipa: "/laʊd/" },
      { word: "brown", ipa: "/braʊn/" },
      { word: "cloud", ipa: "/klaʊd/" },
      { word: "round", ipa: "/raʊnd/" },
    ],
    difficulty: "easy",
    description: "由 /a/ 滑向 /ʊ/，嘴巴由大张到收圆",
  },
  {
    ipa: "/ɔɪ/",
    symbol: "ɔɪ",
    slug: "oi",
    name: "diphthong",
    category: "vowel",
    example: "boy",
    chartWord: "turquoise",
    chartImage: "turquoise",
    chartIpa: "/ˈtɝ·kɔɪz/",
    chartIpaHighlight: "ɔɪ",
    keywords: [
      { word: "boy", ipa: "/bɔɪ/" },
      { word: "oil", ipa: "/ɔɪl/" },
      { word: "coin", ipa: "/kɔɪn/" },
      { word: "join", ipa: "/dʒɔɪn/" },
      { word: "noise", ipa: "/nɔɪz/" },
      { word: "voice", ipa: "/vɔɪs/" },
      { word: "enjoy", ipa: "/ɪnˈdʒɔɪ/" },
      { word: "point", ipa: "/pɔɪnt/" },
    ],
    difficulty: "easy",
    description: "由 /ɔ/ 滑向 /ɪ/，嘴巴由圆唇到扁平",
  },

  // ===== Consonants (24) =====
  {
    ipa: "/p/",
    symbol: "p",
    slug: "p",
    name: "voiceless bilabial plosive",
    category: "consonant",
    example: "pen",
    chartWord: "pig",
    chartImage: "pig",
    chartIpa: "/pɪɡ/",
    chartIpaHighlight: "p",
    keywords: [
      { word: "pen", ipa: "/pen/" },
      { word: "map", ipa: "/mæp/" },
      { word: "stop", ipa: "/stɑːp/" },
      { word: "paper", ipa: "/ˈpeɪpər/" },
      { word: "happy", ipa: "/ˈhæpi/" },
      { word: "people", ipa: "/ˈpiːpl/" },
      { word: "keep", ipa: "/kiːp/" },
      { word: "trip", ipa: "/trɪp/" },
    ],
    difficulty: "easy",
    description: "双唇紧闭后突然打开，送出气流，声带不振动",
  },
  {
    ipa: "/b/",
    symbol: "b",
    slug: "b",
    name: "voiced bilabial plosive",
    category: "consonant",
    example: "boy",
    chartWord: "bear",
    chartImage: "bear",
    chartIpa: "/bɛɹ/",
    chartIpaHighlight: "b",
    keywords: [
      { word: "boy", ipa: "/bɔɪ/" },
      { word: "baby", ipa: "/ˈbeɪbi/" },
      { word: "job", ipa: "/dʒɑːb/" },
      { word: "black", ipa: "/blæk/" },
      { word: "above", ipa: "/əˈbʌv/" },
      { word: "table", ipa: "/ˈteɪbl/" },
      { word: "club", ipa: "/klʌb/" },
      { word: "grab", ipa: "/ɡræb/" },
    ],
    difficulty: "easy",
    description: "双唇紧闭后突然打开，声带振动发出浊音",
  },
  {
    ipa: "/t/",
    symbol: "t",
    slug: "t",
    name: "voiceless alveolar plosive",
    category: "consonant",
    example: "ten",
    chartWord: "turtle",
    chartImage: "turtle",
    chartIpa: "/ˈtɝ·təɫ/",
    chartIpaHighlight: "t",
    keywords: [
      { word: "ten", ipa: "/ten/" },
      { word: "cat", ipa: "/kæt/" },
      { word: "water", ipa: "/ˈwɔːtər/" },
      { word: "take", ipa: "/teɪk/" },
      { word: "right", ipa: "/raɪt/" },
      { word: "better", ipa: "/ˈbetər/" },
      { word: "hot", ipa: "/hɑːt/" },
      { word: "start", ipa: "/stɑːrt/" },
    ],
    difficulty: "easy",
    description: "舌尖抵上齿龈后突然放开，送出气流，不振动声带",
  },
  {
    ipa: "/d/",
    symbol: "d",
    slug: "d",
    name: "voiced alveolar plosive",
    category: "consonant",
    example: "dog",
    chartWord: "dog",
    chartImage: "dog",
    chartIpa: "/dɔg/",
    chartIpaHighlight: "d",
    keywords: [
      { word: "dog", ipa: "/dɔːɡ/" },
      { word: "bad", ipa: "/bæd/" },
      { word: "daddy", ipa: "/ˈdædi/" },
      { word: "day", ipa: "/deɪ/" },
      { word: "middle", ipa: "/ˈmɪdl/" },
      { word: "under", ipa: "/ˈʌndər/" },
      { word: "head", ipa: "/hed/" },
      { word: "road", ipa: "/roʊd/" },
    ],
    difficulty: "easy",
    description: "舌尖抵上齿龈后突然放开，声带振动",
  },
  {
    ipa: "/k/",
    symbol: "k",
    slug: "k",
    name: "voiceless velar plosive",
    category: "consonant",
    example: "cat",
    chartWord: "cat",
    chartImage: "cat",
    chartIpa: "/kæt/",
    chartIpaHighlight: "k",
    keywords: [
      { word: "cat", ipa: "/kæt/" },
      { word: "black", ipa: "/blæk/" },
      { word: "school", ipa: "/skuːl/" },
      { word: "back", ipa: "/bæk/" },
      { word: "kitchen", ipa: "/ˈkɪtʃɪn/" },
      { word: "quick", ipa: "/kwɪk/" },
      { word: "cake", ipa: "/keɪk/" },
      { word: "music", ipa: "/ˈmjuːzɪk/" },
    ],
    difficulty: "easy",
    description: "舌后部抵软腭后突然放开，送出气流，不振动声带",
  },
  {
    ipa: "/ɡ/",
    symbol: "ɡ",
    slug: "g",
    name: "voiced velar plosive",
    category: "consonant",
    example: "go",
    chartWord: "goat",
    chartImage: "goat",
    chartIpa: "/goʊt/",
    chartIpaHighlight: "g",
    keywords: [
      { word: "go", ipa: "/ɡoʊ/" },
      { word: "big", ipa: "/bɪɡ/" },
      { word: "egg", ipa: "/eɡ/" },
      { word: "give", ipa: "/ɡɪv/" },
      { word: "again", ipa: "/əˈɡen/" },
      { word: "glass", ipa: "/ɡlæs/" },
      { word: "dog", ipa: "/dɔːɡ/" },
      { word: "green", ipa: "/ɡriːn/" },
    ],
    difficulty: "easy",
    description: "舌后部抵软腭后突然放开，声带振动",
  },
  {
    ipa: "/f/",
    symbol: "f",
    slug: "f",
    name: "voiceless labiodental fricative",
    category: "consonant",
    example: "fish",
    chartWord: "frog",
    chartImage: "frog",
    chartIpa: "/fɹɑg/",
    chartIpaHighlight: "f",
    keywords: [
      { word: "fish", ipa: "/fɪʃ/" },
      { word: "off", ipa: "/ɔːf/" },
      { word: "phone", ipa: "/foʊn/" },
      { word: "life", ipa: "/laɪf/" },
      { word: "coffee", ipa: "/ˈkɔːfi/" },
      { word: "leaf", ipa: "/liːf/" },
      { word: "safe", ipa: "/seɪf/" },
      { word: "half", ipa: "/hæf/" },
    ],
    difficulty: "easy",
    description: "上齿轻触下唇，气流从缝隙中挤出，不振动声带",
  },
  {
    ipa: "/v/",
    symbol: "v",
    slug: "v",
    name: "voiced labiodental fricative",
    category: "consonant",
    example: "very",
    chartWord: "beaver",
    chartImage: "beaver",
    chartIpa: "/ˈbi·vɝ/",
    chartIpaHighlight: "v",
    keywords: [
      { word: "very", ipa: "/ˈveri/" },
      { word: "have", ipa: "/həv/" },
      { word: "love", ipa: "/lʌv/" },
      { word: "voice", ipa: "/vɔɪs/" },
      { word: "seven", ipa: "/ˈsevn/" },
      { word: "never", ipa: "/ˈnevər/" },
      { word: "drive", ipa: "/draɪv/" },
      { word: "movie", ipa: "/ˈmuːvi/" },
    ],
    difficulty: "high",
    description: "上齿轻触下唇，气流从缝隙中挤出，同时振动声带",
  },
  {
    ipa: "/θ/",
    symbol: "θ",
    slug: "th",
    name: "voiceless dental fricative",
    category: "consonant",
    example: "think",
    chartWord: "panther",
    chartImage: "panther",
    chartIpa: "/ˈpæn·θɝ/",
    chartIpaHighlight: "θ",
    keywords: [
      { word: "think", ipa: "/θɪŋk/" },
      { word: "three", ipa: "/θriː/" },
      { word: "bath", ipa: "/bæθ/" },
      { word: "month", ipa: "/mʌnθ/" },
      { word: "teeth", ipa: "/tiːθ/" },
      { word: "north", ipa: "/nɔːrθ/" },
      { word: "health", ipa: "/helθ/" },
      { word: "earth", ipa: "/ɜːrθ/" },
    ],
    difficulty: "high",
    description: "舌尖轻触上齿背，气流从舌齿间挤出，不振动声带",
  },
  {
    ipa: "/ð/",
    symbol: "ð",
    slug: "dh",
    name: "voiced dental fricative",
    category: "consonant",
    example: "this",
    chartWord: "feather",
    chartImage: "feather",
    chartIpa: "/ˈfɛð·ɝ/",
    chartIpaHighlight: "ð",
    keywords: [
      { word: "this", ipa: "/ðɪs/" },
      { word: "that", ipa: "/ðæt/" },
      { word: "other", ipa: "/ˈʌðər/" },
      { word: "mother", ipa: "/ˈmʌðər/" },
      { word: "weather", ipa: "/ˈweðər/" },
      { word: "together", ipa: "/təˈɡeðər/" },
      { word: "brother", ipa: "/ˈbrʌðər/" },
      { word: "smooth", ipa: "/smuːð/" },
    ],
    difficulty: "high",
    description: "舌尖轻触上齿背，气流从舌齿间挤出，同时振动声带",
  },
  {
    ipa: "/s/",
    symbol: "s",
    slug: "s",
    name: "voiceless alveolar fricative",
    category: "consonant",
    example: "sun",
    chartWord: "snake",
    chartImage: "snake",
    chartIpa: "/sneɪk/",
    chartIpaHighlight: "s",
    keywords: [
      { word: "sun", ipa: "/sʌn/" },
      { word: "miss", ipa: "/mɪs/" },
      { word: "city", ipa: "/ˈsɪti/" },
      { word: "face", ipa: "/feɪs/" },
      { word: "nice", ipa: "/naɪs/" },
      { word: "bus", ipa: "/bʌs/" },
      { word: "class", ipa: "/klæs/" },
      { word: "place", ipa: "/pleɪs/" },
    ],
    difficulty: "easy",
    description: "舌尖靠近上齿龈但不接触，气流从窄缝中挤出",
  },
  {
    ipa: "/z/",
    symbol: "z",
    slug: "z",
    name: "voiced alveolar fricative",
    category: "consonant",
    example: "zoo",
    chartWord: "zebra",
    chartImage: "zebra",
    chartIpa: "/ˈzi·bɹə/",
    chartIpaHighlight: "z",
    keywords: [
      { word: "zoo", ipa: "/zuː/" },
      { word: "is", ipa: "/ɪz/" },
      { word: "buzz", ipa: "/bʌz/" },
      { word: "easy", ipa: "/ˈiːzi/" },
      { word: "nose", ipa: "/noʊz/" },
      { word: "music", ipa: "/ˈmjuːzɪk/" },
      { word: "please", ipa: "/pliːz/" },
      { word: "reason", ipa: "/ˈriːzn/" },
    ],
    difficulty: "easy",
    description: "舌尖靠近上齿龈，气流从窄缝中挤出，声带振动",
  },
  {
    ipa: "/ʃ/",
    symbol: "ʃ",
    slug: "sh",
    name: "voiceless postalveolar fricative",
    category: "consonant",
    example: "she",
    chartWord: "sheep",
    chartImage: "sheep",
    chartIpa: "/ʃip/",
    chartIpaHighlight: "ʃ",
    keywords: [
      { word: "she", ipa: "/ʃi/" },
      { word: "fish", ipa: "/fɪʃ/" },
      { word: "nation", ipa: "/ˈneɪʃn/" },
      { word: "wash", ipa: "/wɑːʃ/" },
      { word: "shop", ipa: "/ʃɑːp/" },
      { word: "sure", ipa: "/ʃʊr/" },
      { word: "fresh", ipa: "/freʃ/" },
      { word: "ocean", ipa: "/ˈoʊʃn/" },
    ],
    difficulty: "easy",
    description: "舌面前部抬向硬腭，双唇略前突，气流从宽缝中挤出",
  },
  {
    ipa: "/ʒ/",
    symbol: "ʒ",
    slug: "zh",
    name: "voiced postalveolar fricative",
    category: "consonant",
    example: "vision",
    chartWord: "television",
    chartImage: "television",
    chartIpa: "/ˈtɛɫ·əˌvɪʒ·ən/",
    chartIpaHighlight: "ʒ",
    keywords: [
      { word: "vision", ipa: "/ˈvɪʒn/" },
      { word: "measure", ipa: "/ˈmeʒər/" },
      { word: "beige", ipa: "/beɪʒ/" },
      { word: "garage", ipa: "/ɡəˈrɑːʒ/" },
      { word: "pleasure", ipa: "/ˈpleʒər/" },
      { word: "usual", ipa: "/ˈjuːʒuəl/" },
      { word: "treasure", ipa: "/ˈtreʒər/" },
      { word: "leisure", ipa: "/ˈliːʒər/" },
    ],
    difficulty: "high",
    description: "舌面前部抬向硬腭，双唇略前突，同时振动声带",
  },
  {
    ipa: "/tʃ/",
    symbol: "tʃ",
    slug: "ch",
    name: "voiceless postalveolar affricate",
    category: "consonant",
    example: "cheese",
    chartWord: "chicken",
    chartImage: "chicken",
    chartIpa: "/ˈtʃɪk·ɪn/",
    chartIpaHighlight: "tʃ",
    keywords: [
      { word: "cheese", ipa: "/tʃiːz/" },
      { word: "watch", ipa: "/wɑːtʃ/" },
      { word: "nature", ipa: "/ˈneɪtʃər/" },
      { word: "church", ipa: "/tʃɜːrtʃ/" },
      { word: "lunch", ipa: "/lʌntʃ/" },
      { word: "teacher", ipa: "/ˈtiːtʃər/" },
      { word: "beach", ipa: "/biːtʃ/" },
      { word: "catch", ipa: "/kætʃ/" },
    ],
    difficulty: "medium",
    description: "舌尖抵上齿龈后部，先阻塞再释放为摩擦音，不振动声带",
  },
  {
    ipa: "/dʒ/",
    symbol: "dʒ",
    slug: "dj",
    name: "voiced postalveolar affricate",
    category: "consonant",
    example: "job",
    chartWord: "giraffe",
    chartImage: "giraffe",
    chartIpa: "/dʒəˈɹæf/",
    chartIpaHighlight: "dʒ",
    keywords: [
      { word: "job", ipa: "/dʒɑːb/" },
      { word: "age", ipa: "/eɪdʒ/" },
      { word: "bridge", ipa: "/brɪdʒ/" },
      { word: "judge", ipa: "/dʒʌdʒ/" },
      { word: "orange", ipa: "/ˈɔːrɪndʒ/" },
      { word: "magic", ipa: "/ˈmædʒɪk/" },
      { word: "strange", ipa: "/streɪndʒ/" },
      { word: "gentle", ipa: "/ˈdʒentl/" },
    ],
    difficulty: "medium",
    description: "舌尖抵上齿龈后部，先阻塞再释放为摩擦音，声带振动",
  },
  {
    ipa: "/m/",
    symbol: "m",
    slug: "m",
    name: "bilabial nasal",
    category: "consonant",
    example: "man",
    chartWord: "mouse",
    chartImage: "mouse",
    chartIpa: "/maʊs/",
    chartIpaHighlight: "m",
    keywords: [
      { word: "man", ipa: "/mæn/" },
      { word: "him", ipa: "/hɪm/" },
      { word: "summer", ipa: "/ˈsʌmər/" },
      { word: "make", ipa: "/meɪk/" },
      { word: "room", ipa: "/ruːm/" },
      { word: "dream", ipa: "/driːm/" },
      { word: "time", ipa: "/taɪm/" },
      { word: "swim", ipa: "/swɪm/" },
    ],
    difficulty: "easy",
    description: "双唇紧闭，气流从鼻腔出来，声带振动",
  },
  {
    ipa: "/n/",
    symbol: "n",
    slug: "n",
    name: "alveolar nasal",
    category: "consonant",
    example: "no",
    chartWord: "dinosaur",
    chartImage: "dinosaur",
    chartIpa: "/ˈdɑɪ·nəˌsɔɹ/",
    chartIpaHighlight: "n",
    keywords: [
      { word: "no", ipa: "/noʊ/" },
      { word: "sun", ipa: "/sʌn/" },
      { word: "dinner", ipa: "/ˈdɪnər/" },
      { word: "nice", ipa: "/naɪs/" },
      { word: "rain", ipa: "/reɪn/" },
      { word: "funny", ipa: "/ˈfʌni/" },
      { word: "clean", ipa: "/kliːn/" },
      { word: "noon", ipa: "/nuːn/" },
    ],
    difficulty: "easy",
    description: "舌尖抵上齿龈，气流从鼻腔出来，声带振动",
  },
  {
    ipa: "/ŋ/",
    symbol: "ŋ",
    slug: "ng",
    name: "velar nasal",
    category: "consonant",
    example: "sing",
    chartWord: "penguin",
    chartImage: "penguin",
    chartIpa: "/ˈpɛŋ·gwən/",
    chartIpaHighlight: "ŋ",
    keywords: [
      { word: "sing", ipa: "/sɪŋ/" },
      { word: "ring", ipa: "/rɪŋ/" },
      { word: "think", ipa: "/θɪŋk/" },
      { word: "long", ipa: "/lɔːŋ/" },
      { word: "young", ipa: "/jʌŋ/" },
      { word: "wrong", ipa: "/rɔːŋ/" },
      { word: "strong", ipa: "/strɔːŋ/" },
      { word: "king", ipa: "/kɪŋ/" },
    ],
    difficulty: "medium",
    description: "舌后部抵软腭，气流从鼻腔出来，声带振动",
  },
  {
    ipa: "/l/",
    symbol: "l",
    slug: "l",
    name: "alveolar lateral approximant",
    category: "consonant",
    example: "leg",
    chartWord: "lion",
    chartImage: "lion",
    chartIpa: "/ˈɫɑɪ·ən/",
    chartIpaHighlight: "ɫ",
    keywords: [
      { word: "leg", ipa: "/leɡ/" },
      { word: "hill", ipa: "/hɪl/" },
      { word: "little", ipa: "/ˈlɪtl/" },
      { word: "life", ipa: "/laɪf/" },
      { word: "world", ipa: "/wɜːrld/" },
      { word: "full", ipa: "/fʊl/" },
      { word: "smile", ipa: "/smaɪl/" },
      { word: "cool", ipa: "/kuːl/" },
    ],
    difficulty: "high",
    description: "舌尖抵上齿龈，气流从舌两侧通过，声带振动",
  },
  {
    ipa: "/r/",
    symbol: "r",
    slug: "r",
    name: "alveolar approximant",
    category: "consonant",
    example: "red",
    chartWord: "rabbit",
    chartImage: "rabbit",
    chartIpa: "/ˈɹæb·ɪt/",
    chartIpaHighlight: "ɹ",
    keywords: [
      { word: "red", ipa: "/red/" },
      { word: "car", ipa: "/kɑːr/" },
      { word: "sorry", ipa: "/ˈsɑːri/" },
      { word: "right", ipa: "/raɪt/" },
      { word: "green", ipa: "/ɡriːn/" },
      { word: "every", ipa: "/ˈevri/" },
      { word: "street", ipa: "/striːt/" },
      { word: "price", ipa: "/praɪs/" },
    ],
    difficulty: "high",
    description: "舌尖卷起指向硬腭但不接触，双唇略收圆，声带振动",
  },
  {
    ipa: "/w/",
    symbol: "w",
    slug: "w",
    name: "labial-velar approximant",
    category: "consonant",
    example: "we",
    chartWord: "wolf",
    chartImage: "wolf",
    chartIpa: "/wʊɫf/",
    chartIpaHighlight: "w",
    keywords: [
      { word: "we", ipa: "/wi/" },
      { word: "away", ipa: "/əˈweɪ/" },
      { word: "quick", ipa: "/kwɪk/" },
      { word: "water", ipa: "/ˈwɔːtər/" },
      { word: "want", ipa: "/wɑːnt/" },
      { word: "sweet", ipa: "/swiːt/" },
      { word: "wide", ipa: "/waɪd/" },
      { word: "warm", ipa: "/wɔːrm/" },
    ],
    difficulty: "easy",
    description: "双唇收成小圆形，舌后部抬高，然后迅速滑向后续元音",
  },
  {
    ipa: "/j/",
    symbol: "j",
    slug: "y",
    name: "palatal approximant",
    category: "consonant",
    example: "yes",
    chartWord: "yak",
    chartImage: "yak",
    chartIpa: "/jæk/",
    chartIpaHighlight: "j",
    keywords: [
      { word: "yes", ipa: "/jes/" },
      { word: "you", ipa: "/juː/" },
      { word: "music", ipa: "/ˈmjuːzɪk/" },
      { word: "year", ipa: "/jɪr/" },
      { word: "young", ipa: "/jʌŋ/" },
      { word: "yellow", ipa: "/ˈjeloʊ/" },
      { word: "use", ipa: "/juːz/" },
      { word: "view", ipa: "/vjuː/" },
    ],
    difficulty: "easy",
    description: "舌前部抬向硬腭，然后迅速滑向后续元音，类似中文一的起始",
  },
  {
    ipa: "/h/",
    symbol: "h",
    slug: "h",
    name: "voiceless glottal fricative",
    category: "consonant",
    example: "he",
    chartWord: "horse",
    chartImage: "horse",
    chartIpa: "/hɔɹs/",
    chartIpaHighlight: "h",
    keywords: [
      { word: "he", ipa: "/hi/" },
      { word: "hello", ipa: "/həˈloʊ/" },
      { word: "behind", ipa: "/bɪˈhaɪnd/" },
      { word: "house", ipa: "/haʊs/" },
      { word: "happy", ipa: "/ˈhæpi/" },
      { word: "ahead", ipa: "/əˈhed/" },
      { word: "hand", ipa: "/hænd/" },
      { word: "hope", ipa: "/hoʊp/" },
    ],
    difficulty: "easy",
    description: "口腔自然张开，气流从声门中轻轻送出，像呵气",
  },
];

export function getPhonemeBySlug(slug: string): PhonemeData | undefined {
  return PHONEMES.find((p) => p.slug === slug);
}

export function getPhonemesByCategory(
  category: PhonemeCategory,
): PhonemeData[] {
  return PHONEMES.filter((p) => p.category === category);
}

export function getAllSlugs(): string[] {
  return PHONEMES.map((p) => p.slug);
}
