import type { KeywordEntry } from "@/types/phoneme";

/**
 * Extended word pool per phoneme slug.
 * These supplement the 8 static keywords in phoneme-data.ts.
 * IPA aligned to 欧陆词典美式音标 conventions.
 */
export const WORD_BANK: Record<string, KeywordEntry[]> = {
  // ===== Vowels =====

  // /iː/ — close front unrounded
  ee: [
    { word: "feel", ipa: "/fiːl/" },
    { word: "meet", ipa: "/miːt/" },
    { word: "clean", ipa: "/kliːn/" },
    { word: "team", ipa: "/tiːm/" },
    { word: "read", ipa: "/riːd/" },
    { word: "keep", ipa: "/kiːp/" },
    { word: "need", ipa: "/niːd/" },
    { word: "week", ipa: "/wiːk/" },
    { word: "speed", ipa: "/spiːd/" },
    { word: "cream", ipa: "/kriːm/" },
    { word: "sweet", ipa: "/swiːt/" },
    { word: "freeze", ipa: "/friːz/" },
    { word: "east", ipa: "/iːst/" },
    { word: "dream", ipa: "/driːm/" },
    { word: "leave", ipa: "/liːv/" },
    { word: "breathe", ipa: "/briːð/" },
  ],

  // /ɪ/ — near-close near-front unrounded
  ih: [
    { word: "swim", ipa: "/swɪm/" },
    { word: "thin", ipa: "/θɪn/" },
    { word: "trick", ipa: "/trɪk/" },
    { word: "skip", ipa: "/skɪp/" },
    { word: "fill", ipa: "/fɪl/" },
    { word: "stick", ipa: "/stɪk/" },
    { word: "click", ipa: "/klɪk/" },
    { word: "drink", ipa: "/drɪŋk/" },
    { word: "wish", ipa: "/wɪʃ/" },
    { word: "print", ipa: "/prɪnt/" },
    { word: "grin", ipa: "/ɡrɪn/" },
    { word: "brick", ipa: "/brɪk/" },
    { word: "list", ipa: "/lɪst/" },
    { word: "dinner", ipa: "/ˈdɪnər/" },
    { word: "picture", ipa: "/ˈpɪktʃər/" },
    { word: "busy", ipa: "/ˈbɪzi/" },
  ],

  // /eɪ/ — diphthong
  ey: [
    { word: "face", ipa: "/feɪs/" },
    { word: "take", ipa: "/teɪk/" },
    { word: "safe", ipa: "/seɪf/" },
    { word: "shape", ipa: "/ʃeɪp/" },
    { word: "break", ipa: "/breɪk/" },
    { word: "place", ipa: "/pleɪs/" },
    { word: "train", ipa: "/treɪn/" },
    { word: "taste", ipa: "/teɪst/" },
    { word: "blame", ipa: "/bleɪm/" },
    { word: "grade", ipa: "/ɡreɪd/" },
    { word: "flame", ipa: "/fleɪm/" },
    { word: "chase", ipa: "/tʃeɪs/" },
    { word: "game", ipa: "/ɡeɪm/" },
    { word: "awake", ipa: "/əˈweɪk/" },
    { word: "paper", ipa: "/ˈpeɪpər/" },
    { word: "escape", ipa: "/ɪˈskeɪp/" },
  ],

  // /e/ — open-mid front unrounded
  eh: [
    { word: "ten", ipa: "/ten/" },
    { word: "check", ipa: "/tʃek/" },
    { word: "spend", ipa: "/spend/" },
    { word: "fresh", ipa: "/freʃ/" },
    { word: "test", ipa: "/test/" },
    { word: "desk", ipa: "/desk/" },
    { word: "neck", ipa: "/nek/" },
    { word: "next", ipa: "/nekst/" },
    { word: "bread", ipa: "/bred/" },
    { word: "spell", ipa: "/spel/" },
    { word: "press", ipa: "/pres/" },
    { word: "blend", ipa: "/blend/" },
    { word: "end", ipa: "/end/" },
    { word: "friend", ipa: "/frend/" },
    { word: "every", ipa: "/ˈevri/" },
    { word: "heavy", ipa: "/ˈhevi/" },
  ],

  // /æ/ — near-open front unrounded
  ae: [
    { word: "back", ipa: "/bæk/" },
    { word: "glass", ipa: "/ɡlæs/" },
    { word: "match", ipa: "/mætʃ/" },
    { word: "crash", ipa: "/kræʃ/" },
    { word: "grab", ipa: "/ɡræb/" },
    { word: "stamp", ipa: "/stæmp/" },
    { word: "flag", ipa: "/flæɡ/" },
    { word: "snap", ipa: "/snæp/" },
    { word: "track", ipa: "/træk/" },
    { word: "clap", ipa: "/klæp/" },
    { word: "math", ipa: "/mæθ/" },
    { word: "ranch", ipa: "/ræntʃ/" },
    { word: "apple", ipa: "/ˈæpəl/" },
    { word: "angry", ipa: "/ˈæŋɡri/" },
    { word: "family", ipa: "/ˈfæməli/" },
    { word: "travel", ipa: "/ˈtrævəl/" },
  ],

  // /ɑː/ — open back unrounded
  ah: [
    { word: "rock", ipa: "/rɑːk/" },
    { word: "box", ipa: "/bɑːks/" },
    { word: "drop", ipa: "/drɑːp/" },
    { word: "clock", ipa: "/klɑːk/" },
    { word: "shop", ipa: "/ʃɑːp/" },
    { word: "lock", ipa: "/lɑːk/" },
    { word: "calm", ipa: "/kɑːm/" },
    { word: "palm", ipa: "/pɑːm/" },
    { word: "job", ipa: "/dʒɑːb/" },
    { word: "cop", ipa: "/kɑːp/" },
    { word: "dot", ipa: "/dɑːt/" },
    { word: "stock", ipa: "/stɑːk/" },
    { word: "lot", ipa: "/lɑːt/" },
    { word: "possible", ipa: "/ˈpɑːsəbəl/" },
    { word: "office", ipa: "/ˈɑːfɪs/" },
    { word: "body", ipa: "/ˈbɑːdi/" },
  ],

  // /ɔː/ — open-mid back rounded
  aw: [
    { word: "door", ipa: "/dɔːr/" },
    { word: "more", ipa: "/mɔːr/" },
    { word: "sort", ipa: "/sɔːrt/" },
    { word: "born", ipa: "/bɔːrn/" },
    { word: "cause", ipa: "/kɔːz/" },
    { word: "sauce", ipa: "/sɔːs/" },
    { word: "force", ipa: "/fɔːrs/" },
    { word: "sport", ipa: "/spɔːrt/" },
    { word: "floor", ipa: "/flɔːr/" },
    { word: "storm", ipa: "/stɔːrm/" },
    { word: "warm", ipa: "/wɔːrm/" },
    { word: "horse", ipa: "/hɔːrs/" },
    { word: "talk", ipa: "/tɔːk/" },
    { word: "coffee", ipa: "/ˈkɔːfi/" },
    { word: "bought", ipa: "/bɔːt/" },
    { word: "daughter", ipa: "/ˈdɔːtər/" },
  ],

  // /oʊ/ — diphthong
  oh: [
    { word: "stone", ipa: "/stoʊn/" },
    { word: "phone", ipa: "/foʊn/" },
    { word: "close", ipa: "/kloʊz/" },
    { word: "smoke", ipa: "/smoʊk/" },
    { word: "grow", ipa: "/ɡroʊ/" },
    { word: "flow", ipa: "/floʊ/" },
    { word: "bone", ipa: "/boʊn/" },
    { word: "code", ipa: "/koʊd/" },
    { word: "note", ipa: "/noʊt/" },
    { word: "hope", ipa: "/hoʊp/" },
    { word: "throw", ipa: "/θroʊ/" },
    { word: "globe", ipa: "/ɡloʊb/" },
    { word: "own", ipa: "/oʊn/" },
    { word: "alone", ipa: "/əˈloʊn/" },
    { word: "open", ipa: "/ˈoʊpən/" },
    { word: "coat", ipa: "/koʊt/" },
  ],

  // /ʊ/ — near-close near-back rounded
  uh: [
    { word: "pull", ipa: "/pʊl/" },
    { word: "full", ipa: "/fʊl/" },
    { word: "bull", ipa: "/bʊl/" },
    { word: "wolf", ipa: "/wʊlf/" },
    { word: "bush", ipa: "/bʊʃ/" },
    { word: "hook", ipa: "/hʊk/" },
    { word: "stood", ipa: "/stʊd/" },
    { word: "could", ipa: "/kʊd/" },
    { word: "would", ipa: "/wʊd/" },
    { word: "should", ipa: "/ʃʊd/" },
    { word: "sugar", ipa: "/ˈʃʊɡər/" },
    { word: "wool", ipa: "/wʊl/" },
    { word: "took", ipa: "/tʊk/" },
    { word: "cushion", ipa: "/ˈkʊʃən/" },
    { word: "woman", ipa: "/ˈwʊmən/" },
    { word: "pudding", ipa: "/ˈpʊdɪŋ/" },
  ],

  // /uː/ — close back rounded
  oo: [
    { word: "room", ipa: "/ruːm/" },
    { word: "choose", ipa: "/tʃuːz/" },
    { word: "pool", ipa: "/puːl/" },
    { word: "prove", ipa: "/pruːv/" },
    { word: "fruit", ipa: "/fruːt/" },
    { word: "smooth", ipa: "/smuːð/" },
    { word: "group", ipa: "/ɡruːp/" },
    { word: "loose", ipa: "/luːs/" },
    { word: "rule", ipa: "/ruːl/" },
    { word: "shoot", ipa: "/ʃuːt/" },
    { word: "boot", ipa: "/buːt/" },
    { word: "goose", ipa: "/ɡuːs/" },
    { word: "move", ipa: "/muːv/" },
    { word: "soon", ipa: "/suːn/" },
    { word: "student", ipa: "/ˈstuːdənt/" },
    { word: "tooth", ipa: "/tuːθ/" },
  ],

  // /ʌ/ — open-mid back unrounded
  uh2: [
    { word: "dust", ipa: "/dʌst/" },
    { word: "jump", ipa: "/dʒʌmp/" },
    { word: "shut", ipa: "/ʃʌt/" },
    { word: "crush", ipa: "/krʌʃ/" },
    { word: "stuff", ipa: "/stʌf/" },
    { word: "club", ipa: "/klʌb/" },
    { word: "drum", ipa: "/drʌm/" },
    { word: "stuck", ipa: "/stʌk/" },
    { word: "brush", ipa: "/brʌʃ/" },
    { word: "trust", ipa: "/trʌst/" },
    { word: "blood", ipa: "/blʌd/" },
    { word: "month", ipa: "/mʌnθ/" },
    { word: "under", ipa: "/ˈʌndər/" },
    { word: "enough", ipa: "/ɪˈnʌf/" },
    { word: "trouble", ipa: "/ˈtrʌbəl/" },
    { word: "country", ipa: "/ˈkʌntri/" },
  ],

  // /ə/ — mid central (schwa)
  schwa: [
    { word: "above", ipa: "/əˈbʌv/" },
    { word: "alone", ipa: "/əˈloʊn/" },
    { word: "begin", ipa: "/bɪˈɡɪn/" },
    { word: "common", ipa: "/ˈkɑːmən/" },
    { word: "happen", ipa: "/ˈhæpən/" },
    { word: "lesson", ipa: "/ˈlesn/" },
    { word: "support", ipa: "/səˈpɔːrt/" },
    { word: "perhaps", ipa: "/pərˈhæps/" },
    { word: "famous", ipa: "/ˈfeɪməs/" },
    { word: "suggest", ipa: "/səˈdʒest/" },
    { word: "supply", ipa: "/səˈplaɪ/" },
    { word: "suppose", ipa: "/səˈpoʊz/" },
    { word: "today", ipa: "/təˈdeɪ/" },
    { word: "around", ipa: "/əˈraʊnd/" },
    { word: "polite", ipa: "/pəˈlaɪt/" },
    { word: "control", ipa: "/kənˈtroʊl/" },
  ],

  // /ɜːr/ — rhotacized mid central
  er: [
    { word: "work", ipa: "/wɜːrk/" },
    { word: "girl", ipa: "/ɡɜːrl/" },
    { word: "hurt", ipa: "/hɜːrt/" },
    { word: "search", ipa: "/sɜːrtʃ/" },
    { word: "world", ipa: "/wɜːrld/" },
    { word: "church", ipa: "/tʃɜːrtʃ/" },
    { word: "shirt", ipa: "/ʃɜːrt/" },
    { word: "curve", ipa: "/kɜːrv/" },
    { word: "third", ipa: "/θɜːrd/" },
    { word: "verb", ipa: "/vɜːrb/" },
    { word: "merge", ipa: "/mɜːrdʒ/" },
    { word: "worth", ipa: "/wɜːrθ/" },
    { word: "purple", ipa: "/ˈpɜːrpəl/" },
    { word: "perfect", ipa: "/ˈpɜːrfɪkt/" },
    { word: "early", ipa: "/ˈɜːrli/" },
    { word: "circle", ipa: "/ˈsɜːrkəl/" },
  ],

  // /aɪ/ — diphthong
  ai: [
    { word: "life", ipa: "/laɪf/" },
    { word: "write", ipa: "/raɪt/" },
    { word: "find", ipa: "/faɪnd/" },
    { word: "mind", ipa: "/maɪnd/" },
    { word: "climb", ipa: "/klaɪm/" },
    { word: "bright", ipa: "/braɪt/" },
    { word: "prize", ipa: "/praɪz/" },
    { word: "knife", ipa: "/naɪf/" },
    { word: "tribe", ipa: "/traɪb/" },
    { word: "slide", ipa: "/slaɪd/" },
    { word: "stripe", ipa: "/straɪp/" },
    { word: "blind", ipa: "/blaɪnd/" },
    { word: "ice", ipa: "/aɪs/" },
    { word: "arrive", ipa: "/əˈraɪv/" },
    { word: "behind", ipa: "/bɪˈhaɪnd/" },
    { word: "quiet", ipa: "/ˈkwaɪət/" },
  ],

  // /aʊ/ — diphthong
  au: [
    { word: "sound", ipa: "/saʊnd/" },
    { word: "mouth", ipa: "/maʊθ/" },
    { word: "crowd", ipa: "/kraʊd/" },
    { word: "ground", ipa: "/ɡraʊnd/" },
    { word: "proud", ipa: "/praʊd/" },
    { word: "shout", ipa: "/ʃaʊt/" },
    { word: "count", ipa: "/kaʊnt/" },
    { word: "found", ipa: "/faʊnd/" },
    { word: "scout", ipa: "/skaʊt/" },
    { word: "power", ipa: "/ˈpaʊər/" },
    { word: "flour", ipa: "/flaʊr/" },
    { word: "frown", ipa: "/fraʊn/" },
    { word: "allow", ipa: "/əˈlaʊ/" },
    { word: "about", ipa: "/əˈbaʊt/" },
    { word: "outside", ipa: "/ˌaʊtˈsaɪd/" },
    { word: "mountain", ipa: "/ˈmaʊntən/" },
  ],

  // /ɔɪ/ — diphthong
  oi: [
    { word: "toy", ipa: "/tɔɪ/" },
    { word: "choice", ipa: "/tʃɔɪs/" },
    { word: "moist", ipa: "/mɔɪst/" },
    { word: "spoil", ipa: "/spɔɪl/" },
    { word: "royal", ipa: "/ˈrɔɪəl/" },
    { word: "loyal", ipa: "/ˈlɔɪəl/" },
    { word: "avoid", ipa: "/əˈvɔɪd/" },
    { word: "soil", ipa: "/sɔɪl/" },
    { word: "boil", ipa: "/bɔɪl/" },
    { word: "destroy", ipa: "/dɪˈstrɔɪ/" },
    { word: "employ", ipa: "/ɪmˈplɔɪ/" },
    { word: "joyful", ipa: "/ˈdʒɔɪfl/" },
    { word: "annoy", ipa: "/əˈnɔɪ/" },
    { word: "oyster", ipa: "/ˈɔɪstər/" },
    { word: "pointed", ipa: "/ˈpɔɪntɪd/" },
    { word: "poison", ipa: "/ˈpɔɪzən/" },
  ],

  // ===== Consonants =====

  // /p/ — voiceless bilabial plosive
  p: [
    { word: "pick", ipa: "/pɪk/" },
    { word: "push", ipa: "/pʊʃ/" },
    { word: "drop", ipa: "/drɑːp/" },
    { word: "price", ipa: "/praɪs/" },
    { word: "spring", ipa: "/sprɪŋ/" },
    { word: "simple", ipa: "/ˈsɪmpl/" },
    { word: "clap", ipa: "/klæp/" },
    { word: "plant", ipa: "/plænt/" },
    { word: "proof", ipa: "/pruːf/" },
    { word: "sharp", ipa: "/ʃɑːrp/" },
    { word: "stamp", ipa: "/stæmp/" },
    { word: "split", ipa: "/splɪt/" },
    { word: "pack", ipa: "/pæk/" },
    { word: "appear", ipa: "/əˈpɪr/" },
    { word: "pocket", ipa: "/ˈpɑːkɪt/" },
    { word: "copy", ipa: "/ˈkɑːpi/" },
  ],

  // /b/ — voiced bilabial plosive
  b: [
    { word: "best", ipa: "/best/" },
    { word: "bring", ipa: "/brɪŋ/" },
    { word: "brain", ipa: "/breɪn/" },
    { word: "rob", ipa: "/rɑːb/" },
    { word: "bold", ipa: "/boʊld/" },
    { word: "brand", ipa: "/brænd/" },
    { word: "blend", ipa: "/blend/" },
    { word: "globe", ipa: "/ɡloʊb/" },
    { word: "climb", ipa: "/klaɪm/" },
    { word: "block", ipa: "/blɑːk/" },
    { word: "tribe", ipa: "/traɪb/" },
    { word: "bulb", ipa: "/bʌlb/" },
    { word: "bag", ipa: "/bæɡ/" },
    { word: "able", ipa: "/ˈeɪbəl/" },
    { word: "rubber", ipa: "/ˈrʌbər/" },
    { word: "describe", ipa: "/dɪˈskraɪb/" },
  ],

  // /t/ — voiceless alveolar plosive
  t: [
    { word: "top", ipa: "/tɑːp/" },
    { word: "test", ipa: "/test/" },
    { word: "fast", ipa: "/fæst/" },
    { word: "trust", ipa: "/trʌst/" },
    { word: "street", ipa: "/striːt/" },
    { word: "plant", ipa: "/plænt/" },
    { word: "chest", ipa: "/tʃest/" },
    { word: "twist", ipa: "/twɪst/" },
    { word: "split", ipa: "/splɪt/" },
    { word: "tight", ipa: "/taɪt/" },
    { word: "treat", ipa: "/triːt/" },
    { word: "script", ipa: "/skrɪpt/" },
    { word: "time", ipa: "/taɪm/" },
    { word: "city", ipa: "/ˈsɪti/" },
    { word: "little", ipa: "/ˈlɪtəl/" },
    { word: "twenty", ipa: "/ˈtwenti/" },
  ],

  // /d/ — voiced alveolar plosive
  d: [
    { word: "deep", ipa: "/diːp/" },
    { word: "drive", ipa: "/draɪv/" },
    { word: "build", ipa: "/bɪld/" },
    { word: "mind", ipa: "/maɪnd/" },
    { word: "speed", ipa: "/spiːd/" },
    { word: "blend", ipa: "/blend/" },
    { word: "slide", ipa: "/slaɪd/" },
    { word: "ground", ipa: "/ɡraʊnd/" },
    { word: "cloud", ipa: "/klaʊd/" },
    { word: "draft", ipa: "/dræft/" },
    { word: "judge", ipa: "/dʒʌdʒ/" },
    { word: "shade", ipa: "/ʃeɪd/" },
    { word: "done", ipa: "/dʌn/" },
    { word: "ready", ipa: "/ˈredi/" },
    { word: "today", ipa: "/təˈdeɪ/" },
    { word: "ladder", ipa: "/ˈlædər/" },
  ],

  // /k/ — voiceless velar plosive
  k: [
    { word: "cold", ipa: "/koʊld/" },
    { word: "click", ipa: "/klɪk/" },
    { word: "track", ipa: "/træk/" },
    { word: "stock", ipa: "/stɑːk/" },
    { word: "trick", ipa: "/trɪk/" },
    { word: "clock", ipa: "/klɑːk/" },
    { word: "skill", ipa: "/skɪl/" },
    { word: "crack", ipa: "/kræk/" },
    { word: "check", ipa: "/tʃek/" },
    { word: "knock", ipa: "/nɑːk/" },
    { word: "blank", ipa: "/blæŋk/" },
    { word: "strike", ipa: "/straɪk/" },
    { word: "kind", ipa: "/kaɪnd/" },
    { word: "camera", ipa: "/ˈkæmərə/" },
    { word: "cookie", ipa: "/ˈkʊki/" },
    { word: "because", ipa: "/bɪˈkɔːz/" },
  ],

  // /ɡ/ — voiced velar plosive
  g: [
    { word: "grab", ipa: "/ɡræb/" },
    { word: "goal", ipa: "/ɡoʊl/" },
    { word: "glad", ipa: "/ɡlæd/" },
    { word: "grade", ipa: "/ɡreɪd/" },
    { word: "drag", ipa: "/dræɡ/" },
    { word: "flag", ipa: "/flæɡ/" },
    { word: "plug", ipa: "/plʌɡ/" },
    { word: "drug", ipa: "/drʌɡ/" },
    { word: "guess", ipa: "/ɡes/" },
    { word: "ghost", ipa: "/ɡoʊst/" },
    { word: "grind", ipa: "/ɡraɪnd/" },
    { word: "guide", ipa: "/ɡaɪd/" },
    { word: "game", ipa: "/ɡeɪm/" },
    { word: "begin", ipa: "/bɪˈɡɪn/" },
    { word: "bigger", ipa: "/ˈbɪɡər/" },
    { word: "target", ipa: "/ˈtɑːrɡɪt/" },
  ],

  // /f/ — voiceless labiodental fricative
  f: [
    { word: "fact", ipa: "/fækt/" },
    { word: "roof", ipa: "/ruːf/" },
    { word: "fruit", ipa: "/fruːt/" },
    { word: "chief", ipa: "/tʃiːf/" },
    { word: "flesh", ipa: "/fleʃ/" },
    { word: "flame", ipa: "/fleɪm/" },
    { word: "staff", ipa: "/stæf/" },
    { word: "draft", ipa: "/dræft/" },
    { word: "swift", ipa: "/swɪft/" },
    { word: "frost", ipa: "/frɔːst/" },
    { word: "shelf", ipa: "/ʃelf/" },
    { word: "cliff", ipa: "/klɪf/" },
    { word: "fire", ipa: "/ˈfaɪər/" },
    { word: "offer", ipa: "/ˈɔːfər/" },
    { word: "before", ipa: "/bɪˈfɔːr/" },
    { word: "enough", ipa: "/ɪˈnʌf/" },
  ],

  // /v/ — voiced labiodental fricative
  v: [
    { word: "vast", ipa: "/væst/" },
    { word: "give", ipa: "/ɡɪv/" },
    { word: "solve", ipa: "/sɑːlv/" },
    { word: "valve", ipa: "/vælv/" },
    { word: "vine", ipa: "/vaɪn/" },
    { word: "prove", ipa: "/pruːv/" },
    { word: "curve", ipa: "/kɜːrv/" },
    { word: "nerve", ipa: "/nɜːrv/" },
    { word: "vivid", ipa: "/ˈvɪvɪd/" },
    { word: "stove", ipa: "/stoʊv/" },
    { word: "shave", ipa: "/ʃeɪv/" },
    { word: "glove", ipa: "/ɡlʌv/" },
    { word: "visit", ipa: "/ˈvɪzɪt/" },
    { word: "over", ipa: "/ˈoʊvər/" },
    { word: "alive", ipa: "/əˈlaɪv/" },
    { word: "cover", ipa: "/ˈkʌvər/" },
  ],

  // /θ/ — voiceless dental fricative
  th: [
    { word: "thick", ipa: "/θɪk/" },
    { word: "throw", ipa: "/θroʊ/" },
    { word: "truth", ipa: "/truːθ/" },
    { word: "fifth", ipa: "/fɪfθ/" },
    { word: "depth", ipa: "/depθ/" },
    { word: "cloth", ipa: "/klɔːθ/" },
    { word: "theme", ipa: "/θiːm/" },
    { word: "throat", ipa: "/θroʊt/" },
    { word: "thrill", ipa: "/θrɪl/" },
    { word: "growth", ipa: "/ɡroʊθ/" },
    { word: "strength", ipa: "/streŋθ/" },
    { word: "thumb", ipa: "/θʌm/" },
    { word: "thirty", ipa: "/ˈθɜːrti/" },
    { word: "method", ipa: "/ˈmeθəd/" },
    { word: "athlete", ipa: "/ˈæθliːt/" },
    { word: "something", ipa: "/ˈsʌmθɪŋ/" },
  ],

  // /ð/ — voiced dental fricative
  dh: [
    { word: "these", ipa: "/ðiːz/" },
    { word: "those", ipa: "/ðoʊz/" },
    { word: "there", ipa: "/ðer/" },
    { word: "then", ipa: "/ðen/" },
    { word: "though", ipa: "/ðoʊ/" },
    { word: "father", ipa: "/ˈfɑːðər/" },
    { word: "breathe", ipa: "/briːð/" },
    { word: "bathe", ipa: "/beɪð/" },
    { word: "clothe", ipa: "/kloʊð/" },
    { word: "soothe", ipa: "/suːð/" },
    { word: "within", ipa: "/wɪˈðɪn/" },
    { word: "rhythm", ipa: "/ˈrɪðəm/" },
    { word: "either", ipa: "/ˈiːðər/" },
    { word: "another", ipa: "/əˈnʌðər/" },
    { word: "without", ipa: "/wɪˈðaʊt/" },
    { word: "clothing", ipa: "/ˈkloʊðɪŋ/" },
  ],

  // /s/ — voiceless alveolar fricative
  s: [
    { word: "soft", ipa: "/sɔːft/" },
    { word: "stop", ipa: "/stɑːp/" },
    { word: "cross", ipa: "/krɔːs/" },
    { word: "space", ipa: "/speɪs/" },
    { word: "sense", ipa: "/sens/" },
    { word: "slice", ipa: "/slaɪs/" },
    { word: "strict", ipa: "/strɪkt/" },
    { word: "skill", ipa: "/skɪl/" },
    { word: "stress", ipa: "/stres/" },
    { word: "smooth", ipa: "/smuːð/" },
    { word: "switch", ipa: "/swɪtʃ/" },
    { word: "split", ipa: "/splɪt/" },
    { word: "say", ipa: "/seɪ/" },
    { word: "pencil", ipa: "/ˈpensəl/" },
    { word: "answer", ipa: "/ˈænsər/" },
    { word: "receive", ipa: "/rɪˈsiːv/" },
  ],

  // /z/ — voiced alveolar fricative
  z: [
    { word: "zone", ipa: "/zoʊn/" },
    { word: "size", ipa: "/saɪz/" },
    { word: "prize", ipa: "/praɪz/" },
    { word: "freeze", ipa: "/friːz/" },
    { word: "choose", ipa: "/tʃuːz/" },
    { word: "quiz", ipa: "/kwɪz/" },
    { word: "breeze", ipa: "/briːz/" },
    { word: "raise", ipa: "/reɪz/" },
    { word: "phase", ipa: "/feɪz/" },
    { word: "close", ipa: "/kloʊz/" },
    { word: "cause", ipa: "/kɔːz/" },
    { word: "bronze", ipa: "/brɑːnz/" },
    { word: "zero", ipa: "/ˈzɪroʊ/" },
    { word: "visit", ipa: "/ˈvɪzɪt/" },
    { word: "busy", ipa: "/ˈbɪzi/" },
    { word: "amazing", ipa: "/əˈmeɪzɪŋ/" },
  ],

  // /ʃ/ — voiceless postalveolar fricative
  sh: [
    { word: "shade", ipa: "/ʃeɪd/" },
    { word: "crash", ipa: "/kræʃ/" },
    { word: "brush", ipa: "/brʌʃ/" },
    { word: "shelf", ipa: "/ʃelf/" },
    { word: "shine", ipa: "/ʃaɪn/" },
    { word: "shape", ipa: "/ʃeɪp/" },
    { word: "shift", ipa: "/ʃɪft/" },
    { word: "crush", ipa: "/krʌʃ/" },
    { word: "flash", ipa: "/flæʃ/" },
    { word: "sharp", ipa: "/ʃɑːrp/" },
    { word: "shout", ipa: "/ʃaʊt/" },
    { word: "push", ipa: "/pʊʃ/" },
    { word: "special", ipa: "/ˈspeʃəl/" },
    { word: "machine", ipa: "/məˈʃiːn/" },
    { word: "social", ipa: "/ˈsoʊʃəl/" },
    { word: "pressure", ipa: "/ˈpreʃər/" },
  ],

  // /ʒ/ — voiced postalveolar fricative
  zh: [
    { word: "rouge", ipa: "/ruːʒ/" },
    { word: "genre", ipa: "/ˈʒɑːnrə/" },
    { word: "massage", ipa: "/məˈsɑːʒ/" },
    { word: "mirage", ipa: "/mɪˈrɑːʒ/" },
    { word: "fusion", ipa: "/ˈfjuːʒn/" },
    { word: "version", ipa: "/ˈvɜːrʒn/" },
    { word: "decision", ipa: "/dɪˈsɪʒn/" },
    { word: "occasion", ipa: "/əˈkeɪʒn/" },
    { word: "explosion", ipa: "/ɪkˈsploʊʒn/" },
    { word: "invasion", ipa: "/ɪnˈveɪʒn/" },
    { word: "confusion", ipa: "/kənˈfjuːʒn/" },
    { word: "collision", ipa: "/kəˈlɪʒn/" },
    { word: "television", ipa: "/ˈteləvɪʒən/" },
    { word: "usually", ipa: "/ˈjuːʒuəli/" },
    { word: "Asia", ipa: "/ˈeɪʒə/" },
    { word: "casual", ipa: "/ˈkæʒuəl/" },
  ],

  // /tʃ/ — voiceless postalveolar affricate
  ch: [
    { word: "child", ipa: "/tʃaɪld/" },
    { word: "chain", ipa: "/tʃeɪn/" },
    { word: "choice", ipa: "/tʃɔɪs/" },
    { word: "match", ipa: "/mætʃ/" },
    { word: "stretch", ipa: "/stretʃ/" },
    { word: "chest", ipa: "/tʃest/" },
    { word: "cheap", ipa: "/tʃiːp/" },
    { word: "switch", ipa: "/swɪtʃ/" },
    { word: "branch", ipa: "/bræntʃ/" },
    { word: "sketch", ipa: "/sketʃ/" },
    { word: "charm", ipa: "/tʃɑːrm/" },
    { word: "pitch", ipa: "/pɪtʃ/" },
    { word: "kitchen", ipa: "/ˈkɪtʃən/" },
    { word: "question", ipa: "/ˈkwestʃən/" },
    { word: "future", ipa: "/ˈfjuːtʃər/" },
    { word: "picture", ipa: "/ˈpɪktʃər/" },
  ],

  // /dʒ/ — voiced postalveolar affricate
  dj: [
    { word: "gym", ipa: "/dʒɪm/" },
    { word: "huge", ipa: "/hjuːdʒ/" },
    { word: "edge", ipa: "/edʒ/" },
    { word: "page", ipa: "/peɪdʒ/" },
    { word: "change", ipa: "/tʃeɪndʒ/" },
    { word: "stage", ipa: "/steɪdʒ/" },
    { word: "charge", ipa: "/tʃɑːrdʒ/" },
    { word: "pledge", ipa: "/pledʒ/" },
    { word: "range", ipa: "/reɪndʒ/" },
    { word: "lodge", ipa: "/lɑːdʒ/" },
    { word: "badge", ipa: "/bædʒ/" },
    { word: "wedge", ipa: "/wedʒ/" },
    { word: "July", ipa: "/dʒuˈlaɪ/" },
    { word: "major", ipa: "/ˈmeɪdʒər/" },
    { word: "enjoy", ipa: "/ɪnˈdʒɔɪ/" },
    { word: "project", ipa: "/ˈprɑːdʒekt/" },
  ],

  // /m/ — bilabial nasal
  m: [
    { word: "storm", ipa: "/stɔːrm/" },
    { word: "farm", ipa: "/fɑːrm/" },
    { word: "cream", ipa: "/kriːm/" },
    { word: "flame", ipa: "/fleɪm/" },
    { word: "smooth", ipa: "/smuːð/" },
    { word: "prime", ipa: "/praɪm/" },
    { word: "charm", ipa: "/tʃɑːrm/" },
    { word: "match", ipa: "/mætʃ/" },
    { word: "might", ipa: "/maɪt/" },
    { word: "month", ipa: "/mʌnθ/" },
    { word: "stamp", ipa: "/stæmp/" },
    { word: "climb", ipa: "/klaɪm/" },
    { word: "money", ipa: "/ˈmʌni/" },
    { word: "moment", ipa: "/ˈmoʊmənt/" },
    { word: "remember", ipa: "/rɪˈmembər/" },
    { word: "family", ipa: "/ˈfæməli/" },
  ],

  // /n/ — alveolar nasal
  n: [
    { word: "nine", ipa: "/naɪn/" },
    { word: "note", ipa: "/noʊt/" },
    { word: "stone", ipa: "/stoʊn/" },
    { word: "brain", ipa: "/breɪn/" },
    { word: "shine", ipa: "/ʃaɪn/" },
    { word: "plane", ipa: "/pleɪn/" },
    { word: "skin", ipa: "/skɪn/" },
    { word: "scan", ipa: "/skæn/" },
    { word: "train", ipa: "/treɪn/" },
    { word: "green", ipa: "/ɡriːn/" },
    { word: "blend", ipa: "/blend/" },
    { word: "print", ipa: "/prɪnt/" },
    { word: "number", ipa: "/ˈnʌmbər/" },
    { word: "never", ipa: "/ˈnevər/" },
    { word: "enough", ipa: "/ɪˈnʌf/" },
    { word: "answer", ipa: "/ˈænsər/" },
  ],

  // /ŋ/ — velar nasal
  ng: [
    { word: "bring", ipa: "/brɪŋ/" },
    { word: "song", ipa: "/sɔːŋ/" },
    { word: "spring", ipa: "/sprɪŋ/" },
    { word: "hang", ipa: "/hæŋ/" },
    { word: "tongue", ipa: "/tʌŋ/" },
    { word: "swing", ipa: "/swɪŋ/" },
    { word: "sting", ipa: "/stɪŋ/" },
    { word: "cling", ipa: "/klɪŋ/" },
    { word: "among", ipa: "/əˈmʌŋ/" },
    { word: "along", ipa: "/əˈlɔːŋ/" },
    { word: "belong", ipa: "/bɪˈlɔːŋ/" },
    { word: "string", ipa: "/strɪŋ/" },
    { word: "morning", ipa: "/ˈmɔːrnɪŋ/" },
    { word: "singer", ipa: "/ˈsɪŋər/" },
    { word: "English", ipa: "/ˈɪŋɡlɪʃ/" },
    { word: "walking", ipa: "/ˈwɔːkɪŋ/" },
  ],

  // /l/ — alveolar lateral approximant
  l: [
    { word: "land", ipa: "/lænd/" },
    { word: "still", ipa: "/stɪl/" },
    { word: "spell", ipa: "/spel/" },
    { word: "shall", ipa: "/ʃæl/" },
    { word: "sleep", ipa: "/sliːp/" },
    { word: "split", ipa: "/splɪt/" },
    { word: "cloud", ipa: "/klaʊd/" },
    { word: "flame", ipa: "/fleɪm/" },
    { word: "blind", ipa: "/blaɪnd/" },
    { word: "float", ipa: "/floʊt/" },
    { word: "skill", ipa: "/skɪl/" },
    { word: "blame", ipa: "/bleɪm/" },
    { word: "light", ipa: "/laɪt/" },
    { word: "really", ipa: "/ˈriːəli/" },
    { word: "people", ipa: "/ˈpiːpəl/" },
    { word: "family", ipa: "/ˈfæməli/" },
  ],

  // /r/ — alveolar approximant
  r: [
    { word: "bring", ipa: "/brɪŋ/" },
    { word: "proud", ipa: "/praʊd/" },
    { word: "trail", ipa: "/treɪl/" },
    { word: "fresh", ipa: "/freʃ/" },
    { word: "crowd", ipa: "/kraʊd/" },
    { word: "spring", ipa: "/sprɪŋ/" },
    { word: "strong", ipa: "/strɔːŋ/" },
    { word: "cream", ipa: "/kriːm/" },
    { word: "grand", ipa: "/ɡrænd/" },
    { word: "throw", ipa: "/θroʊ/" },
    { word: "shrink", ipa: "/ʃrɪŋk/" },
    { word: "stripe", ipa: "/straɪp/" },
    { word: "real", ipa: "/riːl/" },
    { word: "around", ipa: "/əˈraʊnd/" },
    { word: "correct", ipa: "/kəˈrekt/" },
    { word: "story", ipa: "/ˈstɔːri/" },
  ],

  // /w/ — labial-velar approximant
  w: [
    { word: "wind", ipa: "/wɪnd/" },
    { word: "wish", ipa: "/wɪʃ/" },
    { word: "wait", ipa: "/weɪt/" },
    { word: "west", ipa: "/west/" },
    { word: "world", ipa: "/wɜːrld/" },
    { word: "watch", ipa: "/wɑːtʃ/" },
    { word: "swim", ipa: "/swɪm/" },
    { word: "twist", ipa: "/twɪst/" },
    { word: "twice", ipa: "/twaɪs/" },
    { word: "swing", ipa: "/swɪŋ/" },
    { word: "witch", ipa: "/wɪtʃ/" },
    { word: "wrap", ipa: "/ræp/" },
    { word: "word", ipa: "/wɜːrd/" },
    { word: "welcome", ipa: "/ˈwelkəm/" },
    { word: "always", ipa: "/ˈɔːlweɪz/" },
    { word: "between", ipa: "/bɪˈtwiːn/" },
  ],

  // /j/ — palatal approximant
  y: [
    { word: "yet", ipa: "/jet/" },
    { word: "your", ipa: "/jʊr/" },
    { word: "cute", ipa: "/kjuːt/" },
    { word: "huge", ipa: "/hjuːdʒ/" },
    { word: "unit", ipa: "/ˈjuːnɪt/" },
    { word: "human", ipa: "/ˈhjuːmən/" },
    { word: "fuel", ipa: "/fjuːl/" },
    { word: "argue", ipa: "/ˈɑːrɡjuː/" },
    { word: "value", ipa: "/ˈvæljuː/" },
    { word: "rescue", ipa: "/ˈreskjuː/" },
    { word: "beauty", ipa: "/ˈbjuːti/" },
    { word: "abuse", ipa: "/əˈbjuːz/" },
    { word: "yesterday", ipa: "/ˈjestərdeɪ/" },
    { word: "million", ipa: "/ˈmɪljən/" },
    { word: "familiar", ipa: "/fəˈmɪljər/" },
    { word: "onion", ipa: "/ˈʌnjən/" },
  ],

  // /h/ — voiceless glottal fricative
  h: [
    { word: "hurt", ipa: "/hɜːrt/" },
    { word: "hide", ipa: "/haɪd/" },
    { word: "heart", ipa: "/hɑːrt/" },
    { word: "help", ipa: "/help/" },
    { word: "high", ipa: "/haɪ/" },
    { word: "huge", ipa: "/hjuːdʒ/" },
    { word: "heat", ipa: "/hiːt/" },
    { word: "hint", ipa: "/hɪnt/" },
    { word: "host", ipa: "/hoʊst/" },
    { word: "hunt", ipa: "/hʌnt/" },
    { word: "harm", ipa: "/hɑːrm/" },
    { word: "hook", ipa: "/hʊk/" },
    { word: "hotel", ipa: "/hoʊˈtel/" },
    { word: "perhaps", ipa: "/pərˈhæps/" },
    { word: "history", ipa: "/ˈhɪstəri/" },
    { word: "healthy", ipa: "/ˈhelθi/" },
  ],
};

export function getExtendedWords(slug: string): KeywordEntry[] {
  return WORD_BANK[slug] ?? [];
}
