import type { LanguageId } from "@/types/language";

export const REQUIRED_SPANISH_UNITS = [
  "es-a",
  "es-e",
  "es-i",
  "es-o",
  "es-u",
  "es-p",
  "es-t",
  "es-k",
  "es-f",
  "es-m",
  "es-n",
  "es-bv",
  "es-d",
  "es-g",
  "es-theta",
  "es-s",
  "es-x",
  "es-ny",
  "es-ch",
  "es-y-ll",
  "es-l",
  "es-nasal-place",
  "es-tap-r",
  "es-trill-r",
  "es-diphthongs-j",
  "es-diphthongs-w",
  "es-lexical-stress",
  "es-syllable-rhythm",
] as const;

export const REQUIRED_FRENCH_UNITS = [
  "fr-i",
  "fr-y",
  "fr-u",
  "fr-e",
  "fr-e-open",
  "fr-eu-close",
  "fr-eu-open",
  "fr-a",
  "fr-schwa",
  "fr-o-close",
  "fr-o-open",
  "fr-an",
  "fr-in",
  "fr-on",
  "fr-un",
  "fr-r",
  "fr-p",
  "fr-b",
  "fr-t",
  "fr-d",
  "fr-k",
  "fr-g",
  "fr-f",
  "fr-v",
  "fr-s",
  "fr-z",
  "fr-m",
  "fr-n",
  "fr-l",
  "fr-sh",
  "fr-zh",
  "fr-ny",
  "fr-glide-j",
  "fr-glide-hui",
  "fr-glide-w",
  "fr-final-consonant-silence",
  "fr-liaison",
  "fr-enchainement",
  "fr-elision",
] as const;

export const REQUIRED_RUSSIAN_UNITS = [
  "ru-a",
  "ru-o",
  "ru-e",
  "ru-i",
  "ru-y",
  "ru-u",
  "ru-hard-soft",
  "ru-soft-t-d",
  "ru-soft-s-z",
  "ru-soft-n-l-r",
  "ru-soft-labials",
  "ru-soft-sign",
  "ru-r",
  "ru-x",
  "ru-sh-zh",
  "ru-ts",
  "ru-ch",
  "ru-shch",
  "ru-j",
  "ru-iotated-vowels",
  "ru-stress-reduction",
  "ru-unstressed-o-a",
  "ru-unstressed-e-ya",
  "ru-final-devoicing",
  "ru-voicing-assimilation",
  "ru-clusters",
] as const;

export const REQUIRED_LANGUAGE_UNITS: Partial<Record<LanguageId, readonly string[]>> = {
  "es-ES": REQUIRED_SPANISH_UNITS,
  "fr-FR": REQUIRED_FRENCH_UNITS,
  "ru-RU": REQUIRED_RUSSIAN_UNITS,
};
