import { PHONEMES } from "@/lib/phoneme-data";
import type { LanguageId } from "@/types/language";
import type {
  Difficulty,
  KeywordEntry,
  PhonemeCategory,
  PhonemeData,
  RolloutPriority,
  ScoringPolicy,
} from "@/types/phoneme";

type UnitInput = {
  languageId: LanguageId;
  slug: string;
  ipa: string;
  symbol?: string;
  name: string;
  category: PhonemeCategory;
  example: string;
  keywords: KeywordEntry[];
  difficulty: Difficulty;
  description: string;
  notes?: string[];
  soundUnitType?: PhonemeData["soundUnitType"];
  displayNameZh?: string;
  rolloutPriority?: RolloutPriority;
  commonMistakesZh?: string[];
  scoringPolicy?: ScoringPolicy;
};

function defaultScoringPolicy(input: UnitInput): ScoringPolicy {
  const soundUnitType = input.soundUnitType ?? "phoneme";

  if (soundUnitType === "phoneme") {
    return {
      singlePhonemeScore: "caution",
      recommendedMode: "word",
      azureRisk: "medium",
      notes: "非英语音素级评分需要母语者 fixture 校准；当前只作为反馈，不自动升级 mastery。",
    };
  }

  if (soundUnitType === "allophone") {
    return {
      singlePhonemeScore: "no",
      recommendedMode: "phrase",
      azureRisk: "high",
      notes: "这是上下文变体训练单位，不适合用单次音素分判断掌握。",
    };
  }

  if (soundUnitType === "contrast") {
    return {
      singlePhonemeScore: "no",
      recommendedMode: "phrase",
      azureRisk: "high",
      notes: "这是对比训练单位，优先用听辨、最小对立和多词跟读验证。",
    };
  }

  if (soundUnitType === "cluster") {
    return {
      singlePhonemeScore: "no",
      recommendedMode: "phrase",
      azureRisk: "high",
      notes: "这是组合型训练单位，单个音素分不能代表掌握。",
    };
  }

  return {
    singlePhonemeScore: "no",
    recommendedMode: "rule",
    azureRisk: "high",
    notes: "这是重音、连诵或语流规则训练单位，只能作为规则/跟读反馈。",
  };
}

function unit(input: UnitInput): PhonemeData {
  return {
    languageId: input.languageId,
    ipa: input.ipa,
    symbol: input.symbol ?? input.ipa.replaceAll("/", ""),
    slug: input.slug,
    name: input.name,
    displayNameZh: input.displayNameZh,
    category: input.category,
    soundUnitType: input.soundUnitType ?? "phoneme",
    rolloutPriority: input.rolloutPriority ?? "must",
    commonMistakesZh: input.commonMistakesZh,
    scoringPolicy: input.scoringPolicy ?? defaultScoringPolicy(input),
    example: input.example,
    keywords: input.keywords,
    difficulty: input.difficulty,
    description: input.description,
    notes: input.notes,
    video: {
      status: "planned",
      label: "待补充授权教学视频",
    },
  };
}

const ENGLISH_PHONEMES: PhonemeData[] = PHONEMES.map((phoneme) => ({
  ...phoneme,
  languageId: "en-US",
  soundUnitType: "phoneme",
  video: {
    localSrc: `/videos/phonemes/${phoneme.slug}.mp4`,
    status: "ready",
    label: "Rachel's English 本地教学视频",
  },
}));

const SPANISH_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "es-ES",
    slug: "es-a",
    ipa: "/a/",
    name: "open central vowel",
    category: "vowel",
    example: "casa",
    keywords: [
      { word: "casa", ipa: "/ˈkasa/" },
      { word: "mano", ipa: "/ˈmano/" },
      { word: "agua", ipa: "/ˈaɣwa/" },
      { word: "mapa", ipa: "/ˈmapa/" },
      { word: "nada", ipa: "/ˈnaða/" },
      { word: "sal", ipa: "/sal/" },
    ],
    difficulty: "easy",
    description: "嘴巴自然张开，舌位低而居中，保持短、纯、稳定，不滑向英语 /æ/ 或 /ɑː/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-e",
    ipa: "/e/",
    name: "close-mid front vowel",
    category: "vowel",
    example: "mesa",
    keywords: [
      { word: "mesa", ipa: "/ˈmesa/" },
      { word: "leche", ipa: "/ˈletʃe/" },
      { word: "perro", ipa: "/ˈpero/" },
      { word: "verde", ipa: "/ˈbeɾðe/" },
      { word: "tres", ipa: "/tɾes/" },
      { word: "dedo", ipa: "/ˈdeðo/" },
    ],
    difficulty: "easy",
    description: "舌前部抬起，嘴巴半闭；不要读成英语双元音 /eɪ/，结尾不滑。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-i",
    ipa: "/i/",
    name: "close front vowel",
    category: "vowel",
    example: "sí",
    keywords: [
      { word: "sí", ipa: "/si/" },
      { word: "vida", ipa: "/ˈbiða/" },
      { word: "niño", ipa: "/ˈniɲo/" },
      { word: "libro", ipa: "/ˈlibɾo/" },
      { word: "cinco", ipa: "/ˈθinko/" },
      { word: "mira", ipa: "/ˈmiɾa/" },
    ],
    difficulty: "easy",
    description: "嘴角微展，舌前高位；声音短而干净，不拖成长英语 /iː/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-o",
    ipa: "/o/",
    name: "close-mid back rounded vowel",
    category: "vowel",
    example: "sol",
    keywords: [
      { word: "sol", ipa: "/sol/" },
      { word: "hola", ipa: "/ˈola/" },
      { word: "coche", ipa: "/ˈkotʃe/" },
      { word: "rojo", ipa: "/ˈroxo/" },
      { word: "todo", ipa: "/ˈtoðo/" },
      { word: "boca", ipa: "/ˈboka/" },
    ],
    difficulty: "easy",
    description: "双唇收圆，舌后部抬起；保持单元音，不要滑成英语 /oʊ/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-u",
    ipa: "/u/",
    name: "close back rounded vowel",
    category: "vowel",
    example: "luna",
    keywords: [
      { word: "luna", ipa: "/ˈluna/" },
      { word: "uno", ipa: "/ˈuno/" },
      { word: "tú", ipa: "/tu/" },
      { word: "azul", ipa: "/aˈθul/" },
      { word: "mundo", ipa: "/ˈmundo/" },
      { word: "curso", ipa: "/ˈkuɾso/" },
    ],
    difficulty: "easy",
    description: "双唇收圆但声音短，不要按英语长 /uː/ 拉长。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-bv",
    ipa: "/b/ [β]",
    name: "Spanish b/v stop and approximant",
    category: "consonant",
    soundUnitType: "allophone",
    example: "vida",
    keywords: [
      { word: "vida", ipa: "/ˈbiða/" },
      { word: "vino", ipa: "/ˈbino/" },
      { word: "boca", ipa: "/ˈboka/" },
      { word: "bebé", ipa: "/beˈβe/" },
      { word: "saber", ipa: "/saˈβeɾ/" },
      { word: "uva", ipa: "/ˈuβa/" },
    ],
    difficulty: "high",
    description: "词首或鼻音后更像 /b/；两个元音之间放松成 /β/，双唇接近但不要咬下唇读英语 /v/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-d",
    ipa: "/d̪/",
    name: "Spanish dental d",
    category: "consonant",
    example: "dedo",
    keywords: [
      { word: "dedo", ipa: "/ˈdeðo/" },
      { word: "día", ipa: "/ˈdia/" },
      { word: "nada", ipa: "/ˈnaða/" },
      { word: "verde", ipa: "/ˈbeɾðe/" },
      { word: "lado", ipa: "/ˈlaðo/" },
      { word: "dos", ipa: "/dos/" },
    ],
    difficulty: "high",
    description: "舌尖靠近上齿背，齿化而短促；元音间放松另见 b/d/g 放松训练单位。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-g",
    ipa: "/g/",
    name: "Spanish voiced velar stop",
    category: "consonant",
    example: "gato",
    keywords: [
      { word: "gato", ipa: "/ˈgato/" },
      { word: "agua", ipa: "/ˈaɣwa/" },
      { word: "amigo", ipa: "/aˈmiɣo/" },
      { word: "grande", ipa: "/ˈgɾande/" },
      { word: "juego", ipa: "/ˈxweɣo/" },
      { word: "lago", ipa: "/ˈlaɣo/" },
    ],
    difficulty: "medium",
    description: "词首或鼻音后较闭合；元音间放松为 /ɣ/ 的训练另见 b/d/g 放松单位。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-theta",
    ipa: "/θ/",
    name: "Castilian c/z",
    category: "consonant",
    example: "cielo",
    keywords: [
      { word: "cielo", ipa: "/ˈθjelo/" },
      { word: "zapato", ipa: "/θaˈpato/" },
      { word: "cinco", ipa: "/ˈθinko/" },
      { word: "gracias", ipa: "/ˈgɾaθjas/" },
      { word: "luz", ipa: "/luθ/" },
      { word: "azul", ipa: "/aˈθul/" },
    ],
    difficulty: "medium",
    description: "西班牙本土常用；舌尖轻触上下齿间，让气流从齿间形成清擦音。拉美西语常并入 /s/，后续需要做方言开关。",
    notes: ["当前按 es-ES 处理；拉美西语需要单独 profile。"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-s",
    ipa: "/s/",
    name: "voiceless alveolar fricative",
    category: "consonant",
    example: "casa",
    keywords: [
      { word: "casa", ipa: "/ˈkasa/" },
      { word: "sopa", ipa: "/ˈsopa/" },
      { word: "seis", ipa: "/sejs/" },
      { word: "mesa", ipa: "/ˈmesa/" },
      { word: "tasa", ipa: "/ˈtasa/" },
      { word: "sien", ipa: "/sjen/" },
    ],
    difficulty: "medium",
    description: "舌尖靠近上齿龈形成窄缝，气流稳定；不要卷舌，也不要把 es-ES 的 c/z 全并成 /s/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-x",
    ipa: "/x/",
    name: "voiceless velar fricative",
    category: "consonant",
    example: "jamón",
    keywords: [
      { word: "jamón", ipa: "/xaˈmon/" },
      { word: "juego", ipa: "/ˈxweɣo/" },
      { word: "rojo", ipa: "/ˈroxo/" },
      { word: "gente", ipa: "/ˈxente/" },
      { word: "José", ipa: "/xoˈse/" },
      { word: "México", ipa: "/ˈmexiko/" },
    ],
    difficulty: "high",
    description: "舌后部靠近软腭形成摩擦，像更靠后的“哈”，不要读成英语 /h/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-n",
    ipa: "/n/",
    name: "alveolar nasal",
    category: "consonant",
    example: "nada",
    keywords: [
      { word: "nada", ipa: "/ˈnaða/" },
      { word: "noche", ipa: "/ˈnotʃe/" },
      { word: "uno", ipa: "/ˈuno/" },
      { word: "cana", ipa: "/ˈkana/" },
      { word: "una", ipa: "/ˈuna/" },
      { word: "mano", ipa: "/ˈmano/" },
    ],
    difficulty: "easy",
    description: "舌尖抵住上齿龈，鼻腔出声；要和舌面贴硬腭的 /ɲ/ 分开。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-ny",
    ipa: "/ɲ/",
    name: "palatal nasal",
    category: "consonant",
    example: "niño",
    keywords: [
      { word: "niño", ipa: "/ˈniɲo/" },
      { word: "año", ipa: "/ˈaɲo/" },
      { word: "señor", ipa: "/seˈɲoɾ/" },
      { word: "mañana", ipa: "/maˈɲana/" },
      { word: "sueño", ipa: "/ˈsweɲo/" },
      { word: "España", ipa: "/esˈpaɲa/" },
    ],
    difficulty: "medium",
    description: "舌面贴近硬腭，鼻音从硬腭位置出来，不要拆成 /n/ + /j/ 两个音。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-tap-r",
    ipa: "/ɾ/",
    name: "single tap r",
    category: "consonant",
    example: "pero",
    keywords: [
      { word: "pero", ipa: "/ˈpeɾo/" },
      { word: "caro", ipa: "/ˈkaɾo/" },
      { word: "para", ipa: "/ˈpaɾa/" },
      { word: "tarde", ipa: "/ˈtaɾðe/" },
      { word: "verde", ipa: "/ˈbeɾðe/" },
      { word: "libro", ipa: "/ˈlibɾo/" },
    ],
    difficulty: "high",
    description: "舌尖快速弹一下上齿龈，只有一次接触，不要读成英语卷舌 r。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-trill-r",
    ipa: "/r/",
    name: "trilled rr",
    category: "consonant",
    example: "perro",
    keywords: [
      { word: "perro", ipa: "/ˈpero/" },
      { word: "rojo", ipa: "/ˈroxo/" },
      { word: "rápido", ipa: "/ˈrapido/" },
      { word: "carro", ipa: "/ˈkaro/" },
      { word: "tierra", ipa: "/ˈtjera/" },
      { word: "río", ipa: "/ˈri.o/" },
    ],
    difficulty: "high",
    description: "舌尖在上齿龈处连续颤动；先练稳定气流和舌尖放松，再追求多次颤动。",
  }),
];

const SPANISH_EXTRA_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "es-ES",
    slug: "es-p",
    ipa: "/p/",
    name: "voiceless bilabial stop",
    displayNameZh: "清双唇塞音",
    category: "consonant",
    example: "pan",
    keywords: [
      { word: "pan", ipa: "/pan/" },
      { word: "papa", ipa: "/ˈpapa/" },
      { word: "poco", ipa: "/ˈpoko/" },
      { word: "mapa", ipa: "/ˈmapa/" },
      { word: "papel", ipa: "/paˈpel/" },
      { word: "sopa", ipa: "/ˈsopa/" },
    ],
    difficulty: "easy",
    description: "双唇完全闭合后轻快打开，西语 /p/ 不像普通话 p 或英语词首 p 那样强送气。",
    commonMistakesZh: ["读成强送气 /pʰ/", "尾部加多余元音"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-t",
    ipa: "/t̪/",
    name: "dentalized voiceless stop",
    displayNameZh: "齿化清塞音",
    category: "consonant",
    example: "tú",
    keywords: [
      { word: "tú", ipa: "/tu/" },
      { word: "taza", ipa: "/ˈtaθa/" },
      { word: "toma", ipa: "/ˈtoma/" },
      { word: "tomate", ipa: "/toˈmate/" },
      { word: "tarde", ipa: "/ˈtaɾðe/" },
      { word: "texto", ipa: "/ˈteksto/" },
    ],
    difficulty: "medium",
    description: "舌尖更靠近上齿背，爆破短促；不要做成英语齿龈 t 或普通话强送气 t。",
    commonMistakesZh: ["舌位太靠后", "送气过强"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-k",
    ipa: "/k/",
    name: "voiceless velar stop",
    displayNameZh: "清软腭塞音",
    category: "consonant",
    example: "casa",
    keywords: [
      { word: "casa", ipa: "/ˈkasa/" },
      { word: "café", ipa: "/kaˈfe/" },
      { word: "kilo", ipa: "/ˈkilo/" },
      { word: "poco", ipa: "/ˈpoko/" },
      { word: "aquí", ipa: "/aˈki/" },
      { word: "queso", ipa: "/ˈkeso/" },
    ],
    difficulty: "easy",
    description: "舌后部抵住软腭后轻快打开，避免英语/普通话式强送气。",
    commonMistakesZh: ["读成 /kʰ/", "把 que/qui 的 u 读出来"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-b",
    ipa: "/b/",
    name: "voiced bilabial stop",
    displayNameZh: "浊双唇塞音",
    category: "consonant",
    example: "boca",
    keywords: [
      { word: "boca", ipa: "/ˈboka/" },
      { word: "vino", ipa: "/ˈbino/" },
      { word: "vida", ipa: "/ˈbiða/" },
      { word: "beso", ipa: "/ˈbeso/" },
      { word: "Barcelona", ipa: "/baɾθeˈlona/" },
      { word: "bebé", ipa: "/beˈβe/" },
    ],
    difficulty: "medium",
    description: "b 和 v 在标准西语里共享 /b/ 音位；词首或鼻音后更闭合，元音间会放松。",
    commonMistakesZh: ["把 v 咬唇读成英语 /v/", "全程读得过硬"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-f",
    ipa: "/f/",
    name: "voiceless labiodental fricative",
    displayNameZh: "清唇齿擦音",
    category: "consonant",
    example: "familia",
    keywords: [
      { word: "familia", ipa: "/faˈmilja/" },
      { word: "café", ipa: "/kaˈfe/" },
      { word: "foto", ipa: "/ˈfoto/" },
      { word: "fácil", ipa: "/ˈfaθil/" },
      { word: "frío", ipa: "/ˈfɾi.o/" },
      { word: "fuerte", ipa: "/ˈfweɾte/" },
    ],
    difficulty: "easy",
    description: "上齿轻触下唇，气流持续摩擦；和 b/v 的双唇动作分开。",
    rolloutPriority: "should",
    commonMistakesZh: ["唇齿接触不足", "和 /x/ 或 /s/ 混"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-tch",
    ipa: "/tʃ/",
    name: "voiceless postalveolar affricate",
    displayNameZh: "ch 塞擦音",
    category: "consonant",
    example: "chico",
    keywords: [
      { word: "chico", ipa: "/ˈtʃiko/" },
      { word: "coche", ipa: "/ˈkotʃe/" },
      { word: "mucho", ipa: "/ˈmutʃo/" },
      { word: "noche", ipa: "/ˈnotʃe/" },
      { word: "chocolate", ipa: "/tʃokoˈlate/" },
      { word: "ocho", ipa: "/ˈotʃo/" },
    ],
    difficulty: "medium",
    description: "先短暂堵住气流再释放成擦音，保持一个完整塞擦音，不要拆成两个音。",
    commonMistakesZh: ["读成普通话 q/ch 的混合", "摩擦段太弱"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-m",
    ipa: "/m/",
    name: "bilabial nasal",
    displayNameZh: "双唇鼻音",
    category: "consonant",
    example: "mano",
    keywords: [
      { word: "mano", ipa: "/ˈmano/" },
      { word: "mamá", ipa: "/maˈma/" },
      { word: "mesa", ipa: "/ˈmesa/" },
      { word: "amigo", ipa: "/aˈmiɣo/" },
      { word: "mundo", ipa: "/ˈmundo/" },
      { word: "comer", ipa: "/koˈmeɾ/" },
    ],
    difficulty: "easy",
    description: "双唇闭合，气流从鼻腔出来；保持短促清楚，不要加尾音。",
    rolloutPriority: "should",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-l",
    ipa: "/l/",
    name: "alveolar lateral",
    displayNameZh: "齿龈边音",
    category: "consonant",
    example: "luna",
    keywords: [
      { word: "luna", ipa: "/ˈluna/" },
      { word: "lado", ipa: "/ˈlaðo/" },
      { word: "leche", ipa: "/ˈletʃe/" },
      { word: "clase", ipa: "/ˈklase/" },
      { word: "azul", ipa: "/aˈθul/" },
      { word: "papel", ipa: "/paˈpel/" },
    ],
    difficulty: "easy",
    description: "舌尖抵住上齿龈，舌侧出气；不要做成英语词尾那种后缩厚重的 L 音色。",
    rolloutPriority: "should",
    commonMistakesZh: ["受英语词尾厚 L 影响过重", "词尾加元音"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-y",
    ipa: "/ʝ/",
    name: "voiced palatal approximant-fricative",
    displayNameZh: "y/ll 腭音",
    category: "consonant",
    example: "yo",
    keywords: [
      { word: "yo", ipa: "/ʝo/" },
      { word: "ya", ipa: "/ʝa/" },
      { word: "llave", ipa: "/ˈʝaβe/" },
      { word: "llama", ipa: "/ˈʝama/" },
      { word: "llegar", ipa: "/ʝeˈɣaɾ/" },
      { word: "ella", ipa: "/ˈeʝa/" },
    ],
    difficulty: "high",
    description: "y/ll 在多数现代西语中并入这个腭部近音/擦音；不要简单读成英语 /j/。",
    commonMistakesZh: ["读成英语 yes 的 /j/", "忽略 yeísmo 方言说明"],
    scoringPolicy: {
      singlePhonemeScore: "no",
      recommendedMode: "word",
      azureRisk: "high",
      notes: "西语 y/ll 有显著地区差异，第一阶段只做发音反馈和方言说明。",
    },
  }),
  unit({
    languageId: "es-ES",
    slug: "es-j",
    ipa: "/j/",
    name: "palatal glide",
    displayNameZh: "半元音 y",
    category: "semivowel",
    soundUnitType: "allophone",
    example: "bien",
    keywords: [
      { word: "bien", ipa: "/bjen/" },
      { word: "ciudad", ipa: "/θjuˈðað/" },
      { word: "familia", ipa: "/faˈmilja/" },
      { word: "piano", ipa: "/ˈpjano/" },
      { word: "siete", ipa: "/ˈsjete/" },
      { word: "viaje", ipa: "/ˈbjaxe/" },
    ],
    difficulty: "medium",
    rolloutPriority: "should",
    description: "在双元音里 /i/ 变得更短更滑，不能读成一个完整独立的 /i/ 音节。",
    commonMistakesZh: ["把双元音拆开", "把 /j/ 拉成长元音"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-w",
    ipa: "/w/",
    name: "labiovelar glide",
    displayNameZh: "半元音 u",
    category: "semivowel",
    soundUnitType: "allophone",
    example: "bueno",
    keywords: [
      { word: "bueno", ipa: "/ˈbweno/" },
      { word: "cuando", ipa: "/ˈkwando/" },
      { word: "agua", ipa: "/ˈaɣwa/" },
      { word: "cuatro", ipa: "/ˈkwatɾo/" },
      { word: "fuerte", ipa: "/ˈfweɾte/" },
      { word: "juego", ipa: "/ˈxweɣo/" },
    ],
    difficulty: "medium",
    rolloutPriority: "should",
    description: "在双元音里保持短滑和圆唇，不要把它读成完整 /u/ 音节。",
    commonMistakesZh: ["把 /w/ 拆成完整 /u/", "圆唇不足"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-bdg-lenition",
    ipa: "[β ð ɣ]",
    name: "intervocalic b/d/g approximants",
    displayNameZh: "b/d/g 元音间放松",
    category: "consonant",
    soundUnitType: "allophone",
    example: "saber",
    keywords: [
      { word: "beber", ipa: "/beˈβeɾ/" },
      { word: "saber", ipa: "/saˈβeɾ/" },
      { word: "nada", ipa: "/ˈnaða/" },
      { word: "lado", ipa: "/ˈlaðo/" },
      { word: "amigo", ipa: "/aˈmiɣo/" },
      { word: "lago", ipa: "/ˈlaɣo/" },
    ],
    difficulty: "high",
    description: "两个元音之间 b/d/g 通常放松成近音；这是上下文动作，不是三个新音素。",
    commonMistakesZh: ["把 b/d/g 全部硬塞", "把 b/v 读成英语 /v/"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-r-contrast",
    ipa: "/ɾ ~ r/",
    name: "tap-trill contrast",
    displayNameZh: "单击 r / 颤音 rr 对比",
    category: "consonant",
    soundUnitType: "contrast",
    example: "pero / perro",
    keywords: [
      { word: "pero / perro", ipa: "/ˈpeɾo/ /ˈpero/" },
      { word: "caro / carro", ipa: "/ˈkaɾo/ /ˈkaro/" },
      { word: "coro / corro", ipa: "/ˈkoɾo/ /ˈkoro/" },
      { word: "para / parra", ipa: "/ˈpaɾa/ /ˈpara/" },
      { word: "mira / mirra", ipa: "/ˈmiɾa/ /ˈmira/" },
      { word: "cero / cerro", ipa: "/ˈθeɾo/ /ˈθero/" },
    ],
    difficulty: "high",
    description: "西语 /ɾ/ 与 /r/ 能区别词义，必须做听辨和最小对立训练。",
    commonMistakesZh: ["两个 r 全读成英语 r", "单击和颤音对立消失"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-s-theta",
    ipa: "/s ~ θ/",
    name: "seseo-distinción contrast",
    displayNameZh: "s / c-z 对比",
    category: "consonant",
    soundUnitType: "contrast",
    example: "casa / caza",
    keywords: [
      { word: "casa / caza", ipa: "/ˈkasa/ /ˈkaθa/" },
      { word: "tasa / taza", ipa: "/ˈtasa/ /ˈtaθa/" },
      { word: "sien / cien", ipa: "/sjen/ /θjen/" },
      { word: "coser / cocer", ipa: "/koˈseɾ/ /koˈθeɾ/" },
      { word: "ves / vez", ipa: "/bes/ /beθ/" },
      { word: "as / haz", ipa: "/as/ /aθ/" },
    ],
    difficulty: "medium",
    description: "es-ES 主线保留 /s/ 与 /θ/；拉美 profile 需要另做，不能混在一起。",
    commonMistakesZh: ["把 es-ES 的 c/z 全部并入 /s/"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-n-ny",
    ipa: "/n ~ ɲ/",
    name: "alveolar-palatal nasal contrast",
    displayNameZh: "n / ñ 对比",
    category: "consonant",
    soundUnitType: "contrast",
    example: "cana / caña",
    keywords: [
      { word: "cana / caña", ipa: "/ˈkana/ /ˈkaɲa/" },
      { word: "una / uña", ipa: "/ˈuna/ /ˈuɲa/" },
      { word: "pena / peña", ipa: "/ˈpena/ /ˈpeɲa/" },
      { word: "mono / moño", ipa: "/ˈmono/ /ˈmoɲo/" },
      { word: "pana / paña", ipa: "/ˈpana/ /ˈpaɲa/" },
      { word: "suena / sueña", ipa: "/ˈswena/ /ˈsweɲa/" },
    ],
    difficulty: "medium",
    description: "/ɲ/ 不是 /n/ + /j/ 的简单拼接，要把舌面抬向硬腭。",
    commonMistakesZh: ["把 ñ 拆成两个音", "和普通 n 混"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-e-i",
    ipa: "/e ~ i/",
    name: "mid-close front vowel contrast",
    displayNameZh: "e / i 对比",
    category: "vowel",
    soundUnitType: "contrast",
    example: "peso / piso",
    keywords: [
      { word: "peso / piso", ipa: "/ˈpeso/ /ˈpiso/" },
      { word: "mesa / misa", ipa: "/ˈmesa/ /ˈmisa/" },
      { word: "pesa / pisa", ipa: "/ˈpesa/ /ˈpisa/" },
      { word: "se / sí", ipa: "/se/ /si/" },
      { word: "de / di", ipa: "/de/ /di/" },
      { word: "le / li", ipa: "/le/ /li/" },
    ],
    difficulty: "medium",
    rolloutPriority: "should",
    description: "保持 /e/ 的中高舌位，不要抬到 /i/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-o-u",
    ipa: "/o ~ u/",
    name: "back rounded vowel contrast",
    displayNameZh: "o / u 对比",
    category: "vowel",
    soundUnitType: "contrast",
    example: "poco / pudo",
    keywords: [
      { word: "poco / pudo", ipa: "/ˈpoko/ /ˈpuðo/" },
      { word: "tomo / tubo", ipa: "/ˈtomo/ /ˈtuβo/" },
      { word: "solo / subo", ipa: "/ˈsolo/ /ˈsuβo/" },
      { word: "no / tú", ipa: "/no/ /tu/" },
      { word: "dos / dulce", ipa: "/dos/ /ˈdulθe/" },
      { word: "rojo / ruta", ipa: "/ˈroxo/ /ˈruta/" },
    ],
    difficulty: "medium",
    rolloutPriority: "should",
    description: "/o/ 是半闭圆唇，/u/ 更高更紧；两个都不能滑成英语双元音。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-stress",
    ipa: "/ˈ/",
    name: "lexical stress",
    displayNameZh: "词重音",
    category: "prosody",
    soundUnitType: "prosody",
    example: "café",
    keywords: [
      { word: "café", ipa: "/kaˈfe/" },
      { word: "teléfono", ipa: "/teˈlefono/" },
      { word: "rápido", ipa: "/ˈrapido/" },
      { word: "difícil", ipa: "/diˈfiθil/" },
      { word: "canción", ipa: "/kanˈθjon/" },
      { word: "universidad", ipa: "/uniβeɾsiˈðað/" },
    ],
    difficulty: "medium",
    description: "西语词重音和书面重音符号直接影响清晰度；按音节节奏练，不按中文声调处理。",
    commonMistakesZh: ["所有音节平均用力", "忽略重音符号"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-diphthong-hiatus",
    ipa: "/j w/ + hiatus",
    name: "diphthong vs hiatus",
    displayNameZh: "双元音 / 分音节",
    category: "prosody",
    soundUnitType: "prosody",
    example: "piano / país",
    keywords: [
      { word: "país", ipa: "/paˈis/" },
      { word: "piano", ipa: "/ˈpjano/" },
      { word: "ciudad", ipa: "/θjuˈðað/" },
      { word: "día", ipa: "/ˈdia/" },
      { word: "bueno", ipa: "/ˈbweno/" },
      { word: "río", ipa: "/ˈri.o/" },
    ],
    difficulty: "medium",
    rolloutPriority: "should",
    description: "有些 i/u 是半元音，有些要分成独立音节；重音符号常提示 hiatus。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-clusters",
    ipa: "/pl pr tr br gr kl/",
    name: "onset clusters",
    displayNameZh: "起首辅音丛",
    category: "cluster",
    soundUnitType: "cluster",
    example: "tres",
    keywords: [
      { word: "plato", ipa: "/ˈplato/" },
      { word: "pronto", ipa: "/ˈpɾonto/" },
      { word: "tres", ipa: "/tɾes/" },
      { word: "brazo", ipa: "/ˈbɾaθo/" },
      { word: "grande", ipa: "/ˈgɾande/" },
      { word: "clase", ipa: "/ˈklase/" },
    ],
    difficulty: "medium",
    rolloutPriority: "later",
    description: "辅音丛中间不要插入额外元音；先慢速保留每个辅音，再逐渐加速。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-ll",
    ipa: "/ʎ/",
    name: "palatal lateral",
    displayNameZh: "传统 ll 边音",
    category: "consonant",
    rolloutPriority: "later",
    example: "calle",
    keywords: [
      { word: "pollo", ipa: "/ˈpoʎo/" },
      { word: "calle", ipa: "/ˈkaʎe/" },
      { word: "llave", ipa: "/ˈʎaβe/" },
      { word: "llano", ipa: "/ˈʎano/" },
      { word: "lluvia", ipa: "/ˈʎuβja/" },
      { word: "allí", ipa: "/aˈʎi/" },
    ],
    difficulty: "high",
    description: "部分地区仍保留 /ʎ/，但多数现代西语已 yeísmo；本轮只作为方言/进阶说明。",
    notes: ["默认 es-ES 主线不强制掌握；后续可做方言开关。"],
  }),
];

const FRENCH_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "fr-FR",
    slug: "fr-i",
    ipa: "/i/",
    name: "close front unrounded vowel",
    category: "vowel",
    example: "si",
    keywords: [
      { word: "si", ipa: "/si/" },
      { word: "ville", ipa: "/vil/" },
      { word: "vite", ipa: "/vit/" },
      { word: "midi", ipa: "/midi/" },
      { word: "ici", ipa: "/isi/" },
      { word: "lit", ipa: "/li/" },
    ],
    difficulty: "easy",
    description: "舌前高位，嘴角微展；短而紧，不按英语 /iː/ 拉长。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-y",
    ipa: "/y/",
    name: "close front rounded vowel",
    category: "vowel",
    example: "tu",
    keywords: [
      { word: "tu", ipa: "/ty/" },
      { word: "lune", ipa: "/lyn/" },
      { word: "rue", ipa: "/ʁy/" },
      { word: "dur", ipa: "/dyʁ/" },
      { word: "musique", ipa: "/myzik/" },
      { word: "sur", ipa: "/syʁ/" },
    ],
    difficulty: "high",
    description: "舌头摆 /i/ 的高前位置，同时双唇像 /u/ 一样收圆；中文学习者很容易退成 /u/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-u",
    ipa: "/u/",
    name: "close back rounded vowel",
    category: "vowel",
    example: "vous",
    keywords: [
      { word: "vous", ipa: "/vu/" },
      { word: "nous", ipa: "/nu/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "jour", ipa: "/ʒuʁ/" },
      { word: "sous", ipa: "/su/" },
      { word: "tout", ipa: "/tu/" },
    ],
    difficulty: "medium",
    description: "双唇收圆，舌后高位；要和 /y/ 分开，/u/ 的舌位更靠后。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-e",
    ipa: "/e/",
    name: "close-mid front vowel",
    category: "vowel",
    example: "été",
    keywords: [
      { word: "été", ipa: "/ete/" },
      { word: "nez", ipa: "/ne/" },
      { word: "parler", ipa: "/paʁle/" },
      { word: "café", ipa: "/kafe/" },
      { word: "mes", ipa: "/me/" },
      { word: "bébé", ipa: "/bebe/" },
    ],
    difficulty: "medium",
    description: "舌前中高位，声音干净稳定，不滑成英语 /eɪ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-e-open",
    ipa: "/ɛ/",
    name: "open-mid front vowel",
    category: "vowel",
    example: "sel",
    keywords: [
      { word: "sel", ipa: "/sɛl/" },
      { word: "mère", ipa: "/mɛʁ/" },
      { word: "très", ipa: "/tʁɛ/" },
      { word: "belle", ipa: "/bɛl/" },
      { word: "sept", ipa: "/sɛt/" },
      { word: "faire", ipa: "/fɛʁ/" },
    ],
    difficulty: "medium",
    description: "嘴巴比 /e/ 更开，舌前略低；要和 /e/ 做对比训练。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-eu-close",
    ipa: "/ø/",
    name: "close-mid front rounded vowel",
    category: "vowel",
    example: "deux",
    keywords: [
      { word: "deux", ipa: "/dø/" },
      { word: "bleu", ipa: "/blø/" },
      { word: "peu", ipa: "/pø/" },
      { word: "heureux", ipa: "/øʁø/" },
      { word: "feu", ipa: "/fø/" },
      { word: "jeu", ipa: "/ʒø/" },
    ],
    difficulty: "high",
    description: "像 /e/ 的舌位加上圆唇；不要变成 /o/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-eu-open",
    ipa: "/œ/",
    name: "open-mid front rounded vowel",
    category: "vowel",
    example: "sœur",
    keywords: [
      { word: "sœur", ipa: "/sœʁ/" },
      { word: "jeune", ipa: "/ʒœn/" },
      { word: "peur", ipa: "/pœʁ/" },
      { word: "fleur", ipa: "/flœʁ/" },
      { word: "neuf", ipa: "/nœf/" },
      { word: "seul", ipa: "/sœl/" },
    ],
    difficulty: "high",
    description: "像 /ɛ/ 的开口加圆唇；法语圆唇前元音是中国学习者重点难点。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-an",
    ipa: "/ɑ̃/",
    name: "nasal vowel an/en",
    category: "vowel",
    example: "sans",
    keywords: [
      { word: "sans", ipa: "/sɑ̃/" },
      { word: "France", ipa: "/fʁɑ̃s/" },
      { word: "temps", ipa: "/tɑ̃/" },
      { word: "grand", ipa: "/gʁɑ̃/" },
      { word: "dans", ipa: "/dɑ̃/" },
      { word: "maman", ipa: "/mamɑ̃/" },
    ],
    difficulty: "high",
    description: "口腔元音同时打开鼻腔共鸣，不要在后面加清楚的 /n/ 或 /ŋ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-in",
    ipa: "/ɛ̃/",
    name: "nasal vowel in/ain",
    category: "vowel",
    example: "vin",
    keywords: [
      { word: "vin", ipa: "/vɛ̃/" },
      { word: "pain", ipa: "/pɛ̃/" },
      { word: "bien", ipa: "/bjɛ̃/" },
      { word: "matin", ipa: "/matɛ̃/" },
      { word: "cinq", ipa: "/sɛ̃k/" },
      { word: "main", ipa: "/mɛ̃/" },
    ],
    difficulty: "high",
    description: "舌前中低位加鼻化；和 /ɑ̃/、/ɔ̃/ 的口型距离要拉开。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-on",
    ipa: "/ɔ̃/",
    name: "nasal vowel on",
    category: "vowel",
    example: "bon",
    keywords: [
      { word: "bon", ipa: "/bɔ̃/" },
      { word: "nom", ipa: "/nɔ̃/" },
      { word: "son", ipa: "/sɔ̃/" },
      { word: "monde", ipa: "/mɔ̃d/" },
      { word: "bonjour", ipa: "/bɔ̃ʒuʁ/" },
      { word: "long", ipa: "/lɔ̃/" },
    ],
    difficulty: "high",
    description: "圆唇后元音加鼻化；不要读成“ong”的明显尾音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-r",
    ipa: "/ʁ/",
    name: "French uvular r",
    category: "consonant",
    example: "rue",
    keywords: [
      { word: "rue", ipa: "/ʁy/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "Paris", ipa: "/paʁi/" },
      { word: "merci", ipa: "/mɛʁsi/" },
      { word: "très", ipa: "/tʁɛ/" },
      { word: "frère", ipa: "/fʁɛʁ/" },
    ],
    difficulty: "high",
    description: "舌根靠近小舌产生摩擦或近音，不是英语卷舌 r，也不是西语弹舌 r。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-liaison",
    ipa: "/‿/",
    name: "liaison",
    displayNameZh: "联诵",
    category: "prosody",
    soundUnitType: "prosody",
    example: "les amis",
    keywords: [
      { word: "les amis", ipa: "/le.z‿a.mi/" },
      { word: "un ami", ipa: "/œ̃.n‿a.mi/" },
      { word: "vous avez", ipa: "/vu.z‿a.ve/" },
      { word: "petit ami", ipa: "/pə.ti.t‿a.mi/" },
      { word: "grand homme", ipa: "/gʁɑ̃.t‿ɔm/" },
      { word: "chez elle", ipa: "/ʃe.z‿ɛl/" },
    ],
    difficulty: "high",
    description: "法语部分潜在词尾辅音会在后接元音词前重新出现；这是词边界规则，和普通连续诵读分开训练。",
    notes: ["现代巴黎/北法中 un 的 /œ̃/ 常与 /ɛ̃/ 合并；这里保留变体说明。"],
  }),
];

const FRENCH_EXTRA_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "fr-FR",
    slug: "fr-a",
    ipa: "/a/",
    name: "open front-central vowel",
    displayNameZh: "开前/央元音",
    category: "vowel",
    example: "chat",
    keywords: [
      { word: "chat", ipa: "/ʃa/" },
      { word: "la", ipa: "/la/" },
      { word: "madame", ipa: "/madam/" },
      { word: "parler", ipa: "/paʁle/" },
      { word: "table", ipa: "/tabl/" },
      { word: "ami", ipa: "/ami/" },
    ],
    difficulty: "easy",
    description: "嘴巴自然打开，声音短而清楚；现代法国法语里 /ɑ/ 多数先作为变体说明。",
    commonMistakesZh: ["读得过后或过长", "受英语 /æ/ 影响"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-o-close",
    ipa: "/o/",
    name: "close-mid back rounded vowel",
    displayNameZh: "半闭后圆唇元音",
    category: "vowel",
    example: "eau",
    keywords: [
      { word: "eau", ipa: "/o/" },
      { word: "beau", ipa: "/bo/" },
      { word: "mot", ipa: "/mo/" },
      { word: "chaud", ipa: "/ʃo/" },
      { word: "rose", ipa: "/ʁoz/" },
      { word: "photo", ipa: "/foto/" },
    ],
    difficulty: "medium",
    description: "双唇收圆，舌后中高位；不要滑成英语 /oʊ/。",
    commonMistakesZh: ["加英语式滑音", "和 /ɔ/ 混"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-o-open",
    ipa: "/ɔ/",
    name: "open-mid back rounded vowel",
    displayNameZh: "半开后圆唇元音",
    category: "vowel",
    example: "porte",
    keywords: [
      { word: "porte", ipa: "/pɔʁt/" },
      { word: "homme", ipa: "/ɔm/" },
      { word: "comme", ipa: "/kɔm/" },
      { word: "école", ipa: "/ekɔl/" },
      { word: "fort", ipa: "/fɔʁ/" },
      { word: "donne", ipa: "/dɔn/" },
    ],
    difficulty: "medium",
    description: "比 /o/ 更开，但仍保持圆唇；适合和 /o/ 成组听辨。",
    commonMistakesZh: ["读成 /o/", "圆唇不足"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-schwa",
    ipa: "/ə/",
    name: "French schwa / e caduc",
    displayNameZh: "法语弱 e",
    category: "vowel",
    soundUnitType: "prosody",
    rolloutPriority: "should",
    example: "petit",
    keywords: [
      { word: "petit", ipa: "/pəti/" },
      { word: "demain", ipa: "/dəmɛ̃/" },
      { word: "le", ipa: "/lə/" },
      { word: "je", ipa: "/ʒə/" },
      { word: "semaine", ipa: "/səmɛn/" },
      { word: "fenêtre", ipa: "/fənɛtʁ/" },
    ],
    difficulty: "high",
    description: "这个 e 常可弱读或脱落，是节奏和拼写规则训练单位，不适合单次音素评分。",
    commonMistakesZh: ["每个 e 都重读", "完全忽略 e caduc 规则"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-p",
    ipa: "/p/",
    name: "voiceless bilabial stop",
    displayNameZh: "清双唇塞音",
    category: "consonant",
    example: "pas",
    keywords: [
      { word: "pas", ipa: "/pa/" },
      { word: "père", ipa: "/pɛʁ/" },
      { word: "petit", ipa: "/pəti/" },
      { word: "paris", ipa: "/paʁi/" },
      { word: "peur", ipa: "/pœʁ/" },
      { word: "tape", ipa: "/tap/" },
    ],
    difficulty: "easy",
    description: "双唇闭合后轻快打开；法语清塞音通常不需要英语式强送气。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-b",
    ipa: "/b/",
    name: "voiced bilabial stop",
    displayNameZh: "浊双唇塞音",
    category: "consonant",
    example: "beau",
    keywords: [
      { word: "beau", ipa: "/bo/" },
      { word: "bon", ipa: "/bɔ̃/" },
      { word: "bébé", ipa: "/bebe/" },
      { word: "table", ipa: "/tabl/" },
      { word: "robe", ipa: "/ʁɔb/" },
      { word: "bleu", ipa: "/blø/" },
    ],
    difficulty: "easy",
    description: "保持声带振动，爆破不要拖长；和 /p/ 做清浊对比。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-t",
    ipa: "/t/",
    name: "voiceless alveolar stop",
    displayNameZh: "清齿龈塞音",
    category: "consonant",
    example: "tu",
    keywords: [
      { word: "tu", ipa: "/ty/" },
      { word: "table", ipa: "/tabl/" },
      { word: "tout", ipa: "/tu/" },
      { word: "thé", ipa: "/te/" },
      { word: "vite", ipa: "/vit/" },
      { word: "tête", ipa: "/tɛt/" },
    ],
    difficulty: "easy",
    description: "舌尖/舌叶接近上齿龈，释放短促；不要强送气。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-d",
    ipa: "/d/",
    name: "voiced alveolar stop",
    displayNameZh: "浊齿龈塞音",
    category: "consonant",
    example: "deux",
    keywords: [
      { word: "deux", ipa: "/dø/" },
      { word: "dire", ipa: "/diʁ/" },
      { word: "dans", ipa: "/dɑ̃/" },
      { word: "dame", ipa: "/dam/" },
      { word: "dormir", ipa: "/dɔʁmiʁ/" },
      { word: "samedi", ipa: "/samdi/" },
    ],
    difficulty: "easy",
    description: "保持浊音和短促爆破；不要读成英语式重爆破。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-k",
    ipa: "/k/",
    name: "voiceless velar stop",
    displayNameZh: "清软腭塞音",
    category: "consonant",
    example: "qui",
    keywords: [
      { word: "qui", ipa: "/ki/" },
      { word: "café", ipa: "/kafe/" },
      { word: "quand", ipa: "/kɑ̃/" },
      { word: "cou", ipa: "/ku/" },
      { word: "école", ipa: "/ekɔl/" },
      { word: "sac", ipa: "/sak/" },
    ],
    difficulty: "easy",
    description: "舌后部抵住软腭后打开；qu 通常读 /k/，u 不一定发音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-g",
    ipa: "/g/",
    name: "voiced velar stop",
    displayNameZh: "浊软腭塞音",
    category: "consonant",
    example: "gare",
    keywords: [
      { word: "gare", ipa: "/gaʁ/" },
      { word: "goût", ipa: "/gu/" },
      { word: "grand", ipa: "/gʁɑ̃/" },
      { word: "guerre", ipa: "/gɛʁ/" },
      { word: "égal", ipa: "/egal/" },
      { word: "guide", ipa: "/gid/" },
    ],
    difficulty: "medium",
    description: "保持浊音，和拼写 g/ge/gu 的读音规则分开练。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-f",
    ipa: "/f/",
    name: "voiceless labiodental fricative",
    displayNameZh: "清唇齿擦音",
    category: "consonant",
    example: "faire",
    keywords: [
      { word: "faire", ipa: "/fɛʁ/" },
      { word: "femme", ipa: "/fam/" },
      { word: "fou", ipa: "/fu/" },
      { word: "français", ipa: "/fʁɑ̃sɛ/" },
      { word: "photo", ipa: "/foto/" },
      { word: "neuf", ipa: "/nœf/" },
    ],
    difficulty: "easy",
    description: "上齿轻触下唇，气流持续摩擦；和 /v/ 成清浊对比。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-v",
    ipa: "/v/",
    name: "voiced labiodental fricative",
    displayNameZh: "浊唇齿擦音",
    category: "consonant",
    example: "vous",
    keywords: [
      { word: "vous", ipa: "/vu/" },
      { word: "ville", ipa: "/vil/" },
      { word: "vin", ipa: "/vɛ̃/" },
      { word: "avec", ipa: "/avɛk/" },
      { word: "vivre", ipa: "/vivʁ/" },
      { word: "vrai", ipa: "/vʁɛ/" },
    ],
    difficulty: "medium",
    description: "保持唇齿摩擦和声带振动；不要退成 /w/ 或 /f/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-s",
    ipa: "/s/",
    name: "voiceless alveolar fricative",
    displayNameZh: "清齿龈擦音",
    category: "consonant",
    example: "si",
    keywords: [
      { word: "si", ipa: "/si/" },
      { word: "sac", ipa: "/sak/" },
      { word: "ça", ipa: "/sa/" },
      { word: "merci", ipa: "/mɛʁsi/" },
      { word: "français", ipa: "/fʁɑ̃sɛ/" },
      { word: "classe", ipa: "/klas/" },
    ],
    difficulty: "easy",
    description: "舌尖靠近上齿龈形成稳定窄缝；不要卷舌化。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-z",
    ipa: "/z/",
    name: "voiced alveolar fricative",
    displayNameZh: "浊齿龈擦音",
    category: "consonant",
    example: "zéro",
    keywords: [
      { word: "zéro", ipa: "/zeʁo/" },
      { word: "rose", ipa: "/ʁoz/" },
      { word: "maison", ipa: "/mɛzɔ̃/" },
      { word: "zoo", ipa: "/zo/" },
      { word: "les amis", ipa: "/lezami/" },
      { word: "onze", ipa: "/ɔ̃z/" },
    ],
    difficulty: "medium",
    description: "和 /s/ 位置相近，但声带振动； liaison 中也常出现 /z/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-sh",
    ipa: "/ʃ/",
    name: "voiceless postalveolar fricative",
    displayNameZh: "清后齿龈擦音",
    category: "consonant",
    example: "chat",
    keywords: [
      { word: "chat", ipa: "/ʃa/" },
      { word: "chez", ipa: "/ʃe/" },
      { word: "chose", ipa: "/ʃoz/" },
      { word: "chien", ipa: "/ʃjɛ̃/" },
      { word: "chaud", ipa: "/ʃo/" },
      { word: "chercher", ipa: "/ʃɛʁʃe/" },
    ],
    difficulty: "medium",
    description: "舌面靠后形成摩擦，音色比 /s/ 更宽更后。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-zh",
    ipa: "/ʒ/",
    name: "voiced postalveolar fricative",
    displayNameZh: "浊后齿龈擦音",
    category: "consonant",
    example: "je",
    keywords: [
      { word: "je", ipa: "/ʒə/" },
      { word: "jour", ipa: "/ʒuʁ/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "bonjour", ipa: "/bɔ̃ʒuʁ/" },
      { word: "joli", ipa: "/ʒɔli/" },
      { word: "manger", ipa: "/mɑ̃ʒe/" },
    ],
    difficulty: "medium",
    description: "保持 /ʃ/ 的后部摩擦位置，同时声带振动；不要清化成 /ʃ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-m",
    ipa: "/m/",
    name: "bilabial nasal",
    displayNameZh: "双唇鼻音",
    category: "consonant",
    example: "maman",
    keywords: [
      { word: "maman", ipa: "/mamɑ̃/" },
      { word: "moi", ipa: "/mwa/" },
      { word: "merci", ipa: "/mɛʁsi/" },
      { word: "madame", ipa: "/madam/" },
      { word: "aimer", ipa: "/eme/" },
      { word: "homme", ipa: "/ɔm/" },
    ],
    difficulty: "easy",
    description: "双唇闭合，鼻腔出声；注意不要把鼻化元音后面额外加 /m/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-n",
    ipa: "/n/",
    name: "alveolar nasal",
    displayNameZh: "齿龈鼻音",
    category: "consonant",
    example: "non",
    keywords: [
      { word: "non", ipa: "/nɔ̃/" },
      { word: "nous", ipa: "/nu/" },
      { word: "bonne", ipa: "/bɔn/" },
      { word: "année", ipa: "/ane/" },
      { word: "venir", ipa: "/vəniʁ/" },
      { word: "personne", ipa: "/pɛʁsɔn/" },
    ],
    difficulty: "easy",
    description: "舌尖抵上齿龈，鼻腔出声；鼻化元音不是简单的元音 + /n/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-ny",
    ipa: "/ɲ/",
    name: "palatal nasal",
    displayNameZh: "gn 硬腭鼻音",
    category: "consonant",
    example: "montagne",
    keywords: [
      { word: "montagne", ipa: "/mɔ̃taɲ/" },
      { word: "gagner", ipa: "/gaɲe/" },
      { word: "ligne", ipa: "/liɲ/" },
      { word: "oignon", ipa: "/ɔɲɔ̃/" },
      { word: "Espagne", ipa: "/ɛspaɲ/" },
      { word: "campagne", ipa: "/kɑ̃paɲ/" },
    ],
    difficulty: "medium",
    description: "舌面贴近硬腭，不能拆成 /n/ + /j/。",
    commonMistakesZh: ["拆成两个音", "和 /n/ 混"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-ng",
    ipa: "/ŋ/",
    name: "velar nasal in loanwords",
    displayNameZh: "外来词软腭鼻音",
    category: "consonant",
    rolloutPriority: "later",
    example: "parking",
    keywords: [
      { word: "parking", ipa: "/paʁkiŋ/" },
      { word: "camping", ipa: "/kɑ̃piŋ/" },
      { word: "jogging", ipa: "/ʒɔgiŋ/" },
      { word: "shopping", ipa: "/ʃɔpiŋ/" },
      { word: "marketing", ipa: "/maʁkɛtiŋ/" },
      { word: "smoking", ipa: "/smɔkiŋ/" },
    ],
    difficulty: "medium",
    description: "/ŋ/ 主要出现在外来词中，不是第一阶段核心法语音素。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-l",
    ipa: "/l/",
    name: "alveolar lateral",
    displayNameZh: "齿龈边音",
    category: "consonant",
    example: "lune",
    keywords: [
      { word: "lune", ipa: "/lyn/" },
      { word: "la", ipa: "/la/" },
      { word: "ville", ipa: "/vil/" },
      { word: "bleu", ipa: "/blø/" },
      { word: "table", ipa: "/tabl/" },
      { word: "elle", ipa: "/ɛl/" },
    ],
    difficulty: "easy",
    description: "舌尖抵上齿龈，舌侧出气；法语 /l/ 不应像英语词尾 L 那样后缩发厚。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-j",
    ipa: "/j/",
    name: "palatal approximant",
    displayNameZh: "半元音 yod",
    category: "semivowel",
    example: "yeux",
    keywords: [
      { word: "yeux", ipa: "/jø/" },
      { word: "hier", ipa: "/jɛʁ/" },
      { word: "travail", ipa: "/tʁavaj/" },
      { word: "fille", ipa: "/fij/" },
      { word: "pied", ipa: "/pje/" },
      { word: "bien", ipa: "/bjɛ̃/" },
    ],
    difficulty: "medium",
    description: "短而滑的硬腭近音，不要拉成完整 /i/ 音节。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-hui",
    ipa: "/ɥ/",
    name: "labial-palatal approximant",
    displayNameZh: "圆唇前半元音",
    category: "semivowel",
    example: "huit",
    keywords: [
      { word: "huit", ipa: "/ɥit/" },
      { word: "lui", ipa: "/lɥi/" },
      { word: "pluie", ipa: "/plɥi/" },
      { word: "nuit", ipa: "/nɥi/" },
      { word: "puis", ipa: "/pɥi/" },
      { word: "aujourd'hui", ipa: "/oʒuʁdɥi/" },
    ],
    difficulty: "high",
    description: "舌头像 /y/，嘴唇圆，动作短滑；中文学习者很容易退成 /w/ 或完整 /y/。",
    commonMistakesZh: ["读成 /w/", "把 /ɥ/ 拆成完整 /y/"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-w",
    ipa: "/w/",
    name: "labiovelar approximant",
    displayNameZh: "圆唇后半元音",
    category: "semivowel",
    example: "oui",
    keywords: [
      { word: "oui", ipa: "/wi/" },
      { word: "moi", ipa: "/mwa/" },
      { word: "toi", ipa: "/twa/" },
      { word: "quoi", ipa: "/kwa/" },
      { word: "oiseau", ipa: "/wazo/" },
      { word: "ouest", ipa: "/wɛst/" },
    ],
    difficulty: "medium",
    description: "短滑圆唇近音，舌位比 /ɥ/ 更靠后；要和 /ɥ/ 明确分开。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-nasal-contrast",
    ipa: "/ɑ̃ ɛ̃ ɔ̃/",
    name: "nasal vowel contrast",
    displayNameZh: "鼻化元音对比",
    category: "vowel",
    soundUnitType: "contrast",
    example: "sans / vin / bon",
    keywords: [
      { word: "sans / vin", ipa: "/sɑ̃/ /vɛ̃/" },
      { word: "vin / bon", ipa: "/vɛ̃/ /bɔ̃/" },
      { word: "grand / grain", ipa: "/gʁɑ̃/ /gʁɛ̃/" },
      { word: "temps / ton", ipa: "/tɑ̃/ /tɔ̃/" },
      { word: "pain / pont", ipa: "/pɛ̃/ /pɔ̃/" },
      { word: "France / français", ipa: "/fʁɑ̃s/ /fʁɑ̃sɛ/" },
    ],
    difficulty: "high",
    description: "鼻化元音要同时控制口型和鼻腔共鸣，不能统一读成“ang/eng/ong”。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-i-y-u",
    ipa: "/i y u/",
    name: "high vowel triangle",
    displayNameZh: "i / y / u 三角对比",
    category: "vowel",
    soundUnitType: "contrast",
    rolloutPriority: "should",
    example: "si / su / sous",
    keywords: [
      { word: "si / su", ipa: "/si/ /sy/" },
      { word: "tu / tout", ipa: "/ty/ /tu/" },
      { word: "lune / loupe", ipa: "/lyn/ /lup/" },
      { word: "rue / roue", ipa: "/ʁy/ /ʁu/" },
      { word: "sur / sourd", ipa: "/syʁ/ /suʁ/" },
      { word: "vu / vous", ipa: "/vy/ /vu/" },
    ],
    difficulty: "high",
    description: "法语 /y/ 是最容易被中文学习者挤到 /u/ 的核心难点，必须和 /i/、/u/ 成组练。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-e-eopen",
    ipa: "/e ~ ɛ/",
    name: "close-mid vs open-mid e",
    displayNameZh: "闭 e / 开 e 对比",
    category: "vowel",
    soundUnitType: "contrast",
    rolloutPriority: "should",
    example: "été / était",
    keywords: [
      { word: "été / était", ipa: "/ete/ /etɛ/" },
      { word: "mes / mère", ipa: "/me/ /mɛʁ/" },
      { word: "nez / net", ipa: "/ne/ /nɛt/" },
      { word: "parler / belle", ipa: "/paʁle/ /bɛl/" },
      { word: "café / faire", ipa: "/kafe/ /fɛʁ/" },
      { word: "clé / clair", ipa: "/kle/ /klɛʁ/" },
    ],
    difficulty: "medium",
    description: "开口大小不同，不要把所有 e 都读成同一个音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-eu-contrast",
    ipa: "/ø ~ œ/",
    name: "rounded front vowel contrast",
    displayNameZh: "闭 eu / 开 eu 对比",
    category: "vowel",
    soundUnitType: "contrast",
    rolloutPriority: "should",
    example: "deux / sœur",
    keywords: [
      { word: "deux / sœur", ipa: "/dø/ /sœʁ/" },
      { word: "peu / peur", ipa: "/pø/ /pœʁ/" },
      { word: "feu / fleur", ipa: "/fø/ /flœʁ/" },
      { word: "jeu / jeune", ipa: "/ʒø/ /ʒœn/" },
      { word: "bleu / seul", ipa: "/blø/ /sœl/" },
      { word: "heureux / neuf", ipa: "/øʁø/ /nœf/" },
    ],
    difficulty: "high",
    description: "两个都是前圆唇元音，差别在开口和舌位；不要退成 /o/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-silent-finals",
    ipa: "final C",
    name: "silent final consonants",
    displayNameZh: "词尾辅音静音",
    category: "prosody",
    soundUnitType: "prosody",
    example: "petit",
    keywords: [
      { word: "petit", ipa: "/pəti/" },
      { word: "grand", ipa: "/gʁɑ̃/" },
      { word: "vous", ipa: "/vu/" },
      { word: "blanc", ipa: "/blɑ̃/" },
      { word: "temps", ipa: "/tɑ̃/" },
      { word: "parler", ipa: "/paʁle/" },
    ],
    difficulty: "high",
    description: "很多词尾辅音默认不发音，但在连诵环境可能重新出现；这是规则训练。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-enchainement",
    ipa: "/‿/",
    name: "enchaînement",
    displayNameZh: "连续诵读",
    category: "prosody",
    soundUnitType: "prosody",
    example: "avec elle",
    keywords: [
      { word: "avec elle", ipa: "/avɛkɛl/" },
      { word: "il aime", ipa: "/ilɛm/" },
      { word: "elle arrive", ipa: "/ɛlaʁiv/" },
      { word: "petite amie", ipa: "/pətitami/" },
      { word: "chaque année", ipa: "/ʃakane/" },
      { word: "tout entier", ipa: "/tutɑ̃tje/" },
    ],
    difficulty: "high",
    description: "法语倾向把相邻词连成节奏组，辅音会自然接到后面的元音上。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-rhythm-group",
    ipa: "/ˈ phrase-final/",
    name: "French rhythm group",
    displayNameZh: "节奏组末重音",
    category: "prosody",
    soundUnitType: "prosody",
    rolloutPriority: "should",
    example: "je voudrais un café",
    keywords: [
      { word: "je voudrais un café", ipa: "/ʒəvudʁɛœ̃kafe/" },
      { word: "à Paris", ipa: "/apaʁi/" },
      { word: "très important", ipa: "/tʁɛzɛ̃pɔʁtɑ̃/" },
      { word: "dans la maison", ipa: "/dɑ̃lamɛzɔ̃/" },
      { word: "avec mes amis", ipa: "/avɛkmezami/" },
      { word: "pendant les vacances", ipa: "/pɑ̃dɑ̃levakɑ̃s/" },
    ],
    difficulty: "high",
    description: "法语不是每个单词都有英语式强重音，主要在节奏组末尾形成突出。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-a-back",
    ipa: "/ɑ/",
    name: "back open vowel variant",
    displayNameZh: "后开元音变体",
    category: "vowel",
    rolloutPriority: "later",
    example: "pâte",
    keywords: [
      { word: "pâte", ipa: "/pɑt/" },
      { word: "âge", ipa: "/ɑʒ/" },
      { word: "âme", ipa: "/ɑm/" },
      { word: "tâche", ipa: "/tɑʃ/" },
      { word: "bâle", ipa: "/bɑl/" },
      { word: "théâtre", ipa: "/teɑtʁ/" },
    ],
    difficulty: "medium",
    description: "现代法国法语许多地区与 /a/ 合并，本轮只作为地区/高级说明。",
    notes: ["不作为 fr-FR 第一阶段主线。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-un",
    ipa: "/œ̃/",
    name: "nasal rounded front vowel variant",
    displayNameZh: "un 鼻化元音变体",
    category: "vowel",
    rolloutPriority: "later",
    example: "un",
    keywords: [
      { word: "un", ipa: "/œ̃/" },
      { word: "brun", ipa: "/bʁœ̃/" },
      { word: "parfum", ipa: "/paʁfœ̃/" },
      { word: "lundi", ipa: "/lœ̃di/" },
      { word: "commun", ipa: "/kɔmœ̃/" },
      { word: "quelqu'un", ipa: "/kɛlkœ̃/" },
    ],
    difficulty: "high",
    description: "很多现代法国口音已并入 /ɛ̃/，先作为变体说明，不强制主线掌握。",
    notes: ["后续可做地区变体开关。"],
  }),
];

const RUSSIAN_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "ru-RU",
    slug: "ru-a",
    ipa: "/a/",
    name: "Russian а",
    category: "vowel",
    example: "мама",
    keywords: [
      { word: "мама", ipa: "/ˈmamə/" },
      { word: "да", ipa: "/da/" },
      { word: "там", ipa: "/tam/" },
      { word: "парк", ipa: "/park/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "сахар", ipa: "/ˈsaxər/" },
    ],
    difficulty: "easy",
    description: "重读时清楚开放，非重读时会弱化；俄语元音练习必须带重音位置。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-o",
    ipa: "/o/",
    name: "Russian stressed о",
    category: "vowel",
    example: "дом",
    keywords: [
      { word: "дом", ipa: "/dom/" },
      { word: "кот", ipa: "/kot/" },
      { word: "мост", ipa: "/most/" },
      { word: "нос", ipa: "/nos/" },
      { word: "рот", ipa: "/rot/" },
      { word: "город", ipa: "/ˈgorət/" },
    ],
    difficulty: "medium",
    description: "重读 /o/ 圆唇清楚；非重读 о 通常弱化接近 /a/ 或 /ə/，不能只按字母读。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-i",
    ipa: "/i/",
    name: "Russian и",
    category: "vowel",
    example: "мир",
    keywords: [
      { word: "мир", ipa: "/mʲir/" },
      { word: "лиса", ipa: "/lʲɪˈsa/" },
      { word: "имя", ipa: "/ˈimʲə/" },
      { word: "тихо", ipa: "/ˈtʲixə/" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/" },
      { word: "пить", ipa: "/pʲitʲ/" },
    ],
    difficulty: "medium",
    description: "常让前面的辅音软化；练这个音时要同时听辅音硬软变化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-y",
    ipa: "/ɨ/",
    name: "Russian ы",
    category: "vowel",
    example: "мы",
    keywords: [
      { word: "мы", ipa: "/mɨ/" },
      { word: "сыр", ipa: "/sɨr/" },
      { word: "ты", ipa: "/tɨ/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "быстро", ipa: "/ˈbɨstrə/" },
      { word: "сын", ipa: "/sɨn/" },
    ],
    difficulty: "high",
    description: "舌身更靠后更紧，不能读成 /i/；中文学习者需要和 и 成组对比。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-u",
    ipa: "/u/",
    name: "Russian у",
    category: "vowel",
    example: "луна",
    keywords: [
      { word: "луна", ipa: "/lʊˈna/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "утро", ipa: "/ˈutrə/" },
      { word: "музыка", ipa: "/ˈmuzɨkə/" },
      { word: "суп", ipa: "/sup/" },
      { word: "стул", ipa: "/stul/" },
    ],
    difficulty: "medium",
    description: "圆唇高后元音；非重读时会弱化，但仍要保留圆唇趋势。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-hard-soft",
    ipa: "/C ~ Cʲ/",
    name: "hard vs soft consonants",
    category: "consonant",
    soundUnitType: "contrast",
    example: "брат / брать",
    keywords: [
      { word: "брат", ipa: "/brat/" },
      { word: "брать", ipa: "/bratʲ/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мэр", ipa: "/mɛr/" },
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
    ],
    difficulty: "high",
    description: "俄语不是一个软音，而是成体系的硬/软辅音对；软音时舌面抬向硬腭。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-r",
    ipa: "/r/",
    name: "Russian trilled r",
    category: "consonant",
    example: "река",
    keywords: [
      { word: "река", ipa: "/rʲɪˈka/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "город", ipa: "/ˈgorət/" },
      { word: "рад", ipa: "/rat/" },
      { word: "работа", ipa: "/rɐˈbotə/" },
    ],
    difficulty: "high",
    description: "舌尖颤音，且有硬 /r/ 与软 /rʲ/ 对比；不能替换成英语卷舌 r。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-x",
    ipa: "/x/",
    name: "Russian х",
    category: "consonant",
    example: "хлеб",
    keywords: [
      { word: "хата", ipa: "/ˈxatə/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
      { word: "тихо", ipa: "/ˈtʲixə/" },
      { word: "сахар", ipa: "/ˈsaxər/" },
      { word: "мох", ipa: "/mox/" },
      { word: "холод", ipa: "/ˈxolət/" },
    ],
    difficulty: "medium",
    description: "舌后部靠近软腭摩擦，比英语 /h/ 更靠后、更有摩擦感。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-clusters",
    ipa: "/CC(C)/",
    name: "consonant clusters",
    category: "cluster",
    soundUnitType: "cluster",
    example: "встреча",
    keywords: [
      { word: "встреча", ipa: "/ˈfstrʲet͡ɕə/" },
      { word: "здравствуйте", ipa: "/ˈzdrastvʊjtʲe/" },
      { word: "текст", ipa: "/tʲekst/" },
      { word: "спорт", ipa: "/sport/" },
      { word: "взгляд", ipa: "/vzglʲat/" },
      { word: "стол", ipa: "/stol/" },
    ],
    difficulty: "high",
    description: "俄语辅音丛不能自动插入元音；先慢速保留每个辅音，再逐步加速。",
  }),
];

const RUSSIAN_EXTRA_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "ru-RU",
    slug: "ru-e",
    ipa: "/e ~ ɛ/",
    name: "Russian э/е vowel",
    displayNameZh: "俄语 э/е 元音",
    category: "vowel",
    example: "это",
    keywords: [
      { word: "это", ipa: "/ˈɛtə/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "свет", ipa: "/svʲet/" },
      { word: "нет", ipa: "/nʲet/" },
      { word: "река", ipa: "/rʲɪˈka/" },
      { word: "текст", ipa: "/tʲekst/" },
    ],
    difficulty: "medium",
    description: "俄语 е 常伴随前面辅音软化；э 更硬。这个元音必须和硬软辅音一起练。",
    commonMistakesZh: ["只按拼写读", "忽略 е 前的软化"],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-pb-pair",
    ipa: "/p pʲ b bʲ/",
    name: "labial stop hard-soft pair",
    displayNameZh: "п/б 硬软组",
    category: "consonant",
    soundUnitType: "contrast",
    rolloutPriority: "should",
    example: "пыл / пил",
    keywords: [
      { word: "пыл", ipa: "/pɨl/" },
      { word: "пил", ipa: "/pʲil/" },
      { word: "был", ipa: "/bɨl/" },
      { word: "бить", ipa: "/bʲitʲ/" },
      { word: "пять", ipa: "/pʲatʲ/" },
      { word: "брат", ipa: "/brat/" },
    ],
    difficulty: "medium",
    description: "双唇塞音也有硬软对立，软音时舌面同步抬向硬腭。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-td-pair",
    ipa: "/t tʲ d dʲ/",
    name: "dental stop hard-soft pair",
    displayNameZh: "т/д 硬软组",
    category: "consonant",
    soundUnitType: "contrast",
    example: "там / тянуть",
    keywords: [
      { word: "там", ipa: "/tam/" },
      { word: "тень", ipa: "/tʲenʲ/" },
      { word: "тётя", ipa: "/ˈtʲɵtʲə/" },
      { word: "дом", ipa: "/dom/" },
      { word: "день", ipa: "/dʲenʲ/" },
      { word: "дядя", ipa: "/ˈdʲadʲə/" },
    ],
    difficulty: "high",
    description: "俄语 т/д 的硬软差别非常高频；软音不是后面加一个 /j/，而是辅音本身软化。",
    commonMistakesZh: ["把软音读成辅音 + /j/", "硬软差别消失"],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-sz-pair",
    ipa: "/s sʲ z zʲ/",
    name: "alveolar fricative hard-soft pair",
    displayNameZh: "с/з 硬软组",
    category: "consonant",
    soundUnitType: "contrast",
    rolloutPriority: "should",
    example: "сын / синий",
    keywords: [
      { word: "сын", ipa: "/sɨn/" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/" },
      { word: "нос", ipa: "/nos/" },
      { word: "нести", ipa: "/nʲɪˈsʲtʲi/" },
      { word: "зуб", ipa: "/zup/" },
      { word: "зима", ipa: "/zʲɪˈma/" },
    ],
    difficulty: "high",
    description: "软 /sʲ zʲ/ 更前、更尖；不要全读成中文 s/z。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-fv-pair",
    ipa: "/f fʲ v vʲ/",
    name: "labiodental fricative hard-soft pair",
    displayNameZh: "ф/в 硬软组",
    category: "consonant",
    soundUnitType: "contrast",
    rolloutPriority: "should",
    example: "факт / фильм",
    keywords: [
      { word: "факт", ipa: "/fakt/" },
      { word: "фильм", ipa: "/fʲilʲm/" },
      { word: "кофе", ipa: "/ˈkofʲe/" },
      { word: "вот", ipa: "/vot/" },
      { word: "весь", ipa: "/vʲesʲ/" },
      { word: "вино", ipa: "/vʲɪˈno/" },
    ],
    difficulty: "medium",
    description: "唇齿擦音也会受软化影响；/v/ 还会参与清浊同化和词尾清化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-mn-pair",
    ipa: "/m mʲ n nʲ/",
    name: "nasal hard-soft pair",
    displayNameZh: "м/н 硬软组",
    category: "consonant",
    soundUnitType: "contrast",
    rolloutPriority: "should",
    example: "мать / мять",
    keywords: [
      { word: "мать", ipa: "/matʲ/" },
      { word: "мять", ipa: "/mʲatʲ/" },
      { word: "мы", ipa: "/mɨ/" },
      { word: "мир", ipa: "/mʲir/" },
      { word: "нос", ipa: "/nos/" },
      { word: "нёс", ipa: "/nʲɵs/" },
    ],
    difficulty: "medium",
    description: "鼻音软化时舌面抬起；尤其 /n/ 与 /nʲ/ 对清晰度影响很大。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-kgx-pair",
    ipa: "/k kʲ g gʲ x xʲ/",
    name: "velar hard-soft pair",
    displayNameZh: "к/г/х 硬软组",
    category: "consonant",
    soundUnitType: "contrast",
    rolloutPriority: "later",
    example: "кот / кино",
    keywords: [
      { word: "кот", ipa: "/kot/" },
      { word: "кино", ipa: "/kʲɪˈno/" },
      { word: "год", ipa: "/got/" },
      { word: "герой", ipa: "/gʲɪˈroj/" },
      { word: "хата", ipa: "/ˈxatə/" },
      { word: "хитрый", ipa: "/ˈxʲitrɨj/" },
    ],
    difficulty: "medium",
    description: "软腭音软化有分布限制和例外，第一阶段先认识，不急着做 mastery。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-l-hard-soft",
    ipa: "/l ~ lʲ/",
    name: "hard vs soft l",
    displayNameZh: "л / ль 对比",
    category: "consonant",
    soundUnitType: "contrast",
    example: "лук / люк",
    keywords: [
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мель", ipa: "/mʲelʲ/" },
      { word: "соль", ipa: "/solʲ/" },
      { word: "лампа", ipa: "/ˈlampə/" },
    ],
    difficulty: "high",
    description: "硬 л 厚而后，软 ль 舌面抬高；中文学习者常把两者合并。",
    commonMistakesZh: ["硬 л 不够厚", "软 ль 读成 /lj/"],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-r-hard-soft",
    ipa: "/r ~ rʲ/",
    name: "hard vs soft r",
    displayNameZh: "р / рь 对比",
    category: "consonant",
    soundUnitType: "contrast",
    example: "рад / ряд",
    keywords: [
      { word: "рад", ipa: "/rat/" },
      { word: "ряд", ipa: "/rʲat/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "река", ipa: "/rʲɪˈka/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
    ],
    difficulty: "high",
    description: "俄语 r 既要舌尖颤，又有硬软对立；不能用英语卷舌 r 替代。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-j",
    ipa: "/j/",
    name: "palatal approximant",
    displayNameZh: "й 半元音",
    category: "semivowel",
    rolloutPriority: "should",
    example: "мой",
    keywords: [
      { word: "я", ipa: "/ja/" },
      { word: "мой", ipa: "/moj/" },
      { word: "край", ipa: "/kraj/" },
      { word: "семья", ipa: "/sʲɪˈmʲja/" },
      { word: "йогурт", ipa: "/ˈjogurt/" },
      { word: "дай", ipa: "/daj/" },
    ],
    difficulty: "medium",
    description: "短滑硬腭近音；要和前面辅音的软化区别开。",
    commonMistakesZh: ["把软化和 /j/ 混成一件事", "加额外元音"],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-sh",
    ipa: "/ʂ/",
    name: "hard retroflex-like sh",
    displayNameZh: "ш 硬后擦音",
    category: "consonant",
    example: "шум",
    keywords: [
      { word: "шум", ipa: "/ʂum/" },
      { word: "школа", ipa: "/ˈʂkolə/" },
      { word: "машина", ipa: "/mɐˈʂinə/" },
      { word: "шесть", ipa: "/ʂesʲtʲ/" },
      { word: "шапка", ipa: "/ˈʂapkə/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
    ],
    difficulty: "high",
    description: "舌尖/舌叶后缩，音色比英语 /ʃ/ 更厚，通常为硬音。",
    commonMistakesZh: ["读得太像普通话 sh", "和 щ 软音色混"],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-zh",
    ipa: "/ʐ/",
    name: "hard voiced retroflex-like zh",
    displayNameZh: "ж 硬浊后擦音",
    category: "consonant",
    example: "жук",
    keywords: [
      { word: "жук", ipa: "/ʐuk/" },
      { word: "жена", ipa: "/ʐɨˈna/" },
      { word: "жить", ipa: "/ʐɨtʲ/" },
      { word: "уже", ipa: "/ʊˈʐe/" },
      { word: "нож", ipa: "/noʂ/" },
      { word: "этаж", ipa: "/ɪˈtaʂ/" },
    ],
    difficulty: "high",
    description: "保持后缩和浊音；词尾会清化，所以 нож 末尾实际接近 /ʂ/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ts",
    ipa: "/t͡s/",
    name: "voiceless alveolar affricate",
    displayNameZh: "ц 塞擦音",
    category: "consonant",
    example: "цирк",
    keywords: [
      { word: "цирк", ipa: "/t͡sɨrk/" },
      { word: "улица", ipa: "/ˈulʲɪtsə/" },
      { word: "цена", ipa: "/t͡sɨˈna/" },
      { word: "отец", ipa: "/ɐˈtʲet͡s/" },
      { word: "цвет", ipa: "/t͡svʲet/" },
      { word: "центр", ipa: "/t͡sentr/" },
    ],
    difficulty: "high",
    description: "ц 是硬的 /t͡s/，不要读成普通话 q，也不要软化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ch",
    ipa: "/t͡ɕ/",
    name: "voiceless alveolo-palatal affricate",
    displayNameZh: "ч 软塞擦音",
    category: "consonant",
    example: "чай",
    keywords: [
      { word: "чай", ipa: "/t͡ɕaj/" },
      { word: "часы", ipa: "/t͡ɕɪˈsɨ/" },
      { word: "очень", ipa: "/ˈot͡ɕɪnʲ/" },
      { word: "ночь", ipa: "/not͡ɕ/" },
      { word: "читать", ipa: "/t͡ɕɪˈtatʲ/" },
      { word: "врач", ipa: "/vrat͡ɕ/" },
    ],
    difficulty: "high",
    description: "ч 是软的塞擦音，音色比 ц 更前更软。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-shch",
    ipa: "/ɕː/",
    name: "long alveolo-palatal fricative",
    displayNameZh: "щ 长软擦音",
    category: "consonant",
    example: "щи",
    keywords: [
      { word: "щи", ipa: "/ɕːi/" },
      { word: "щука", ipa: "/ˈɕːukə/" },
      { word: "площадь", ipa: "/ˈploɕːətʲ/" },
      { word: "ещё", ipa: "/jɪˈɕːo/" },
      { word: "товарищ", ipa: "/tɐˈvarʲiɕː/" },
      { word: "вещь", ipa: "/vʲeɕː/" },
    ],
    difficulty: "high",
    description: "щ 更软、更前，且常带长度；不能和硬 ш 混。",
    scoringPolicy: {
      singlePhonemeScore: "no",
      recommendedMode: "word",
      azureRisk: "high",
      notes: "щ 的长度和软音色需要词级/对比级验证，不适合单音素 mastery。",
    },
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-sh-shch-contrast",
    ipa: "/ʂ ~ ɕː/",
    name: "hard vs soft sibilant contrast",
    displayNameZh: "ш / щ 对比",
    category: "consonant",
    soundUnitType: "contrast",
    example: "шит / щит",
    keywords: [
      { word: "шит / щит", ipa: "/ʂit/ /ɕːit/" },
      { word: "шум / щука", ipa: "/ʂum/ /ˈɕːukə/" },
      { word: "наш / вещь", ipa: "/naʂ/ /vʲeɕː/" },
      { word: "машина / площадь", ipa: "/mɐˈʂinə/ /ˈploɕːətʲ/" },
      { word: "шесть / щель", ipa: "/ʂesʲtʲ/ /ɕːelʲ/" },
      { word: "шёл / ещё", ipa: "/ʂol/ /jɪˈɕːo/" },
    ],
    difficulty: "high",
    description: "这是俄语高价值对比：硬厚的 ш 和软长的 щ 必须分开。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ts-ch-contrast",
    ipa: "/t͡s ~ t͡ɕ/",
    name: "ts vs ch contrast",
    displayNameZh: "ц / ч 对比",
    category: "consonant",
    soundUnitType: "contrast",
    example: "цена / чашка",
    keywords: [
      { word: "цирк / чай", ipa: "/t͡sɨrk/ /t͡ɕaj/" },
      { word: "цена / чаша", ipa: "/t͡sɨˈna/ /ˈt͡ɕaʂə/" },
      { word: "отец / ночь", ipa: "/ɐˈtʲet͡s/ /not͡ɕ/" },
      { word: "цвет / человек", ipa: "/t͡svʲet/ /t͡ɕɪlɐˈvʲek/" },
      { word: "улица / учиться", ipa: "/ˈulʲɪt͡sə/ /ʊˈt͡ɕit͡sə/" },
      { word: "центр / часы", ipa: "/t͡sentr/ /t͡ɕɪˈsɨ/" },
    ],
    difficulty: "high",
    description: "ц 更硬，ч 更软更前；不要都读成中文 q/c。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-stress",
    ipa: "/ˈ/",
    name: "lexical stress",
    displayNameZh: "词重音",
    category: "prosody",
    soundUnitType: "prosody",
    example: "за́мок / замо́к",
    keywords: [
      { word: "за́мок / замо́к", ipa: "/ˈzamək/ /zɐˈmok/" },
      { word: "му́ка / мука́", ipa: "/ˈmukə/ /mʊˈka/" },
      { word: "до́ма / дома́", ipa: "/ˈdomə/ /dɐˈma/" },
      { word: "пи́сать / писа́ть", ipa: "/ˈpʲisətʲ/ /pʲɪˈsatʲ/" },
      { word: "го́род / города́", ipa: "/ˈgorət/ /gərɐˈda/" },
      { word: "во́да / вода́", ipa: "/ˈvodə/ /vɐˈda/" },
    ],
    difficulty: "high",
    description: "俄语重音位置不可预测，能改变词义和元音质量；必须独立训练。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-vowel-reduction",
    ipa: "/ɐ ə ɪ/",
    name: "vowel reduction",
    displayNameZh: "非重读元音弱化",
    category: "prosody",
    soundUnitType: "prosody",
    example: "молоко",
    keywords: [
      { word: "молоко", ipa: "/məlɐˈko/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
      { word: "вода", ipa: "/vɐˈda/" },
      { word: "города", ipa: "/gərɐˈda/" },
      { word: "сегодня", ipa: "/sʲɪˈvodnʲə/" },
      { word: "работа", ipa: "/rɐˈbotə/" },
    ],
    difficulty: "high",
    description: "非重读 о/а/е/я 等会弱化；按字母逐个读会非常不像俄语。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-final-devoicing",
    ipa: "/b d g v z ʐ → p t k f s ʂ/",
    name: "final devoicing",
    displayNameZh: "词尾清化",
    category: "prosody",
    soundUnitType: "prosody",
    rolloutPriority: "should",
    example: "друг",
    keywords: [
      { word: "друг", ipa: "/drug/ → [druk]" },
      { word: "хлеб", ipa: "/xlʲeb/ → [xlʲep]" },
      { word: "город", ipa: "/ˈgorəd/ → [ˈgorət]" },
      { word: "нож", ipa: "/noʐ/ → [noʂ]" },
      { word: "мороз", ipa: "/mɐˈroz/ → [mɐˈros]" },
      { word: "клуб", ipa: "/klub/ → [klup]" },
    ],
    difficulty: "medium",
    description: "浊辅音在词尾通常清化；不能完全按字母读。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-voicing-assimilation",
    ipa: "/±voice/",
    name: "voicing assimilation",
    displayNameZh: "清浊同化",
    category: "prosody",
    soundUnitType: "prosody",
    rolloutPriority: "later",
    example: "с другом",
    keywords: [
      { word: "с другом", ipa: "/ˈzdrugəm/" },
      { word: "в парке", ipa: "/fˈparkʲe/" },
      { word: "просьба", ipa: "/ˈprozʲbə/" },
      { word: "сделать", ipa: "/ˈzdʲelətʲ/" },
      { word: "к брату", ipa: "/gˈbratu/" },
      { word: "от дома", ipa: "/ɐdˈdomə/" },
    ],
    difficulty: "high",
    description: "相邻辅音会互相影响清浊；这是短语级训练，不适合单音素评分。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-sign",
    ipa: "/ʲ/",
    name: "soft sign cue",
    displayNameZh: "软音符号 ь",
    category: "prosody",
    soundUnitType: "prosody",
    rolloutPriority: "should",
    example: "мать",
    keywords: [
      { word: "мать", ipa: "/matʲ/" },
      { word: "день", ipa: "/dʲenʲ/" },
      { word: "соль", ipa: "/solʲ/" },
      { word: "пить", ipa: "/pʲitʲ/" },
      { word: "тетрадь", ipa: "/tʲɪˈtratʲ/" },
      { word: "любовь", ipa: "/lʲʊˈbofʲ/" },
    ],
    difficulty: "medium",
    description: "ь 不是独立音，而是提示前一个辅音软化；要和 /j/ 分开。",
  }),
];

export const LANGUAGE_PHONEMES: Record<LanguageId, PhonemeData[]> = {
  "en-US": ENGLISH_PHONEMES,
  "es-ES": [...SPANISH_PHONEMES, ...SPANISH_EXTRA_PHONEMES],
  "fr-FR": [...FRENCH_PHONEMES, ...FRENCH_EXTRA_PHONEMES],
  "ru-RU": [...RUSSIAN_PHONEMES, ...RUSSIAN_EXTRA_PHONEMES],
};

export function getLanguagePhonemes(languageId: LanguageId): PhonemeData[] {
  return LANGUAGE_PHONEMES[languageId];
}

export function getLanguagePhonemesByCategory(
  languageId: LanguageId,
  category: PhonemeCategory,
): PhonemeData[] {
  return LANGUAGE_PHONEMES[languageId].filter((phoneme) => phoneme.category === category);
}

export function getLanguagePhonemeBySlug(
  languageId: LanguageId,
  slug: string,
): PhonemeData | undefined {
  return LANGUAGE_PHONEMES[languageId].find((phoneme) => phoneme.slug === slug);
}

export function getAnyLanguagePhonemeBySlug(slug: string): PhonemeData | undefined {
  return Object.values(LANGUAGE_PHONEMES)
    .flat()
    .find((phoneme) => phoneme.slug === slug);
}

export function getAllLanguagePhonemeSlugs(): string[] {
  return Object.values(LANGUAGE_PHONEMES)
    .flat()
    .map((phoneme) => phoneme.slug);
}

export function hasLocalPhonemeAssets(phoneme: PhonemeData): boolean {
  return phoneme.languageId === "en-US";
}
