import type {
  LanguageId,
  LanguageResourceKind,
  LanguageResourceSite,
} from "@/types/language";

export const LANGUAGE_RESOURCE_SITES: LanguageResourceSite[] = [
  {
    id: "ipa-handbook",
    languageIds: ["es-ES", "fr-FR", "ru-RU"],
    title: "Handbook of the International Phonetic Association",
    url: "https://www.internationalphoneticassociation.org/content/handbook-ipa",
    kind: "phonology-rules",
    strengths: ["IPA 描写框架", "跨语言音位和转写口径", "适合作为课程锚点层基准"],
    limitations: ["不是逐词词典", "不能替代每种语言的母语发音规则"],
    usagePolicy: "manual-verification",
  },
  {
    id: "rae-ngle-phonology",
    languageIds: ["es-ES"],
    title: "RAE/ASALE Nueva gramática: Fonética y fonología",
    url: "https://www.rae.es/obras-academicas/gramatica/nueva-gramatica-de-la-lengua-espanola",
    kind: "phonology-rules",
    strengths: ["西班牙语官方音系参考", "重音、音素、地区变体口径"],
    limitations: ["需要结合具体方言目标和词典审音"],
    usagePolicy: "manual-verification",
  },
  {
    id: "jipa-castilian-spanish",
    languageIds: ["es-ES"],
    title: "Journal of the IPA: Castilian Spanish",
    url: "https://doi.org/10.1017/S0025100303001373",
    kind: "phonology-rules",
    strengths: ["Castilian Spanish IPA inventory", "母语实例和发音实现说明"],
    limitations: ["覆盖 Castilian 口径，不代表所有拉美变体"],
    usagePolicy: "manual-verification",
  },
  {
    id: "jipa-french",
    languageIds: ["fr-FR"],
    title: "Journal of the IPA: French",
    url: "https://doi.org/10.1017/S0025100300004874",
    kind: "phonology-rules",
    strengths: ["法语 IPA inventory", "口腔/鼻化元音和语流现象基准"],
    limitations: ["地区和现代合并现象仍需单独标注"],
    usagePolicy: "manual-verification",
  },
  {
    id: "jipa-russian",
    languageIds: ["ru-RU"],
    title: "Journal of the IPA: Russian",
    url: "https://doi.org/10.1017/S0025100314000395",
    kind: "phonology-rules",
    strengths: ["俄语 IPA inventory", "硬软辅音、重音和弱化描述"],
    limitations: ["词级重音和语流同化仍需词典/母语音频复核"],
    usagePolicy: "manual-verification",
  },
  {
    id: "easypronunciation-es-ipa",
    languageIds: ["es-ES"],
    title: "EasyPronunciation Spanish IPA",
    url: "https://easypronunciation.com/en/spanish-phonetic-transcription-converter",
    kind: "ipa-converter",
    strengths: ["西语词句 IPA", "可对照欧洲/拉美变体", "适合人工复核词表"],
    limitations: ["只作转写校验", "不可把第三方音频打包进仓库"],
    usagePolicy: "manual-verification",
  },
  {
    id: "ipatics-es-ipa",
    languageIds: ["es-ES"],
    title: "IPAtics Spanish to IPA",
    url: "https://www.ipatics.com/tools/spanish-to-ipa",
    kind: "ipa-converter",
    strengths: ["可复核 r/rr、b/v、c/z/s 等规则", "适合短词和短句交叉校验"],
    limitations: ["自动转写仍需人工确认方言"],
    usagePolicy: "manual-verification",
  },
  {
    id: "spanishdict-pronunciation",
    languageIds: ["es-ES"],
    title: "SpanishDict Pronunciation",
    url: "https://www.spanishdict.com/pronunciation",
    kind: "dictionary",
    strengths: ["西班牙/拉美读音参考", "词级音频和例词入口"],
    limitations: ["作为外链参考，不下载音频"],
    usagePolicy: "link-out",
  },
  {
    id: "wiktionary-es",
    languageIds: ["es-ES"],
    title: "Wiktionary Spanish entries",
    url: "https://en.wiktionary.org/wiki/casa#Spanish",
    kind: "dictionary",
    strengths: ["词级 IPA 和变体", "可追溯来源"],
    limitations: ["不同词条质量不均", "引用时保留 URL"],
    usagePolicy: "manual-verification",
  },
  {
    id: "forvo-es",
    languageIds: ["es-ES"],
    title: "Forvo Spanish",
    url: "https://forvo.com/languages/es/",
    kind: "native-audio",
    strengths: ["母语者真实发音参考", "可比较地区差异"],
    limitations: ["只作参考，不打包音频"],
    usagePolicy: "reference-only",
  },
  {
    id: "sounds-of-speech-es",
    languageIds: ["es-ES"],
    title: "Sounds of Speech Spanish",
    url: "https://soundsofspeech.uiowa.edu/spanish",
    kind: "articulation-guide",
    strengths: ["舌位/口型动画", "发音部位解释", "适合替代未授权本地视频"],
    limitations: [
      "本轮仅按用户授权导入 es-ES 核心 sound units；韵律素材仍需补齐",
    ],
    usagePolicy: "manual-verification",
  },
  {
    id: "easypronunciation-fr-ipa",
    languageIds: ["fr-FR"],
    title: "EasyPronunciation French IPA",
    url: "https://easypronunciation.com/en/french-phonetic-transcription-converter",
    kind: "ipa-converter",
    strengths: ["法语词句 IPA", "适合复核鼻化元音和静音词尾"],
    limitations: ["连诵/省音仍需人工判断"],
    usagePolicy: "manual-verification",
  },
  {
    id: "openipa-fr",
    languageIds: ["fr-FR"],
    title: "Open IPA French",
    url: "https://www.openipa.org/transcription/french",
    kind: "ipa-converter",
    strengths: ["可辅助分析 liaison 和 elision", "适合短句训练"],
    limitations: ["自动分析结果需与词典交叉校验"],
    usagePolicy: "manual-verification",
  },
  {
    id: "ipatics-fr-ipa",
    languageIds: ["fr-FR"],
    title: "IPAtics French to IPA",
    url: "https://www.ipatics.com/tools/french-to-ipa",
    kind: "ipa-converter",
    strengths: ["可复核鼻化、法语 r、静音词尾"],
    limitations: ["不替代课程审音"],
    usagePolicy: "manual-verification",
  },
  {
    id: "wiktionary-fr",
    languageIds: ["fr-FR"],
    title: "Wiktionary French entries",
    url: "https://en.wiktionary.org/wiki/bonjour#French",
    kind: "dictionary",
    strengths: ["词级 IPA 和地区变体", "可追溯来源"],
    limitations: ["词条质量不均"],
    usagePolicy: "manual-verification",
  },
  {
    id: "forvo-fr",
    languageIds: ["fr-FR"],
    title: "Forvo French",
    url: "https://forvo.com/languages/fr/",
    kind: "native-audio",
    strengths: ["母语者音频参考", "可比较地区差异"],
    limitations: ["只作参考，不打包音频"],
    usagePolicy: "reference-only",
  },
  {
    id: "lawless-french-ipa",
    languageIds: ["fr-FR"],
    title: "Lawless French IPA",
    url: "https://www.lawlessfrench.com/pronunciation/ipa/",
    kind: "phonology-rules",
    strengths: ["法语 IPA 总表", "鼻化/前圆唇元音说明"],
    limitations: ["不提供完整应用内课程"],
    usagePolicy: "link-out",
  },
  {
    id: "phonetique-ca",
    languageIds: ["fr-FR"],
    title: "Phonetique.ca",
    url: "https://www.phonetique.ca/",
    kind: "articulation-guide",
    strengths: ["法语音位训练", "听辨和发音练习入口"],
    limitations: [
      "本轮按用户授权导入核心元音、辅音和 glide 视频；短语级语流规则素材仍需补齐",
    ],
    usagePolicy: "manual-verification",
  },
  {
    id: "easypronunciation-ru-ipa",
    languageIds: ["ru-RU"],
    title: "EasyPronunciation Russian IPA",
    url: "https://easypronunciation.com/en/russian-phonetic-transcription-converter",
    kind: "ipa-converter",
    strengths: ["俄语词句 IPA", "可复核重音和弱化"],
    limitations: ["词级重音仍要人工确认"],
    usagePolicy: "manual-verification",
  },
  {
    id: "ipatics-ru-ipa",
    languageIds: ["ru-RU"],
    title: "IPAtics Russian to IPA",
    url: "https://www.ipatics.com/tools/russian-to-ipa",
    kind: "ipa-converter",
    strengths: ["重音、软化、非重读元音转写参考"],
    limitations: ["自动转写需用词典/母语音频复核"],
    usagePolicy: "manual-verification",
  },
  {
    id: "easypronunciation-ru-trainer",
    languageIds: ["ru-RU"],
    title: "EasyPronunciation Russian Pronunciation Trainer",
    url: "https://easypronunciation.com/en/practice-russian-pronunciation-online",
    kind: "pronunciation-trainer",
    strengths: ["俄语单词音频", "重音和转写训练参考"],
    limitations: ["只作参考，不下载音频"],
    usagePolicy: "reference-only",
  },
  {
    id: "forvo-ru",
    languageIds: ["ru-RU"],
    title: "Forvo Russian",
    url: "https://forvo.com/languages/ru/",
    kind: "native-audio",
    strengths: ["母语者词级音频参考"],
    limitations: ["只作参考，不打包音频"],
    usagePolicy: "reference-only",
  },
  {
    id: "wiktionary-ru-pronunciation-appendix",
    languageIds: ["ru-RU"],
    title: "Wiktionary Russian Pronunciation Appendix",
    url: "https://en.wiktionary.org/wiki/Appendix:Russian_pronunciation",
    kind: "phonology-rules",
    strengths: ["硬/软辅音", "元音弱化", "IPA 映射规则"],
    limitations: ["规则页不是逐词审音"],
    usagePolicy: "manual-verification",
  },
  {
    id: "wiktionary-ru",
    languageIds: ["ru-RU"],
    title: "Wiktionary Russian entries",
    url: "https://en.wiktionary.org/wiki/%D1%81%D0%BF%D0%B0%D1%81%D0%B8%D0%B1%D0%BE#Russian",
    kind: "dictionary",
    strengths: ["词级 IPA 和重音参考", "可追溯来源"],
    limitations: ["词条质量不均"],
    usagePolicy: "manual-verification",
  },
  {
    id: "seeing-speech-ru",
    languageIds: ["ru-RU"],
    title: "Seeing Speech IPA Charts",
    url: "https://www.seeingspeech.ac.uk/ipa-charts/",
    kind: "articulation-guide",
    strengths: ["IPA 口腔/MRI 视频", "可作为俄语音位与规则 proxy 的本地素材源"],
    limitations: [
      "素材是 IPA 发音动作，不是完整俄语课程；硬软辅音、重音弱化、同化和辅音丛仍需俄语专属讲解",
      "CC BY-NC-ND 4.0，公开分发时必须保留来源、署名和非商业/不改作边界",
    ],
    usagePolicy: "manual-verification",
  },
];

export function getLanguageResourceSites(
  languageId: LanguageId,
): LanguageResourceSite[] {
  return LANGUAGE_RESOURCE_SITES.filter((site) =>
    site.languageIds.includes(languageId),
  );
}

export function getLanguageResourceSite(
  id: string,
): LanguageResourceSite | undefined {
  return LANGUAGE_RESOURCE_SITES.find((site) => site.id === id);
}

export function hasLanguageResourceKind(
  languageId: LanguageId,
  kinds: LanguageResourceKind[],
): boolean {
  return getLanguageResourceSites(languageId).some((site) =>
    kinds.includes(site.kind),
  );
}
