import type { PhonemeData } from "@/types/phoneme";
import { unit } from "@/lib/language-sound-units/utils";

export const RUSSIAN_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "ru-RU",
    slug: "ru-a",
    ipa: "/a/",
    name: "Russian а",
    category: "vowel",
    example: "мама",
    keywords: [
      { word: "мама", ipa: "/ˈmamə/" },
      { word: "да", ipa: "/da/" },
      { word: "там", ipa: "/tam/" },
      { word: "парк", ipa: "/park/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "сахар", ipa: "/ˈsaxər/" },
    ],
    difficulty: "easy",
    description: "重读时清楚开放，非重读时会弱化；俄语元音练习必须带重音位置。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-o",
    ipa: "/o/",
    name: "Russian stressed о",
    category: "vowel",
    example: "дом",
    keywords: [
      { word: "дом", ipa: "/dom/" },
      { word: "кот", ipa: "/kot/" },
      { word: "мост", ipa: "/most/" },
      { word: "нос", ipa: "/nos/" },
      { word: "рот", ipa: "/rot/" },
      { word: "город", ipa: "/ˈgorət/" },
    ],
    difficulty: "medium",
    description:
      "重读 /o/ 圆唇清楚；非重读 о 通常弱化接近 /a/ 或 /ə/，不能只按字母读。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-i",
    ipa: "/i/",
    name: "Russian и",
    category: "vowel",
    example: "мир",
    keywords: [
      { word: "мир", ipa: "/mir/" },
      { word: "лиса", ipa: "/lʲɪˈsa/" },
      { word: "имя", ipa: "/ˈimʲə/" },
      { word: "тихо", ipa: "/ˈtʲixə/" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/" },
      { word: "пить", ipa: "/pʲitʲ/" },
    ],
    difficulty: "medium",
    description: "常让前面的辅音软化；练这个音时要同时听辅音硬软变化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-y",
    ipa: "/ɨ/",
    name: "Russian ы",
    category: "vowel",
    example: "мы",
    keywords: [
      { word: "мы", ipa: "/mɨ/" },
      { word: "сыр", ipa: "/sɨr/" },
      { word: "ты", ipa: "/tɨ/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "быстро", ipa: "/ˈbɨstrə/" },
      { word: "сын", ipa: "/sɨn/" },
    ],
    difficulty: "high",
    description: "舌身更靠后更紧，不能读成 /i/；中文学习者需要和 и 成组对比。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-u",
    ipa: "/u/",
    name: "Russian у",
    category: "vowel",
    example: "луна",
    keywords: [
      { word: "луна", ipa: "/lʊˈna/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "утро", ipa: "/ˈutrə/" },
      { word: "музыка", ipa: "/ˈmuzɨkə/" },
      { word: "суп", ipa: "/sup/" },
      { word: "друг", ipa: "/druk/" },
    ],
    difficulty: "medium",
    description: "圆唇高后元音；非重读时会弱化，但仍要保留圆唇趋势。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-hard-soft",
    ipa: "/C ~ Cʲ/",
    name: "hard vs soft consonants",
    category: "consonant",
    soundUnitType: "contrast",
    example: "брат / брать",
    keywords: [
      { word: "брат", ipa: "/brat/" },
      { word: "брать", ipa: "/bratʲ/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мэр", ipa: "/mɛr/" },
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
    ],
    difficulty: "high",
    description:
      "俄语不是一个软音，而是成体系的硬/软辅音对；软音时舌面抬向硬腭。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-r",
    ipa: "/r/",
    name: "Russian trilled r",
    category: "consonant",
    example: "река",
    keywords: [
      { word: "река", ipa: "/rʲɪˈka/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "город", ipa: "/ˈgorət/" },
      { word: "друг", ipa: "/druk/" },
      { word: "работа", ipa: "/rɐˈbotə/" },
    ],
    difficulty: "high",
    description: "舌尖颤音，且有硬 /r/ 与软 /rʲ/ 对比；不能替换成英语卷舌 r。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-x",
    ipa: "/x/",
    name: "Russian х",
    category: "consonant",
    example: "хлеб",
    keywords: [
      { word: "хлеб", ipa: "/xlʲep/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
      { word: "тихо", ipa: "/ˈtʲixə/" },
      { word: "сахар", ipa: "/ˈsaxər/" },
      { word: "мох", ipa: "/mox/" },
      { word: "холод", ipa: "/ˈxolət/" },
    ],
    difficulty: "medium",
    description: "舌后部靠近软腭摩擦，比英语 /h/ 更靠后、更有摩擦感。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-sh-zh",
    ipa: "/ʂ ʐ/",
    name: "retroflex-like ш/ж",
    category: "consonant",
    soundUnitType: "contrast",
    example: "шум / жук",
    keywords: [
      { word: "шум", ipa: "/ʂum/" },
      { word: "жук", ipa: "/ʐuk/" },
      { word: "школа", ipa: "/ˈʂkolə/" },
      { word: "жена", ipa: "/ʐɨˈna/" },
      { word: "машина", ipa: "/mɐˈʂinə/" },
      { word: "жить", ipa: "/ʐɨtʲ/" },
    ],
    difficulty: "high",
    description:
      "舌尖/舌叶后缩，音色比英语 /ʃ ʒ/ 更厚；注意 ж 后常接 /ɨ/ 音色。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ts-ch-shch",
    ipa: "/ts tɕ ɕː/",
    name: "ц/ч/щ affricate and fricative set",
    category: "consonant",
    soundUnitType: "contrast",
    example: "цирк / чай / щи",
    keywords: [
      { word: "цирк", ipa: "/tsɨrk/" },
      { word: "чай", ipa: "/tɕaj/" },
      { word: "щи", ipa: "/ɕːi/" },
      { word: "улица", ipa: "/ˈulʲɪtsə/" },
      { word: "часы", ipa: "/tɕɪˈsɨ/" },
      { word: "площадь", ipa: "/ˈploɕːətʲ/" },
    ],
    difficulty: "high",
    description: "三个音位置和软硬感不同，不能全部用中文“吃/七”近似替代。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-stress-reduction",
    ipa: "/ˈ + ə ɐ/",
    name: "stress and vowel reduction",
    category: "prosody",
    soundUnitType: "prosody",
    example: "молоко",
    keywords: [
      { word: "молоко", ipa: "/məlɐˈko/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
      { word: "город", ipa: "/ˈgorət/" },
      { word: "мама", ipa: "/ˈmamə/" },
      { word: "работа", ipa: "/rɐˈbotə/" },
      { word: "сегодня", ipa: "/sʲɪˈvodnʲə/" },
    ],
    difficulty: "high",
    description:
      "俄语重音会改变元音质量。这个是句词层训练单位，不应被当成单个音素评分。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-clusters",
    ipa: "/CC(C)/",
    name: "consonant clusters",
    category: "prosody",
    soundUnitType: "prosody",
    example: "встреча",
    keywords: [
      { word: "встреча", ipa: "/ˈfstrʲetɕə/" },
      { word: "здравствуйте", ipa: "/ˈzdrastvʊjtʲe/" },
      { word: "текст", ipa: "/tʲekst/" },
      { word: "спорт", ipa: "/sport/" },
      { word: "взгляд", ipa: "/vzglʲat/" },
      { word: "стол", ipa: "/stol/" },
    ],
    difficulty: "high",
    description: "俄语辅音丛不能自动插入元音；先慢速保留每个辅音，再逐步加速。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-e",
    ipa: "/e/",
    name: "Russian stressed э/е",
    category: "vowel",
    example: "это",
    keywords: [
      { word: "это", ipa: "/ˈetə/", stressText: "э́то" },
      { word: "мэр", ipa: "/mɛr/" },
      { word: "эхо", ipa: "/ˈexə/", stressText: "э́хо" },
      { word: "метро", ipa: "/mʲɪˈtro/", stressText: "метро́" },
      { word: "центр", ipa: "/tsentr/" },
      { word: "текст", ipa: "/tʲekst/" },
      { word: "лес", ipa: "/lʲes/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "семь", ipa: "/sʲemʲ/" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "вечер", ipa: "/ˈvʲetɕɪr/", stressText: "ве́чер" },
      { word: "билет", ipa: "/bʲɪˈlʲet/", stressText: "биле́т" },
      { word: "экзамен", ipa: "/ɪgˈzamʲɪn/", stressText: "экза́мен" },
      { word: "этаж", ipa: "/ɪˈtaʂ/", stressText: "эта́ж" },
      { word: "энергия", ipa: "/ɪˈnʲergʲɪjə/", stressText: "эне́ргия" },
      { word: "десять", ipa: "/ˈdʲesʲɪtʲ/", stressText: "де́сять" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "это лес", ipa: "/ˈetə lʲes/" },
      { word: "вечер в метро", ipa: "/ˈvʲetɕɪr v mʲɪˈtro/" },
      { word: "текст билета", ipa: "/tʲekst bʲɪˈlʲetə/" },
    ],
    difficulty: "medium",
    description:
      "重读 /e/ 清楚；字母 е 往往同时软化前面的辅音，э 通常不软化前辅音。",
    notes: ["把 /e/ 和前面辅音是否软化一起看；мэр /mɛr/ 与 мел /mʲel/ 是好对比。"],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-t-d",
    ipa: "/t tʲ d dʲ/",
    name: "soft т/д",
    category: "consonant",
    soundUnitType: "contrast",
    example: "ток / тётя",
    keywords: [
      { word: "ток", ipa: "/tok/" },
      { word: "тётя", ipa: "/ˈtʲotʲə/" },
      { word: "дом", ipa: "/dom/" },
      { word: "день", ipa: "/dʲenʲ/" },
      { word: "там", ipa: "/tam/" },
      { word: "тень", ipa: "/tʲenʲ/" },
      { word: "да", ipa: "/da/" },
      { word: "дядя", ipa: "/ˈdʲadʲə/", stressText: "дя́дя" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "идти", ipa: "/ɪtˈtʲi/", stressText: "идти́" },
      { word: "тетрадь", ipa: "/tʲɪˈtratʲ/", stressText: "тетра́дь" },
      { word: "дети", ipa: "/ˈdʲetʲɪ/", stressText: "де́ти" },
      { word: "театр", ipa: "/tʲɪˈatr/", stressText: "теа́тр" },
      { word: "долго", ipa: "/ˈdolgə/", stressText: "до́лго" },
      { word: "труд", ipa: "/trut/" },
      { word: "друг", ipa: "/druk/" },
      { word: "ток и тень", ipa: "/tok i tʲenʲ/" },
      { word: "дом и день", ipa: "/dom i dʲenʲ/" },
      { word: "тётя дома", ipa: "/ˈtʲotʲə ˈdomə/" },
      { word: "дети идут", ipa: "/ˈdʲetʲɪ ɪˈdut/" },
    ],
    difficulty: "high",
    description:
      "软化是辅音本身舌面抬高，不是在硬辅音后面加一个完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-t-tj",
    ipa: "/t tʲ/",
    name: "hard-soft т / ть",
    category: "consonant",
    soundUnitType: "contrast",
    example: "там / тень",
    keywords: [
      { word: "там", ipa: "/tam/" },
      { word: "тень", ipa: "/tʲenʲ/" },
      { word: "ток", ipa: "/tok/" },
      { word: "тётя", ipa: "/ˈtʲotʲə/" },
      { word: "ты", ipa: "/tɨ/" },
      { word: "тихо", stressText: "ти́хо", ipa: "/ˈtʲixə/" },
      { word: "театр", stressText: "теа́тр", ipa: "/tʲɪˈatr/" },
      { word: "тетрадь", stressText: "тетра́дь", ipa: "/tʲɪˈtratʲ/" },
      { word: "телефон", stressText: "телефо́н", ipa: "/tʲɪlʲɪˈfon/" },
      { word: "текст", ipa: "/tʲekst/" },
      { word: "транспорт", stressText: "тра́нспорт", ipa: "/ˈtransport/" },
      { word: "трава", stressText: "трава́", ipa: "/trɐˈva/" },
      { word: "стол", ipa: "/stol/" },
      { word: "студент", stressText: "студе́нт", ipa: "/stʊˈdʲent/" },
      { word: "труд", ipa: "/trut/" },
      { word: "товарищ", stressText: "това́рищ", ipa: "/tɐˈvarʲɪɕː/" },
      { word: "ток и тень", ipa: "/tok i tʲenʲ/" },
      { word: "там и тихо", stressText: "там и ти́хо", ipa: "/tam i ˈtʲixə/" },
      { word: "ты и тётя", ipa: "/tɨ i ˈtʲotʲə/" },
      { word: "театр и транспорт", stressText: "теа́тр и тра́нспорт", ipa: "/tʲɪˈatr i ˈtransport/" },
      { word: "тихий текст", stressText: "ти́хий текст", ipa: "/ˈtʲixʲɪj tʲekst/" },
      { word: "тетрадь на столе", stressText: "тетра́дь на столе́", ipa: "/tʲɪˈtratʲ nɐ stɐˈlʲe/" },
      { word: "студент читает", stressText: "студе́нт чита́ет", ipa: "/stʊˈdʲent tɕɪˈtajɪt/" },
      { word: "транспорт стоит", stressText: "тра́нспорт стои́т", ipa: "/ˈtransport stɐˈit/" },
    ],
    difficulty: "medium",
    description:
      "硬 /t/ 和软 /tʲ/ 的差别是舌面抬向硬腭；不要把软 ть 读成硬 /t/ 后面再加完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-d-dj",
    ipa: "/d dʲ/",
    name: "hard-soft д / дь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "дом / день",
    keywords: [
      { word: "да", ipa: "/da/" },
      { word: "день", ipa: "/dʲenʲ/" },
      { word: "дом", ipa: "/dom/" },
      { word: "дядя", stressText: "дя́дя", ipa: "/ˈdʲadʲə/" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "дети", stressText: "де́ти", ipa: "/ˈdʲetʲɪ/" },
      { word: "долго", stressText: "до́лго", ipa: "/ˈdolgə/" },
      { word: "друг", ipa: "/druk/" },
      { word: "дорога", stressText: "доро́га", ipa: "/dɐˈrogə/" },
      { word: "директор", stressText: "дире́ктор", ipa: "/dʲɪˈrʲektər/" },
      { word: "дуб", ipa: "/dup/" },
      { word: "дуба", stressText: "дуба́", ipa: "/duˈba/" },
      { word: "два", ipa: "/dva/" },
      { word: "двадцать", stressText: "два́дцать", ipa: "/ˈdvatsətʲ/" },
      { word: "девушка", stressText: "де́вушка", ipa: "/ˈdʲevʊʂkə/" },
      { word: "делать", stressText: "де́лать", ipa: "/ˈdʲelətʲ/" },
      { word: "дом и день", ipa: "/dom i dʲenʲ/" },
      { word: "да и дядя", stressText: "да и дя́дя", ipa: "/da i ˈdʲadʲə/" },
      { word: "друг дома", stressText: "друг до́ма", ipa: "/drug ˈdomə/" },
      { word: "дети идут", stressText: "де́ти иду́т", ipa: "/ˈdʲetʲɪ ɪˈdut/" },
      { word: "дверь дома", stressText: "дверь до́ма", ipa: "/dvʲerʲ ˈdomə/" },
      { word: "директор дома", stressText: "дире́ктор до́ма", ipa: "/dʲɪˈrʲektər ˈdomə/" },
      { word: "дорога далеко", stressText: "доро́га далеко́", ipa: "/dɐˈrogə dəlʲɪˈko/" },
      { word: "двадцать дней", stressText: "два́дцать дней", ipa: "/ˈdvatsətʲ dʲenʲ/" },
    ],
    difficulty: "medium",
    description:
      "硬 /d/ 和软 /dʲ/ 都是浊塞音；训练时要保留浊音，同时让软 дь 带出前腭化过渡。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-s-z",
    ipa: "/s sʲ z zʲ/",
    name: "soft с/з",
    category: "consonant",
    soundUnitType: "contrast",
    example: "сад / сядь",
    keywords: [
      { word: "сад", ipa: "/sat/" },
      { word: "сядь", ipa: "/sʲatʲ/" },
      { word: "зуб", ipa: "/zup/" },
      { word: "зима", ipa: "/zʲɪˈma/", stressText: "зима́" },
      { word: "сок", ipa: "/sok/" },
      { word: "сено", ipa: "/ˈsʲenə/", stressText: "се́но" },
      { word: "сын", ipa: "/sɨn/" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/", stressText: "си́ний" },
      { word: "звук", ipa: "/zvuk/" },
      { word: "земля", ipa: "/zʲɪˈmlʲa/", stressText: "земля́" },
      { word: "вес", ipa: "/vʲes/" },
      { word: "весь", ipa: "/vʲesʲ/" },
      { word: "сестра", ipa: "/sʲɪˈstra/", stressText: "сестра́" },
      { word: "сказать", ipa: "/skɐˈzatʲ/", stressText: "сказа́ть" },
      { word: "здесь", ipa: "/zdʲesʲ/" },
      { word: "музей", ipa: "/mʊˈzʲej/", stressText: "музе́й" },
      { word: "сад и сено", ipa: "/sat i ˈsʲenə/" },
      { word: "зуб и зима", ipa: "/zup i zʲɪˈma/" },
      { word: "сын синий", ipa: "/sɨn ˈsʲinʲɪj/" },
      { word: "здесь музей", ipa: "/zdʲesʲ mʊˈzʲej/" },
    ],
    difficulty: "high",
    description:
      "软 с/з 的摩擦位置更靠前、更细；硬 с/з 不要被后面的元音自动软化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-n-l-r",
    ipa: "/n nʲ l lʲ r rʲ/",
    name: "soft н/л/р",
    category: "consonant",
    soundUnitType: "contrast",
    example: "лук / люк",
    keywords: [
      { word: "нос", ipa: "/nos/" },
      { word: "нёс", ipa: "/nʲos/" },
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
      { word: "рад", ipa: "/rat/" },
      { word: "ряд", ipa: "/rʲat/" },
      { word: "кон", ipa: "/kon/" },
      { word: "конь", ipa: "/konʲ/" },
      { word: "угол", ipa: "/ˈugəl/", stressText: "у́гол" },
      { word: "уголь", ipa: "/ˈugəlʲ/", stressText: "у́голь" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мель", ipa: "/mʲelʲ/" },
      { word: "река", ipa: "/rʲɪˈka/", stressText: "река́" },
      { word: "рука", ipa: "/rʊˈka/", stressText: "рука́" },
      { word: "сибирь", ipa: "/sʲɪˈbirʲ/", stressText: "Сиби́рь" },
      { word: "линия", ipa: "/ˈlʲinʲɪjə/", stressText: "ли́ния" },
      { word: "нос и нёс", ipa: "/nos i nʲos/" },
      { word: "лук и люк", ipa: "/luk i lʲuk/" },
      { word: "рад и ряд", ipa: "/rat i rʲat/" },
      { word: "угол и уголь", ipa: "/ˈugəl i ˈugəlʲ/" },
    ],
    difficulty: "high",
    description:
      "н/л/р 的硬软对立很高频；软音时舌面抬起，不能只靠后面加 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-s-sj",
    ipa: "/s sʲ/",
    name: "hard-soft с / сь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "сын / синий",
    keywords: [
      { word: "сын", ipa: "/sɨn/" },
      { word: "синий", stressText: "си́ний", ipa: "/ˈsʲinʲɪj/" },
      { word: "сад", ipa: "/sat/" },
      { word: "сено", stressText: "се́но", ipa: "/ˈsʲenə/" },
      { word: "сок", ipa: "/sok/" },
      { word: "семь", ipa: "/sʲemʲ/" },
      { word: "суп", ipa: "/sup/" },
      { word: "село", stressText: "село́", ipa: "/sʲɪˈlo/" },
      { word: "сон", ipa: "/son/" },
      { word: "сеть", ipa: "/sʲetʲ/" },
      { word: "сахар", stressText: "са́хар", ipa: "/ˈsaxər/" },
      { word: "сила", stressText: "си́ла", ipa: "/ˈsʲilə/" },
      { word: "собака", stressText: "соба́ка", ipa: "/sɐˈbakə/" },
      { word: "сестра", stressText: "сестра́", ipa: "/sʲɪˈstra/" },
      { word: "сумка", stressText: "су́мка", ipa: "/ˈsumkə/" },
      { word: "сегодня", stressText: "сего́дня", ipa: "/sʲɪˈvodnʲə/" },
      { word: "сын и синий", stressText: "сын и си́ний", ipa: "/sɨn i ˈsʲinʲɪj/" },
      { word: "сад и сено", stressText: "сад и се́но", ipa: "/sat i ˈsʲenə/" },
      { word: "сон и семь", ipa: "/son i sʲemʲ/" },
      { word: "сок и сеть", ipa: "/sok i sʲetʲ/" },
      { word: "сахар и сила", stressText: "са́хар и си́ла", ipa: "/ˈsaxər i ˈsʲilə/" },
      { word: "собака сегодня", stressText: "соба́ка сего́дня", ipa: "/sɐˈbakə sʲɪˈvodnʲə/" },
      { word: "сестра с сумкой", stressText: "сестра́ с су́мкой", ipa: "/sʲɪˈstra s ˈsumkəj/" },
      { word: "синий сад", stressText: "си́ний сад", ipa: "/ˈsʲinʲɪj sat/" },
    ],
    difficulty: "medium",
    description:
      "硬 /s/ 和软 /sʲ/ 的差别在摩擦位置和舌面抬起；软 сь/си/се 不能读成硬 /s/ 后加完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-z-zj",
    ipa: "/z zʲ/",
    name: "hard-soft з / зь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "зуб / зима",
    keywords: [
      { word: "зуб", ipa: "/zup/" },
      { word: "зима", stressText: "зима́", ipa: "/zʲɪˈma/" },
      { word: "зал", ipa: "/zal/" },
      { word: "земля", stressText: "земля́", ipa: "/zʲɪˈmlʲa/" },
      { word: "звук", ipa: "/zvuk/" },
      { word: "здесь", ipa: "/zdʲesʲ/" },
      { word: "зона", stressText: "зо́на", ipa: "/ˈzonə/" },
      { word: "зеркало", stressText: "зе́ркало", ipa: "/ˈzʲerkələ/" },
      { word: "завтра", stressText: "за́втра", ipa: "/ˈzaftrə/" },
      { word: "зелёный", stressText: "зелёный", ipa: "/zʲɪˈlʲonɨj/" },
      { word: "закон", stressText: "зако́н", ipa: "/zɐˈkon/" },
      { word: "зеркало и зал", stressText: "зе́ркало и зал", ipa: "/ˈzʲerkələ i zal/" },
      { word: "зуб и зима", stressText: "зуб и зима́", ipa: "/zup i zʲɪˈma/" },
      { word: "зал и земля", stressText: "зал и земля́", ipa: "/zal i zʲɪˈmlʲa/" },
      { word: "звук и здесь", ipa: "/zvuk i zdʲesʲ/" },
      { word: "зона и зеркало", stressText: "зо́на и зе́ркало", ipa: "/ˈzonə i ˈzʲerkələ/" },
      { word: "завтра зима", stressText: "за́втра зима́", ipa: "/ˈzaftrə zʲɪˈma/" },
      { word: "зелёная земля", stressText: "зелёная земля́", ipa: "/zʲɪˈlʲonəjə zʲɪˈmlʲa/" },
      { word: "закон здесь", stressText: "зако́н здесь", ipa: "/zɐˈkon zdʲesʲ/" },
      { word: "звук зимой", stressText: "звук зимо́й", ipa: "/zvuk zʲɪˈmoj/" },
    ],
    difficulty: "medium",
    description:
      "硬 /z/ 和软 /zʲ/ 都要保持浊擦音质量；软 зь/зи/зе 的软化不是额外插入一个 й。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-n-nj",
    ipa: "/n nʲ/",
    name: "hard-soft н / нь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "нос / нёс",
    keywords: [
      { word: "нос", ipa: "/nos/" },
      { word: "нёс", ipa: "/nʲos/" },
      { word: "на", ipa: "/na/" },
      { word: "нет", ipa: "/nʲet/" },
      { word: "новый", stressText: "но́вый", ipa: "/ˈnovɨj/" },
      { word: "небо", stressText: "не́бо", ipa: "/ˈnʲebə/" },
      { word: "нога", stressText: "нога́", ipa: "/nɐˈga/" },
      { word: "неделя", stressText: "неде́ля", ipa: "/nʲɪˈdʲelʲə/" },
      { word: "ночь", ipa: "/notɕ/" },
      { word: "няня", stressText: "ня́ня", ipa: "/ˈnʲanʲə/" },
      { word: "номер", stressText: "но́мер", ipa: "/ˈnomʲɪr/" },
      { word: "нитка", stressText: "ни́тка", ipa: "/ˈnʲitkə/" },
      { word: "кон", ipa: "/kon/" },
      { word: "конь", ipa: "/konʲ/" },
      { word: "нос и нёс", ipa: "/nos i nʲos/" },
      { word: "на и нет", ipa: "/na i nʲet/" },
      { word: "новый и небо", stressText: "но́вый и не́бо", ipa: "/ˈnovɨj i ˈnʲebə/" },
      { word: "нога и неделя", stressText: "нога́ и неде́ля", ipa: "/nɐˈga i nʲɪˈdʲelʲə/" },
      { word: "ночь и няня", stressText: "ночь и ня́ня", ipa: "/notɕ i ˈnʲanʲə/" },
      { word: "номер и нитка", stressText: "но́мер и ни́тка", ipa: "/ˈnomʲɪr i ˈnʲitkə/" },
      { word: "кон и конь", ipa: "/kon i konʲ/" },
      { word: "новый номер", stressText: "но́вый но́мер", ipa: "/ˈnovɨj ˈnomʲɪr/" },
      { word: "нет на неделе", stressText: "нет на неде́ле", ipa: "/nʲet nɐ nʲɪˈdʲelʲe/" },
      { word: "няня несёт", stressText: "ня́ня несёт", ipa: "/ˈnʲanʲə nʲɪˈsʲot/" },
    ],
    difficulty: "medium",
    description:
      "硬 /n/ 和软 /nʲ/ 的鼻音位置不同；软 нь/ни/не 要让舌面抬起，而不是在 /n/ 后补一个完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-l-lj",
    ipa: "/l lʲ/",
    name: "hard-soft л / ль",
    category: "consonant",
    soundUnitType: "contrast",
    example: "лук / люк",
    keywords: [
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
      { word: "лак", ipa: "/lak/" },
      { word: "лес", ipa: "/lʲes/" },
      { word: "луна", stressText: "луна́", ipa: "/lʊˈna/" },
      { word: "линия", stressText: "ли́ния", ipa: "/ˈlʲinʲɪjə/" },
      { word: "лампа", stressText: "ла́мпа", ipa: "/ˈlampə/" },
      { word: "любовь", stressText: "любо́вь", ipa: "/lʲʊˈbofʲ/" },
      { word: "стол", ipa: "/stol/" },
      { word: "соль", ipa: "/solʲ/" },
      { word: "ложка", stressText: "ло́жка", ipa: "/ˈloʂkə/" },
      { word: "лиса", stressText: "лиса́", ipa: "/lʲɪˈsa/" },
      { word: "молоко", stressText: "молоко́", ipa: "/məlɐˈko/" },
      { word: "лёд", ipa: "/lʲot/" },
      { word: "лук и люк", ipa: "/luk i lʲuk/" },
      { word: "лак и лес", ipa: "/lak i lʲes/" },
      { word: "луна и линия", stressText: "луна́ и ли́ния", ipa: "/lʊˈna i ˈlʲinʲɪjə/" },
      { word: "лампа и любовь", stressText: "ла́мпа и любо́вь", ipa: "/ˈlampə i lʲʊˈbofʲ/" },
      { word: "стол и соль", ipa: "/stol i solʲ/" },
      { word: "ложка и лиса", stressText: "ло́жка и лиса́", ipa: "/ˈloʂkə i lʲɪˈsa/" },
      { word: "молоко и лёд", stressText: "молоко́ и лёд", ipa: "/məlɐˈko i lʲot/" },
      { word: "луна светит", stressText: "луна́ све́тит", ipa: "/lʊˈna ˈsʲvetʲɪt/" },
      { word: "линия длинная", stressText: "ли́ния дли́нная", ipa: "/ˈlʲinʲɪjə ˈdlʲinːəjə/" },
      { word: "любовь к лесу", stressText: "любо́вь к ле́су", ipa: "/lʲʊˈbofʲ k ˈlʲesʊ/" },
    ],
    difficulty: "high",
    description:
      "硬 /l/ 和软 /lʲ/ 是俄语学习的核心对立；软 ль/ли/ле 要前腭化，不能读成英语式 dark L。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-r-rj",
    ipa: "/r rʲ/",
    name: "hard-soft р / рь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "рад / ряд",
    keywords: [
      { word: "рад", ipa: "/rat/" },
      { word: "ряд", ipa: "/rʲat/" },
      { word: "рот", ipa: "/rot/" },
      { word: "река", stressText: "река́", ipa: "/rʲɪˈka/" },
      { word: "рука", stressText: "рука́", ipa: "/rʊˈka/" },
      { word: "рис", ipa: "/rʲis/" },
      { word: "рыба", stressText: "ры́ба", ipa: "/ˈrɨbə/" },
      { word: "ритм", ipa: "/rʲitm/" },
      { word: "рынок", stressText: "ры́нок", ipa: "/ˈrɨnək/" },
      { word: "ребёнок", stressText: "ребёнок", ipa: "/rʲɪˈbʲonək/" },
      { word: "рано", stressText: "ра́но", ipa: "/ˈranə/" },
      { word: "рядом", stressText: "ря́дом", ipa: "/ˈrʲadəm/" },
      { word: "красный", stressText: "кра́сный", ipa: "/ˈkrasnɨj/" },
      { word: "время", stressText: "вре́мя", ipa: "/ˈvrʲemʲə/" },
      { word: "рад и ряд", ipa: "/rat i rʲat/" },
      { word: "рот и река", stressText: "рот и река́", ipa: "/rot i rʲɪˈka/" },
      { word: "рука и рис", stressText: "рука́ и рис", ipa: "/rʊˈka i rʲis/" },
      { word: "рыба и ритм", stressText: "ры́ба и ритм", ipa: "/ˈrɨbə i rʲitm/" },
      { word: "рынок и ребёнок", stressText: "ры́нок и ребёнок", ipa: "/ˈrɨnək i rʲɪˈbʲonək/" },
      { word: "рано рядом", stressText: "ра́но ря́дом", ipa: "/ˈranə ˈrʲadəm/" },
      { word: "красное время", stressText: "кра́сное вре́мя", ipa: "/ˈkrasnəjə ˈvrʲemʲə/" },
      { word: "рядом река", stressText: "ря́дом река́", ipa: "/ˈrʲadəm rʲɪˈka/" },
      { word: "рад ребёнку", stressText: "рад ребёнку", ipa: "/rat rʲɪˈbʲonkʊ/" },
      { word: "рыба рядом", stressText: "ры́ба ря́дом", ipa: "/ˈrɨbə ˈrʲadəm/" },
    ],
    difficulty: "high",
    description:
      "硬 /r/ 和软 /rʲ/ 都保持俄语颤音/闪颤性质；软 рь/ри/ре 需要前腭化，不能退回英语 r。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-labials",
    ipa: "/pʲ bʲ mʲ fʲ vʲ/",
    name: "soft labials",
    category: "consonant",
    soundUnitType: "contrast",
    example: "пять",
    keywords: [
      { word: "пять", ipa: "/pʲatʲ/" },
      { word: "билет", ipa: "/bʲɪˈlʲet/", stressText: "биле́т" },
      { word: "мир", ipa: "/mir/" },
      { word: "фильм", ipa: "/fʲilʲm/" },
      { word: "вес", ipa: "/vʲes/" },
      { word: "весь", ipa: "/vʲesʲ/" },
      { word: "пить", ipa: "/pʲitʲ/" },
      { word: "белый", ipa: "/ˈbʲelɨj/", stressText: "бе́лый" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мель", ipa: "/mʲelʲ/" },
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "любовь", ipa: "/lʲʊˈbofʲ/", stressText: "любо́вь" },
      { word: "время", ipa: "/ˈvrʲemʲə/", stressText: "вре́мя" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "письмо", ipa: "/pʲɪsʲˈmo/", stressText: "письмо́" },
      { word: "автобус", ipa: "/ɐfˈtobʊs/", stressText: "авто́бус" },
      { word: "пять билетов", ipa: "/pʲatʲ bʲɪˈlʲetəf/" },
      { word: "мир и фильм", ipa: "/mir i fʲilʲm/" },
      { word: "вес весь", ipa: "/vʲes vʲesʲ/" },
      { word: "семья любит", ipa: "/sʲɪmʲˈja ˈlʲubʲɪt/" },
    ],
    difficulty: "high",
    description:
      "双唇/唇齿辅音也会软化；嘴唇动作不变，但舌面同时抬向硬腭。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-p-pj",
    ipa: "/p pʲ/",
    name: "hard-soft п / пь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "пыл / пить",
    keywords: [
      { word: "пыл", ipa: "/pɨl/" },
      { word: "пить", ipa: "/pʲitʲ/" },
      { word: "парк", ipa: "/park/" },
      { word: "пять", ipa: "/pʲatʲ/" },
      { word: "пол", ipa: "/pol/" },
      { word: "пёс", ipa: "/pʲos/" },
      { word: "пара", stressText: "па́ра", ipa: "/ˈparə/" },
      { word: "песня", stressText: "пе́сня", ipa: "/ˈpʲesʲnʲə/" },
      { word: "папа", stressText: "па́па", ipa: "/ˈpapə/" },
      { word: "письмо", stressText: "письмо́", ipa: "/pʲɪsʲˈmo/" },
      { word: "плащ", ipa: "/plaɕː/" },
      { word: "пир", ipa: "/pʲir/" },
      { word: "порог", stressText: "поро́г", ipa: "/pɐˈrok/" },
      { word: "перец", stressText: "пе́рец", ipa: "/ˈpʲerʲɪts/" },
      { word: "путешествие", stressText: "путеше́ствие", ipa: "/pʊtʲɪˈʂestvʲɪjə/" },
      { word: "певец", stressText: "певе́ц", ipa: "/pʲɪˈvʲets/" },
      { word: "пыл и пить", ipa: "/pɨl i pʲitʲ/" },
      { word: "парк и пять", ipa: "/park i pʲatʲ/" },
      { word: "пол и пёс", ipa: "/pol i pʲos/" },
      { word: "пара и песня", stressText: "па́ра и пе́сня", ipa: "/ˈparə i ˈpʲesʲnʲə/" },
      { word: "папа пишет", stressText: "па́па пи́шет", ipa: "/ˈpapə ˈpʲiʂɨt/" },
      { word: "письмо пришло", stressText: "письмо́ пришло́", ipa: "/pʲɪsʲˈmo prʲɪˈʂlo/" },
      { word: "пять песен", stressText: "пять пе́сен", ipa: "/pʲatʲ ˈpʲesʲɪn/" },
      { word: "парк перед домом", stressText: "парк пе́ред до́мом", ipa: "/park ˈpʲerʲɪt ˈdoməm/" },
    ],
    difficulty: "medium",
    description:
      "硬 /p/ 和软 /pʲ/ 的差别在舌面是否同时抬向硬腭，不是英语式送气对立。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-b-bj",
    ipa: "/b bʲ/",
    name: "hard-soft б / бь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "был / бил",
    keywords: [
      { word: "был", ipa: "/bɨl/" },
      { word: "бил", ipa: "/bʲil/" },
      { word: "бок", ipa: "/bok/" },
      { word: "белый", stressText: "бе́лый", ipa: "/ˈbʲelɨj/" },
      { word: "брат", ipa: "/brat/" },
      { word: "брать", ipa: "/bratʲ/" },
      { word: "быт", ipa: "/bɨt/" },
      { word: "бить", ipa: "/bʲitʲ/" },
      { word: "банк", ipa: "/bank/" },
      { word: "билет", stressText: "биле́т", ipa: "/bʲɪˈlʲet/" },
      { word: "буду", stressText: "бу́ду", ipa: "/ˈbudu/" },
      { word: "беда", stressText: "беда́", ipa: "/bʲɪˈda/" },
      { word: "бор", ipa: "/bor/" },
      { word: "берёза", stressText: "берёза", ipa: "/bʲɪˈrʲozə/" },
      { word: "Борис", stressText: "Бори́с", ipa: "/bɐˈrʲis/" },
      { word: "беречь", stressText: "бере́чь", ipa: "/bʲɪˈrʲetɕ/" },
      { word: "большой", stressText: "большо́й", ipa: "/bɐlʲˈʂoj/" },
      { word: "был и бил", ipa: "/bɨl i bʲil/" },
      { word: "брат и брать", ipa: "/brat i bratʲ/" },
      { word: "бок и белый", stressText: "бок и бе́лый", ipa: "/bok i ˈbʲelɨj/" },
      { word: "банк и билет", stressText: "банк и биле́т", ipa: "/bank i bʲɪˈlʲet/" },
      { word: "белый билет", stressText: "бе́лый биле́т", ipa: "/ˈbʲelɨj bʲɪˈlʲet/" },
      { word: "брат берёт", stressText: "брат берёт", ipa: "/brat bʲɪˈrʲot/" },
      { word: "банк большой", stressText: "банк большо́й", ipa: "/bank bɐlʲˈʂoj/" },
    ],
    difficulty: "medium",
    description:
      "硬 /b/ 与软 /bʲ/ 都是双唇浊塞音；训练重点是软音的前腭化过渡。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-m-mj",
    ipa: "/m mʲ/",
    name: "hard-soft м / мь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "мэр / мел",
    keywords: [
      { word: "мэр", ipa: "/mɛr/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мать", ipa: "/matʲ/" },
      { word: "мять", ipa: "/mʲatʲ/" },
      { word: "мой", ipa: "/moj/" },
      { word: "мир", ipa: "/mʲir/" },
      { word: "мыл", ipa: "/mɨl/" },
      { word: "мил", ipa: "/mʲil/" },
      { word: "мак", ipa: "/mak/" },
      { word: "мяч", ipa: "/mʲatɕ/" },
      { word: "мама", stressText: "ма́ма", ipa: "/ˈmamə/" },
      { word: "место", stressText: "ме́сто", ipa: "/ˈmʲestə/" },
      { word: "март", ipa: "/mart/" },
      { word: "метр", ipa: "/mʲetr/" },
      { word: "молоко", stressText: "молоко́", ipa: "/məlɐˈko/" },
      { word: "минута", stressText: "мину́та", ipa: "/mʲɪˈnutə/" },
      { word: "мэр и мел", ipa: "/mɛr i mʲel/" },
      { word: "мать и мять", ipa: "/matʲ i mʲatʲ/" },
      { word: "мой мир", ipa: "/moj mʲir/" },
      { word: "мак и мяч", ipa: "/mak i mʲatɕ/" },
      { word: "мама мыла", stressText: "ма́ма мы́ла", ipa: "/ˈmamə ˈmɨlə/" },
      { word: "место на карте", stressText: "ме́сто на ка́рте", ipa: "/ˈmʲestə nɐ ˈkartʲe/" },
      { word: "минута молчания", stressText: "мину́та молча́ния", ipa: "/mʲɪˈnutə mɐlˈtɕanʲɪjə/" },
      { word: "мел между книгами", stressText: "мел ме́жду кни́гами", ipa: "/mʲel ˈmʲeʐdʊ ˈknʲigəmʲɪ/" },
    ],
    difficulty: "medium",
    description:
      "硬 /m/ 与软 /mʲ/ 都是双唇鼻音，不能简单套用英语 /m/；软音要带舌面抬起。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-f-fj",
    ipa: "/f fʲ/",
    name: "hard-soft ф / фь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "факт / фильм",
    keywords: [
      { word: "факт", ipa: "/fakt/" },
      { word: "фильм", ipa: "/fʲilʲm/" },
      { word: "фаза", stressText: "фа́за", ipa: "/ˈfazə/" },
      { word: "финал", stressText: "фина́л", ipa: "/fʲɪˈnal/" },
      { word: "форма", stressText: "фо́рма", ipa: "/ˈformə/" },
      { word: "фирма", stressText: "фи́рма", ipa: "/ˈfʲirmə/" },
      { word: "фон", ipa: "/fon/" },
      { word: "февраль", stressText: "февра́ль", ipa: "/fʲɪˈvralʲ/" },
      { word: "фокус", stressText: "фо́кус", ipa: "/ˈfokʊs/" },
      { word: "физика", stressText: "фи́зика", ipa: "/ˈfʲizʲɪkə/" },
      { word: "футбол", stressText: "футбо́л", ipa: "/fʊdˈbol/" },
      { word: "ферма", stressText: "фе́рма", ipa: "/ˈfʲermə/" },
      { word: "шкаф", ipa: "/ʂkaf/" },
      { word: "эфир", stressText: "эфи́р", ipa: "/ɪˈfʲir/" },
      { word: "факт и фильм", ipa: "/fakt i fʲilʲm/" },
      { word: "форма и фирма", stressText: "фо́рма и фи́рма", ipa: "/ˈformə i ˈfʲirmə/" },
      { word: "фон и ферма", stressText: "фон и фе́рма", ipa: "/fon i ˈfʲermə/" },
      { word: "фаза и физика", stressText: "фа́за и фи́зика", ipa: "/ˈfazə i ˈfʲizʲɪkə/" },
      { word: "новый факт", stressText: "но́вый факт", ipa: "/ˈnovɨj fakt/" },
      { word: "хороший фильм", stressText: "хоро́ший фильм", ipa: "/xɐˈroʂɨj fʲilʲm/" },
      { word: "футбол в феврале", stressText: "футбо́л в феврале́", ipa: "/fʊdˈbol v fʲɪvraˈlʲe/" },
      { word: "фокус фильма", stressText: "фо́кус фи́льма", ipa: "/ˈfokʊs ˈfʲilʲmə/" },
      { word: "ферма рядом", stressText: "фе́рма ря́дом", ipa: "/ˈfʲermə ˈrʲadəm/" },
      { word: "шкаф фирмы", stressText: "шкаф фи́рмы", ipa: "/ʂkaf ˈfʲirmɨ/" },
    ],
    difficulty: "medium",
    description:
      "硬 /f/ 与软 /fʲ/ 多见于借词和国际词，但仍需要按俄语硬软系统训练。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-v-vj",
    ipa: "/v vʲ/",
    name: "hard-soft в / вь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "вот / вес",
    keywords: [
      { word: "вот", ipa: "/vot/" },
      { word: "вес", ipa: "/vʲes/" },
      { word: "вал", ipa: "/val/" },
      { word: "вёл", ipa: "/vʲol/" },
      { word: "вы", ipa: "/vɨ/" },
      { word: "вид", ipa: "/vʲit/" },
      { word: "вода", stressText: "вода́", ipa: "/vɐˈda/" },
      { word: "вечер", stressText: "ве́чер", ipa: "/ˈvʲetɕɪr/" },
      { word: "ваш", ipa: "/vaʂ/" },
      { word: "весь", ipa: "/vʲesʲ/" },
      { word: "война", stressText: "война́", ipa: "/vɐjˈna/" },
      { word: "весна", stressText: "весна́", ipa: "/vʲɪsˈna/" },
      { word: "ваза", stressText: "ва́за", ipa: "/ˈvazə/" },
      { word: "ветер", stressText: "ве́тер", ipa: "/ˈvʲetʲɪr/" },
      { word: "время", stressText: "вре́мя", ipa: "/ˈvrʲemʲə/" },
      { word: "вино", stressText: "вино́", ipa: "/vʲɪˈno/" },
      { word: "вот и вес", ipa: "/vot i vʲes/" },
      { word: "вал и вёл", ipa: "/val i vʲol/" },
      { word: "вы и вид", ipa: "/vɨ i vʲit/" },
      { word: "вода и вечер", stressText: "вода́ и ве́чер", ipa: "/vɐˈda i ˈvʲetɕɪr/" },
      { word: "ваш и весь", ipa: "/vaʂ i vʲesʲ/" },
      { word: "весна в городе", stressText: "весна́ в го́роде", ipa: "/vʲɪsˈna v ˈgorədʲe/" },
      { word: "ветер во дворе", stressText: "ве́тер во дворе́", ipa: "/ˈvʲetʲɪr vɐ dvɐˈrʲe/" },
      { word: "вино вечером", stressText: "вино́ ве́чером", ipa: "/vʲɪˈno ˈvʲetɕɪrəm/" },
    ],
    difficulty: "medium",
    description:
      "硬 /v/ 和软 /vʲ/ 的软化要和词尾清化、跨词清浊同化分开讲，避免混成一个规则。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-k-kj",
    ipa: "/k kʲ/",
    name: "hard-soft к / кь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "кот / кит",
    keywords: [
      { word: "кот", ipa: "/kot/" },
      { word: "кит", ipa: "/kʲit/" },
      { word: "как", ipa: "/kak/" },
      { word: "кино", stressText: "кино́", ipa: "/kʲɪˈno/" },
      { word: "класс", ipa: "/klas/" },
      { word: "кефир", stressText: "кефи́р", ipa: "/kʲɪˈfʲir/" },
      { word: "карта", stressText: "ка́рта", ipa: "/ˈkartə/" },
      { word: "кислый", stressText: "ки́слый", ipa: "/ˈkʲislɨj/" },
      { word: "комната", stressText: "ко́мната", ipa: "/ˈkomnətə/" },
      { word: "кирпич", stressText: "кирпи́ч", ipa: "/kʲɪrˈpʲitɕ/" },
      { word: "курс", ipa: "/kurs/" },
      { word: "кедр", ipa: "/kʲedr/" },
      { word: "камень", stressText: "ка́мень", ipa: "/ˈkamʲɪnʲ/" },
      { word: "книга", stressText: "кни́га", ipa: "/ˈknʲigə/" },
      { word: "кухня", stressText: "ку́хня", ipa: "/ˈkuxnʲə/" },
      { word: "кисть", ipa: "/kʲistʲ/" },
      { word: "кот и кит", ipa: "/kot i kʲit/" },
      { word: "как и кино", stressText: "как и кино́", ipa: "/kak i kʲɪˈno/" },
      { word: "класс и кефир", stressText: "класс и кефи́р", ipa: "/klas i kʲɪˈfʲir/" },
      { word: "карта и кит", stressText: "ка́рта и кит", ipa: "/ˈkartə i kʲit/" },
      { word: "книга на кухне", stressText: "кни́га на ку́хне", ipa: "/ˈknʲigə nɐ ˈkuxnʲe/" },
      { word: "кино и класс", stressText: "кино́ и класс", ipa: "/kʲɪˈno i klas/" },
      { word: "кефир в комнате", stressText: "кефи́р в ко́мнате", ipa: "/kʲɪˈfʲir f ˈkomnətʲe/" },
      { word: "тихий кит", stressText: "ти́хий кит", ipa: "/ˈtʲixʲɪj kʲit/" },
    ],
    difficulty: "medium",
    description:
      "硬 /k/ 和软 /kʲ/ 都是软腭塞音；软 кь/ки/ке 的舌面要前抬，不要读成硬 /k/ 后面再加完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-g-gj",
    ipa: "/g gʲ/",
    name: "hard-soft г / гь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "газ / герой",
    keywords: [
      { word: "газ", ipa: "/gas/" },
      { word: "герой", stressText: "геро́й", ipa: "/gʲɪˈroj/" },
      { word: "год", ipa: "/got/" },
      { word: "гитара", stressText: "гита́ра", ipa: "/gʲɪˈtarə/" },
      { word: "гора", stressText: "гора́", ipa: "/gɐˈra/" },
      { word: "гений", stressText: "ге́ний", ipa: "/ˈgʲenʲɪj/" },
      { word: "гол", ipa: "/gol/" },
      { word: "гимн", ipa: "/gʲimn/" },
      { word: "группа", stressText: "гру́ппа", ipa: "/ˈgrupə/" },
      { word: "герб", ipa: "/gʲerp/" },
      { word: "гулять", stressText: "гуля́ть", ipa: "/gʊˈlʲatʲ/" },
      { word: "гектар", stressText: "ге́ктар", ipa: "/ˈgʲektər/" },
      { word: "вагон", stressText: "ваго́н", ipa: "/vɐˈgon/" },
      { word: "книга", stressText: "кни́га", ipa: "/ˈknʲigə/" },
      { word: "ноги", stressText: "но́ги", ipa: "/ˈnogʲɪ/" },
      { word: "дорогой", stressText: "дорого́й", ipa: "/dərɐˈgoj/" },
      { word: "газ и герой", stressText: "газ и геро́й", ipa: "/gas i gʲɪˈroj/" },
      { word: "год и гитара", stressText: "год и гита́ра", ipa: "/got i gʲɪˈtarə/" },
      { word: "гора и гений", stressText: "гора́ и ге́ний", ipa: "/gɐˈra i ˈgʲenʲɪj/" },
      { word: "группа и гимн", stressText: "гру́ппа и гимн", ipa: "/ˈgrupə i gʲimn/" },
      { word: "дорогой герой", stressText: "дорого́й геро́й", ipa: "/dərɐˈgoj gʲɪˈroj/" },
      { word: "книга героя", stressText: "кни́га геро́я", ipa: "/ˈknʲigə gʲɪˈrojə/" },
      { word: "гитара в группе", stressText: "гита́ра в гру́ппе", ipa: "/gʲɪˈtarə v ˈgrupʲe/" },
      { word: "город и герой", stressText: "го́род и геро́й", ipa: "/ˈgorət i gʲɪˈroj/" },
    ],
    difficulty: "medium",
    description:
      "硬 /g/ 和软 /gʲ/ 的对立仍属于俄语硬软系统；软 гь/ги/ге 不能用英语 /g/ 加 /j/ 粗略替代。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-x-xj",
    ipa: "/x xʲ/",
    name: "hard-soft х / хь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "хор / хит",
    keywords: [
      { word: "хор", ipa: "/xor/" },
      { word: "хит", ipa: "/xʲit/" },
      { word: "холод", stressText: "хо́лод", ipa: "/ˈxolət/" },
      { word: "химия", stressText: "хи́мия", ipa: "/ˈxʲimʲɪjə/" },
      { word: "хлеб", ipa: "/xlʲep/" },
      { word: "хищник", stressText: "хи́щник", ipa: "/ˈxʲiɕːnʲɪk/" },
      { word: "смех", ipa: "/smʲex/" },
      { word: "тихий", stressText: "ти́хий", ipa: "/ˈtʲixʲɪj/" },
      { word: "ухо", stressText: "у́хо", ipa: "/ˈuxə/" },
      { word: "хитрый", stressText: "хи́трый", ipa: "/ˈxʲitrɨj/" },
      { word: "хата", stressText: "ха́та", ipa: "/ˈxatə/" },
      { word: "хоккей", stressText: "хокке́й", ipa: "/xɐˈkʲej/" },
      { word: "сухой", stressText: "сухо́й", ipa: "/sʊˈxoj/" },
      { word: "архив", stressText: "архи́в", ipa: "/ɐrˈxʲif/" },
      { word: "муха", stressText: "му́ха", ipa: "/ˈmuxə/" },
      { word: "мухи", stressText: "му́хи", ipa: "/ˈmuxʲɪ/" },
      { word: "хор и хит", ipa: "/xor i xʲit/" },
      { word: "холод и химия", stressText: "хо́лод и хи́мия", ipa: "/ˈxolət i ˈxʲimʲɪjə/" },
      { word: "смех и тихий", stressText: "смех и ти́хий", ipa: "/smʲex i ˈtʲixʲɪj/" },
      { word: "ухо и мухи", stressText: "у́хо и му́хи", ipa: "/ˈuxə i ˈmuxʲɪ/" },
      { word: "хороший хлеб", stressText: "хоро́ший хлеб", ipa: "/xɐˈroʂɨj xlʲep/" },
      { word: "химия в архиве", stressText: "хи́мия в архи́ве", ipa: "/ˈxʲimʲɪjə v ɐrˈxʲivʲe/" },
      { word: "сухой холод", stressText: "сухо́й хо́лод", ipa: "/sʊˈxoj ˈxolət/" },
      { word: "хитрый ход", stressText: "хи́трый ход", ipa: "/ˈxʲitrɨj xot/" },
    ],
    difficulty: "high",
    description:
      "硬 /x/ 和软 /xʲ/ 都是俄语 х 的核心实现；软化时摩擦位置更前，不能退回英语 /h/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-sign",
    ipa: "/ʲ/",
    name: "soft sign ь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "мать",
    keywords: [
      { word: "мать", ipa: "/matʲ/" },
      { word: "уголь", ipa: "/ˈugəlʲ/", stressText: "у́голь" },
      { word: "день", ipa: "/dʲenʲ/" },
      { word: "письмо", ipa: "/pʲɪsʲˈmo/", stressText: "письмо́" },
      { word: "конь", ipa: "/konʲ/" },
      { word: "мель", ipa: "/mʲelʲ/" },
      { word: "пить", ipa: "/pʲitʲ/" },
      { word: "брать", ipa: "/bratʲ/" },
      { word: "семь", ipa: "/sʲemʲ/" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "ночь", ipa: "/notɕ/" },
      { word: "помощь", ipa: "/ˈpoməɕː/", stressText: "по́мощь" },
      { word: "сибирь", ipa: "/sʲɪˈbirʲ/", stressText: "Сиби́рь" },
      { word: "учитель", ipa: "/ʊˈtɕitʲɪlʲ/", stressText: "учи́тель" },
      { word: "любовь", ipa: "/lʲʊˈbofʲ/", stressText: "любо́вь" },
      { word: "июнь", ipa: "/ɪˈjunʲ/", stressText: "ию́нь" },
      { word: "мат и мать", ipa: "/mat i matʲ/" },
      { word: "угол и уголь", ipa: "/ˈugəl i ˈugəlʲ/" },
      { word: "кон и конь", ipa: "/kon i konʲ/" },
      { word: "пить письмо", ipa: "/pʲitʲ pʲɪsʲˈmo/" },
    ],
    difficulty: "high",
    description:
      "软音符号不发独立声音，它改变前一个辅音的软化；训练时要显示出来但不能读成一个额外音节。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ts",
    ipa: "/ts/",
    name: "Russian ц",
    category: "consonant",
    example: "царь",
    keywords: [
      { word: "царь", ipa: "/tsarʲ/" },
      { word: "цена", ipa: "/tsɨˈna/", stressText: "цена́" },
      { word: "центр", ipa: "/tsentr/" },
      { word: "улица", ipa: "/ˈulʲɪtsə/", stressText: "у́лица" },
      { word: "конец", ipa: "/kɐˈnʲets/", stressText: "коне́ц" },
      { word: "цирк", ipa: "/tsɨrk/" },
      { word: "цепь", ipa: "/tsepʲ/" },
      { word: "танец", ipa: "/ˈtanʲɪts/", stressText: "та́нец" },
      { word: "отец", ipa: "/ɐˈtʲets/", stressText: "оте́ц" },
      { word: "птица", ipa: "/ˈptʲitsə/", stressText: "пти́ца" },
      { word: "станция", ipa: "/ˈstantsɨjə/", stressText: "ста́нция" },
      { word: "традиция", ipa: "/trɐˈdʲitsɨjə/", stressText: "тради́ция" },
      { word: "месяц", ipa: "/ˈmʲesʲɪts/", stressText: "ме́сяц" },
      { word: "двадцать", ipa: "/ˈdvatsətʲ/", stressText: "два́дцать" },
      { word: "пятьдесят", ipa: "/pʲɪdʲɪˈsʲat/", stressText: "пятьдеся́т" },
      { word: "процент", ipa: "/prɐˈtsent/", stressText: "проце́нт" },
      { word: "цена центра", ipa: "/tsɨˈna ˈtsentrə/" },
      { word: "улица и центр", ipa: "/ˈulʲɪtsə i tsentr/" },
      { word: "цирк в конце", ipa: "/tsɨrk f kɐˈnʲtse/" },
      { word: "отец танцует", ipa: "/ɐˈtʲets tɐnˈtsujɪt/" },
    ],
    difficulty: "medium",
    description: "ц 是 /ts/，通常偏硬；不要把后面的 и 读成普通 /i/ 的软化环境。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ch",
    ipa: "/tɕ/",
    name: "Russian ч",
    category: "consonant",
    example: "чай",
    keywords: [
      { word: "чай", ipa: "/tɕaj/" },
      { word: "час", ipa: "/tɕas/" },
      { word: "читать", ipa: "/tɕɪˈtatʲ/", stressText: "чита́ть" },
      { word: "человек", ipa: "/tɕɪlɐˈvʲek/", stressText: "челове́к" },
      { word: "ключ", ipa: "/klʲutɕ/" },
      { word: "чашка", ipa: "/ˈtɕaʂkə/", stressText: "ча́шка" },
      { word: "часто", ipa: "/ˈtɕastə/", stressText: "ча́сто" },
      { word: "вечер", ipa: "/ˈvʲetɕɪr/", stressText: "ве́чер" },
      { word: "учить", ipa: "/ʊˈtɕitʲ/", stressText: "учи́ть" },
      { word: "учитель", ipa: "/ʊˈtɕitʲɪlʲ/", stressText: "учи́тель" },
      { word: "дочь", ipa: "/dotɕ/" },
      { word: "ночь", ipa: "/notɕ/" },
      { word: "мяч", ipa: "/mʲatɕ/" },
      { word: "врач", ipa: "/vratɕ/" },
      { word: "почему", ipa: "/pətɕɪˈmu/", stressText: "почему́" },
      { word: "часы", ipa: "/tɕɪˈsɨ/", stressText: "часы́" },
      { word: "чай и час", ipa: "/tɕaj i tɕas/" },
      { word: "читать вечером", ipa: "/tɕɪˈtatʲ ˈvʲetɕɪrəm/" },
      { word: "учитель читает", ipa: "/ʊˈtɕitʲɪlʲ tɕɪˈtajɪt/" },
      { word: "чашка чая", ipa: "/ˈtɕaʂkə ˈtɕajə/" },
    ],
    difficulty: "high",
    description: "ч 通常偏软，是紧凑的 /tɕ/；不要把它读成硬 /tʃ/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-shch",
    ipa: "/ɕː/",
    name: "Russian щ",
    category: "consonant",
    example: "щи",
    keywords: [
      { word: "щи", ipa: "/ɕːi/" },
      { word: "щука", ipa: "/ˈɕːukə/", stressText: "щу́ка" },
      { word: "ещё", ipa: "/jɪˈɕːo/" },
      { word: "площадь", ipa: "/ˈploɕːətʲ/", stressText: "пло́щадь" },
      { word: "помощь", ipa: "/ˈpoməɕː/", stressText: "по́мощь" },
      { word: "борщ", ipa: "/borɕː/" },
      { word: "товарищ", ipa: "/tɐˈvarʲɪɕː/", stressText: "това́рищ" },
      { word: "щётка", ipa: "/ˈɕːotkə/" },
      { word: "ящик", ipa: "/ˈjaɕːɪk/", stressText: "я́щик" },
      { word: "женщина", ipa: "/ˈʐenɕːɪnə/", stressText: "же́нщина" },
      { word: "будущий", ipa: "/ˈbuduɕːɪj/", stressText: "бу́дущий" },
      { word: "ищу", ipa: "/ɪˈɕːu/", stressText: "ищу́" },
      { word: "защита", ipa: "/zɐˈɕːitə/", stressText: "защи́та" },
      { word: "вещь", ipa: "/vʲeɕː/" },
      { word: "роща", ipa: "/ˈroɕːə/", stressText: "ро́ща" },
      { word: "общий", ipa: "/ˈopɕːɪj/", stressText: "о́бщий" },
      { word: "борщ и щи", ipa: "/borɕː i ɕːi/" },
      { word: "помощь нужна", ipa: "/ˈpoməɕː nʊˈʐna/" },
      { word: "ещё щука", ipa: "/jɪˈɕːo ˈɕːukə/" },
      { word: "площадь большая", ipa: "/ˈploɕːətʲ bɐlʲˈʂajə/" },
    ],
    difficulty: "high",
    description: "щ 长而软，接近 /ɕː/；不要简单读成 ш + ч 的硬组合。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-j",
    ipa: "/j/",
    name: "Russian й",
    category: "consonant",
    soundUnitType: "contrast",
    example: "йогурт",
    keywords: [
      { word: "йогурт", ipa: "/ˈjogʊrt/", stressText: "йо́гурт" },
      { word: "мой", ipa: "/moj/" },
      { word: "твой", ipa: "/tvoj/" },
      { word: "край", ipa: "/kraj/" },
      { word: "чай", ipa: "/tɕaj/" },
      { word: "май", ipa: "/maj/" },
      { word: "свой", ipa: "/svoj/" },
      { word: "герой", ipa: "/gʲɪˈroj/", stressText: "геро́й" },
      { word: "музей", ipa: "/mʊˈzʲej/", stressText: "музе́й" },
      { word: "новый", ipa: "/ˈnovɨj/", stressText: "но́вый" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/", stressText: "си́ний" },
      { word: "язык", ipa: "/jɪˈzɨk/", stressText: "язы́к" },
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "поезд", ipa: "/ˈpojɪst/", stressText: "по́езд" },
      { word: "июнь", ipa: "/ɪˈjunʲ/", stressText: "ию́нь" },
      { word: "июль", ipa: "/ɪˈjulʲ/", stressText: "ию́ль" },
      { word: "мой чай", ipa: "/moj tɕaj/" },
      { word: "новый музей", ipa: "/ˈnovɨj mʊˈzʲej/" },
      { word: "семья у моря", ipa: "/sʲɪmʲˈja u ˈmorʲə/" },
      { word: "поезд идёт", ipa: "/ˈpojɪst ɪˈdʲot/" },
    ],
    difficulty: "medium",
    description: "/j/ 是短滑音；和软辅音 [ʲ] 不同，软化不是额外加一个 й。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-iotated-vowels",
    ipa: "/ja je jo ju/",
    name: "iotated vowels я/е/ё/ю",
    category: "prosody",
    soundUnitType: "prosody",
    example: "я",
    keywords: [
      { word: "я", ipa: "/ja/" },
      { word: "есть", ipa: "/jesʲtʲ/" },
      { word: "ёж", ipa: "/joʂ/" },
      { word: "юг", ipa: "/juk/" },
      { word: "язык", ipa: "/jɪˈzɨk/", stressText: "язы́к" },
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "мяч", ipa: "/mʲatɕ/" },
      { word: "ёлка", ipa: "/ˈjolkə/" },
      { word: "люк", ipa: "/lʲuk/" },
      { word: "моя семья", ipa: "/mɐˈja sʲɪmʲˈja/" },
      { word: "новая юбка", ipa: "/ˈnovəjə ˈjupkə/" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "земля", ipa: "/zʲɪˈmlʲa/", stressText: "земля́" },
      { word: "Я люблю русский язык.", ipa: "/ja lʲʊˈblʲu ˈruskʲɪj jɪˈzɨk/" },
      { word: "Мой поезд идёт на юг.", ipa: "/moj ˈpojɪst ɪˈdʲot nɐ juk/" },
      { word: "варенье", ipa: "/vɐˈrʲenʲjə/", stressText: "варе́нье" },
      { word: "я люблю", ipa: "/ja lʲʊˈblʲu/" },
      { word: "семья едет", ipa: "/sʲɪmʲˈja ˈjedʲɪt/" },
      { word: "юг и ёж", ipa: "/juk i joʂ/" },
      { word: "песня о семье", ipa: "/ˈpʲesʲnʲə o sʲɪmʲˈje/" },
    ],
    difficulty: "high",
    description:
      "я/е/ё/ю 在词首或元音后常带 /j/，在辅音后常标记前辅音软化；要按位置判断。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-unstressed-o-a",
    ipa: "/ɐ ə/",
    name: "unstressed о/а reduction",
    category: "prosody",
    soundUnitType: "prosody",
    example: "молоко",
    keywords: [
      { word: "молоко", ipa: "/məlɐˈko/", stressText: "молоко́" },
      { word: "хорошо", ipa: "/xərɐˈʂo/", stressText: "хорошо́" },
      { word: "Москва", ipa: "/mɐˈskva/", stressText: "Москва́" },
      { word: "собака", ipa: "/sɐˈbakə/", stressText: "соба́ка" },
      { word: "работа", ipa: "/rɐˈbotə/", stressText: "рабо́та" },
      { word: "дорога", ipa: "/dɐˈrogə/", stressText: "доро́га" },
      { word: "вода", ipa: "/vɐˈda/", stressText: "вода́" },
      { word: "окно", ipa: "/ɐkˈno/", stressText: "окно́" },
      { word: "погода", ipa: "/pɐˈgodə/", stressText: "пого́да" },
      { word: "магазин", ipa: "/məgɐˈzʲin/", stressText: "магази́н" },
      { word: "телефон", ipa: "/tʲɪlʲɪˈfon/", stressText: "телефо́н" },
      { word: "окно открыто", ipa: "/ɐkˈno ɐtˈkrɨtə/" },
      { word: "собака голодная", ipa: "/sɐˈbakə ˈgolədnəjə/" },
      { word: "мама дома", ipa: "/ˈmamə ˈdomə/" },
      { word: "город", ipa: "/ˈgorət/", stressText: "го́род" },
      { word: "Хорошо, спасибо.", ipa: "/xərɐˈʂo spɐˈsʲibə/" },
      { word: "Москва сегодня", ipa: "/mɐˈskva sʲɪˈvodnʲə/" },
      { word: "молоко дома", ipa: "/məlɐˈko ˈdomə/" },
      { word: "собака во дворе", ipa: "/sɐˈbakə vɐ dvɐˈrʲe/" },
      { word: "хорошая погода", ipa: "/xɐˈroʂəjə pɐˈgodə/" },
    ],
    difficulty: "high",
    description:
      "非重读 о/а 常弱化到 [ɐ]/[ə] 附近；先找重音，不要逐字母读。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-unstressed-e-ya",
    ipa: "/ɪ ə/",
    name: "unstressed е/я reduction",
    category: "prosody",
    soundUnitType: "prosody",
    example: "семья",
    keywords: [
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "язык", ipa: "/jɪˈzɨk/", stressText: "язы́к" },
      { word: "сегодня", ipa: "/sʲɪˈvodnʲə/", stressText: "сего́дня" },
      { word: "минута", ipa: "/mʲɪˈnutə/", stressText: "мину́та" },
      { word: "директор", ipa: "/dʲɪˈrʲektər/", stressText: "дире́ктор" },
      { word: "билет", ipa: "/bʲɪˈlʲet/", stressText: "биле́т" },
      { word: "земля", ipa: "/zʲɪˈmlʲa/", stressText: "земля́" },
      { word: "письмо", ipa: "/pʲɪsʲˈmo/", stressText: "письмо́" },
      { word: "тетрадь", ipa: "/tʲɪˈtratʲ/", stressText: "тетра́дь" },
      { word: "человек", ipa: "/tɕɪlɐˈvʲek/", stressText: "челове́к" },
      { word: "понедельник", ipa: "/pənʲɪˈdʲelʲnʲɪk/", stressText: "понеде́льник" },
      { word: "интересно", ipa: "/ɪntʲɪˈrʲesnə/", stressText: "интере́сно" },
      { word: "дети идут", ipa: "/ˈdʲetʲɪ ɪˈdut/" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "пять билетов", ipa: "/pʲætʲ bʲɪˈlʲetəf/" },
      { word: "Это билет в театр.", ipa: "/ˈetə bʲɪˈlʲet f tʲɪˈatr/" },
      { word: "семья сегодня", ipa: "/sʲɪmʲˈja sʲɪˈvodnʲə/" },
      { word: "билет в театр", ipa: "/bʲɪˈlʲet f tʲɪˈatr/" },
      { word: "язык человека", ipa: "/jɪˈzɨk tɕɪlɐˈvʲekə/" },
      { word: "интересная минута", ipa: "/ɪntʲɪˈrʲesnəjə mʲɪˈnutə/" },
    ],
    difficulty: "high",
    description:
      "非重读 е/я 常趋向 [ɪ]/[ə]，同时前后辅音软化明显；不要把每个字母都读成完整 /e/ 或 /ja/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-final-devoicing",
    ipa: "final devoicing",
    name: "word-final devoicing",
    category: "prosody",
    soundUnitType: "prosody",
    example: "друг",
    keywords: [
      { word: "друг", ipa: "/druk/" },
      { word: "город", ipa: "/ˈgorət/", stressText: "го́род" },
      { word: "нож", ipa: "/noʂ/" },
      { word: "гараж", ipa: "/gɐˈraʂ/", stressText: "гара́ж" },
      { word: "хлеб", ipa: "/xlʲep/" },
      { word: "дуб", ipa: "/dup/" },
      { word: "глаз", ipa: "/glas/" },
      { word: "год", ipa: "/got/" },
      { word: "мёд", ipa: "/mʲot/" },
      { word: "луг", ipa: "/luk/" },
      { word: "сад пустой", ipa: "/sat pʊˈstoj/" },
      { word: "поезд идёт", ipa: "/ˈpojɪst ɪˈdʲot/" },
      { word: "нож тупой", ipa: "/noʂ tʊˈpoj/" },
      { word: "зуб", ipa: "/zup/" },
      { word: "Сад зимой синий.", ipa: "/sad zʲɪˈmoj ˈsʲinʲɪj/" },
      { word: "снег", ipa: "/snʲek/" },
      { word: "друг дома", ipa: "/drug ˈdomə/" },
      { word: "город большой", ipa: "/ˈgorəd bɐlʲˈʂoj/" },
      { word: "нож острый", ipa: "/noʐ ˈostrɨj/" },
      { word: "гараж открыт", ipa: "/gɐˈraʂ ɐtˈkrɨt/" },
    ],
    difficulty: "high",
    description:
      "停顿或清辅音前，词尾 б/д/г/ж/з 常清化；但连到浊辅音、响音或元音前时要按语流处理，不能把每个词都孤立清化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-voicing-assimilation",
    ipa: "voicing assimilation",
    name: "consonant voicing assimilation",
    category: "prosody",
    soundUnitType: "prosody",
    example: "встреча",
    keywords: [
      { word: "встреча", ipa: "/ˈfstrʲetɕə/", stressText: "встре́ча" },
      { word: "сделать", ipa: "/ˈzdʲelətʲ/", stressText: "сде́лать" },
      { word: "просьба", ipa: "/ˈprozʲbə/", stressText: "про́сьба" },
      { word: "сдать", ipa: "/zdatʲ/" },
      { word: "вокзал", ipa: "/vɐgˈzal/", stressText: "вокза́л" },
      { word: "подписать", ipa: "/pətpʲɪˈsatʲ/", stressText: "подписа́ть" },
      { word: "отдых", ipa: "/ˈoddɨx/", stressText: "о́тдых" },
      { word: "книга", ipa: "/ˈknʲigə/", stressText: "кни́га" },
      { word: "сбор", ipa: "/zbor/" },
      { word: "к дому", ipa: "/g ˈdomu/" },
      { word: "в школе", ipa: "/f ˈʂkolʲe/" },
      { word: "с братом", ipa: "/z ˈbratəm/" },
      { word: "под столом", ipa: "/pət stɐˈlom/" },
      { word: "над книгой", ipa: "/nat ˈknʲigəj/" },
      { word: "из школы", ipa: "/is ˈʂkolɨ/" },
      { word: "без тебя", ipa: "/bʲɪs tʲɪˈbʲa/" },
      { word: "встреча завтра", ipa: "/ˈfstrʲetɕə ˈzaftrə/" },
      { word: "сделать быстро", ipa: "/ˈzdʲelətʲ ˈbɨstrə/" },
      { word: "просьба друга", ipa: "/ˈprozʲbə ˈdrugə/" },
      { word: "вокзал рядом", ipa: "/vɐgˈzal ˈrʲadəm/" },
    ],
    difficulty: "high",
    description:
      "相邻辅音会影响清浊；例如 встреча 中 в 接清辅音读 [f]，不是按字母逐个读。",
  }),
];
