import type { PhonemeData } from "@/types/phoneme";
import { unit } from "@/lib/language-sound-units/utils";

export const RUSSIAN_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "ru-RU",
    slug: "ru-a",
    ipa: "/a/",
    name: "Russian а",
    category: "vowel",
    example: "мама",
    keywords: [
      { word: "мама", ipa: "/ˈmamə/" },
      { word: "да", ipa: "/da/" },
      { word: "там", ipa: "/tam/" },
      { word: "парк", ipa: "/park/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "сахар", ipa: "/ˈsaxər/" },
    ],
    difficulty: "easy",
    description: "重读时清楚开放，非重读时会弱化；俄语元音练习必须带重音位置。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-o",
    ipa: "/o/",
    name: "Russian stressed о",
    category: "vowel",
    example: "дом",
    keywords: [
      { word: "дом", ipa: "/dom/" },
      { word: "кот", ipa: "/kot/" },
      { word: "мост", ipa: "/most/" },
      { word: "нос", ipa: "/nos/" },
      { word: "рот", ipa: "/rot/" },
      { word: "город", ipa: "/ˈgorət/" },
    ],
    difficulty: "medium",
    description:
      "重读 /o/ 圆唇清楚；非重读 о 通常弱化接近 /a/ 或 /ə/，不能只按字母读。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-i",
    ipa: "/i/",
    name: "Russian и",
    category: "vowel",
    example: "мир",
    keywords: [
      { word: "мир", ipa: "/mir/" },
      { word: "лиса", ipa: "/lʲɪˈsa/" },
      { word: "имя", ipa: "/ˈimʲə/" },
      { word: "тихо", ipa: "/ˈtʲixə/" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/" },
      { word: "пить", ipa: "/pʲitʲ/" },
    ],
    difficulty: "medium",
    description: "常让前面的辅音软化；练这个音时要同时听辅音硬软变化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-y",
    ipa: "/ɨ/",
    name: "Russian ы",
    category: "vowel",
    example: "мы",
    keywords: [
      { word: "мы", ipa: "/mɨ/" },
      { word: "сыр", ipa: "/sɨr/" },
      { word: "ты", ipa: "/tɨ/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "быстро", ipa: "/ˈbɨstrə/" },
      { word: "сын", ipa: "/sɨn/" },
    ],
    difficulty: "high",
    description: "舌身更靠后更紧，不能读成 /i/；中文学习者需要和 и 成组对比。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-u",
    ipa: "/u/",
    name: "Russian у",
    category: "vowel",
    example: "луна",
    keywords: [
      { word: "луна", ipa: "/lʊˈna/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "утро", ipa: "/ˈutrə/" },
      { word: "музыка", ipa: "/ˈmuzɨkə/" },
      { word: "суп", ipa: "/sup/" },
      { word: "друг", ipa: "/druk/" },
    ],
    difficulty: "medium",
    description: "圆唇高后元音；非重读时会弱化，但仍要保留圆唇趋势。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-hard-soft",
    ipa: "/C ~ Cʲ/",
    name: "hard vs soft consonants",
    category: "consonant",
    soundUnitType: "contrast",
    example: "брат / брать",
    keywords: [
      { word: "брат", ipa: "/brat/" },
      { word: "брать", ipa: "/bratʲ/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мэр", ipa: "/mɛr/" },
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
    ],
    difficulty: "high",
    description:
      "俄语不是一个软音，而是成体系的硬/软辅音对；软音时舌面抬向硬腭。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-r",
    ipa: "/r/",
    name: "Russian trilled r",
    category: "consonant",
    example: "река",
    keywords: [
      { word: "река", ipa: "/rʲɪˈka/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "город", ipa: "/ˈgorət/" },
      { word: "друг", ipa: "/druk/" },
      { word: "работа", ipa: "/rɐˈbotə/" },
    ],
    difficulty: "high",
    description: "舌尖颤音，且有硬 /r/ 与软 /rʲ/ 对比；不能替换成英语卷舌 r。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-x",
    ipa: "/x/",
    name: "Russian х",
    category: "consonant",
    example: "хлеб",
    keywords: [
      { word: "хлеб", ipa: "/xlʲep/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
      { word: "тихо", ipa: "/ˈtʲixə/" },
      { word: "сахар", ipa: "/ˈsaxər/" },
      { word: "мох", ipa: "/mox/" },
      { word: "холод", ipa: "/ˈxolət/" },
    ],
    difficulty: "medium",
    description: "舌后部靠近软腭摩擦，比英语 /h/ 更靠后、更有摩擦感。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-sh-zh",
    ipa: "/ʂ ʐ/",
    name: "retroflex-like ш/ж",
    category: "consonant",
    soundUnitType: "contrast",
    example: "шум / жук",
    keywords: [
      { word: "шум", ipa: "/ʂum/" },
      { word: "жук", ipa: "/ʐuk/" },
      { word: "школа", ipa: "/ˈʂkolə/" },
      { word: "жена", ipa: "/ʐɨˈna/" },
      { word: "машина", ipa: "/mɐˈʂinə/" },
      { word: "жить", ipa: "/ʐɨtʲ/" },
    ],
    difficulty: "high",
    description:
      "舌尖/舌叶后缩，音色比英语 /ʃ ʒ/ 更厚；注意 ж 后常接 /ɨ/ 音色。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ts-ch-shch",
    ipa: "/ts tɕ ɕː/",
    name: "ц/ч/щ affricate and fricative set",
    category: "consonant",
    soundUnitType: "contrast",
    example: "цирк / чай / щи",
    keywords: [
      { word: "цирк", ipa: "/tsɨrk/" },
      { word: "чай", ipa: "/tɕaj/" },
      { word: "щи", ipa: "/ɕːi/" },
      { word: "улица", ipa: "/ˈulʲɪtsə/" },
      { word: "часы", ipa: "/tɕɪˈsɨ/" },
      { word: "площадь", ipa: "/ˈploɕːətʲ/" },
    ],
    difficulty: "high",
    description: "三个音位置和软硬感不同，不能全部用中文“吃/七”近似替代。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-stress-reduction",
    ipa: "/ˈ + ə ɐ/",
    name: "stress and vowel reduction",
    category: "prosody",
    soundUnitType: "prosody",
    example: "молоко",
    keywords: [
      { word: "молоко", ipa: "/məlɐˈko/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
      { word: "город", ipa: "/ˈgorət/" },
      { word: "мама", ipa: "/ˈmamə/" },
      { word: "работа", ipa: "/rɐˈbotə/" },
      { word: "сегодня", ipa: "/sʲɪˈvodnʲə/" },
    ],
    difficulty: "high",
    description:
      "俄语重音会改变元音质量。这个是句词层训练单位，不应被当成单个音素评分。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-clusters",
    ipa: "/CC(C)/",
    name: "consonant clusters",
    category: "cluster",
    soundUnitType: "cluster",
    example: "встреча",
    keywords: [
      { word: "встреча", ipa: "/ˈfstrʲetɕə/" },
      { word: "здравствуйте", ipa: "/ˈzdrastvʊjtʲe/" },
      { word: "текст", ipa: "/tʲekst/" },
      { word: "спорт", ipa: "/sport/" },
      { word: "взгляд", ipa: "/vzglʲat/" },
      { word: "стол", ipa: "/stol/" },
    ],
    difficulty: "high",
    description: "俄语辅音丛不能自动插入元音；先慢速保留每个辅音，再逐步加速。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-e",
    ipa: "/e/",
    name: "Russian stressed э/е",
    category: "vowel",
    example: "это",
    keywords: [
      { word: "это", ipa: "/ˈetə/", stressText: "э́то" },
      { word: "мэр", ipa: "/mɛr/" },
      { word: "эхо", ipa: "/ˈexə/", stressText: "э́хо" },
      { word: "метро", ipa: "/mʲɪˈtro/", stressText: "метро́" },
      { word: "центр", ipa: "/tsentr/" },
      { word: "текст", ipa: "/tʲekst/" },
      { word: "лес", ipa: "/lʲes/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "семь", ipa: "/sʲemʲ/" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "вечер", ipa: "/ˈvʲetɕɪr/", stressText: "ве́чер" },
      { word: "билет", ipa: "/bʲɪˈlʲet/", stressText: "биле́т" },
      { word: "экзамен", ipa: "/ɪgˈzamʲɪn/", stressText: "экза́мен" },
      { word: "этаж", ipa: "/ɪˈtaʂ/", stressText: "эта́ж" },
      { word: "энергия", ipa: "/ɪˈnʲergʲɪjə/", stressText: "эне́ргия" },
      { word: "десять", ipa: "/ˈdʲesʲɪtʲ/", stressText: "де́сять" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "это лес", ipa: "/ˈetə lʲes/" },
      { word: "вечер в метро", ipa: "/ˈvʲetɕɪr v mʲɪˈtro/" },
      { word: "текст билета", ipa: "/tʲekst bʲɪˈlʲetə/" },
    ],
    difficulty: "medium",
    description:
      "重读 /e/ 清楚；字母 е 往往同时软化前面的辅音，э 通常不软化前辅音。",
    notes: ["把 /e/ 和前面辅音是否软化一起看；мэр /mɛr/ 与 мел /mʲel/ 是好对比。"],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-t-d",
    ipa: "/t tʲ d dʲ/",
    name: "soft т/д",
    category: "consonant",
    soundUnitType: "contrast",
    example: "ток / тётя",
    keywords: [
      { word: "ток", ipa: "/tok/" },
      { word: "тётя", ipa: "/ˈtʲotʲə/" },
      { word: "дом", ipa: "/dom/" },
      { word: "день", ipa: "/dʲenʲ/" },
      { word: "там", ipa: "/tam/" },
      { word: "тень", ipa: "/tʲenʲ/" },
      { word: "да", ipa: "/da/" },
      { word: "дядя", ipa: "/ˈdʲadʲə/", stressText: "дя́дя" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "идти", ipa: "/ɪtˈtʲi/", stressText: "идти́" },
      { word: "тетрадь", ipa: "/tʲɪˈtratʲ/", stressText: "тетра́дь" },
      { word: "дети", ipa: "/ˈdʲetʲɪ/", stressText: "де́ти" },
      { word: "театр", ipa: "/tʲɪˈatr/", stressText: "теа́тр" },
      { word: "долго", ipa: "/ˈdolgə/", stressText: "до́лго" },
      { word: "труд", ipa: "/trut/" },
      { word: "друг", ipa: "/druk/" },
      { word: "ток и тень", ipa: "/tok i tʲenʲ/" },
      { word: "дом и день", ipa: "/dom i dʲenʲ/" },
      { word: "тётя дома", ipa: "/ˈtʲotʲə ˈdomə/" },
      { word: "дети идут", ipa: "/ˈdʲetʲɪ ɪˈdut/" },
    ],
    difficulty: "high",
    description:
      "软化是辅音本身舌面抬高，不是在硬辅音后面加一个完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-s-z",
    ipa: "/s sʲ z zʲ/",
    name: "soft с/з",
    category: "consonant",
    soundUnitType: "contrast",
    example: "сад / сядь",
    keywords: [
      { word: "сад", ipa: "/sat/" },
      { word: "сядь", ipa: "/sʲatʲ/" },
      { word: "зуб", ipa: "/zup/" },
      { word: "зима", ipa: "/zʲɪˈma/", stressText: "зима́" },
      { word: "сок", ipa: "/sok/" },
      { word: "сено", ipa: "/ˈsʲenə/", stressText: "се́но" },
      { word: "сын", ipa: "/sɨn/" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/", stressText: "си́ний" },
      { word: "звук", ipa: "/zvuk/" },
      { word: "земля", ipa: "/zʲɪˈmlʲa/", stressText: "земля́" },
      { word: "вес", ipa: "/vʲes/" },
      { word: "весь", ipa: "/vʲesʲ/" },
      { word: "сестра", ipa: "/sʲɪˈstra/", stressText: "сестра́" },
      { word: "сказать", ipa: "/skɐˈzatʲ/", stressText: "сказа́ть" },
      { word: "здесь", ipa: "/zdʲesʲ/" },
      { word: "музей", ipa: "/mʊˈzʲej/", stressText: "музе́й" },
      { word: "сад и сено", ipa: "/sat i ˈsʲenə/" },
      { word: "зуб и зима", ipa: "/zup i zʲɪˈma/" },
      { word: "сын синий", ipa: "/sɨn ˈsʲinʲɪj/" },
      { word: "здесь музей", ipa: "/zdʲesʲ mʊˈzʲej/" },
    ],
    difficulty: "high",
    description:
      "软 с/з 的摩擦位置更靠前、更细；硬 с/з 不要被后面的元音自动软化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-n-l-r",
    ipa: "/n nʲ l lʲ r rʲ/",
    name: "soft н/л/р",
    category: "consonant",
    soundUnitType: "contrast",
    example: "лук / люк",
    keywords: [
      { word: "нос", ipa: "/nos/" },
      { word: "нёс", ipa: "/nʲos/" },
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
      { word: "рад", ipa: "/rat/" },
      { word: "ряд", ipa: "/rʲat/" },
      { word: "кон", ipa: "/kon/" },
      { word: "конь", ipa: "/konʲ/" },
      { word: "угол", ipa: "/ˈugəl/", stressText: "у́гол" },
      { word: "уголь", ipa: "/ˈugəlʲ/", stressText: "у́голь" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мель", ipa: "/mʲelʲ/" },
      { word: "река", ipa: "/rʲɪˈka/", stressText: "река́" },
      { word: "рука", ipa: "/rʊˈka/", stressText: "рука́" },
      { word: "сибирь", ipa: "/sʲɪˈbirʲ/", stressText: "Сиби́рь" },
      { word: "линия", ipa: "/ˈlʲinʲɪjə/", stressText: "ли́ния" },
      { word: "нос и нёс", ipa: "/nos i nʲos/" },
      { word: "лук и люк", ipa: "/luk i lʲuk/" },
      { word: "рад и ряд", ipa: "/rat i rʲat/" },
      { word: "угол и уголь", ipa: "/ˈugəl i ˈugəlʲ/" },
    ],
    difficulty: "high",
    description:
      "н/л/р 的硬软对立很高频；软音时舌面抬起，不能只靠后面加 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-labials",
    ipa: "/pʲ bʲ mʲ fʲ vʲ/",
    name: "soft labials",
    category: "consonant",
    soundUnitType: "contrast",
    example: "пять",
    keywords: [
      { word: "пять", ipa: "/pʲatʲ/" },
      { word: "билет", ipa: "/bʲɪˈlʲet/", stressText: "биле́т" },
      { word: "мир", ipa: "/mir/" },
      { word: "фильм", ipa: "/fʲilʲm/" },
      { word: "вес", ipa: "/vʲes/" },
      { word: "весь", ipa: "/vʲesʲ/" },
      { word: "пить", ipa: "/pʲitʲ/" },
      { word: "белый", ipa: "/ˈbʲelɨj/", stressText: "бе́лый" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мель", ipa: "/mʲelʲ/" },
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "любовь", ipa: "/lʲʊˈbofʲ/", stressText: "любо́вь" },
      { word: "время", ipa: "/ˈvrʲemʲə/", stressText: "вре́мя" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "письмо", ipa: "/pʲɪsʲˈmo/", stressText: "письмо́" },
      { word: "автобус", ipa: "/ɐfˈtobʊs/", stressText: "авто́бус" },
      { word: "пять билетов", ipa: "/pʲatʲ bʲɪˈlʲetəf/" },
      { word: "мир и фильм", ipa: "/mir i fʲilʲm/" },
      { word: "вес весь", ipa: "/vʲes vʲesʲ/" },
      { word: "семья любит", ipa: "/sʲɪmʲˈja ˈlʲubʲɪt/" },
    ],
    difficulty: "high",
    description:
      "双唇/唇齿辅音也会软化；嘴唇动作不变，但舌面同时抬向硬腭。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-sign",
    ipa: "/ʲ/",
    name: "soft sign ь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "мать",
    keywords: [
      { word: "мать", ipa: "/matʲ/" },
      { word: "уголь", ipa: "/ˈugəlʲ/", stressText: "у́голь" },
      { word: "день", ipa: "/dʲenʲ/" },
      { word: "письмо", ipa: "/pʲɪsʲˈmo/", stressText: "письмо́" },
      { word: "конь", ipa: "/konʲ/" },
      { word: "мель", ipa: "/mʲelʲ/" },
      { word: "пить", ipa: "/pʲitʲ/" },
      { word: "брать", ipa: "/bratʲ/" },
      { word: "семь", ipa: "/sʲemʲ/" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "ночь", ipa: "/notɕ/" },
      { word: "помощь", ipa: "/ˈpoməɕː/", stressText: "по́мощь" },
      { word: "сибирь", ipa: "/sʲɪˈbirʲ/", stressText: "Сиби́рь" },
      { word: "учитель", ipa: "/ʊˈtɕitʲɪlʲ/", stressText: "учи́тель" },
      { word: "любовь", ipa: "/lʲʊˈbofʲ/", stressText: "любо́вь" },
      { word: "июнь", ipa: "/ɪˈjunʲ/", stressText: "ию́нь" },
      { word: "мат и мать", ipa: "/mat i matʲ/" },
      { word: "угол и уголь", ipa: "/ˈugəl i ˈugəlʲ/" },
      { word: "кон и конь", ipa: "/kon i konʲ/" },
      { word: "пить письмо", ipa: "/pʲitʲ pʲɪsʲˈmo/" },
    ],
    difficulty: "high",
    description:
      "软音符号不发独立声音，它改变前一个辅音的软化；训练时要显示出来但不能读成一个额外音节。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ts",
    ipa: "/ts/",
    name: "Russian ц",
    category: "consonant",
    example: "царь",
    keywords: [
      { word: "царь", ipa: "/tsarʲ/" },
      { word: "цена", ipa: "/tsɨˈna/", stressText: "цена́" },
      { word: "центр", ipa: "/tsentr/" },
      { word: "улица", ipa: "/ˈulʲɪtsə/", stressText: "у́лица" },
      { word: "конец", ipa: "/kɐˈnʲets/", stressText: "коне́ц" },
      { word: "цирк", ipa: "/tsɨrk/" },
      { word: "цепь", ipa: "/tsepʲ/" },
      { word: "танец", ipa: "/ˈtanʲɪts/", stressText: "та́нец" },
      { word: "отец", ipa: "/ɐˈtʲets/", stressText: "оте́ц" },
      { word: "птица", ipa: "/ˈptʲitsə/", stressText: "пти́ца" },
      { word: "станция", ipa: "/ˈstantsɨjə/", stressText: "ста́нция" },
      { word: "традиция", ipa: "/trɐˈdʲitsɨjə/", stressText: "тради́ция" },
      { word: "месяц", ipa: "/ˈmʲesʲɪts/", stressText: "ме́сяц" },
      { word: "двадцать", ipa: "/ˈdvatsətʲ/", stressText: "два́дцать" },
      { word: "пятьдесят", ipa: "/pʲɪdʲɪˈsʲat/", stressText: "пятьдеся́т" },
      { word: "процент", ipa: "/prɐˈtsent/", stressText: "проце́нт" },
      { word: "цена центра", ipa: "/tsɨˈna ˈtsentrə/" },
      { word: "улица и центр", ipa: "/ˈulʲɪtsə i tsentr/" },
      { word: "цирк в конце", ipa: "/tsɨrk f kɐˈnʲtse/" },
      { word: "отец танцует", ipa: "/ɐˈtʲets tɐnˈtsujɪt/" },
    ],
    difficulty: "medium",
    description: "ц 是 /ts/，通常偏硬；不要把后面的 и 读成普通 /i/ 的软化环境。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ch",
    ipa: "/tɕ/",
    name: "Russian ч",
    category: "consonant",
    example: "чай",
    keywords: [
      { word: "чай", ipa: "/tɕaj/" },
      { word: "час", ipa: "/tɕas/" },
      { word: "читать", ipa: "/tɕɪˈtatʲ/", stressText: "чита́ть" },
      { word: "человек", ipa: "/tɕɪlɐˈvʲek/", stressText: "челове́к" },
      { word: "ключ", ipa: "/klʲutɕ/" },
      { word: "чашка", ipa: "/ˈtɕaʂkə/", stressText: "ча́шка" },
      { word: "часто", ipa: "/ˈtɕastə/", stressText: "ча́сто" },
      { word: "вечер", ipa: "/ˈvʲetɕɪr/", stressText: "ве́чер" },
      { word: "учить", ipa: "/ʊˈtɕitʲ/", stressText: "учи́ть" },
      { word: "учитель", ipa: "/ʊˈtɕitʲɪlʲ/", stressText: "учи́тель" },
      { word: "дочь", ipa: "/dotɕ/" },
      { word: "ночь", ipa: "/notɕ/" },
      { word: "мяч", ipa: "/mʲatɕ/" },
      { word: "врач", ipa: "/vratɕ/" },
      { word: "почему", ipa: "/pətɕɪˈmu/", stressText: "почему́" },
      { word: "часы", ipa: "/tɕɪˈsɨ/", stressText: "часы́" },
      { word: "чай и час", ipa: "/tɕaj i tɕas/" },
      { word: "читать вечером", ipa: "/tɕɪˈtatʲ ˈvʲetɕɪrəm/" },
      { word: "учитель читает", ipa: "/ʊˈtɕitʲɪlʲ tɕɪˈtajɪt/" },
      { word: "чашка чая", ipa: "/ˈtɕaʂkə ˈtɕajə/" },
    ],
    difficulty: "high",
    description: "ч 通常偏软，是紧凑的 /tɕ/；不要把它读成硬 /tʃ/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-shch",
    ipa: "/ɕː/",
    name: "Russian щ",
    category: "consonant",
    example: "щи",
    keywords: [
      { word: "щи", ipa: "/ɕːi/" },
      { word: "щука", ipa: "/ˈɕːukə/", stressText: "щу́ка" },
      { word: "ещё", ipa: "/jɪˈɕːo/" },
      { word: "площадь", ipa: "/ˈploɕːətʲ/", stressText: "пло́щадь" },
      { word: "помощь", ipa: "/ˈpoməɕː/", stressText: "по́мощь" },
      { word: "борщ", ipa: "/borɕː/" },
      { word: "товарищ", ipa: "/tɐˈvarʲɪɕː/", stressText: "това́рищ" },
      { word: "щётка", ipa: "/ˈɕːotkə/" },
      { word: "ящик", ipa: "/ˈjaɕːɪk/", stressText: "я́щик" },
      { word: "женщина", ipa: "/ˈʐenɕːɪnə/", stressText: "же́нщина" },
      { word: "будущий", ipa: "/ˈbuduɕːɪj/", stressText: "бу́дущий" },
      { word: "ищу", ipa: "/ɪˈɕːu/", stressText: "ищу́" },
      { word: "защита", ipa: "/zɐˈɕːitə/", stressText: "защи́та" },
      { word: "вещь", ipa: "/vʲeɕː/" },
      { word: "роща", ipa: "/ˈroɕːə/", stressText: "ро́ща" },
      { word: "общий", ipa: "/ˈopɕːɪj/", stressText: "о́бщий" },
      { word: "борщ и щи", ipa: "/borɕː i ɕːi/" },
      { word: "помощь нужна", ipa: "/ˈpoməɕː nʊˈʐna/" },
      { word: "ещё щука", ipa: "/jɪˈɕːo ˈɕːukə/" },
      { word: "площадь большая", ipa: "/ˈploɕːətʲ bɐlʲˈʂajə/" },
    ],
    difficulty: "high",
    description: "щ 长而软，接近 /ɕː/；不要简单读成 ш + ч 的硬组合。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-j",
    ipa: "/j/",
    name: "Russian й",
    category: "consonant",
    soundUnitType: "contrast",
    example: "йогурт",
    keywords: [
      { word: "йогурт", ipa: "/ˈjogʊrt/", stressText: "йо́гурт" },
      { word: "мой", ipa: "/moj/" },
      { word: "твой", ipa: "/tvoj/" },
      { word: "край", ipa: "/kraj/" },
      { word: "чай", ipa: "/tɕaj/" },
      { word: "май", ipa: "/maj/" },
      { word: "свой", ipa: "/svoj/" },
      { word: "герой", ipa: "/gʲɪˈroj/", stressText: "геро́й" },
      { word: "музей", ipa: "/mʊˈzʲej/", stressText: "музе́й" },
      { word: "новый", ipa: "/ˈnovɨj/", stressText: "но́вый" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/", stressText: "си́ний" },
      { word: "язык", ipa: "/jɪˈzɨk/", stressText: "язы́к" },
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "поезд", ipa: "/ˈpojɪst/", stressText: "по́езд" },
      { word: "июнь", ipa: "/ɪˈjunʲ/", stressText: "ию́нь" },
      { word: "июль", ipa: "/ɪˈjulʲ/", stressText: "ию́ль" },
      { word: "мой чай", ipa: "/moj tɕaj/" },
      { word: "новый музей", ipa: "/ˈnovɨj mʊˈzʲej/" },
      { word: "семья у моря", ipa: "/sʲɪmʲˈja u ˈmorʲə/" },
      { word: "поезд идёт", ipa: "/ˈpojɪst ɪˈdʲot/" },
    ],
    difficulty: "medium",
    description: "/j/ 是短滑音；和软辅音 [ʲ] 不同，软化不是额外加一个 й。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-iotated-vowels",
    ipa: "/ja je jo ju/",
    name: "iotated vowels я/е/ё/ю",
    category: "prosody",
    soundUnitType: "prosody",
    example: "я",
    keywords: [
      { word: "я", ipa: "/ja/" },
      { word: "есть", ipa: "/jesʲtʲ/" },
      { word: "ёж", ipa: "/joʂ/" },
      { word: "юг", ipa: "/juk/" },
      { word: "язык", ipa: "/jɪˈzɨk/", stressText: "язы́к" },
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "мяч", ipa: "/mʲatɕ/" },
      { word: "ёлка", ipa: "/ˈjolkə/" },
      { word: "люк", ipa: "/lʲuk/" },
      { word: "моя семья", ipa: "/mɐˈja sʲɪmʲˈja/" },
      { word: "новая юбка", ipa: "/ˈnovəjə ˈjupkə/" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "земля", ipa: "/zʲɪˈmlʲa/", stressText: "земля́" },
      { word: "Я люблю русский язык.", ipa: "/ja lʲʊˈblʲu ˈruskʲɪj jɪˈzɨk/" },
      { word: "Мой поезд идёт на юг.", ipa: "/moj ˈpojɪst ɪˈdʲot nɐ juk/" },
      { word: "варенье", ipa: "/vɐˈrʲenʲjə/", stressText: "варе́нье" },
      { word: "я люблю", ipa: "/ja lʲʊˈblʲu/" },
      { word: "семья едет", ipa: "/sʲɪmʲˈja ˈjedʲɪt/" },
      { word: "юг и ёж", ipa: "/juk i joʂ/" },
      { word: "песня о семье", ipa: "/ˈpʲesʲnʲə o sʲɪmʲˈje/" },
    ],
    difficulty: "high",
    description:
      "я/е/ё/ю 在词首或元音后常带 /j/，在辅音后常标记前辅音软化；要按位置判断。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-unstressed-o-a",
    ipa: "/ɐ ə/",
    name: "unstressed о/а reduction",
    category: "prosody",
    soundUnitType: "prosody",
    example: "молоко",
    keywords: [
      { word: "молоко", ipa: "/məlɐˈko/", stressText: "молоко́" },
      { word: "хорошо", ipa: "/xərɐˈʂo/", stressText: "хорошо́" },
      { word: "Москва", ipa: "/mɐˈskva/", stressText: "Москва́" },
      { word: "собака", ipa: "/sɐˈbakə/", stressText: "соба́ка" },
      { word: "работа", ipa: "/rɐˈbotə/", stressText: "рабо́та" },
      { word: "дорога", ipa: "/dɐˈrogə/", stressText: "доро́га" },
      { word: "вода", ipa: "/vɐˈda/", stressText: "вода́" },
      { word: "окно", ipa: "/ɐkˈno/", stressText: "окно́" },
      { word: "погода", ipa: "/pɐˈgodə/", stressText: "пого́да" },
      { word: "магазин", ipa: "/məgɐˈzʲin/", stressText: "магази́н" },
      { word: "телефон", ipa: "/tʲɪlʲɪˈfon/", stressText: "телефо́н" },
      { word: "окно открыто", ipa: "/ɐkˈno ɐtˈkrɨtə/" },
      { word: "собака голодная", ipa: "/sɐˈbakə ˈgolədnəjə/" },
      { word: "мама дома", ipa: "/ˈmamə ˈdomə/" },
      { word: "город", ipa: "/ˈgorət/", stressText: "го́род" },
      { word: "Хорошо, спасибо.", ipa: "/xərɐˈʂo spɐˈsʲibə/" },
      { word: "Москва сегодня", ipa: "/mɐˈskva sʲɪˈvodnʲə/" },
      { word: "молоко дома", ipa: "/məlɐˈko ˈdomə/" },
      { word: "собака во дворе", ipa: "/sɐˈbakə vɐ dvɐˈrʲe/" },
      { word: "хорошая погода", ipa: "/xɐˈroʂəjə pɐˈgodə/" },
    ],
    difficulty: "high",
    description:
      "非重读 о/а 常弱化到 [ɐ]/[ə] 附近；先找重音，不要逐字母读。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-unstressed-e-ya",
    ipa: "/ɪ ə/",
    name: "unstressed е/я reduction",
    category: "prosody",
    soundUnitType: "prosody",
    example: "семья",
    keywords: [
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "язык", ipa: "/jɪˈzɨk/", stressText: "язы́к" },
      { word: "сегодня", ipa: "/sʲɪˈvodnʲə/", stressText: "сего́дня" },
      { word: "минута", ipa: "/mʲɪˈnutə/", stressText: "мину́та" },
      { word: "директор", ipa: "/dʲɪˈrʲektər/", stressText: "дире́ктор" },
      { word: "билет", ipa: "/bʲɪˈlʲet/", stressText: "биле́т" },
      { word: "земля", ipa: "/zʲɪˈmlʲa/", stressText: "земля́" },
      { word: "письмо", ipa: "/pʲɪsʲˈmo/", stressText: "письмо́" },
      { word: "тетрадь", ipa: "/tʲɪˈtratʲ/", stressText: "тетра́дь" },
      { word: "человек", ipa: "/tɕɪlɐˈvʲek/", stressText: "челове́к" },
      { word: "понедельник", ipa: "/pənʲɪˈdʲelʲnʲɪk/", stressText: "понеде́льник" },
      { word: "интересно", ipa: "/ɪntʲɪˈrʲesnə/", stressText: "интере́сно" },
      { word: "дети идут", ipa: "/ˈdʲetʲɪ ɪˈdut/" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "пять билетов", ipa: "/pʲætʲ bʲɪˈlʲetəf/" },
      { word: "Это билет в театр.", ipa: "/ˈetə bʲɪˈlʲet f tʲɪˈatr/" },
      { word: "семья сегодня", ipa: "/sʲɪmʲˈja sʲɪˈvodnʲə/" },
      { word: "билет в театр", ipa: "/bʲɪˈlʲet f tʲɪˈatr/" },
      { word: "язык человека", ipa: "/jɪˈzɨk tɕɪlɐˈvʲekə/" },
      { word: "интересная минута", ipa: "/ɪntʲɪˈrʲesnəjə mʲɪˈnutə/" },
    ],
    difficulty: "high",
    description:
      "非重读 е/я 常趋向 [ɪ]/[ə]，同时前后辅音软化明显；不要把每个字母都读成完整 /e/ 或 /ja/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-final-devoicing",
    ipa: "final devoicing",
    name: "word-final devoicing",
    category: "prosody",
    soundUnitType: "prosody",
    example: "друг",
    keywords: [
      { word: "друг", ipa: "/druk/" },
      { word: "город", ipa: "/ˈgorət/", stressText: "го́род" },
      { word: "нож", ipa: "/noʂ/" },
      { word: "гараж", ipa: "/gɐˈraʂ/", stressText: "гара́ж" },
      { word: "хлеб", ipa: "/xlʲep/" },
      { word: "дуб", ipa: "/dup/" },
      { word: "глаз", ipa: "/glas/" },
      { word: "год", ipa: "/got/" },
      { word: "мёд", ipa: "/mʲot/" },
      { word: "луг", ipa: "/luk/" },
      { word: "сад пустой", ipa: "/sat pʊˈstoj/" },
      { word: "поезд идёт", ipa: "/ˈpojɪst ɪˈdʲot/" },
      { word: "нож тупой", ipa: "/noʂ tʊˈpoj/" },
      { word: "зуб", ipa: "/zup/" },
      { word: "Сад зимой синий.", ipa: "/sad zʲɪˈmoj ˈsʲinʲɪj/" },
      { word: "снег", ipa: "/snʲek/" },
      { word: "друг дома", ipa: "/drug ˈdomə/" },
      { word: "город большой", ipa: "/ˈgorəd bɐlʲˈʂoj/" },
      { word: "нож острый", ipa: "/noʐ ˈostrɨj/" },
      { word: "гараж открыт", ipa: "/gɐˈraʂ ɐtˈkrɨt/" },
    ],
    difficulty: "high",
    description:
      "停顿或清辅音前，词尾 б/д/г/ж/з 常清化；但连到浊辅音、响音或元音前时要按语流处理，不能把每个词都孤立清化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-voicing-assimilation",
    ipa: "voicing assimilation",
    name: "consonant voicing assimilation",
    category: "prosody",
    soundUnitType: "prosody",
    example: "встреча",
    keywords: [
      { word: "встреча", ipa: "/ˈfstrʲetɕə/", stressText: "встре́ча" },
      { word: "сделать", ipa: "/ˈzdʲelətʲ/", stressText: "сде́лать" },
      { word: "просьба", ipa: "/ˈprozʲbə/", stressText: "про́сьба" },
      { word: "сдать", ipa: "/zdatʲ/" },
      { word: "вокзал", ipa: "/vɐgˈzal/", stressText: "вокза́л" },
      { word: "подписать", ipa: "/pətpʲɪˈsatʲ/", stressText: "подписа́ть" },
      { word: "отдых", ipa: "/ˈoddɨx/", stressText: "о́тдых" },
      { word: "книга", ipa: "/ˈknʲigə/", stressText: "кни́га" },
      { word: "сбор", ipa: "/zbor/" },
      { word: "к дому", ipa: "/g ˈdomu/" },
      { word: "в школе", ipa: "/f ˈʂkolʲe/" },
      { word: "с братом", ipa: "/z ˈbratəm/" },
      { word: "под столом", ipa: "/pət stɐˈlom/" },
      { word: "над книгой", ipa: "/nat ˈknʲigəj/" },
      { word: "из школы", ipa: "/is ˈʂkolɨ/" },
      { word: "без тебя", ipa: "/bʲɪs tʲɪˈbʲa/" },
      { word: "встреча завтра", ipa: "/ˈfstrʲetɕə ˈzaftrə/" },
      { word: "сделать быстро", ipa: "/ˈzdʲelətʲ ˈbɨstrə/" },
      { word: "просьба друга", ipa: "/ˈprozʲbə ˈdrugə/" },
      { word: "вокзал рядом", ipa: "/vɐgˈzal ˈrʲadəm/" },
    ],
    difficulty: "high",
    description:
      "相邻辅音会影响清浊；例如 встреча 中 в 接清辅音读 [f]，不是按字母逐个读。",
  }),
];
