import type { PhonemeData } from "@/types/phoneme";
import { unit } from "@/lib/language-sound-units/utils";

export const FRENCH_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "fr-FR",
    slug: "fr-i",
    ipa: "/i/",
    name: "close front unrounded vowel",
    category: "vowel",
    example: "si",
    keywords: [
      { word: "si", ipa: "/si/" },
      { word: "ville", ipa: "/vil/" },
      { word: "vite", ipa: "/vit/" },
      { word: "midi", ipa: "/midi/" },
      { word: "ici", ipa: "/isi/" },
      { word: "lit", ipa: "/li/" },
    ],
    difficulty: "easy",
    description: "舌前高位，嘴角微展；短而紧，不按英语 /iː/ 拉长。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-y",
    ipa: "/y/",
    name: "close front rounded vowel",
    category: "vowel",
    example: "tu",
    keywords: [
      { word: "tu", ipa: "/ty/" },
      { word: "lune", ipa: "/lyn/" },
      { word: "rue", ipa: "/ʁy/" },
      { word: "dur", ipa: "/dyʁ/" },
      { word: "musique", ipa: "/myzik/" },
      { word: "sur", ipa: "/syʁ/" },
    ],
    difficulty: "high",
    description:
      "舌头摆 /i/ 的高前位置，同时双唇像 /u/ 一样收圆；中文学习者很容易退成 /u/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-u",
    ipa: "/u/",
    name: "close back rounded vowel",
    category: "vowel",
    example: "vous",
    keywords: [
      { word: "vous", ipa: "/vu/" },
      { word: "nous", ipa: "/nu/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "jour", ipa: "/ʒuʁ/" },
      { word: "sous", ipa: "/su/" },
      { word: "tout", ipa: "/tu/" },
    ],
    difficulty: "medium",
    description: "双唇收圆，舌后高位；要和 /y/ 分开，/u/ 的舌位更靠后。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-e",
    ipa: "/e/",
    name: "close-mid front vowel",
    category: "vowel",
    example: "été",
    keywords: [
      { word: "été", ipa: "/ete/" },
      { word: "nez", ipa: "/ne/" },
      { word: "parler", ipa: "/paʁle/" },
      { word: "café", ipa: "/kafe/" },
      { word: "mes", ipa: "/me/" },
      { word: "bébé", ipa: "/bebe/" },
    ],
    difficulty: "medium",
    description: "舌前中高位，声音干净稳定，不滑成英语 /eɪ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-e-open",
    ipa: "/ɛ/",
    name: "open-mid front vowel",
    category: "vowel",
    example: "sel",
    keywords: [
      { word: "sel", ipa: "/sɛl/" },
      { word: "mère", ipa: "/mɛʁ/" },
      { word: "très", ipa: "/tʁɛ/" },
      { word: "belle", ipa: "/bɛl/" },
      { word: "sept", ipa: "/sɛt/" },
      { word: "faire", ipa: "/fɛʁ/" },
    ],
    difficulty: "medium",
    description: "嘴巴比 /e/ 更开，舌前略低；要和 /e/ 做对比训练。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-eu-close",
    ipa: "/ø/",
    name: "close-mid front rounded vowel",
    category: "vowel",
    example: "deux",
    keywords: [
      { word: "deux", ipa: "/dø/" },
      { word: "bleu", ipa: "/blø/" },
      { word: "peu", ipa: "/pø/" },
      { word: "heureux", ipa: "/øʁø/" },
      { word: "feu", ipa: "/fø/" },
      { word: "jeu", ipa: "/ʒø/" },
    ],
    difficulty: "high",
    description: "像 /e/ 的舌位加上圆唇；不要变成 /o/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-eu-open",
    ipa: "/œ/",
    name: "open-mid front rounded vowel",
    category: "vowel",
    example: "sœur",
    keywords: [
      { word: "sœur", ipa: "/sœʁ/" },
      { word: "jeune", ipa: "/ʒœn/" },
      { word: "peur", ipa: "/pœʁ/" },
      { word: "fleur", ipa: "/flœʁ/" },
      { word: "neuf", ipa: "/nœf/" },
      { word: "seul", ipa: "/sœl/" },
    ],
    difficulty: "high",
    description: "像 /ɛ/ 的开口加圆唇；法语圆唇前元音是中国学习者重点难点。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-an",
    ipa: "/ɑ̃/",
    name: "nasal vowel an/en",
    category: "vowel",
    example: "sans",
    keywords: [
      { word: "sans", ipa: "/sɑ̃/" },
      { word: "France", ipa: "/fʁɑ̃s/" },
      { word: "temps", ipa: "/tɑ̃/" },
      { word: "grand", ipa: "/gʁɑ̃/" },
      { word: "dans", ipa: "/dɑ̃/" },
      { word: "maman", ipa: "/mamɑ̃/" },
    ],
    difficulty: "high",
    description: "口腔元音同时打开鼻腔共鸣，不要在后面加清楚的 /n/ 或 /ŋ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-in",
    ipa: "/ɛ̃/",
    name: "nasal vowel in/ain",
    category: "vowel",
    example: "vin",
    keywords: [
      { word: "vin", ipa: "/vɛ̃/" },
      { word: "pain", ipa: "/pɛ̃/" },
      { word: "bien", ipa: "/bjɛ̃/" },
      { word: "matin", ipa: "/matɛ̃/" },
      { word: "cinq", ipa: "/sɛ̃k/" },
      { word: "main", ipa: "/mɛ̃/" },
    ],
    difficulty: "high",
    description: "舌前中低位加鼻化；和 /ɑ̃/、/ɔ̃/ 的口型距离要拉开。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-on",
    ipa: "/ɔ̃/",
    name: "nasal vowel on",
    category: "vowel",
    example: "bon",
    keywords: [
      { word: "bon", ipa: "/bɔ̃/" },
      { word: "nom", ipa: "/nɔ̃/" },
      { word: "son", ipa: "/sɔ̃/" },
      { word: "monde", ipa: "/mɔ̃d/" },
      { word: "bonjour", ipa: "/bɔ̃ʒuʁ/" },
      { word: "long", ipa: "/lɔ̃/" },
    ],
    difficulty: "high",
    description: "圆唇后元音加鼻化；不要读成“ong”的明显尾音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-r",
    ipa: "/ʁ/",
    name: "French uvular r",
    category: "consonant",
    example: "rue",
    keywords: [
      { word: "rue", ipa: "/ʁy/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "Paris", ipa: "/paʁi/" },
      { word: "merci", ipa: "/mɛʁsi/" },
      { word: "très", ipa: "/tʁɛ/" },
      { word: "frère", ipa: "/fʁɛʁ/" },
    ],
    difficulty: "high",
    description:
      "舌根靠近小舌产生摩擦或近音，不是英语卷舌 r，也不是西语弹舌 r。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-p",
    ipa: "/p/",
    name: "French p",
    category: "consonant",
    example: "pas",
    keywords: [
      { word: "pas", ipa: "/pa/" },
      { word: "père", ipa: "/pɛʁ/" },
      { word: "petit", ipa: "/pəti/" },
      { word: "pain", ipa: "/pɛ̃/" },
      { word: "porte", ipa: "/pɔʁt/" },
      { word: "Paris", ipa: "/paʁi/" },
      { word: "papier", ipa: "/papje/" },
      { word: "pomme", ipa: "/pɔm/" },
      { word: "pluie", ipa: "/plɥi/" },
      { word: "prendre", ipa: "/pʁɑ̃dʁ/" },
      { word: "appel", ipa: "/apɛl/" },
      { word: "soupe", ipa: "/sup/" },
      { word: "tapis", ipa: "/tapi/" },
      { word: "repas", ipa: "/ʁəpa/" },
      { word: "peuple", ipa: "/pœpl/" },
      { word: "poche", ipa: "/pɔʃ/" },
      { word: "propre", ipa: "/pʁɔpʁ/" },
      { word: "place", ipa: "/plas/" },
      { word: "pardon", ipa: "/paʁdɔ̃/" },
      { word: "parler", ipa: "/paʁle/" },
      { word: "petit pain", ipa: "/pəti pɛ̃/" },
      { word: "porte propre", ipa: "/pɔʁt pʁɔpʁ/" },
      { word: "Paris parle", ipa: "/paʁi paʁl/" },
      { word: "pomme et pain", ipa: "/pɔm e pɛ̃/" },
    ],
    difficulty: "easy",
    description:
      "双唇闭合后短促打开；法语 /p/ 比英语词首 p 更少送气，声音短而干净。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-b",
    ipa: "/b/",
    name: "French b",
    category: "consonant",
    example: "beau",
    keywords: [
      { word: "beau", ipa: "/bo/" },
      { word: "bon", ipa: "/bɔ̃/" },
      { word: "bébé", ipa: "/bebe/" },
      { word: "bien", ipa: "/bjɛ̃/" },
      { word: "bouche", ipa: "/buʃ/" },
      { word: "robe", ipa: "/ʁɔb/" },
      { word: "table", ipa: "/tabl/" },
      { word: "billet", ipa: "/bijɛ/" },
      { word: "bleu", ipa: "/blø/" },
      { word: "blanc", ipa: "/blɑ̃/" },
      { word: "brune", ipa: "/bʁyn/" },
      { word: "beaucoup", ipa: "/boku/" },
      { word: "habite", ipa: "/abit/" },
      { word: "bière", ipa: "/bjɛʁ/" },
      { word: "bateau", ipa: "/bato/" },
      { word: "bonne", ipa: "/bɔn/" },
      { word: "bague", ipa: "/bag/" },
      { word: "bureau", ipa: "/byʁo/" },
      { word: "bizarre", ipa: "/bizaʁ/" },
      { word: "bonbon", ipa: "/bɔ̃bɔ̃/" },
      { word: "beau bébé", ipa: "/bo bebe/" },
      { word: "bonne bouche", ipa: "/bɔn buʃ/" },
      { word: "bureau bleu", ipa: "/byʁo blø/" },
      { word: "robe blanche", ipa: "/ʁɔb blɑ̃ʃ/" },
    ],
    difficulty: "easy",
    description:
      "双唇闭合并保持声带振动；不要像英语那样拖出强爆破，也不要和 /p/ 混成清音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-t",
    ipa: "/t/",
    name: "French t",
    category: "consonant",
    example: "tu",
    keywords: [
      { word: "tu", ipa: "/ty/" },
      { word: "tout", ipa: "/tu/" },
      { word: "thé", ipa: "/te/" },
      { word: "tête", ipa: "/tɛt/" },
      { word: "table", ipa: "/tabl/" },
      { word: "vite", ipa: "/vit/" },
      { word: "porte", ipa: "/pɔʁt/" },
      { word: "petit", ipa: "/pəti/" },
      { word: "matin", ipa: "/matɛ̃/" },
      { word: "trois", ipa: "/tʁwa/" },
      { word: "train", ipa: "/tʁɛ̃/" },
      { word: "très", ipa: "/tʁɛ/" },
      { word: "tomate", ipa: "/tɔmat/" },
      { word: "théâtre", ipa: "/teatʁ/" },
      { word: "attendre", ipa: "/atɑ̃dʁ/" },
      { word: "voiture", ipa: "/vwatyʁ/" },
      { word: "tapis", ipa: "/tapi/" },
      { word: "tôt", ipa: "/to/" },
      { word: "tort", ipa: "/tɔʁ/" },
      { word: "étudier", ipa: "/etydje/" },
      { word: "tu attends", ipa: "/ty atɑ̃/" },
      { word: "très tôt", ipa: "/tʁɛ to/" },
      { word: "petite table", ipa: "/pətit tabl/" },
      { word: "tomate très rouge", ipa: "/tɔmat tʁɛ ʁuʒ/" },
    ],
    difficulty: "easy",
    description:
      "舌尖靠近上齿背/齿龈，爆破短；法语 /t/ 不要按英语词首强送气。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-d",
    ipa: "/d/",
    name: "French d",
    category: "consonant",
    example: "deux",
    keywords: [
      { word: "deux", ipa: "/dø/" },
      { word: "dans", ipa: "/dɑ̃/" },
      { word: "dire", ipa: "/diʁ/" },
      { word: "donner", ipa: "/dɔne/" },
      { word: "dimanche", ipa: "/dimɑ̃ʃ/" },
      { word: "midi", ipa: "/midi/" },
      { word: "aide", ipa: "/ɛd/" },
      { word: "malade", ipa: "/malad/" },
      { word: "madame", ipa: "/madam/" },
      { word: "dormir", ipa: "/dɔʁmiʁ/" },
      { word: "doux", ipa: "/du/" },
      { word: "droite", ipa: "/dʁwat/" },
      { word: "demain", ipa: "/dəmɛ̃/" },
      { word: "déjeuner", ipa: "/deʒœne/" },
      { word: "cadeau", ipa: "/kado/" },
      { word: "idée", ipa: "/ide/" },
      { word: "moderne", ipa: "/mɔdɛʁn/" },
      { word: "dialogue", ipa: "/djalɔg/" },
      { word: "dedans", ipa: "/dədɑ̃/" },
      { word: "difficile", ipa: "/difisil/" },
      { word: "dire demain", ipa: "/diʁ dəmɛ̃/" },
      { word: "deux cadeaux", ipa: "/dø kado/" },
      { word: "dimanche midi", ipa: "/dimɑ̃ʃ midi/" },
      { word: "madame donne", ipa: "/madam dɔn/" },
    ],
    difficulty: "easy",
    description:
      "保持清楚的浊塞音，位置靠前；不要把 /d/ 弱化成英语式 flap，也不要和 /t/ 混淆。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-k",
    ipa: "/k/",
    name: "French k",
    category: "consonant",
    example: "qui",
    keywords: [
      { word: "qui", ipa: "/ki/" },
      { word: "que", ipa: "/kə/" },
      { word: "quand", ipa: "/kɑ̃/" },
      { word: "café", ipa: "/kafe/" },
      { word: "école", ipa: "/ekɔl/" },
      { word: "avec", ipa: "/avɛk/" },
      { word: "sac", ipa: "/sak/" },
      { word: "classe", ipa: "/klas/" },
      { word: "quatre", ipa: "/katʁ/" },
      { word: "cœur", ipa: "/kœʁ/" },
      { word: "cadeau", ipa: "/kado/" },
      { word: "écouter", ipa: "/ekute/" },
      { word: "question", ipa: "/kɛstjɔ̃/" },
      { word: "calme", ipa: "/kalm/" },
      { word: "couleur", ipa: "/kulœʁ/" },
      { word: "carte", ipa: "/kaʁt/" },
      { word: "kilomètre", ipa: "/kilɔmɛtʁ/" },
      { word: "musique", ipa: "/myzik/" },
      { word: "choc", ipa: "/ʃɔk/" },
      { word: "cuisine", ipa: "/kɥizin/" },
      { word: "café calme", ipa: "/kafe kalm/" },
      { word: "quatre cadeaux", ipa: "/katʁ kado/" },
      { word: "avec qui", ipa: "/avɛk ki/" },
      { word: "classe courte", ipa: "/klas kuʁt/" },
    ],
    difficulty: "easy",
    description:
      "舌后部贴近软腭后短促打开；法语 /k/ 不要强送气，c/qu/k 可在不同拼写中对应这个音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-g",
    ipa: "/g/",
    name: "French hard g",
    category: "consonant",
    example: "gare",
    keywords: [
      { word: "gare", ipa: "/gaʁ/" },
      { word: "garçon", ipa: "/gaʁsɔ̃/" },
      { word: "goût", ipa: "/gu/" },
      { word: "gomme", ipa: "/gɔm/" },
      { word: "bague", ipa: "/bag/" },
      { word: "grande", ipa: "/gʁɑ̃d/" },
      { word: "gris", ipa: "/gʁi/" },
      { word: "glace", ipa: "/glas/" },
      { word: "gagner", ipa: "/gaɲe/" },
      { word: "guitare", ipa: "/gitaʁ/" },
      { word: "égal", ipa: "/egal/" },
      { word: "seconde", ipa: "/səgɔ̃d/" },
      { word: "dialogue", ipa: "/djalɔg/" },
      { word: "guider", ipa: "/gide/" },
      { word: "groupe", ipa: "/gʁup/" },
      { word: "gauche", ipa: "/goʃ/" },
      { word: "gâteau", ipa: "/gato/" },
      { word: "langue", ipa: "/lɑ̃g/" },
      { word: "longue", ipa: "/lɔ̃g/" },
      { word: "regarder", ipa: "/ʁəgaʁde/" },
      { word: "gare grise", ipa: "/gaʁ gʁiz/" },
      { word: "guitare grave", ipa: "/gitaʁ gʁav/" },
      { word: "grand garçon", ipa: "/gʁɑ̃ gaʁsɔ̃/" },
      { word: "gâteau au goût doux", ipa: "/gato o gu du/" },
    ],
    difficulty: "easy",
    description:
      "软腭浊塞音，声带先参与；注意 g/e、g/i 常变 /ʒ/，这里训练的是硬 /g/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-f",
    ipa: "/f/",
    name: "French f",
    category: "consonant",
    example: "faire",
    keywords: [
      { word: "faire", ipa: "/fɛʁ/" },
      { word: "femme", ipa: "/fam/" },
      { word: "fille", ipa: "/fij/" },
      { word: "fou", ipa: "/fu/" },
      { word: "feu", ipa: "/fø/" },
      { word: "neuf", ipa: "/nœf/" },
      { word: "café", ipa: "/kafe/" },
      { word: "photo", ipa: "/foto/" },
      { word: "famille", ipa: "/famij/" },
      { word: "fleur", ipa: "/flœʁ/" },
      { word: "froid", ipa: "/fʁwa/" },
      { word: "facile", ipa: "/fasil/" },
      { word: "forêt", ipa: "/fɔʁɛ/" },
      { word: "téléphone", ipa: "/telefon/" },
      { word: "français", ipa: "/fʁɑ̃sɛ/" },
      { word: "fort", ipa: "/fɔʁ/" },
      { word: "chef", ipa: "/ʃɛf/" },
      { word: "œuf", ipa: "/œf/" },
      { word: "phrase", ipa: "/fʁaz/" },
      { word: "fenêtre", ipa: "/fənɛtʁ/" },
      { word: "faire facile", ipa: "/fɛʁ fasil/" },
      { word: "fleur froide", ipa: "/flœʁ fʁwad/" },
      { word: "famille française", ipa: "/famij fʁɑ̃sɛz/" },
      { word: "photo floue", ipa: "/foto flu/" },
    ],
    difficulty: "easy",
    description:
      "上齿轻触下唇，连续清摩擦；保持清音，不要读成英语 /v/ 或拖出额外元音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-v",
    ipa: "/v/",
    name: "French v",
    category: "consonant",
    example: "vous",
    keywords: [
      { word: "vous", ipa: "/vu/" },
      { word: "vite", ipa: "/vit/" },
      { word: "vin", ipa: "/vɛ̃/" },
      { word: "ville", ipa: "/vil/" },
      { word: "voir", ipa: "/vwaʁ/" },
      { word: "vivre", ipa: "/vivʁ/" },
      { word: "avec", ipa: "/avɛk/" },
      { word: "rêve", ipa: "/ʁɛv/" },
      { word: "ouvert", ipa: "/uvɛʁ/" },
      { word: "voiture", ipa: "/vwatyʁ/" },
      { word: "vélo", ipa: "/velo/" },
      { word: "venir", ipa: "/vəniʁ/" },
      { word: "voyage", ipa: "/vwajaʒ/" },
      { word: "vingt", ipa: "/vɛ̃/" },
      { word: "veau", ipa: "/vo/" },
      { word: "vrai", ipa: "/vʁɛ/" },
      { word: "avion", ipa: "/avjɔ̃/" },
      { word: "savon", ipa: "/savɔ̃/" },
      { word: "neveu", ipa: "/nəvø/" },
      { word: "arriver", ipa: "/aʁive/" },
      { word: "vous venez", ipa: "/vu vəne/" },
      { word: "ville vivante", ipa: "/vil vivɑ̃t/" },
      { word: "voir le vélo", ipa: "/vwaʁ lə velo/" },
      { word: "voyage avec vous", ipa: "/vwajaʒ avɛk vu/" },
    ],
    difficulty: "easy",
    description:
      "上齿和下唇形成浊摩擦，声带持续振动；不要按中文/英语习惯变成 /w/ 或 /f/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-s",
    ipa: "/s/",
    name: "French s",
    category: "consonant",
    example: "si",
    keywords: [
      { word: "si", ipa: "/si/" },
      { word: "ça", ipa: "/sa/" },
      { word: "sans", ipa: "/sɑ̃/" },
      { word: "sel", ipa: "/sɛl/" },
      { word: "sous", ipa: "/su/" },
      { word: "son", ipa: "/sɔ̃/" },
      { word: "merci", ipa: "/mɛʁsi/" },
      { word: "aussi", ipa: "/osi/" },
      { word: "français", ipa: "/fʁɑ̃sɛ/" },
      { word: "classe", ipa: "/klas/" },
      { word: "poste", ipa: "/pɔst/" },
      { word: "sauce", ipa: "/sos/" },
      { word: "semaine", ipa: "/səmɛn/" },
      { word: "poisson", ipa: "/pwasɔ̃/" },
      { word: "garçon", ipa: "/gaʁsɔ̃/" },
      { word: "souci", ipa: "/susi/" },
      { word: "sûr", ipa: "/syʁ/" },
      { word: "dessert", ipa: "/desɛʁ/" },
      { word: "salade", ipa: "/salad/" },
      { word: "six", ipa: "/sis/" },
      { word: "si simple", ipa: "/si sɛ̃pl/" },
      { word: "sans souci", ipa: "/sɑ̃ susi/" },
      { word: "sauce salée", ipa: "/sos sale/" },
      { word: "classe simple", ipa: "/klas sɛ̃pl/" },
    ],
    difficulty: "easy",
    description:
      "清齿龈摩擦音，气流窄而稳定；注意单词内部 s 可能因拼写环境变 /z/，这里训练清 /s/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-z",
    ipa: "/z/",
    name: "French z",
    category: "consonant",
    example: "zéro",
    keywords: [
      { word: "zéro", ipa: "/zeʁo/" },
      { word: "zoo", ipa: "/zo/" },
      { word: "rose", ipa: "/ʁoz/" },
      { word: "maison", ipa: "/mɛzɔ̃/" },
      { word: "musique", ipa: "/myzik/" },
      { word: "visiter", ipa: "/vizite/" },
      { word: "voisin", ipa: "/vwazɛ̃/" },
      { word: "deuxième", ipa: "/døzjɛm/" },
      { word: "treize", ipa: "/tʁɛz/" },
      { word: "chaise", ipa: "/ʃɛz/" },
      { word: "cuisine", ipa: "/kɥizin/" },
      { word: "bizarre", ipa: "/bizaʁ/" },
      { word: "zèbre", ipa: "/zɛbʁ/" },
      { word: "zone", ipa: "/zon/" },
      { word: "gaz", ipa: "/gaz/" },
      { word: "onze", ipa: "/ɔ̃z/" },
      { word: "douze", ipa: "/duz/" },
      { word: "quinze", ipa: "/kɛ̃z/" },
      { word: "zeste", ipa: "/zɛst/" },
      { word: "zinc", ipa: "/zɛ̃k/" },
      { word: "zéro zone", ipa: "/zeʁo zon/" },
      { word: "rose rouge", ipa: "/ʁoz ʁuʒ/" },
      { word: "maison rose", ipa: "/mɛzɔ̃ ʁoz/" },
      { word: "douze amis", ipa: "/duz ami/" },
    ],
    difficulty: "medium",
    description:
      "像 /s/ 的浊音版本，摩擦时声带振动；不要读成英语 /dʒ/ 或清化成 /s/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-m",
    ipa: "/m/",
    name: "French m",
    category: "consonant",
    example: "ma",
    keywords: [
      { word: "ma", ipa: "/ma/" },
      { word: "me", ipa: "/mə/" },
      { word: "mon", ipa: "/mɔ̃/" },
      { word: "maison", ipa: "/mɛzɔ̃/" },
      { word: "merci", ipa: "/mɛʁsi/" },
      { word: "maman", ipa: "/mamɑ̃/" },
      { word: "femme", ipa: "/fam/" },
      { word: "homme", ipa: "/ɔm/" },
      { word: "comme", ipa: "/kɔm/" },
      { word: "samedi", ipa: "/samdi/" },
      { word: "monde", ipa: "/mɔ̃d/" },
      { word: "musique", ipa: "/myzik/" },
      { word: "minute", ipa: "/minyt/" },
      { word: "malade", ipa: "/malad/" },
      { word: "menu", ipa: "/məny/" },
      { word: "midi", ipa: "/midi/" },
      { word: "moderne", ipa: "/mɔdɛʁn/" },
      { word: "mot", ipa: "/mo/" },
      { word: "même", ipa: "/mɛm/" },
      { word: "miel", ipa: "/mjɛl/" },
      { word: "ma maison", ipa: "/ma mɛzɔ̃/" },
      { word: "merci maman", ipa: "/mɛʁsi mamɑ̃/" },
      { word: "même musique", ipa: "/mɛm myzik/" },
      { word: "menu moderne", ipa: "/məny mɔdɛʁn/" },
    ],
    difficulty: "easy",
    description:
      "双唇闭合、声音从鼻腔出来；保持短而稳定，不在后面加多余元音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-n",
    ipa: "/n/",
    name: "French n",
    category: "consonant",
    example: "nous",
    keywords: [
      { word: "nous", ipa: "/nu/" },
      { word: "non", ipa: "/nɔ̃/" },
      { word: "nuit", ipa: "/nɥi/" },
      { word: "nez", ipa: "/ne/" },
      { word: "venir", ipa: "/vəniʁ/" },
      { word: "bonne", ipa: "/bɔn/" },
      { word: "donne", ipa: "/dɔn/" },
      { word: "année", ipa: "/ane/" },
      { word: "personne", ipa: "/pɛʁsɔn/" },
      { word: "animal", ipa: "/animal/" },
      { word: "fenêtre", ipa: "/fənɛtʁ/" },
      { word: "ton", ipa: "/tɔ̃/" },
      { word: "une", ipa: "/yn/" },
      { word: "lune", ipa: "/lyn/" },
      { word: "nature", ipa: "/natyʁ/" },
      { word: "notre", ipa: "/nɔtʁ/" },
      { word: "canal", ipa: "/kanal/" },
      { word: "cinéma", ipa: "/sinema/" },
      { word: "numéro", ipa: "/nymeʁo/" },
      { word: "normal", ipa: "/nɔʁmal/" },
      { word: "nous venons", ipa: "/nu vənɔ̃/" },
      { word: "bonne nuit", ipa: "/bɔn nɥi/" },
      { word: "une année", ipa: "/yn ane/" },
      { word: "nature normale", ipa: "/natyʁ nɔʁmal/" },
    ],
    difficulty: "easy",
    description:
      "舌尖接近上齿背/齿龈，鼻腔出声；不要把鼻化元音后的拼写 n 当成清楚 /n/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-l",
    ipa: "/l/",
    name: "French l",
    category: "consonant",
    example: "la",
    keywords: [
      { word: "la", ipa: "/la/" },
      { word: "le", ipa: "/lə/" },
      { word: "lune", ipa: "/lyn/" },
      { word: "livre", ipa: "/livʁ/" },
      { word: "lit", ipa: "/li/" },
      { word: "elle", ipa: "/ɛl/" },
      { word: "école", ipa: "/ekɔl/" },
      { word: "salon", ipa: "/salɔ̃/" },
      { word: "malade", ipa: "/malad/" },
      { word: "bleu", ipa: "/blø/" },
      { word: "fleur", ipa: "/flœʁ/" },
      { word: "classe", ipa: "/klas/" },
      { word: "table", ipa: "/tabl/" },
      { word: "parler", ipa: "/paʁle/" },
      { word: "aller", ipa: "/ale/" },
      { word: "mille", ipa: "/mil/" },
      { word: "ville", ipa: "/vil/" },
      { word: "journal", ipa: "/ʒuʁnal/" },
      { word: "soleil", ipa: "/sɔlɛj/" },
      { word: "animal", ipa: "/animal/" },
      { word: "la lune", ipa: "/la lyn/" },
      { word: "le livre", ipa: "/lə livʁ/" },
      { word: "belle école", ipa: "/bɛl ekɔl/" },
      { word: "table bleue", ipa: "/tabl blø/" },
    ],
    difficulty: "easy",
    description:
      "法语 /l/ 保持清亮，舌尖接触前部；不要带英语词尾 dark L 的厚重后舌音色。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-liaison",
    ipa: "/‿/",
    name: "liaison and enchaînement",
    category: "prosody",
    soundUnitType: "connected-speech-rule",
    example: "les amis",
    keywords: [
      { word: "les amis", ipa: "/lezami/" },
      { word: "un ami", ipa: "/œ̃nami/" },
      { word: "vous avez", ipa: "/vuzave/" },
      { word: "petit ami", ipa: "/pətitami/" },
      { word: "grand homme", ipa: "/gʁɑ̃tɔm/" },
      { word: "chez elle", ipa: "/ʃezɛl/" },
    ],
    difficulty: "high",
    description:
      "法语词尾辅音常静音，但在连诵环境会重新出现；这是句子层训练，不该当作单个音素评分。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-a",
    ipa: "/a/",
    name: "open front vowel",
    category: "vowel",
    example: "la",
    keywords: [
      { word: "la", ipa: "/la/" },
      { word: "ma", ipa: "/ma/" },
      { word: "chat", ipa: "/ʃa/" },
      { word: "ami", ipa: "/ami/" },
      { word: "Paris", ipa: "/paʁi/" },
      { word: "table", ipa: "/tabl/" },
      { word: "madame", ipa: "/madam/" },
      { word: "salade", ipa: "/salad/" },
      { word: "classe", ipa: "/klas/" },
      { word: "arrive", ipa: "/aʁiv/" },
      { word: "avec", ipa: "/avɛk/" },
      { word: "animal", ipa: "/animal/" },
      { word: "samedi", ipa: "/samdi/" },
      { word: "matin", ipa: "/matɛ̃/" },
      { word: "facile", ipa: "/fasil/" },
      { word: "baguette", ipa: "/bagɛt/" },
      { word: "jardin", ipa: "/ʒaʁdɛ̃/" },
      { word: "la table", ipa: "/la tabl/" },
      { word: "Paris arrive", ipa: "/paʁi aʁiv/" },
      { word: "un ami", ipa: "/œ̃nami/" },
    ],
    difficulty: "easy",
    description:
      "嘴巴打开，舌位偏前；不要像英语 /æ/ 那样拉扯，也不要拖成双元音。",
    notes: ["现代标准法语常把 /a/ 与后元音 /ɑ/ 合并；本模块先按核心 /a/ 训练。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-schwa",
    ipa: "/ə/",
    name: "French schwa / e caduc",
    category: "vowel",
    soundUnitType: "prosody",
    example: "petit",
    keywords: [
      { word: "ce que je veux", ipa: "/sə kə ʒə vø/" },
      { word: "le", ipa: "/lə/" },
      { word: "de", ipa: "/də/" },
      { word: "Je prends un petit déjeuner.", ipa: "/ʒə pʁɑ̃ œ̃ pəti deʒœne/" },
      { word: "demain", ipa: "/dəmɛ̃/" },
      { word: "demander", ipa: "/dəmɑ̃de/" },
      { word: "menu", ipa: "/məny/" },
      { word: "cheveux", ipa: "/ʃəvø/" },
      { word: "semaine", ipa: "/səmɛn/" },
      { word: "samedi", ipa: "/samdi/" },
      { word: "fenêtre", ipa: "/fənɛtʁ/" },
      { word: "revenez", ipa: "/ʁəvəne/" },
      { word: "premier avril", ipa: "/pʁəmje avʁil/" },
      { word: "petite école", ipa: "/pətitekɔl/" },
      { word: "ce matin", ipa: "/sə matɛ̃/" },
      { word: "je veux", ipa: "/ʒə vø/" },
      { word: "le petit", ipa: "/lə pəti/" },
      { word: "de demain", ipa: "/də dəmɛ̃/" },
      { word: "menu du jour", ipa: "/məny dy ʒuʁ/" },
      { word: "revenez samedi", ipa: "/ʁəvəne samedi/" },
    ],
    difficulty: "high",
    description:
      "法语 e caduc /ə/ 在慢速和教学读法中可听见，在自然语流里可能弱化或省略。",
    notes: [
      "不要把 /ə/ 读成英语重读 /ɜː/；它短、轻、可变。",
      "schwa 是否出现受语速、地区和语境影响，应作为语流规则训练。",
    ],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-o-close",
    ipa: "/o/",
    name: "close-mid back rounded vowel",
    category: "vowel",
    example: "beau",
    keywords: [
      { word: "beau", ipa: "/bo/" },
      { word: "eau", ipa: "/o/" },
      { word: "mot", ipa: "/mo/" },
      { word: "dos", ipa: "/do/" },
      { word: "trop", ipa: "/tʁo/" },
      { word: "chaud", ipa: "/ʃo/" },
      { word: "rose", ipa: "/ʁoz/" },
      { word: "gauche", ipa: "/goʃ/" },
      { word: "photo", ipa: "/foto/" },
      { word: "vélo", ipa: "/velo/" },
      { word: "bureau", ipa: "/byʁo/" },
      { word: "cadeau", ipa: "/kado/" },
      { word: "bateau", ipa: "/bato/" },
      { word: "zéro", ipa: "/zeʁo/" },
      { word: "hôtel", ipa: "/otɛl/" },
      { word: "drôle", ipa: "/dʁol/" },
      { word: "jaune", ipa: "/ʒon/" },
      { word: "beau vélo", ipa: "/bo velo/" },
      { word: "eau chaude", ipa: "/o ʃod/" },
      { word: "un cadeau", ipa: "/œ̃ kado/" },
    ],
    difficulty: "medium",
    description:
      "圆唇、舌后中高位；不要读成英语 /oʊ/ 双元音，结尾不滑。",
    notes: ["常见拼写 eau/au/o 可对应 /o/，但开闭受词和地区影响，需词典复核。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-o-open",
    ipa: "/ɔ/",
    name: "open-mid back rounded vowel",
    category: "vowel",
    example: "porte",
    keywords: [
      { word: "porte", ipa: "/pɔʁt/" },
      { word: "école", ipa: "/ekɔl/" },
      { word: "homme", ipa: "/ɔm/" },
      { word: "comme", ipa: "/kɔm/" },
      { word: "bonne", ipa: "/bɔn/" },
      { word: "fort", ipa: "/fɔʁ/" },
      { word: "encore", ipa: "/ɑ̃kɔʁ/" },
      { word: "corps", ipa: "/kɔʁ/" },
      { word: "sort", ipa: "/sɔʁ/" },
      { word: "note", ipa: "/nɔt/" },
      { word: "ordinateur", ipa: "/ɔʁdinatœʁ/" },
      { word: "d'accord", ipa: "/dakɔʁ/" },
      { word: "pomme", ipa: "/pɔm/" },
      { word: "bol", ipa: "/bɔl/" },
      { word: "colle", ipa: "/kɔl/" },
      { word: "folle", ipa: "/fɔl/" },
      { word: "octobre", ipa: "/ɔktɔbʁ/" },
      { word: "bonne porte", ipa: "/bɔn pɔʁt/" },
      { word: "encore fort", ipa: "/ɑ̃kɔʁ fɔʁ/" },
      { word: "pomme comme ça", ipa: "/pɔm kɔm sa/" },
    ],
    difficulty: "medium",
    description:
      "圆唇但口腔更开；和 /o/ 做 beau/bonne、eau/homme 式对比。",
    notes: ["闭音节中常出现 /ɔ/，但不能只靠拼写猜，要用词典或 IPA 资源复核。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-un",
    ipa: "/œ̃/",
    name: "nasal front rounded vowel un",
    category: "vowel",
    soundUnitType: "contrast",
    example: "un",
    keywords: [
      { word: "un", ipa: "/œ̃/" },
      { word: "brun", ipa: "/bʁœ̃/" },
      { word: "parfum", ipa: "/paʁfœ̃/" },
      { word: "lundi", ipa: "/lœ̃di/" },
      { word: "emprunt", ipa: "/ɑ̃pʁœ̃/" },
      { word: "commun", ipa: "/kɔmœ̃/" },
      { word: "quelqu'un", ipa: "/kɛlkœ̃/" },
      { word: "chacun", ipa: "/ʃakœ̃/" },
      { word: "aucun", ipa: "/okœ̃/" },
      { word: "jeun", ipa: "/ʒœ̃/" },
      { word: "défunt", ipa: "/defœ̃/" },
      { word: "humble", ipa: "/œ̃bl/" },
      { word: "un lundi", ipa: "/œ̃ lœ̃di/" },
      { word: "brun parfum", ipa: "/bʁœ̃ paʁfœ̃/" },
      { word: "aucun emprunt", ipa: "/okœ̃ ɑ̃pʁœ̃/" },
      { word: "quelqu'un vient", ipa: "/kɛlkœ̃ vjɛ̃/" },
      { word: "parfum brun", ipa: "/paʁfœ̃ bʁœ̃/" },
      { word: "lundi matin", ipa: "/lœ̃di matɛ̃/" },
      { word: "un commun", ipa: "/œ̃ kɔmœ̃/" },
      { word: "chacun parle", ipa: "/ʃakœ̃ paʁl/" },
    ],
    difficulty: "high",
    description:
      "传统 IPA 表里单列 /œ̃/；许多现代法语口音会和 /ɛ̃/ 合并，学习时先知道这个变体。",
    notes: [
      "现代巴黎法语常把 /œ̃/ merge/合并到 /ɛ̃/；评分和反馈不应把合并口音直接判错。",
      "先作为听辨和变体提示，再进入精细发音训练。",
    ],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-sh",
    ipa: "/ʃ/",
    name: "French ch",
    category: "consonant",
    example: "chat",
    keywords: [
      { word: "chat", ipa: "/ʃa/" },
      { word: "chez", ipa: "/ʃe/" },
      { word: "chose", ipa: "/ʃoz/" },
      { word: "chaud", ipa: "/ʃo/" },
      { word: "machine", ipa: "/maʃin/" },
      { word: "dimanche", ipa: "/dimɑ̃ʃ/" },
      { word: "chercher", ipa: "/ʃɛʁʃe/" },
      { word: "chemise", ipa: "/ʃəmiz/" },
      { word: "chanson", ipa: "/ʃɑ̃sɔ̃/" },
      { word: "bouche", ipa: "/buʃ/" },
      { word: "gauche", ipa: "/goʃ/" },
      { word: "marché", ipa: "/maʁʃe/" },
      { word: "chemin", ipa: "/ʃəmɛ̃/" },
      { word: "chambre", ipa: "/ʃɑ̃bʁ/" },
      { word: "chapeau", ipa: "/ʃapo/" },
      { word: "chaise", ipa: "/ʃɛz/" },
      { word: "chaque", ipa: "/ʃak/" },
      { word: "chez elle", ipa: "/ʃezɛl/" },
      { word: "chat chaud", ipa: "/ʃa ʃo/" },
      { word: "chercher chez nous", ipa: "/ʃɛʁʃe ʃe nu/" },
    ],
    difficulty: "medium",
    description: "法语 ch 是纯摩擦 /ʃ/，不要读成英语或西语式 /tʃ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-zh",
    ipa: "/ʒ/",
    name: "French j/soft g",
    category: "consonant",
    example: "je",
    keywords: [
      { word: "je", ipa: "/ʒə/" },
      { word: "jour", ipa: "/ʒuʁ/" },
      { word: "jamais", ipa: "/ʒamɛ/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "manger", ipa: "/mɑ̃ʒe/" },
      { word: "jardin", ipa: "/ʒaʁdɛ̃/" },
      { word: "déjeuner", ipa: "/deʒœne/" },
      { word: "général", ipa: "/ʒeneʁal/" },
      { word: "jupe", ipa: "/ʒyp/" },
      { word: "juste", ipa: "/ʒyst/" },
      { word: "image", ipa: "/imaʒ/" },
      { word: "fromage", ipa: "/fʁɔmaʒ/" },
      { word: "garage", ipa: "/gaʁaʒ/" },
      { word: "gentil", ipa: "/ʒɑ̃ti/" },
      { word: "journal", ipa: "/ʒuʁnal/" },
      { word: "gilet", ipa: "/ʒilɛ/" },
      { word: "je joue", ipa: "/ʒə ʒu/" },
      { word: "jour rouge", ipa: "/ʒuʁ ʁuʒ/" },
      { word: "jardin joli", ipa: "/ʒaʁdɛ̃ ʒɔli/" },
      { word: "manger du fromage", ipa: "/mɑ̃ʒe dy fʁɔmaʒ/" },
    ],
    difficulty: "medium",
    description: "声带振动的 /ʒ/，像 /ʃ/ 的浊音版本；不要读成 /dʒ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-ny",
    ipa: "/ɲ/",
    name: "French gn",
    category: "consonant",
    example: "vigne",
    keywords: [
      { word: "vigne", ipa: "/viɲ/" },
      { word: "montagne", ipa: "/mɔ̃taɲ/" },
      { word: "oignon", ipa: "/ɔɲɔ̃/" },
      { word: "signature", ipa: "/siɲatyʁ/" },
      { word: "campagne", ipa: "/kɑ̃paɲ/" },
      { word: "ligne", ipa: "/liɲ/" },
      { word: "peigne", ipa: "/pɛɲ/" },
      { word: "agneau", ipa: "/aɲo/" },
      { word: "Espagne", ipa: "/ɛspaɲ/" },
      { word: "Bretagne", ipa: "/bʁətaɲ/" },
      { word: "gagner", ipa: "/gaɲe/" },
      { word: "enseigner", ipa: "/ɑ̃sɛɲe/" },
      { word: "mignon", ipa: "/miɲɔ̃/" },
      { word: "ignorer", ipa: "/iɲɔʁe/" },
      { word: "signe", ipa: "/siɲ/" },
      { word: "digne", ipa: "/diɲ/" },
      { word: "ligne droite", ipa: "/liɲ dʁwat/" },
      { word: "vigne rouge", ipa: "/viɲ ʁuʒ/" },
      { word: "montagne blanche", ipa: "/mɔ̃taɲ blɑ̃ʃ/" },
      { word: "mignon agneau", ipa: "/miɲɔ̃ aɲo/" },
    ],
    difficulty: "medium",
    description: "gn 常对应 /ɲ/；舌面贴近硬腭发鼻音，不要拆成 /n/ + /j/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-glide-j",
    ipa: "/j/",
    name: "French yod glide",
    category: "consonant",
    soundUnitType: "contrast",
    example: "fille",
    keywords: [
      { word: "fille", ipa: "/fij/" },
      { word: "famille", ipa: "/famij/" },
      { word: "bien", ipa: "/bjɛ̃/" },
      { word: "pied", ipa: "/pje/" },
      { word: "hier", ipa: "/jɛʁ/" },
      { word: "yeux", ipa: "/jø/" },
      { word: "payer", ipa: "/peje/" },
      { word: "voyage", ipa: "/vwajaʒ/" },
      { word: "soleil", ipa: "/sɔlɛj/" },
      { word: "travail", ipa: "/tʁavaj/" },
      { word: "oreille", ipa: "/ɔʁɛj/" },
      { word: "conseil", ipa: "/kɔ̃sɛj/" },
      { word: "meilleur", ipa: "/mɛjœʁ/" },
      { word: "juillet", ipa: "/ʒɥijɛ/" },
      { word: "février", ipa: "/fevʁije/" },
      { word: "Parisien", ipa: "/paʁizjɛ̃/" },
      { word: "bien joué", ipa: "/bjɛ̃ ʒwe/" },
      { word: "ma famille", ipa: "/ma famij/" },
      { word: "payer hier", ipa: "/peje jɛʁ/" },
      { word: "voyage au soleil", ipa: "/vwajaʒ o sɔlɛj/" },
    ],
    difficulty: "medium",
    description: "法语 /j/ 是很短的前滑音；不要额外加一个完整元音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-glide-hui",
    ipa: "/ɥ/",
    name: "French front rounded glide",
    category: "consonant",
    soundUnitType: "contrast",
    example: "huit",
    keywords: [
      { word: "huit", ipa: "/ɥit/" },
      { word: "huile", ipa: "/ɥil/" },
      { word: "huis", ipa: "/ɥi/" },
      { word: "huître", ipa: "/ɥitʁ/" },
      { word: "nuit", ipa: "/nɥi/" },
      { word: "pluie", ipa: "/plɥi/" },
      { word: "suisse", ipa: "/sɥis/" },
      { word: "suivre", ipa: "/sɥivʁ/" },
      { word: "aiguille", ipa: "/egɥij/" },
      { word: "aigu", ipa: "/egy/" },
      { word: "nuire", ipa: "/nɥiʁ/" },
      { word: "lui", ipa: "/lɥi/" },
      { word: "depuis", ipa: "/dəpɥi/" },
      { word: "aujourd'hui", ipa: "/oʒuʁdɥi/" },
      { word: "juin", ipa: "/ʒɥɛ̃/" },
      { word: "Louis", ipa: "/lwi/" },
      { word: "huit nuits", ipa: "/ɥit nɥi/" },
      { word: "pluie suisse", ipa: "/plɥi sɥis/" },
      { word: "depuis juin", ipa: "/dəpɥi ʒɥɛ̃/" },
      { word: "lui aussi", ipa: "/lɥi osi/" },
    ],
    difficulty: "high",
    description:
      "/ɥ/ 是 /y/ 的短滑音：舌位偏前、双唇收圆，不要退成英语 /w/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-glide-w",
    ipa: "/w/",
    name: "French back rounded glide",
    category: "consonant",
    soundUnitType: "contrast",
    example: "oui",
    keywords: [
      { word: "oui", ipa: "/wi/" },
      { word: "ouest", ipa: "/wɛst/" },
      { word: "oiseau", ipa: "/wazo/" },
      { word: "quoi", ipa: "/kwa/" },
      { word: "moi", ipa: "/mwa/" },
      { word: "toi", ipa: "/twa/" },
      { word: "trois", ipa: "/tʁwa/" },
      { word: "boire", ipa: "/bwaʁ/" },
      { word: "voir", ipa: "/vwaʁ/" },
      { word: "pouvoir", ipa: "/puvwaʁ/" },
      { word: "croire", ipa: "/kʁwaʁ/" },
      { word: "noir", ipa: "/nwaʁ/" },
      { word: "soir", ipa: "/swaʁ/" },
      { word: "voiture", ipa: "/vwatyʁ/" },
      { word: "loi", ipa: "/lwa/" },
      { word: "loin", ipa: "/lwɛ̃/" },
      { word: "oui trois", ipa: "/wi tʁwa/" },
      { word: "moi et toi", ipa: "/mwa e twa/" },
      { word: "voir l'oiseau", ipa: "/vwaʁ lwazo/" },
      { word: "soir noir", ipa: "/swaʁ nwaʁ/" },
    ],
    difficulty: "medium",
    description: "/w/ 是短后圆唇滑音；和前圆唇 /ɥ/ 分开，避免把 lui 读成 /lwi/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-final-consonant-silence",
    ipa: "silent final C",
    name: "silent final consonants",
    category: "prosody",
    soundUnitType: "connected-speech-rule",
    example: "petit",
    keywords: [
      { word: "petit", ipa: "/pəti/" },
      { word: "trop", ipa: "/tʁo/" },
      { word: "beaucoup", ipa: "/boku/" },
      { word: "nez", ipa: "/ne/" },
      { word: "dos", ipa: "/do/" },
      { word: "chaud", ipa: "/ʃo/" },
      { word: "froid", ipa: "/fʁwa/" },
      { word: "temps", ipa: "/tɑ̃/" },
      { word: "grand froid", ipa: "/gʁɑ̃ fʁwa/" },
      { word: "Le chat jaune dort.", ipa: "/lə ʃa ʒon dɔʁ/" },
      { word: "le prix bas", ipa: "/lə pʁi ba/" },
      { word: "trois amis", ipa: "/tʁwɑzami/" },
      { word: "un grand choix", ipa: "/œ̃ gʁɑ̃ ʃwa/" },
      { word: "un mot court", ipa: "/œ̃ mo kuʁ/" },
      { word: "temps chaud", ipa: "/tɑ̃ ʃo/" },
      {
        word: "Trop grand, trop lent, trop fort.",
        ipa: "/tʁo gʁɑ̃ tʁo lɑ̃ tʁo fɔʁ/",
      },
      { word: "un petit chat", ipa: "/œ̃ pəti ʃa/" },
      { word: "vin blanc", ipa: "/vɛ̃ blɑ̃/" },
      { word: "Un bon vin blanc.", ipa: "/œ̃ bɔ̃ vɛ̃ blɑ̃/" },
      {
        word: "J'aime le bon vin blanc.",
        ipa: "/ʒɛm lə bɔ̃ vɛ̃ blɑ̃/",
      },
      { word: "les livres", ipa: "/le livʁ/" },
    ],
    difficulty: "high",
    description:
      "许多法语词尾辅音孤立时不发音；不要按拼写把 t/d/p/s/x/z 全部读出来。",
    notes: ["这是 phrase-level 规则：liaison 或派生形式里词尾辅音可能重新出现。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-enchainement",
    ipa: "enchaînement",
    name: "enchaînement",
    category: "prosody",
    soundUnitType: "connected-speech-rule",
    example: "il arrive",
    keywords: [
      { word: "il arrive", ipa: "/ilaʁiv/" },
      { word: "elle arrive", ipa: "/ɛlaʁiv/" },
      { word: "avec elle", ipa: "/avɛkɛl/" },
      { word: "il habite", ipa: "/ilabit/" },
      { word: "elle aime", ipa: "/ɛlɛm/" },
      { word: "un homme", ipa: "/œ̃nɔm/" },
      { word: "mon ami", ipa: "/mɔnami/" },
      { word: "bonne idée", ipa: "/bɔnidɛ/" },
      { word: "petite école", ipa: "/pətitekɔl/" },
      { word: "grande amie", ipa: "/gʁɑ̃dami/" },
      { word: "dans une", ipa: "/dɑ̃zyn/" },
      { word: "chez elle", ipa: "/ʃezɛl/" },
      { word: "la porte ouverte", ipa: "/la pɔʁtuvɛʁt/" },
      { word: "le livre est", ipa: "/lə livʁɛ/" },
      { word: "une robe orange", ipa: "/yn ʁɔbɔʁɑ̃ʒ/" },
      { word: "il est ici", ipa: "/ilɛtisi/" },
      { word: "Paris arrive", ipa: "/paʁi aʁiv/" },
      { word: "Luc arrive", ipa: "/lykaʁiv/" },
      { word: "elle ouvre", ipa: "/ɛluvʁ/" },
      { word: "avec un ami", ipa: "/avɛkœ̃nami/" },
    ],
    difficulty: "high",
    description:
      "本来发音的词尾辅音会自然连到下一个元音开头词；这不是新增音素，而是语流连接。",
    notes: ["和 liaison 不同，enchaînement 中词尾辅音本来就发音，只是跨词连接。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-elision",
    ipa: "elision",
    name: "elision",
    category: "prosody",
    soundUnitType: "connected-speech-rule",
    example: "j'aime",
    keywords: [
      { word: "J'aime le bon vin blanc.", ipa: "/ʒɛm lə bɔ̃ vɛ̃ blɑ̃/" },
      { word: "j'habite", ipa: "/ʒabit/" },
      { word: "L'ami arrive à huit heures.", ipa: "/lami aʁiv a ɥit œʁ/" },
      { word: "l'école", ipa: "/lekɔl/" },
      { word: "c'est", ipa: "/sɛ/" },
      { word: "d'accord", ipa: "/dakɔʁ/" },
      { word: "qu'il", ipa: "/kil/" },
      {
        word: "Un parfum brun peut varier selon l'accent.",
        ipa: "/œ̃ paʁfœ̃ bʁœ̃ pø vaʁje səlɔ̃ laksɑ̃/",
      },
      { word: "jusqu'à", ipa: "/ʒyska/" },
      { word: "n'est-ce pas", ipa: "/nɛs pa/" },
      { word: "l'homme écoute", ipa: "/lɔmekut/" },
      { word: "l'eau", ipa: "/lo/" },
      { word: "j'écoute", ipa: "/ʒekut/" },
      { word: "j'arrive", ipa: "/ʒaʁiv/" },
      { word: "c'était", ipa: "/setɛ/" },
      { word: "d'ici", ipa: "/disi/" },
      { word: "j'aime Paris", ipa: "/ʒɛm paʁi/" },
      { word: "l'ami arrive", ipa: "/lami aʁiv/" },
      { word: "c'est ouvert", ipa: "/sɛ uvɛʁ/" },
      { word: "d'accord avec elle", ipa: "/dakɔʁ avɛkɛl/" },
    ],
    difficulty: "high",
    description:
      "法语在元音前常省略弱元音并用撇号连接；按词逐个读会破坏自然语流。",
    notes: ["elision 是拼写和发音共同发生的 phrase-level 现象，应和单词孤立发音分开评分。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-phrase-final-prominence",
    ipa: "accent final",
    name: "phrase-final prominence",
    category: "prosody",
    soundUnitType: "prosody",
    example: "Bonjour.",
    keywords: [
      { word: "Bonjour.", ipa: "/bɔ̃ʒuʁ/" },
      { word: "Très bien.", ipa: "/tʁɛ bjɛ̃/" },
      { word: "À demain.", ipa: "/a dəmɛ̃/" },
      { word: "Merci beaucoup.", ipa: "/mɛʁsi boku/" },
      { word: "Je suis prêt.", ipa: "/ʒə sɥi pʁɛ/" },
      { word: "Nous arrivons.", ipa: "/nuzaʁivɔ̃/" },
      { word: "Elle écoute.", ipa: "/ɛlekut/" },
      { word: "Le train part.", ipa: "/lə tʁɛ̃ paʁ/" },
      { word: "Marie travaille.", ipa: "/maʁi tʁavaj/" },
      { word: "Paul répond.", ipa: "/pɔl ʁepɔ̃/" },
      { word: "Le café ferme.", ipa: "/lə kafe fɛʁm/" },
      { word: "Cette idée plaît.", ipa: "/sɛtide plɛ/" },
      { word: "Un enfant rit.", ipa: "/œ̃nɑ̃fɑ̃ ʁi/" },
      { word: "Le marché ouvre.", ipa: "/lə maʁʃe uvʁ/" },
      { word: "La voiture arrive.", ipa: "/la vwatyʁaʁiv/" },
      { word: "Ton ami chante.", ipa: "/tɔnami ʃɑ̃t/" },
      { word: "Le professeur explique.", ipa: "/lə pʁɔfɛsœʁ ɛksplik/" },
      { word: "Camille prépare.", ipa: "/kamij pʁepaʁ/" },
      { word: "Le musée ferme tôt.", ipa: "/lə myze fɛʁm to/" },
      { word: "Sa famille voyage.", ipa: "/sa famij vwajaʒ/" },
      { word: "Le silence tombe.", ipa: "/lə silɑ̃s tɔ̃b/" },
      { word: "Une question reste.", ipa: "/yn kɛstjɔ̃ ʁɛst/" },
      { word: "Le jardin respire.", ipa: "/lə ʒaʁdɛ̃ ʁɛspiʁ/" },
      { word: "Ce soir, on sort.", ipa: "/sə swaʁ ɔ̃ sɔʁ/" },
    ],
    difficulty: "medium",
    description:
      "法语没有英语式每个内容词都重读的词重音；突出通常落在节奏组最后一个可发音音节上。",
    notes: [
      "这是 sentence/prosody 目标：练习末尾音节的轻微延长和短语轮廓，不作为单音标播放。",
    ],
  }),
];
