import type { PhonemeData } from "@/types/phoneme";
import { unit } from "@/lib/language-sound-units/utils";

type RussianHardContinuantInput = {
  slug: string;
  ipa: string;
  name: string;
  example: string;
  keywords: PhonemeData["keywords"];
  difficulty?: PhonemeData["difficulty"];
  description: string;
  notes: string[];
};

const RUSSIAN_HARD_STOP_UNITS: PhonemeData[] = [
  unit({
    languageId: "ru-RU",
    slug: "ru-p",
    ipa: "/p/",
    name: "Russian hard п",
    category: "consonant",
    example: "парк",
    keywords: [
      { word: "парк", ipa: "/park/", stressText: "парк" },
      { word: "папа", ipa: "/ˈpapə/", stressText: "па́па" },
      { word: "плохо", ipa: "/ˈploxə/", stressText: "пло́хо" },
      { word: "поезд", ipa: "/ˈpojɪst/", stressText: "по́езд" },
      { word: "помощь", ipa: "/ˈpoməɕː/", stressText: "по́мощь" },
      { word: "площадь", ipa: "/ˈploɕːətʲ/", stressText: "пло́щадь" },
      { word: "проблема", ipa: "/prɐˈblʲemə/", stressText: "пробле́ма" },
      { word: "привет", ipa: "/prʲɪˈvʲet/", stressText: "приве́т" },
      { word: "праздник", ipa: "/ˈpraznʲɪk/", stressText: "пра́здник" },
      { word: "пустой", ipa: "/pʊˈstoj/", stressText: "пусто́й" },
      { word: "пол", ipa: "/pol/", stressText: "пол" },
      { word: "порт", ipa: "/port/", stressText: "порт" },
      { word: "пыль", ipa: "/pɨlʲ/", stressText: "пыль" },
      { word: "путь", ipa: "/putʲ/", stressText: "путь" },
      { word: "спорт", ipa: "/sport/", stressText: "спорт" },
      { word: "полка", ipa: "/ˈpolkə/", stressText: "по́лка" },
      { word: "папа дома", ipa: "/ˈpapə ˈdomə/", stressText: "па́па до́ма" },
      { word: "поезд идёт", ipa: "/ˈpojɪst ɪˈdʲot/", stressText: "по́езд идёт" },
      { word: "простой парк", ipa: "/prɐˈstoj park/", stressText: "просто́й парк" },
      { word: "плохая погода", ipa: "/plɐˈxajə pɐˈgodə/", stressText: "плоха́я пого́да" },
      { word: "пакет", ipa: "/pɐˈkʲet/", stressText: "паке́т" },
      { word: "порог", ipa: "/pɐˈrok/", stressText: "поро́г" },
      { word: "пруд", ipa: "/prut/", stressText: "пруд" },
      { word: "пуля", ipa: "/ˈpulʲə/", stressText: "пу́ля" },
    ],
    difficulty: "medium",
    description:
      "硬 /p/ 是清双唇塞音锚点；在 ы、а、о、у 或辅音前保持硬，不要自动加 /j/ 或英语式强送气。",
    notes: [
      "软 /pʲ/ 仍在 hard-soft 对比单元里训练，本单元只播放并评分硬 /p/ 短音频。",
    ],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-b",
    ipa: "/b/",
    name: "Russian hard б",
    category: "consonant",
    example: "брат",
    keywords: [
      { word: "бар", ipa: "/bar/", stressText: "бар" },
      { word: "брат", ipa: "/brat/", stressText: "брат" },
      { word: "был", ipa: "/bɨl/", stressText: "был" },
      { word: "быть", ipa: "/bɨtʲ/", stressText: "быть" },
      { word: "быстро", ipa: "/ˈbɨstrə/", stressText: "бы́стро" },
      { word: "бумага", ipa: "/bʊˈmagə/", stressText: "бума́га" },
      { word: "собака", ipa: "/sɐˈbakə/", stressText: "соба́ка" },
      { word: "работа", ipa: "/rɐˈbotə/", stressText: "рабо́та" },
      { word: "автобус", ipa: "/ɐfˈtobus/", stressText: "авто́бус" },
      { word: "рыба", ipa: "/ˈrɨbə/", stressText: "ры́ба" },
      { word: "выбор", ipa: "/ˈvɨbər/", stressText: "вы́бор" },
      { word: "банк", ipa: "/bank/", stressText: "банк" },
      { word: "бок", ipa: "/bok/", stressText: "бок" },
      { word: "боль", ipa: "/bolʲ/", stressText: "боль" },
      { word: "большой", ipa: "/bɐlʲˈʂoj/", stressText: "большо́й" },
      { word: "буду", ipa: "/ˈbudu/", stressText: "бу́ду" },
      { word: "база", ipa: "/ˈbazə/", stressText: "ба́за" },
      { word: "брат дома", ipa: "/brat ˈdomə/", stressText: "брат до́ма" },
      { word: "была дома", ipa: "/bɨˈla ˈdomə/", stressText: "была́ до́ма" },
      { word: "большая бумага", ipa: "/bɐlʲˈʂajə bʊˈmagə/", stressText: "больша́я бума́га" },
      { word: "балкон", ipa: "/bɐlˈkon/", stressText: "балко́н" },
      { word: "борщ", ipa: "/borɕː/", stressText: "борщ" },
      { word: "буква", ipa: "/ˈbukvə/", stressText: "бу́ква" },
      { word: "барабан", ipa: "/bərɐˈban/", stressText: "бараба́н" },
    ],
    difficulty: "medium",
    description:
      "硬 /b/ 是浊双唇塞音锚点；保持声带振动，并和词尾清化规则分开处理。",
    notes: [
      "词尾 б 在停顿前常清化成 [p]；本单元优先练非词尾或连到浊环境里的硬 /b/。",
    ],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-t",
    ipa: "/t/",
    name: "Russian hard т",
    category: "consonant",
    example: "там",
    keywords: [
      { word: "там", ipa: "/tam/", stressText: "там" },
      { word: "ток", ipa: "/tok/", stressText: "ток" },
      { word: "ты", ipa: "/tɨ/", stressText: "ты" },
      { word: "транспорт", ipa: "/ˈtransport/", stressText: "тра́нспорт" },
      { word: "трава", ipa: "/trɐˈva/", stressText: "трава́" },
      { word: "труд", ipa: "/trut/", stressText: "труд" },
      { word: "стол", ipa: "/stol/", stressText: "стол" },
      { word: "том", ipa: "/tom/", stressText: "том" },
      { word: "торт", ipa: "/tort/", stressText: "торт" },
      { word: "танк", ipa: "/tank/", stressText: "танк" },
      { word: "карта", ipa: "/ˈkartə/", stressText: "ка́рта" },
      { word: "брат", ipa: "/brat/", stressText: "брат" },
      { word: "рот", ipa: "/rot/", stressText: "рот" },
      { word: "кот", ipa: "/kot/", stressText: "кот" },
      { word: "мост", ipa: "/most/", stressText: "мост" },
      { word: "спорт", ipa: "/sport/", stressText: "спорт" },
      { word: "утро", ipa: "/ˈutrə/", stressText: "у́тро" },
      { word: "это", ipa: "/ˈetə/", stressText: "э́то" },
      { word: "старый стол", ipa: "/ˈstarɨj stol/", stressText: "ста́рый стол" },
      { word: "транспорт стоит", ipa: "/ˈtransport stɐˈit/", stressText: "тра́нспорт стои́т" },
      { word: "туман", ipa: "/tʊˈman/", stressText: "тума́н" },
      { word: "товар", ipa: "/tɐˈvar/", stressText: "това́р" },
      { word: "труба", ipa: "/trʊˈba/", stressText: "труба́" },
      { word: "тропа", ipa: "/trɐˈpa/", stressText: "тропа́" },
    ],
    difficulty: "medium",
    description:
      "硬 /t/ 是清齿龈/齿音塞音锚点；俄语硬 т 不要读成软 /tʲ/，也不要像英语词首 t 那样强送气。",
    notes: [
      "软 /tʲ/ 继续在 hard-soft 对比单元里训练；本单元只验证硬 /t/ 的短音频。",
    ],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-d",
    ipa: "/d/",
    name: "Russian hard д",
    category: "consonant",
    example: "дом",
    keywords: [
      { word: "да", ipa: "/da/", stressText: "да" },
      { word: "дом", ipa: "/dom/", stressText: "дом" },
      { word: "долго", ipa: "/ˈdolgə/", stressText: "до́лго" },
      { word: "друг", ipa: "/druk/", stressText: "друг" },
      { word: "дорога", ipa: "/dɐˈrogə/", stressText: "доро́га" },
      { word: "вода", ipa: "/vɐˈda/", stressText: "вода́" },
      { word: "Даша", ipa: "/ˈdaʂə/", stressText: "Да́ша" },
      { word: "два", ipa: "/dva/", stressText: "два" },
      { word: "двор", ipa: "/dvor/", stressText: "двор" },
      { word: "думать", ipa: "/ˈdumətʲ/", stressText: "ду́мать" },
      { word: "давно", ipa: "/dɐvˈno/", stressText: "давно́" },
      { word: "драма", ipa: "/ˈdramə/", stressText: "дра́ма" },
      { word: "доктор", ipa: "/ˈdoktor/", stressText: "до́ктор" },
      { word: "дата", ipa: "/ˈdatə/", stressText: "да́та" },
      { word: "дочь", ipa: "/dotɕ/", stressText: "дочь" },
      { word: "дым", ipa: "/dɨm/", stressText: "дым" },
      { word: "дума", ipa: "/ˈdumə/", stressText: "ду́ма" },
      { word: "друг дома", ipa: "/drug ˈdomə/", stressText: "друг до́ма" },
      { word: "дорога далеко", ipa: "/dɐˈrogə dəlʲɪˈko/", stressText: "доро́га далеко́" },
      { word: "Даша дома", ipa: "/ˈdaʂə ˈdomə/", stressText: "Да́ша до́ма" },
      { word: "дар", ipa: "/dar/", stressText: "дар" },
      { word: "дуб", ipa: "/dup/", stressText: "дуб" },
      { word: "дух", ipa: "/dux/", stressText: "дух" },
      { word: "доска", ipa: "/dɐˈska/", stressText: "доска́" },
    ],
    difficulty: "medium",
    description:
      "硬 /d/ 是浊舌尖塞音锚点；要保留浊音，同时和软 /dʲ/、词尾清化分开训练。",
    notes: [
      "孤立词尾 д 常清化成 [t]，所以本单元的点击音频只代表硬 /d/ 本身。",
    ],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-k",
    ipa: "/k/",
    name: "Russian hard к",
    category: "consonant",
    example: "кот",
    keywords: [
      { word: "кот", ipa: "/kot/", stressText: "кот" },
      { word: "кто", ipa: "/kto/", stressText: "кто" },
      { word: "как", ipa: "/kak/", stressText: "как" },
      { word: "книга", ipa: "/ˈknʲigə/", stressText: "кни́га" },
      { word: "красный", ipa: "/ˈkrasnɨj/", stressText: "кра́сный" },
      { word: "карта", ipa: "/ˈkartə/", stressText: "ка́рта" },
      { word: "кухня", ipa: "/ˈkuxnʲə/", stressText: "ку́хня" },
      { word: "окно", ipa: "/ɐkˈno/", stressText: "окно́" },
      { word: "Москва", ipa: "/mɐˈskva/", stressText: "Москва́" },
      { word: "сколько", ipa: "/ˈskolʲkə/", stressText: "ско́лько" },
      { word: "урок", ipa: "/ʊˈrok/", stressText: "уро́к" },
      { word: "рынок", ipa: "/ˈrɨnək/", stressText: "ры́нок" },
      { word: "крыло", ipa: "/krɨˈlo/", stressText: "крыло́" },
      { word: "кошка", ipa: "/ˈkoʂkə/", stressText: "ко́шка" },
      { word: "класс", ipa: "/klas/", stressText: "класс" },
      { word: "кофе", ipa: "/ˈkofʲe/", stressText: "ко́фе" },
      { word: "карта Москвы", ipa: "/ˈkartə mɐskˈvɨ/", stressText: "ка́рта Москвы́" },
      { word: "кот у окна", ipa: "/kot u ɐkˈna/", stressText: "кот у окна́" },
      { word: "красная книга", ipa: "/ˈkrasnəjə ˈknʲigə/", stressText: "кра́сная кни́га" },
      { word: "кто как читает", ipa: "/kto kak tɕɪˈtajɪt/", stressText: "кто как чита́ет" },
      { word: "камень", ipa: "/ˈkamʲɪnʲ/", stressText: "ка́мень" },
      { word: "короткий", ipa: "/kɐˈrotkʲɪj/", stressText: "коро́ткий" },
      { word: "кусок", ipa: "/kʊˈsok/", stressText: "кусо́к" },
      { word: "клуб", ipa: "/klup/", stressText: "клуб" },
    ],
    difficulty: "medium",
    description:
      "硬 /k/ 是清软腭塞音锚点；不要退成英语 /h/，也不要在硬 к 后额外插入元音。",
    notes: [
      "软 /kʲ/ 在 е/и 等环境中另行训练；本单元只播放硬 /k/ 的短音频。",
    ],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-g",
    ipa: "/g/",
    name: "Russian hard г",
    category: "consonant",
    example: "город",
    keywords: [
      { word: "гора", ipa: "/gɐˈra/", stressText: "гора́" },
      { word: "город", ipa: "/ˈgorət/", stressText: "го́род" },
      { word: "где", ipa: "/gdʲe/", stressText: "где" },
      { word: "группа", ipa: "/ˈgrupə/", stressText: "гру́ппа" },
      { word: "глаз", ipa: "/glas/", stressText: "глаз" },
      { word: "говорить", ipa: "/gəvɐˈrʲitʲ/", stressText: "говори́ть" },
      { word: "газ", ipa: "/gas/", stressText: "газ" },
      { word: "гость", ipa: "/gosʲtʲ/", stressText: "гость" },
      { word: "книга", ipa: "/ˈknʲigə/", stressText: "кни́га" },
      { word: "бумага", ipa: "/bʊˈmagə/", stressText: "бума́га" },
      { word: "дорога", ipa: "/dɐˈrogə/", stressText: "доро́га" },
      { word: "погода", ipa: "/pɐˈgodə/", stressText: "пого́да" },
      { word: "много", ipa: "/ˈmnogə/", stressText: "мно́го" },
      { word: "магазин", ipa: "/məgɐˈzʲin/", stressText: "магази́н" },
      { word: "друг дома", ipa: "/drug ˈdomə/", stressText: "друг до́ма" },
      { word: "группа большая", ipa: "/ˈgrupə bɐlʲˈʂajə/", stressText: "гру́ппа больша́я" },
      { word: "город большой", ipa: "/ˈgorəd bɐlʲˈʂoj/", stressText: "го́род большо́й" },
      { word: "газ горит", ipa: "/gaz gɐˈrʲit/", stressText: "газ гори́т" },
      { word: "много гор", ipa: "/ˈmnogə gor/", stressText: "мно́го гор" },
      { word: "погода хорошая", ipa: "/pɐˈgodə xɐˈroʂəjə/", stressText: "пого́да хоро́шая" },
      { word: "голос", ipa: "/ˈgoləs/", stressText: "го́лос" },
      { word: "губа", ipa: "/gʊˈba/", stressText: "губа́" },
      { word: "граница", ipa: "/grɐˈnʲitsə/", stressText: "грани́ца" },
      { word: "галерея", ipa: "/gəlʲɪˈrʲejə/", stressText: "галере́я" },
    ],
    difficulty: "medium",
    description:
      "硬 /g/ 是浊软腭塞音锚点；孤立词尾 г 会清化，点击音频只代表硬 /g/ 本身。",
    notes: [
      "软 /gʲ/ 和词尾清化继续在 hard-soft、final devoicing 单元里训练。",
    ],
  }),
];

const RUSSIAN_HARD_CONTINUANT_UNITS: PhonemeData[] = (
  [
    {
      slug: "ru-f",
      ipa: "/f/",
      name: "Russian hard ф",
      example: "фото",
      keywords: [
        { word: "факт", ipa: "/fakt/", stressText: "факт" },
        { word: "фото", ipa: "/ˈfotə/", stressText: "фо́то" },
        { word: "фон", ipa: "/fon/", stressText: "фон" },
        { word: "фонд", ipa: "/font/", stressText: "фонд" },
        { word: "флаг", ipa: "/flak/", stressText: "флаг" },
        { word: "флот", ipa: "/flot/", stressText: "флот" },
        { word: "фраза", ipa: "/ˈfrazə/", stressText: "фра́за" },
        { word: "фрукт", ipa: "/frukt/", stressText: "фрукт" },
        { word: "форма", ipa: "/ˈformə/", stressText: "фо́рма" },
        { word: "фокус", ipa: "/ˈfokʊs/", stressText: "фо́кус" },
        { word: "футбол", ipa: "/fʊdˈbol/", stressText: "футбо́л" },
        { word: "фонарь", ipa: "/fɐˈnarʲ/", stressText: "фона́рь" },
        { word: "фабрика", ipa: "/ˈfabrʲɪkə/", stressText: "фа́брика" },
        { word: "фарфор", ipa: "/fɐrˈfor/", stressText: "фарфо́р" },
        { word: "фара", ipa: "/ˈfarə/", stressText: "фа́ра" },
        { word: "шкаф", ipa: "/ʂkaf/", stressText: "шкаф" },
        { word: "фото дома", ipa: "/ˈfotə ˈdomə/", stressText: "фо́то до́ма" },
        { word: "флаг России", ipa: "/flak rɐˈsʲijɪ/", stressText: "флаг Росси́и" },
        { word: "форма готова", ipa: "/ˈformə gɐˈtovə/", stressText: "фо́рма гото́ва" },
        { word: "фраза простая", ipa: "/ˈfrazə prɐˈstajə/", stressText: "фра́за проста́я" },
      ],
      description:
        "硬 /f/ 是清唇齿擦音锚点；在 а/о/у/ы 或辅音前保持硬，不要读成英语式松散 /h/ 或软 /fʲ/。",
      notes: [
        "软 /fʲ/ 仍在 hard-soft 对比单元里训练，本单元只播放并评分硬 /f/ 短音频。",
      ],
    },
    {
      slug: "ru-v",
      ipa: "/v/",
      name: "Russian hard в",
      example: "вы",
      keywords: [
        { word: "вы", ipa: "/vɨ/", stressText: "вы" },
        { word: "вот", ipa: "/vot/", stressText: "вот" },
        { word: "ваш", ipa: "/vaʂ/", stressText: "ваш" },
        { word: "вода", ipa: "/vɐˈda/", stressText: "вода́" },
        { word: "волк", ipa: "/volk/", stressText: "волк" },
        { word: "враг", ipa: "/vrak/", stressText: "враг" },
        { word: "внук", ipa: "/vnuk/", stressText: "внук" },
        { word: "врач", ipa: "/vratɕ/", stressText: "врач" },
        { word: "восемь", ipa: "/ˈvosʲɪmʲ/", stressText: "во́семь" },
        { word: "война", ipa: "/vɐjˈna/", stressText: "война́" },
        { word: "выбор", ipa: "/ˈvɨbər/", stressText: "вы́бор" },
        { word: "высоко", ipa: "/vɨsɐˈko/", stressText: "высоко́" },
        { word: "волна", ipa: "/vɐlˈna/", stressText: "волна́" },
        { word: "вулкан", ipa: "/vʊlˈkan/", stressText: "вулка́н" },
        { word: "ваза", ipa: "/ˈvazə/", stressText: "ва́за" },
        { word: "новый", ipa: "/ˈnovɨj/", stressText: "но́вый" },
        { word: "право", ipa: "/ˈpravə/", stressText: "пра́во" },
        { word: "слово", ipa: "/ˈslovə/", stressText: "сло́во" },
        { word: "вода холодная", ipa: "/vɐˈda ˈxolədnəjə/", stressText: "вода́ хо́лодная" },
        { word: "вы были дома", ipa: "/vɨ ˈbɨlʲɪ ˈdomə/", stressText: "вы бы́ли до́ма" },
      ],
      description:
        "硬 /v/ 是浊唇齿擦音锚点；保持声带振动，同时把 /v/ 的特殊同化行为留给清浊同化规则单元。",
      notes: [
        "软 /vʲ/ 和 /v/ 在辅音丛里的清浊变化继续用 hard-soft/assimilation 单元解释。",
      ],
    },
    {
      slug: "ru-s",
      ipa: "/s/",
      name: "Russian hard с",
      example: "сад",
      keywords: [
        { word: "сад", ipa: "/sat/", stressText: "сад" },
        { word: "сам", ipa: "/sam/", stressText: "сам" },
        { word: "сон", ipa: "/son/", stressText: "сон" },
        { word: "сыр", ipa: "/sɨr/", stressText: "сыр" },
        { word: "сын", ipa: "/sɨn/", stressText: "сын" },
        { word: "суп", ipa: "/sup/", stressText: "суп" },
        { word: "стол", ipa: "/stol/", stressText: "стол" },
        { word: "спорт", ipa: "/sport/", stressText: "спорт" },
        { word: "мост", ipa: "/most/", stressText: "мост" },
        { word: "собака", ipa: "/sɐˈbakə/", stressText: "соба́ка" },
        { word: "сахар", ipa: "/ˈsaxər/", stressText: "са́хар" },
        { word: "сразу", ipa: "/ˈsrazʊ/", stressText: "сра́зу" },
        { word: "сухой", ipa: "/sʊˈxoj/", stressText: "сухо́й" },
        { word: "салат", ipa: "/sɐˈlat/", stressText: "сала́т" },
        { word: "сумка", ipa: "/ˈsumkə/", stressText: "су́мка" },
        { word: "сосна", ipa: "/sɐˈsna/", stressText: "сосна́" },
        { word: "сад пустой", ipa: "/sat pʊˈstoj/", stressText: "сад пусто́й" },
        { word: "сын дома", ipa: "/sɨn ˈdomə/", stressText: "сын до́ма" },
        { word: "стол старый", ipa: "/stol ˈstarɨj/", stressText: "стол ста́рый" },
        { word: "суп горячий", ipa: "/sup gɐˈrʲatɕɪj/", stressText: "суп горя́чий" },
      ],
      description:
        "硬 /s/ 是清舌尖擦音锚点；和软 /sʲ/ 分开，不能因为后面有 и/е 就自动套用硬音音频。",
      notes: [
        "软 /sʲ/ 继续在 с/сь 对比中训练；本单元只代表硬 /s/。",
      ],
    },
    {
      slug: "ru-z",
      ipa: "/z/",
      name: "Russian hard з",
      example: "зуб",
      keywords: [
        { word: "зал", ipa: "/zal/", stressText: "зал" },
        { word: "зуб", ipa: "/zup/", stressText: "зуб" },
        { word: "зонт", ipa: "/zont/", stressText: "зонт" },
        { word: "звук", ipa: "/zvuk/", stressText: "звук" },
        { word: "знак", ipa: "/znak/", stressText: "знак" },
        { word: "звон", ipa: "/zvon/", stressText: "звон" },
        { word: "злой", ipa: "/zloj/", stressText: "злой" },
        { word: "зона", ipa: "/ˈzonə/", stressText: "зо́на" },
        { word: "зубы", ipa: "/ˈzubɨ/", stressText: "зу́бы" },
        { word: "завод", ipa: "/zɐˈvot/", stressText: "заво́д" },
        { word: "завтра", ipa: "/ˈzaftrə/", stressText: "за́втра" },
        { word: "золото", ipa: "/ˈzolətə/", stressText: "зо́лото" },
        { word: "запах", ipa: "/ˈzapəx/", stressText: "за́пах" },
        { word: "закон", ipa: "/zɐˈkon/", stressText: "зако́н" },
        { word: "забор", ipa: "/zɐˈbor/", stressText: "забо́р" },
        { word: "язык", ipa: "/jɪˈzɨk/", stressText: "язы́к" },
        { word: "музыка", ipa: "/ˈmuzɨkə/", stressText: "му́зыка" },
        { word: "морозы", ipa: "/mɐˈrozɨ/", stressText: "моро́зы" },
        { word: "зуб болит", ipa: "/zup bɐˈlʲit/", stressText: "зуб боли́т" },
        { word: "зона рядом", ipa: "/ˈzonə ˈrʲadəm/", stressText: "зо́на ря́дом" },
      ],
      description:
        "硬 /z/ 是浊舌尖擦音锚点；词尾清化和软 /zʲ/ 都是另外的环境问题。",
      notes: [
        "孤立词尾 з 常按清化实现，本单元优先练非词尾或浊环境里的硬 /z/。",
      ],
    },
    {
      slug: "ru-m",
      ipa: "/m/",
      name: "Russian hard м",
      example: "мама",
      keywords: [
        { word: "мама", ipa: "/ˈmamə/", stressText: "ма́ма" },
        { word: "мы", ipa: "/mɨ/", stressText: "мы" },
        { word: "мост", ipa: "/most/", stressText: "мост" },
        { word: "мало", ipa: "/ˈmalə/", stressText: "ма́ло" },
        { word: "море", ipa: "/ˈmorʲe/", stressText: "мо́ре" },
        { word: "молоко", ipa: "/məlɐˈko/", stressText: "молоко́" },
        { word: "Москва", ipa: "/mɐˈskva/", stressText: "Москва́" },
        { word: "машина", ipa: "/mɐˈʂinə/", stressText: "маши́на" },
        { word: "музыка", ipa: "/ˈmuzɨkə/", stressText: "му́зыка" },
        { word: "муха", ipa: "/ˈmuxə/", stressText: "му́ха" },
        { word: "мыло", ipa: "/ˈmɨlə/", stressText: "мы́ло" },
        { word: "много", ipa: "/ˈmnogə/", stressText: "мно́го" },
        { word: "мороз", ipa: "/mɐˈros/", stressText: "моро́з" },
        { word: "сумка", ipa: "/ˈsumkə/", stressText: "су́мка" },
        { word: "рамка", ipa: "/ˈramkə/", stressText: "ра́мка" },
        { word: "том", ipa: "/tom/", stressText: "том" },
        { word: "мама дома", ipa: "/ˈmamə ˈdomə/", stressText: "ма́ма до́ма" },
        { word: "мы были", ipa: "/mɨ ˈbɨlʲɪ/", stressText: "мы бы́ли" },
        { word: "мост старый", ipa: "/most ˈstarɨj/", stressText: "мост ста́рый" },
        { word: "молоко холодное", ipa: "/məlɐˈko ˈxolədnəjə/", stressText: "молоко́ хо́лодное" },
      ],
      description:
        "硬 /m/ 是双唇鼻音锚点；在硬元音前保持硬，不要把后续软化误听成完整 /j/。",
      notes: [
        "软 /mʲ/ 仍在 hard-soft 唇音对比里训练，本单元只代表硬 /m/。",
      ],
    },
    {
      slug: "ru-n",
      ipa: "/n/",
      name: "Russian hard н",
      example: "нос",
      keywords: [
        { word: "нос", ipa: "/nos/", stressText: "нос" },
        { word: "нам", ipa: "/nam/", stressText: "нам" },
        { word: "на", ipa: "/na/", stressText: "на" },
        { word: "новый", ipa: "/ˈnovɨj/", stressText: "но́вый" },
        { word: "нога", ipa: "/nɐˈga/", stressText: "нога́" },
        { word: "номер", ipa: "/ˈnomʲɪr/", stressText: "но́мер" },
        { word: "он", ipa: "/on/", stressText: "он" },
        { word: "она", ipa: "/ɐˈna/", stressText: "она́" },
        { word: "окно", ipa: "/ɐkˈno/", stressText: "окно́" },
        { word: "сын", ipa: "/sɨn/", stressText: "сын" },
        { word: "сон", ipa: "/son/", stressText: "сон" },
        { word: "зонт", ipa: "/zont/", stressText: "зонт" },
        { word: "банк", ipa: "/bank/", stressText: "банк" },
        { word: "Анна", ipa: "/ˈannə/", stressText: "А́нна" },
        { word: "луна", ipa: "/lʊˈna/", stressText: "луна́" },
        { word: "страна", ipa: "/strɐˈna/", stressText: "страна́" },
        { word: "цена", ipa: "/tsɨˈna/", stressText: "цена́" },
        { word: "внук", ipa: "/vnuk/", stressText: "внук" },
        { word: "нос большой", ipa: "/nos bɐlʲˈʂoj/", stressText: "нос большо́й" },
        { word: "она дома", ipa: "/ɐˈna ˈdomə/", stressText: "она́ до́ма" },
      ],
      description:
        "硬 /n/ 是舌尖鼻音锚点；软 /nʲ/ 与硬 /n/ 的差别是俄语学习重点，不能混用音频。",
      notes: [
        "软 /nʲ/ 继续在 н/нь 对比里训练；本单元只播放硬 /n/。",
      ],
    },
    {
      slug: "ru-l",
      ipa: "/l/",
      name: "Russian hard л",
      example: "луна",
      keywords: [
        { word: "лук", ipa: "/luk/", stressText: "лук" },
        { word: "луна", ipa: "/lʊˈna/", stressText: "луна́" },
        { word: "лампа", ipa: "/ˈlampə/", stressText: "ла́мпа" },
        { word: "лыжи", ipa: "/ˈlɨʐɨ/", stressText: "лы́жи" },
        { word: "стол", ipa: "/stol/", stressText: "стол" },
        { word: "пол", ipa: "/pol/", stressText: "пол" },
        { word: "был", ipa: "/bɨl/", stressText: "был" },
        { word: "волк", ipa: "/volk/", stressText: "волк" },
        { word: "холод", ipa: "/ˈxolət/", stressText: "хо́лод" },
        { word: "школа", ipa: "/ˈʂkolə/", stressText: "шко́ла" },
        { word: "класс", ipa: "/klas/", stressText: "класс" },
        { word: "плохо", ipa: "/ˈploxə/", stressText: "пло́хо" },
        { word: "слово", ipa: "/ˈslovə/", stressText: "сло́во" },
        { word: "молоко", ipa: "/məlɐˈko/", stressText: "молоко́" },
        { word: "угол", ipa: "/ˈugəl/", stressText: "у́гол" },
        { word: "балкон", ipa: "/bɐlˈkon/", stressText: "балко́н" },
        { word: "зал", ipa: "/zal/", stressText: "зал" },
        { word: "золото", ipa: "/ˈzolətə/", stressText: "зо́лото" },
        { word: "луна яркая", ipa: "/lʊˈna ˈjarkəjə/", stressText: "луна́ я́ркая" },
        { word: "стол у окна", ipa: "/stol u ɐkˈna/", stressText: "стол у окна́" },
      ],
      description:
        "硬 /l/ 是俄语硬 л 锚点，舌位比软 /lʲ/ 更靠后；不要把它读成英语词尾 dark-L 的含混收尾。",
      notes: [
        "软 /lʲ/ 继续在 л/ль 对比里训练；本单元只代表硬 /l/。",
      ],
    },
    {
      slug: "ru-sh",
      ipa: "/ʂ/",
      name: "Russian hard ш",
      example: "шум",
      keywords: [
        { word: "шум", ipa: "/ʂum/", stressText: "шум" },
        { word: "шар", ipa: "/ʂar/", stressText: "шар" },
        { word: "шапка", ipa: "/ˈʂapkə/", stressText: "ша́пка" },
        { word: "школа", ipa: "/ˈʂkolə/", stressText: "шко́ла" },
        { word: "машина", ipa: "/mɐˈʂinə/", stressText: "маши́на" },
        { word: "кошка", ipa: "/ˈkoʂkə/", stressText: "ко́шка" },
        { word: "хорошо", ipa: "/xərɐˈʂo/", stressText: "хорошо́" },
        { word: "душ", ipa: "/duʂ/", stressText: "душ" },
        { word: "мышь", ipa: "/mɨʂ/", stressText: "мышь" },
        { word: "широкий", ipa: "/ʂɨˈrokʲɪj/", stressText: "широ́кий" },
        { word: "шесть", ipa: "/ʂesʲtʲ/", stressText: "шесть" },
        { word: "шоссе", ipa: "/ʂɐˈsɛ/", stressText: "шоссе́" },
        { word: "шутка", ipa: "/ˈʂutkə/", stressText: "шу́тка" },
        { word: "пишу", ipa: "/pʲɪˈʂu/", stressText: "пишу́" },
        { word: "крышка", ipa: "/ˈkrɨʂkə/", stressText: "кры́шка" },
        { word: "шёл", ipa: "/ʂol/", stressText: "шёл" },
        { word: "большой", ipa: "/bɐlʲˈʂoj/", stressText: "большо́й" },
        { word: "наша", ipa: "/ˈnaʂə/", stressText: "на́ша" },
        { word: "шум дома", ipa: "/ʂum ˈdomə/", stressText: "шум до́ма" },
        { word: "школа рядом", ipa: "/ˈʂkolə ˈrʲadəm/", stressText: "шко́ла ря́дом" },
      ],
      difficulty: "high",
      description:
        "ш 是总是偏硬的 /ʂ/，舌尖/舌叶后缩，音色比英语 /ʃ/ 更厚；不要用软 щ 或法语/英语 sh 来替代。",
      notes: [
        "ж /ʐ/ 现在有自己的 exact clip；ш/ж 对比仍保留在 contrast 单元里。",
      ],
    },
    {
      slug: "ru-zh",
      ipa: "/ʐ/",
      name: "Russian hard ж",
      example: "жук",
      keywords: [
        { word: "жук", ipa: "/ʐuk/", stressText: "жук" },
        { word: "жена", ipa: "/ʐɨˈna/", stressText: "жена́" },
        { word: "жить", ipa: "/ʐɨtʲ/", stressText: "жить" },
        { word: "журнал", ipa: "/ʐʊrˈnal/", stressText: "журна́л" },
        { word: "живот", ipa: "/ʐɨˈvot/", stressText: "живо́т" },
        { word: "жёлтый", ipa: "/ˈʐoltɨj/", stressText: "жёлтый" },
        { word: "жалко", ipa: "/ˈʐalkə/", stressText: "жа́лко" },
        { word: "ужин", ipa: "/ˈuʐɨn/", stressText: "у́жин" },
        { word: "лыжи", ipa: "/ˈlɨʐɨ/", stressText: "лы́жи" },
        { word: "пожар", ipa: "/pɐˈʐar/", stressText: "пожа́р" },
        { word: "дружба", ipa: "/ˈdruʐbə/", stressText: "дру́жба" },
        { word: "можно", ipa: "/ˈmoʐnə/", stressText: "мо́жно" },
        { word: "каждый", ipa: "/ˈkaʐdɨj/", stressText: "ка́ждый" },
        { word: "одежда", ipa: "/ɐˈdʲeʐdə/", stressText: "оде́жда" },
        { word: "лежать", ipa: "/lʲɪˈʐatʲ/", stressText: "лежа́ть" },
        { word: "вижу", ipa: "/ˈvʲiʐʊ/", stressText: "ви́жу" },
        { word: "Жора", ipa: "/ˈʐorə/", stressText: "Жо́ра" },
        { word: "жара", ipa: "/ʐɐˈra/", stressText: "жара́" },
        { word: "жук живой", ipa: "/ʐuk ʐɨˈvoj/", stressText: "жук живо́й" },
        { word: "лыжи дома", ipa: "/ˈlɨʐɨ ˈdomə/", stressText: "лы́жи до́ма" },
      ],
      difficulty: "high",
      description:
        "ж 是总是偏硬的浊 /ʐ/；保持厚而浊的摩擦，词尾或清辅音前清化是另一个规则问题。",
      notes: [
        "本单元使用独立 /ʐ/ header clip；不再借 ш /ʂ/ 或 ш/ж 组合音频冒充。",
      ],
    },
  ] satisfies RussianHardContinuantInput[]
).map((input) =>
  unit({
    languageId: "ru-RU",
    category: "consonant",
    difficulty: input.difficulty ?? "medium",
    ...input,
  }),
);

export const RUSSIAN_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "ru-RU",
    slug: "ru-a",
    ipa: "/a/",
    name: "Russian а",
    category: "vowel",
    example: "мама",
    keywords: [
      { word: "мама", ipa: "/ˈmamə/" },
      { word: "да", ipa: "/da/" },
      { word: "там", ipa: "/tam/" },
      { word: "парк", ipa: "/park/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "сахар", ipa: "/ˈsaxər/" },
    ],
    difficulty: "easy",
    description: "重读时清楚开放，非重读时会弱化；俄语元音练习必须带重音位置。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-o",
    ipa: "/o/",
    name: "Russian stressed о",
    category: "vowel",
    example: "дом",
    keywords: [
      { word: "дом", ipa: "/dom/" },
      { word: "кот", ipa: "/kot/" },
      { word: "мост", ipa: "/most/" },
      { word: "нос", ipa: "/nos/" },
      { word: "рот", ipa: "/rot/" },
      { word: "город", ipa: "/ˈgorət/" },
    ],
    difficulty: "medium",
    description:
      "重读 /o/ 圆唇清楚；非重读 о 通常弱化接近 /a/ 或 /ə/，不能只按字母读。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-i",
    ipa: "/i/",
    name: "Russian и",
    category: "vowel",
    example: "мир",
    keywords: [
      { word: "мир", ipa: "/mir/" },
      { word: "лиса", ipa: "/lʲɪˈsa/" },
      { word: "имя", ipa: "/ˈimʲə/" },
      { word: "тихо", ipa: "/ˈtʲixə/" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/" },
      { word: "пить", ipa: "/pʲitʲ/" },
    ],
    difficulty: "medium",
    description: "常让前面的辅音软化；练这个音时要同时听辅音硬软变化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-y",
    ipa: "/ɨ/",
    name: "Russian ы",
    category: "vowel",
    example: "мы",
    keywords: [
      { word: "мы", ipa: "/mɨ/" },
      { word: "сыр", ipa: "/sɨr/" },
      { word: "ты", ipa: "/tɨ/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "быстро", ipa: "/ˈbɨstrə/" },
      { word: "сын", ipa: "/sɨn/" },
    ],
    difficulty: "high",
    description: "舌身更靠后更紧，不能读成 /i/；中文学习者需要和 и 成组对比。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-u",
    ipa: "/u/",
    name: "Russian у",
    category: "vowel",
    example: "луна",
    keywords: [
      { word: "луна", ipa: "/lʊˈna/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "утро", ipa: "/ˈutrə/" },
      { word: "музыка", ipa: "/ˈmuzɨkə/" },
      { word: "суп", ipa: "/sup/" },
      { word: "друг", ipa: "/druk/" },
    ],
    difficulty: "medium",
    description: "圆唇高后元音；非重读时会弱化，但仍要保留圆唇趋势。",
  }),
  ...RUSSIAN_HARD_STOP_UNITS,
  ...RUSSIAN_HARD_CONTINUANT_UNITS,
  unit({
    languageId: "ru-RU",
    slug: "ru-hard-soft",
    ipa: "/C ~ Cʲ/",
    name: "hard vs soft consonants",
    category: "consonant",
    soundUnitType: "contrast",
    example: "брат / брать",
    keywords: [
      { word: "брат", ipa: "/brat/" },
      { word: "брать", ipa: "/bratʲ/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мэр", ipa: "/mɛr/" },
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
    ],
    difficulty: "high",
    description:
      "俄语不是一个软音，而是成体系的硬/软辅音对；软音时舌面抬向硬腭。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-r",
    ipa: "/r/",
    name: "Russian trilled r",
    category: "consonant",
    example: "река",
    keywords: [
      { word: "река", ipa: "/rʲɪˈka/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "город", ipa: "/ˈgorət/" },
      { word: "друг", ipa: "/druk/" },
      { word: "работа", ipa: "/rɐˈbotə/" },
    ],
    difficulty: "high",
    description: "舌尖颤音，且有硬 /r/ 与软 /rʲ/ 对比；不能替换成英语卷舌 r。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-x",
    ipa: "/x/",
    name: "Russian х",
    category: "consonant",
    example: "хлеб",
    keywords: [
      { word: "хлеб", ipa: "/xlʲep/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
      { word: "тихо", ipa: "/ˈtʲixə/" },
      { word: "сахар", ipa: "/ˈsaxər/" },
      { word: "мох", ipa: "/mox/" },
      { word: "холод", ipa: "/ˈxolət/" },
    ],
    difficulty: "medium",
    description: "舌后部靠近软腭摩擦，比英语 /h/ 更靠后、更有摩擦感。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-sh-zh",
    ipa: "/ʂ ʐ/",
    name: "retroflex-like ш/ж",
    category: "consonant",
    soundUnitType: "contrast",
    example: "шум / жук",
    keywords: [
      { word: "шум", ipa: "/ʂum/" },
      { word: "жук", ipa: "/ʐuk/" },
      { word: "школа", ipa: "/ˈʂkolə/" },
      { word: "жена", ipa: "/ʐɨˈna/" },
      { word: "машина", ipa: "/mɐˈʂinə/" },
      { word: "жить", ipa: "/ʐɨtʲ/" },
    ],
    difficulty: "high",
    description:
      "舌尖/舌叶后缩，音色比英语 /ʃ ʒ/ 更厚；注意 ж 后常接 /ɨ/ 音色。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ts-ch-shch",
    ipa: "/ts tɕ ɕː/",
    name: "ц/ч/щ affricate and fricative set",
    category: "consonant",
    soundUnitType: "contrast",
    example: "цирк / чай / щи",
    keywords: [
      { word: "цирк", ipa: "/tsɨrk/" },
      { word: "чай", ipa: "/tɕaj/" },
      { word: "щи", ipa: "/ɕːi/" },
      { word: "улица", ipa: "/ˈulʲɪtsə/" },
      { word: "часы", ipa: "/tɕɪˈsɨ/" },
      { word: "площадь", ipa: "/ˈploɕːətʲ/" },
    ],
    difficulty: "high",
    description: "三个音位置和软硬感不同，不能全部用中文“吃/七”近似替代。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-stress-reduction",
    ipa: "/ˈ + ə ɐ/",
    name: "stress and vowel reduction",
    category: "prosody",
    soundUnitType: "prosody",
    example: "молоко",
    keywords: [
      { word: "молоко", ipa: "/məlɐˈko/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
      { word: "город", ipa: "/ˈgorət/" },
      { word: "мама", ipa: "/ˈmamə/" },
      { word: "работа", ipa: "/rɐˈbotə/" },
      { word: "сегодня", ipa: "/sʲɪˈvodnʲə/" },
    ],
    difficulty: "high",
    description:
      "俄语重音会改变元音质量。这个是句词层训练单位，不应被当成单个音素评分。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-clusters",
    ipa: "/CC(C)/",
    name: "consonant clusters",
    category: "prosody",
    soundUnitType: "connected-speech-rule",
    example: "встреча",
    keywords: [
      { word: "встреча", ipa: "/ˈfstrʲetɕə/" },
      { word: "здравствуйте", ipa: "/ˈzdrastvʊjtʲe/" },
      { word: "текст", ipa: "/tʲekst/" },
      { word: "спорт", ipa: "/sport/" },
      { word: "взгляд", ipa: "/vzglʲat/" },
      { word: "стол", ipa: "/stol/" },
    ],
    difficulty: "high",
    description: "俄语辅音丛不能自动插入元音；先慢速保留每个辅音，再逐步加速。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-e",
    ipa: "/e/",
    name: "Russian stressed э/е",
    category: "vowel",
    example: "это",
    keywords: [
      { word: "это", ipa: "/ˈetə/", stressText: "э́то" },
      { word: "мэр", ipa: "/mɛr/" },
      { word: "эхо", ipa: "/ˈexə/", stressText: "э́хо" },
      { word: "метро", ipa: "/mʲɪˈtro/", stressText: "метро́" },
      { word: "центр", ipa: "/tsentr/" },
      { word: "текст", ipa: "/tʲekst/" },
      { word: "лес", ipa: "/lʲes/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "семь", ipa: "/sʲemʲ/" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "вечер", ipa: "/ˈvʲetɕɪr/", stressText: "ве́чер" },
      { word: "билет", ipa: "/bʲɪˈlʲet/", stressText: "биле́т" },
      { word: "экзамен", ipa: "/ɪgˈzamʲɪn/", stressText: "экза́мен" },
      { word: "этаж", ipa: "/ɪˈtaʂ/", stressText: "эта́ж" },
      { word: "энергия", ipa: "/ɪˈnʲergʲɪjə/", stressText: "эне́ргия" },
      { word: "десять", ipa: "/ˈdʲesʲɪtʲ/", stressText: "де́сять" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "это лес", ipa: "/ˈetə lʲes/" },
      { word: "вечер в метро", ipa: "/ˈvʲetɕɪr v mʲɪˈtro/" },
      { word: "текст билета", ipa: "/tʲekst bʲɪˈlʲetə/" },
    ],
    difficulty: "medium",
    description:
      "重读 /e/ 清楚；字母 е 往往同时软化前面的辅音，э 通常不软化前辅音。",
    notes: ["把 /e/ 和前面辅音是否软化一起看；мэр /mɛr/ 与 мел /mʲel/ 是好对比。"],
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-t-d",
    ipa: "/t tʲ d dʲ/",
    name: "soft т/д",
    category: "consonant",
    soundUnitType: "contrast",
    example: "ток / тётя",
    keywords: [
      { word: "ток", ipa: "/tok/" },
      { word: "тётя", ipa: "/ˈtʲotʲə/" },
      { word: "дом", ipa: "/dom/" },
      { word: "день", ipa: "/dʲenʲ/" },
      { word: "там", ipa: "/tam/" },
      { word: "тень", ipa: "/tʲenʲ/" },
      { word: "да", ipa: "/da/" },
      { word: "дядя", ipa: "/ˈdʲadʲə/", stressText: "дя́дя" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "идти", ipa: "/ɪtˈtʲi/", stressText: "идти́" },
      { word: "тетрадь", ipa: "/tʲɪˈtratʲ/", stressText: "тетра́дь" },
      { word: "дети", ipa: "/ˈdʲetʲɪ/", stressText: "де́ти" },
      { word: "театр", ipa: "/tʲɪˈatr/", stressText: "теа́тр" },
      { word: "долго", ipa: "/ˈdolgə/", stressText: "до́лго" },
      { word: "труд", ipa: "/trut/" },
      { word: "друг", ipa: "/druk/" },
      { word: "ток и тень", stressText: "то́к и те́нь", ipa: "/ˈtok i ˈtʲenʲ/" },
      { word: "дом и день", stressText: "до́м и де́нь", ipa: "/ˈdom i ˈdʲenʲ/" },
      { word: "тётя дома", ipa: "/ˈtʲotʲə ˈdomə/" },
      { word: "дети идут", ipa: "/ˈdʲetʲɪ ɪˈdut/" },
    ],
    difficulty: "high",
    description:
      "软化是辅音本身舌面抬高，不是在硬辅音后面加一个完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-t-tj",
    ipa: "/t tʲ/",
    name: "hard-soft т / ть",
    category: "consonant",
    soundUnitType: "contrast",
    example: "там / тень",
    keywords: [
      { word: "там", ipa: "/tam/" },
      { word: "тень", ipa: "/tʲenʲ/" },
      { word: "ток", ipa: "/tok/" },
      { word: "тётя", ipa: "/ˈtʲotʲə/" },
      { word: "ты", ipa: "/tɨ/" },
      { word: "тихо", stressText: "ти́хо", ipa: "/ˈtʲixə/" },
      { word: "театр", stressText: "теа́тр", ipa: "/tʲɪˈatr/" },
      { word: "тетрадь", stressText: "тетра́дь", ipa: "/tʲɪˈtratʲ/" },
      { word: "телефон", stressText: "телефо́н", ipa: "/tʲɪlʲɪˈfon/" },
      { word: "текст", ipa: "/tʲekst/" },
      { word: "транспорт", stressText: "тра́нспорт", ipa: "/ˈtransport/" },
      { word: "трава", stressText: "трава́", ipa: "/trɐˈva/" },
      { word: "стол", ipa: "/stol/" },
      { word: "студент", stressText: "студе́нт", ipa: "/stʊˈdʲent/" },
      { word: "труд", ipa: "/trut/" },
      { word: "товарищ", stressText: "това́рищ", ipa: "/tɐˈvarʲɪɕː/" },
      { word: "ток и тень", stressText: "то́к и те́нь", ipa: "/ˈtok i ˈtʲenʲ/" },
      { word: "там и тихо", stressText: "там и ти́хо", ipa: "/tam i ˈtʲixə/" },
      { word: "ты и тётя", ipa: "/tɨ i ˈtʲotʲə/" },
      { word: "театр и транспорт", stressText: "теа́тр и тра́нспорт", ipa: "/tʲɪˈatr i ˈtransport/" },
      { word: "тихий текст", stressText: "ти́хий текст", ipa: "/ˈtʲixʲɪj tʲekst/" },
      { word: "тетрадь на столе", stressText: "тетра́дь на столе́", ipa: "/tʲɪˈtratʲ nɐ stɐˈlʲe/" },
      { word: "студент читает", stressText: "студе́нт чита́ет", ipa: "/stʊˈdʲent tɕɪˈtajɪt/" },
      { word: "транспорт стоит", stressText: "тра́нспорт стои́т", ipa: "/ˈtransport stɐˈit/" },
    ],
    difficulty: "medium",
    description:
      "硬 /t/ 和软 /tʲ/ 的差别是舌面抬向硬腭；不要把软 ть 读成硬 /t/ 后面再加完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-d-dj",
    ipa: "/d dʲ/",
    name: "hard-soft д / дь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "дом / день",
    keywords: [
      { word: "да", ipa: "/da/" },
      { word: "день", ipa: "/dʲenʲ/" },
      { word: "дом", ipa: "/dom/" },
      { word: "дядя", stressText: "дя́дя", ipa: "/ˈdʲadʲə/" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "дети", stressText: "де́ти", ipa: "/ˈdʲetʲɪ/" },
      { word: "долго", stressText: "до́лго", ipa: "/ˈdolgə/" },
      { word: "друг", ipa: "/druk/" },
      { word: "дорога", stressText: "доро́га", ipa: "/dɐˈrogə/" },
      { word: "директор", stressText: "дире́ктор", ipa: "/dʲɪˈrʲektər/" },
      { word: "дуб", ipa: "/dup/" },
      { word: "дуба", stressText: "дуба́", ipa: "/duˈba/" },
      { word: "два", ipa: "/dva/" },
      { word: "двадцать", stressText: "два́дцать", ipa: "/ˈdvatsətʲ/" },
      { word: "девушка", stressText: "де́вушка", ipa: "/ˈdʲevʊʂkə/" },
      { word: "делать", stressText: "де́лать", ipa: "/ˈdʲelətʲ/" },
      { word: "дом и день", stressText: "до́м и де́нь", ipa: "/ˈdom i ˈdʲenʲ/" },
      { word: "да и дядя", stressText: "да и дя́дя", ipa: "/da i ˈdʲadʲə/" },
      { word: "друг дома", stressText: "друг до́ма", ipa: "/drug ˈdomə/" },
      { word: "дети идут", stressText: "де́ти иду́т", ipa: "/ˈdʲetʲɪ ɪˈdut/" },
      { word: "дверь дома", stressText: "дверь до́ма", ipa: "/dvʲerʲ ˈdomə/" },
      { word: "директор дома", stressText: "дире́ктор до́ма", ipa: "/dʲɪˈrʲektər ˈdomə/" },
      { word: "дорога далеко", stressText: "доро́га далеко́", ipa: "/dɐˈrogə dəlʲɪˈko/" },
      { word: "двадцать дней", stressText: "два́дцать дней", ipa: "/ˈdvatsətʲ dʲenʲ/" },
    ],
    difficulty: "medium",
    description:
      "硬 /d/ 和软 /dʲ/ 都是浊塞音；训练时要保留浊音，同时让软 дь 带出前腭化过渡。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-s-z",
    ipa: "/s sʲ z zʲ/",
    name: "soft с/з",
    category: "consonant",
    soundUnitType: "contrast",
    example: "сад / сядь",
    keywords: [
      { word: "сад", ipa: "/sat/" },
      { word: "сядь", ipa: "/sʲatʲ/" },
      { word: "зуб", ipa: "/zup/" },
      { word: "зима", ipa: "/zʲɪˈma/", stressText: "зима́" },
      { word: "сок", ipa: "/sok/" },
      { word: "сено", ipa: "/ˈsʲenə/", stressText: "се́но" },
      { word: "сын", ipa: "/sɨn/" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/", stressText: "си́ний" },
      { word: "звук", ipa: "/zvuk/" },
      { word: "земля", ipa: "/zʲɪˈmlʲa/", stressText: "земля́" },
      { word: "вес", ipa: "/vʲes/" },
      { word: "весь", ipa: "/vʲesʲ/" },
      { word: "сестра", ipa: "/sʲɪˈstra/", stressText: "сестра́" },
      { word: "сказать", ipa: "/skɐˈzatʲ/", stressText: "сказа́ть" },
      { word: "здесь", ipa: "/zdʲesʲ/" },
      { word: "музей", ipa: "/mʊˈzʲej/", stressText: "музе́й" },
      { word: "сад и сено", ipa: "/sat i ˈsʲenə/" },
      { word: "зуб и зима", ipa: "/zup i zʲɪˈma/" },
      { word: "сын синий", ipa: "/sɨn ˈsʲinʲɪj/" },
      { word: "здесь музей", ipa: "/zdʲesʲ mʊˈzʲej/" },
    ],
    difficulty: "high",
    description:
      "软 с/з 的摩擦位置更靠前、更细；硬 с/з 不要被后面的元音自动软化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-n-l-r",
    ipa: "/n nʲ l lʲ r rʲ/",
    name: "soft н/л/р",
    category: "consonant",
    soundUnitType: "contrast",
    example: "лук / люк",
    keywords: [
      { word: "нос", ipa: "/nos/" },
      { word: "нёс", ipa: "/nʲos/" },
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
      { word: "рад", ipa: "/rat/" },
      { word: "ряд", ipa: "/rʲat/" },
      { word: "кон", ipa: "/kon/" },
      { word: "конь", ipa: "/konʲ/" },
      { word: "угол", ipa: "/ˈugəl/", stressText: "у́гол" },
      { word: "уголь", ipa: "/ˈugəlʲ/", stressText: "у́голь" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мель", ipa: "/mʲelʲ/" },
      { word: "река", ipa: "/rʲɪˈka/", stressText: "река́" },
      { word: "рука", ipa: "/rʊˈka/", stressText: "рука́" },
      { word: "сибирь", ipa: "/sʲɪˈbirʲ/", stressText: "Сиби́рь" },
      { word: "линия", ipa: "/ˈlʲinʲɪjə/", stressText: "ли́ния" },
      { word: "нос и нёс", ipa: "/nos i nʲos/" },
      { word: "лук и люк", ipa: "/luk i lʲuk/" },
      { word: "рад и ряд", ipa: "/rat i rʲat/" },
      { word: "угол и уголь", ipa: "/ˈugəl i ˈugəlʲ/" },
    ],
    difficulty: "high",
    description:
      "н/л/р 的硬软对立很高频；软音时舌面抬起，不能只靠后面加 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-s-sj",
    ipa: "/s sʲ/",
    name: "hard-soft с / сь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "сын / синий",
    keywords: [
      { word: "сын", ipa: "/sɨn/" },
      { word: "синий", stressText: "си́ний", ipa: "/ˈsʲinʲɪj/" },
      { word: "сад", ipa: "/sat/" },
      { word: "сено", stressText: "се́но", ipa: "/ˈsʲenə/" },
      { word: "сок", ipa: "/sok/" },
      { word: "семь", ipa: "/sʲemʲ/" },
      { word: "суп", ipa: "/sup/" },
      { word: "село", stressText: "село́", ipa: "/sʲɪˈlo/" },
      { word: "сон", ipa: "/son/" },
      { word: "сеть", ipa: "/sʲetʲ/" },
      { word: "сахар", stressText: "са́хар", ipa: "/ˈsaxər/" },
      { word: "сила", stressText: "си́ла", ipa: "/ˈsʲilə/" },
      { word: "собака", stressText: "соба́ка", ipa: "/sɐˈbakə/" },
      { word: "сестра", stressText: "сестра́", ipa: "/sʲɪˈstra/" },
      { word: "сумка", stressText: "су́мка", ipa: "/ˈsumkə/" },
      { word: "сегодня", stressText: "сего́дня", ipa: "/sʲɪˈvodnʲə/" },
      { word: "сын и синий", stressText: "сын и си́ний", ipa: "/sɨn i ˈsʲinʲɪj/" },
      { word: "сад и сено", stressText: "сад и се́но", ipa: "/sat i ˈsʲenə/" },
      { word: "сон и семь", stressText: "со́н и се́мь", ipa: "/ˈson i ˈsʲemʲ/" },
      { word: "сок и сеть", stressText: "со́к и се́ть", ipa: "/ˈsok i ˈsʲetʲ/" },
      { word: "сахар и сила", stressText: "са́хар и си́ла", ipa: "/ˈsaxər i ˈsʲilə/" },
      { word: "собака сегодня", stressText: "соба́ка сего́дня", ipa: "/sɐˈbakə sʲɪˈvodnʲə/" },
      { word: "сестра с сумкой", stressText: "сестра́ с су́мкой", ipa: "/sʲɪˈstra s ˈsumkəj/" },
      { word: "синий сад", stressText: "си́ний сад", ipa: "/ˈsʲinʲɪj sat/" },
    ],
    difficulty: "medium",
    description:
      "硬 /s/ 和软 /sʲ/ 的差别在摩擦位置和舌面抬起；软 сь/си/се 不能读成硬 /s/ 后加完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-z-zj",
    ipa: "/z zʲ/",
    name: "hard-soft з / зь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "зуб / зима",
    keywords: [
      { word: "зуб", ipa: "/zup/" },
      { word: "зима", stressText: "зима́", ipa: "/zʲɪˈma/" },
      { word: "зал", ipa: "/zal/" },
      { word: "земля", stressText: "земля́", ipa: "/zʲɪˈmlʲa/" },
      { word: "звук", ipa: "/zvuk/" },
      { word: "здесь", ipa: "/zdʲesʲ/" },
      { word: "зона", stressText: "зо́на", ipa: "/ˈzonə/" },
      { word: "зеркало", stressText: "зе́ркало", ipa: "/ˈzʲerkələ/" },
      { word: "завтра", stressText: "за́втра", ipa: "/ˈzaftrə/" },
      { word: "зелёный", stressText: "зелёный", ipa: "/zʲɪˈlʲonɨj/" },
      { word: "закон", stressText: "зако́н", ipa: "/zɐˈkon/" },
      { word: "зеркало и зал", stressText: "зе́ркало и зал", ipa: "/ˈzʲerkələ i zal/" },
      { word: "зуб и зима", stressText: "зуб и зима́", ipa: "/zup i zʲɪˈma/" },
      { word: "зал и земля", stressText: "зал и земля́", ipa: "/zal i zʲɪˈmlʲa/" },
      { word: "звук и здесь", stressText: "звук и здесь", ipa: "/ˈzvuk i ˈzdʲesʲ/" },
      { word: "зона и зеркало", stressText: "зо́на и зе́ркало", ipa: "/ˈzonə i ˈzʲerkələ/" },
      { word: "завтра зима", stressText: "за́втра зима́", ipa: "/ˈzaftrə zʲɪˈma/" },
      { word: "зелёная земля", stressText: "зелёная земля́", ipa: "/zʲɪˈlʲonəjə zʲɪˈmlʲa/" },
      { word: "закон здесь", stressText: "зако́н здесь", ipa: "/zɐˈkon zdʲesʲ/" },
      { word: "звук зимой", stressText: "звук зимо́й", ipa: "/zvuk zʲɪˈmoj/" },
    ],
    difficulty: "medium",
    description:
      "硬 /z/ 和软 /zʲ/ 都要保持浊擦音质量；软 зь/зи/зе 的软化不是额外插入一个 й。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-n-nj",
    ipa: "/n nʲ/",
    name: "hard-soft н / нь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "нос / нёс",
    keywords: [
      { word: "нос", ipa: "/nos/" },
      { word: "нёс", ipa: "/nʲos/" },
      { word: "на", ipa: "/na/" },
      { word: "нет", ipa: "/nʲet/" },
      { word: "новый", stressText: "но́вый", ipa: "/ˈnovɨj/" },
      { word: "небо", stressText: "не́бо", ipa: "/ˈnʲebə/" },
      { word: "нога", stressText: "нога́", ipa: "/nɐˈga/" },
      { word: "неделя", stressText: "неде́ля", ipa: "/nʲɪˈdʲelʲə/" },
      { word: "ночь", ipa: "/notɕ/" },
      { word: "няня", stressText: "ня́ня", ipa: "/ˈnʲanʲə/" },
      { word: "номер", stressText: "но́мер", ipa: "/ˈnomʲɪr/" },
      { word: "нитка", stressText: "ни́тка", ipa: "/ˈnʲitkə/" },
      { word: "кон", ipa: "/kon/" },
      { word: "конь", ipa: "/konʲ/" },
      { word: "нос и нёс", stressText: "но́с и нёс", ipa: "/ˈnos i ˈnʲos/" },
      { word: "на и нет", stressText: "на и нет", ipa: "/ˈna i ˈnʲet/" },
      { word: "новый и небо", stressText: "но́вый и не́бо", ipa: "/ˈnovɨj i ˈnʲebə/" },
      { word: "нога и неделя", stressText: "нога́ и неде́ля", ipa: "/nɐˈga i nʲɪˈdʲelʲə/" },
      { word: "ночь и няня", stressText: "ночь и ня́ня", ipa: "/notɕ i ˈnʲanʲə/" },
      { word: "номер и нитка", stressText: "но́мер и ни́тка", ipa: "/ˈnomʲɪr i ˈnʲitkə/" },
      { word: "кон и конь", stressText: "кон и ко́нь", ipa: "/ˈkon i ˈkonʲ/" },
      { word: "новый номер", stressText: "но́вый но́мер", ipa: "/ˈnovɨj ˈnomʲɪr/" },
      { word: "нет на неделе", stressText: "нет на неде́ле", ipa: "/nʲet nɐ nʲɪˈdʲelʲe/" },
      { word: "няня несёт", stressText: "ня́ня несёт", ipa: "/ˈnʲanʲə nʲɪˈsʲot/" },
    ],
    difficulty: "medium",
    description:
      "硬 /n/ 和软 /nʲ/ 的鼻音位置不同；软 нь/ни/не 要让舌面抬起，而不是在 /n/ 后补一个完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-l-lj",
    ipa: "/l lʲ/",
    name: "hard-soft л / ль",
    category: "consonant",
    soundUnitType: "contrast",
    example: "лук / люк",
    keywords: [
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
      { word: "лак", ipa: "/lak/" },
      { word: "лес", ipa: "/lʲes/" },
      { word: "луна", stressText: "луна́", ipa: "/lʊˈna/" },
      { word: "линия", stressText: "ли́ния", ipa: "/ˈlʲinʲɪjə/" },
      { word: "лампа", stressText: "ла́мпа", ipa: "/ˈlampə/" },
      { word: "любовь", stressText: "любо́вь", ipa: "/lʲʊˈbofʲ/" },
      { word: "стол", ipa: "/stol/" },
      { word: "соль", ipa: "/solʲ/" },
      { word: "ложка", stressText: "ло́жка", ipa: "/ˈloʂkə/" },
      { word: "лиса", stressText: "лиса́", ipa: "/lʲɪˈsa/" },
      { word: "молоко", stressText: "молоко́", ipa: "/məlɐˈko/" },
      { word: "лёд", ipa: "/lʲot/" },
      { word: "лук и люк", stressText: "лу́к и лю́к", ipa: "/ˈluk i ˈlʲuk/" },
      { word: "лак и лес", stressText: "лак и лес", ipa: "/ˈlak i ˈlʲes/" },
      { word: "луна и линия", stressText: "луна́ и ли́ния", ipa: "/lʊˈna i ˈlʲinʲɪjə/" },
      { word: "лампа и любовь", stressText: "ла́мпа и любо́вь", ipa: "/ˈlampə i lʲʊˈbofʲ/" },
      { word: "стол и соль", stressText: "стол и соль", ipa: "/ˈstol i ˈsolʲ/" },
      { word: "ложка и лиса", stressText: "ло́жка и лиса́", ipa: "/ˈloʂkə i lʲɪˈsa/" },
      { word: "молоко и лёд", stressText: "молоко́ и лёд", ipa: "/məlɐˈko i lʲot/" },
      { word: "луна светит", stressText: "луна́ све́тит", ipa: "/lʊˈna ˈsʲvetʲɪt/" },
      { word: "линия длинная", stressText: "ли́ния дли́нная", ipa: "/ˈlʲinʲɪjə ˈdlʲinːəjə/" },
      { word: "любовь к лесу", stressText: "любо́вь к ле́су", ipa: "/lʲʊˈbofʲ k ˈlʲesʊ/" },
    ],
    difficulty: "high",
    description:
      "硬 /l/ 和软 /lʲ/ 是俄语学习的核心对立；软 ль/ли/ле 要前腭化，不能读成英语式 dark L。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-r-rj",
    ipa: "/r rʲ/",
    name: "hard-soft р / рь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "рад / ряд",
    keywords: [
      { word: "рад", ipa: "/rat/" },
      { word: "ряд", ipa: "/rʲat/" },
      { word: "рот", ipa: "/rot/" },
      { word: "река", stressText: "река́", ipa: "/rʲɪˈka/" },
      { word: "рука", stressText: "рука́", ipa: "/rʊˈka/" },
      { word: "рис", ipa: "/rʲis/" },
      { word: "рыба", stressText: "ры́ба", ipa: "/ˈrɨbə/" },
      { word: "ритм", ipa: "/rʲitm/" },
      { word: "рынок", stressText: "ры́нок", ipa: "/ˈrɨnək/" },
      { word: "ребёнок", stressText: "ребёнок", ipa: "/rʲɪˈbʲonək/" },
      { word: "рано", stressText: "ра́но", ipa: "/ˈranə/" },
      { word: "рядом", stressText: "ря́дом", ipa: "/ˈrʲadəm/" },
      { word: "красный", stressText: "кра́сный", ipa: "/ˈkrasnɨj/" },
      { word: "время", stressText: "вре́мя", ipa: "/ˈvrʲemʲə/" },
      { word: "рад и ряд", stressText: "рад и ряд", ipa: "/ˈrat i ˈrʲat/" },
      { word: "рот и река", stressText: "рот и река́", ipa: "/rot i rʲɪˈka/" },
      { word: "рука и рис", stressText: "рука́ и рис", ipa: "/rʊˈka i rʲis/" },
      { word: "рыба и ритм", stressText: "ры́ба и ритм", ipa: "/ˈrɨbə i rʲitm/" },
      { word: "рынок и ребёнок", stressText: "ры́нок и ребёнок", ipa: "/ˈrɨnək i rʲɪˈbʲonək/" },
      { word: "рано рядом", stressText: "ра́но ря́дом", ipa: "/ˈranə ˈrʲadəm/" },
      { word: "красное время", stressText: "кра́сное вре́мя", ipa: "/ˈkrasnəjə ˈvrʲemʲə/" },
      { word: "рядом река", stressText: "ря́дом река́", ipa: "/ˈrʲadəm rʲɪˈka/" },
      { word: "рад ребёнку", stressText: "рад ребёнку", ipa: "/rat rʲɪˈbʲonkʊ/" },
      { word: "рыба рядом", stressText: "ры́ба ря́дом", ipa: "/ˈrɨbə ˈrʲadəm/" },
    ],
    difficulty: "high",
    description:
      "硬 /r/ 和软 /rʲ/ 都保持俄语颤音/闪颤性质；软 рь/ри/ре 需要前腭化，不能退回英语 r。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-labials",
    ipa: "/pʲ bʲ mʲ fʲ vʲ/",
    name: "soft labials",
    category: "consonant",
    soundUnitType: "contrast",
    example: "пять",
    keywords: [
      { word: "пять", ipa: "/pʲatʲ/" },
      { word: "билет", ipa: "/bʲɪˈlʲet/", stressText: "биле́т" },
      { word: "мир", ipa: "/mir/" },
      { word: "фильм", ipa: "/fʲilʲm/" },
      { word: "вес", ipa: "/vʲes/" },
      { word: "весь", ipa: "/vʲesʲ/" },
      { word: "пить", ipa: "/pʲitʲ/" },
      { word: "белый", ipa: "/ˈbʲelɨj/", stressText: "бе́лый" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мель", ipa: "/mʲelʲ/" },
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "любовь", ipa: "/lʲʊˈbofʲ/", stressText: "любо́вь" },
      { word: "время", ipa: "/ˈvrʲemʲə/", stressText: "вре́мя" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "письмо", ipa: "/pʲɪsʲˈmo/", stressText: "письмо́" },
      { word: "автобус", ipa: "/ɐfˈtobʊs/", stressText: "авто́бус" },
      { word: "пять билетов", ipa: "/pʲatʲ bʲɪˈlʲetəf/" },
      { word: "мир и фильм", ipa: "/mir i fʲilʲm/" },
      { word: "вес весь", ipa: "/vʲes vʲesʲ/" },
      { word: "семья любит", ipa: "/sʲɪmʲˈja ˈlʲubʲɪt/" },
    ],
    difficulty: "high",
    description:
      "双唇/唇齿辅音也会软化；嘴唇动作不变，但舌面同时抬向硬腭。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-p-pj",
    ipa: "/p pʲ/",
    name: "hard-soft п / пь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "пыл / пить",
    keywords: [
      { word: "пыл", ipa: "/pɨl/" },
      { word: "пить", ipa: "/pʲitʲ/" },
      { word: "парк", ipa: "/park/" },
      { word: "пять", ipa: "/pʲatʲ/" },
      { word: "пол", ipa: "/pol/" },
      { word: "пёс", ipa: "/pʲos/" },
      { word: "пара", stressText: "па́ра", ipa: "/ˈparə/" },
      { word: "песня", stressText: "пе́сня", ipa: "/ˈpʲesʲnʲə/" },
      { word: "папа", stressText: "па́па", ipa: "/ˈpapə/" },
      { word: "письмо", stressText: "письмо́", ipa: "/pʲɪsʲˈmo/" },
      { word: "плащ", ipa: "/plaɕː/" },
      { word: "пир", ipa: "/pʲir/" },
      { word: "порог", stressText: "поро́г", ipa: "/pɐˈrok/" },
      { word: "перец", stressText: "пе́рец", ipa: "/ˈpʲerʲɪts/" },
      { word: "путешествие", stressText: "путеше́ствие", ipa: "/pʊtʲɪˈʂestvʲɪjə/" },
      { word: "певец", stressText: "певе́ц", ipa: "/pʲɪˈvʲets/" },
      { word: "пыл и пить", stressText: "пыл и пить", ipa: "/ˈpɨl i ˈpʲitʲ/" },
      { word: "парк и пять", stressText: "парк и пять", ipa: "/ˈpark i ˈpʲatʲ/" },
      { word: "пол и пёс", stressText: "пол и пёс", ipa: "/ˈpol i ˈpʲos/" },
      { word: "пара и песня", stressText: "па́ра и пе́сня", ipa: "/ˈparə i ˈpʲesʲnʲə/" },
      { word: "папа пишет", stressText: "па́па пи́шет", ipa: "/ˈpapə ˈpʲiʂɨt/" },
      { word: "письмо пришло", stressText: "письмо́ пришло́", ipa: "/pʲɪsʲˈmo prʲɪˈʂlo/" },
      { word: "пять песен", stressText: "пять пе́сен", ipa: "/pʲatʲ ˈpʲesʲɪn/" },
      { word: "парк перед домом", stressText: "парк пе́ред до́мом", ipa: "/park ˈpʲerʲɪt ˈdoməm/" },
    ],
    difficulty: "medium",
    description:
      "硬 /p/ 和软 /pʲ/ 的差别在舌面是否同时抬向硬腭，不是英语式送气对立。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-b-bj",
    ipa: "/b bʲ/",
    name: "hard-soft б / бь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "был / бил",
    keywords: [
      { word: "был", ipa: "/bɨl/" },
      { word: "бил", ipa: "/bʲil/" },
      { word: "бок", ipa: "/bok/" },
      { word: "белый", stressText: "бе́лый", ipa: "/ˈbʲelɨj/" },
      { word: "брат", ipa: "/brat/" },
      { word: "брать", ipa: "/bratʲ/" },
      { word: "быт", ipa: "/bɨt/" },
      { word: "бить", ipa: "/bʲitʲ/" },
      { word: "банк", ipa: "/bank/" },
      { word: "билет", stressText: "биле́т", ipa: "/bʲɪˈlʲet/" },
      { word: "буду", stressText: "бу́ду", ipa: "/ˈbudu/" },
      { word: "беда", stressText: "беда́", ipa: "/bʲɪˈda/" },
      { word: "бор", ipa: "/bor/" },
      { word: "берёза", stressText: "берёза", ipa: "/bʲɪˈrʲozə/" },
      { word: "Борис", stressText: "Бори́с", ipa: "/bɐˈrʲis/" },
      { word: "беречь", stressText: "бере́чь", ipa: "/bʲɪˈrʲetɕ/" },
      { word: "большой", stressText: "большо́й", ipa: "/bɐlʲˈʂoj/" },
      { word: "был и бил", stressText: "был и бил", ipa: "/ˈbɨl i ˈbʲil/" },
      { word: "брат и брать", stressText: "брат и брать", ipa: "/ˈbrat i ˈbratʲ/" },
      { word: "бок и белый", stressText: "бок и бе́лый", ipa: "/bok i ˈbʲelɨj/" },
      { word: "банк и билет", stressText: "банк и биле́т", ipa: "/bank i bʲɪˈlʲet/" },
      { word: "белый билет", stressText: "бе́лый биле́т", ipa: "/ˈbʲelɨj bʲɪˈlʲet/" },
      { word: "брат берёт", stressText: "брат берёт", ipa: "/brat bʲɪˈrʲot/" },
      { word: "банк большой", stressText: "банк большо́й", ipa: "/bank bɐlʲˈʂoj/" },
    ],
    difficulty: "medium",
    description:
      "硬 /b/ 与软 /bʲ/ 都是双唇浊塞音；训练重点是软音的前腭化过渡。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-m-mj",
    ipa: "/m mʲ/",
    name: "hard-soft м / мь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "мэр / мел",
    keywords: [
      { word: "мэр", ipa: "/mɛr/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мать", ipa: "/matʲ/" },
      { word: "мять", ipa: "/mʲatʲ/" },
      { word: "мой", ipa: "/moj/" },
      { word: "мир", ipa: "/mʲir/" },
      { word: "мыл", ipa: "/mɨl/" },
      { word: "мил", ipa: "/mʲil/" },
      { word: "мак", ipa: "/mak/" },
      { word: "мяч", ipa: "/mʲatɕ/" },
      { word: "мама", stressText: "ма́ма", ipa: "/ˈmamə/" },
      { word: "место", stressText: "ме́сто", ipa: "/ˈmʲestə/" },
      { word: "март", ipa: "/mart/" },
      { word: "метр", ipa: "/mʲetr/" },
      { word: "молоко", stressText: "молоко́", ipa: "/məlɐˈko/" },
      { word: "минута", stressText: "мину́та", ipa: "/mʲɪˈnutə/" },
      { word: "мэр и мел", stressText: "мэр и мел", ipa: "/ˈmɛr i ˈmʲel/" },
      { word: "мать и мять", stressText: "мать и мять", ipa: "/ˈmatʲ i ˈmʲatʲ/" },
      { word: "мой мир", stressText: "мой мир", ipa: "/ˈmoj ˈmʲir/" },
      { word: "мак и мяч", stressText: "мак и мяч", ipa: "/ˈmak i ˈmʲatɕ/" },
      { word: "мама мыла", stressText: "ма́ма мы́ла", ipa: "/ˈmamə ˈmɨlə/" },
      { word: "место на карте", stressText: "ме́сто на ка́рте", ipa: "/ˈmʲestə nɐ ˈkartʲe/" },
      { word: "минута молчания", stressText: "мину́та молча́ния", ipa: "/mʲɪˈnutə mɐlˈtɕanʲɪjə/" },
      { word: "мел между книгами", stressText: "мел ме́жду кни́гами", ipa: "/mʲel ˈmʲeʐdʊ ˈknʲigəmʲɪ/" },
    ],
    difficulty: "medium",
    description:
      "硬 /m/ 与软 /mʲ/ 都是双唇鼻音，不能简单套用英语 /m/；软音要带舌面抬起。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-f-fj",
    ipa: "/f fʲ/",
    name: "hard-soft ф / фь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "факт / фильм",
    keywords: [
      { word: "факт", ipa: "/fakt/" },
      { word: "фильм", ipa: "/fʲilʲm/" },
      { word: "фаза", stressText: "фа́за", ipa: "/ˈfazə/" },
      { word: "финал", stressText: "фина́л", ipa: "/fʲɪˈnal/" },
      { word: "форма", stressText: "фо́рма", ipa: "/ˈformə/" },
      { word: "фирма", stressText: "фи́рма", ipa: "/ˈfʲirmə/" },
      { word: "фон", ipa: "/fon/" },
      { word: "февраль", stressText: "февра́ль", ipa: "/fʲɪˈvralʲ/" },
      { word: "фокус", stressText: "фо́кус", ipa: "/ˈfokʊs/" },
      { word: "физика", stressText: "фи́зика", ipa: "/ˈfʲizʲɪkə/" },
      { word: "футбол", stressText: "футбо́л", ipa: "/fʊdˈbol/" },
      { word: "ферма", stressText: "фе́рма", ipa: "/ˈfʲermə/" },
      { word: "шкаф", ipa: "/ʂkaf/" },
      { word: "эфир", stressText: "эфи́р", ipa: "/ɪˈfʲir/" },
      { word: "факт и фильм", stressText: "факт и фильм", ipa: "/ˈfakt i ˈfʲilʲm/" },
      { word: "форма и фирма", stressText: "фо́рма и фи́рма", ipa: "/ˈformə i ˈfʲirmə/" },
      { word: "фон и ферма", stressText: "фон и фе́рма", ipa: "/fon i ˈfʲermə/" },
      { word: "фаза и физика", stressText: "фа́за и фи́зика", ipa: "/ˈfazə i ˈfʲizʲɪkə/" },
      { word: "новый факт", stressText: "но́вый факт", ipa: "/ˈnovɨj fakt/" },
      { word: "хороший фильм", stressText: "хоро́ший фильм", ipa: "/xɐˈroʂɨj fʲilʲm/" },
      { word: "футбол в феврале", stressText: "футбо́л в феврале́", ipa: "/fʊdˈbol v fʲɪvraˈlʲe/" },
      { word: "фокус фильма", stressText: "фо́кус фи́льма", ipa: "/ˈfokʊs ˈfʲilʲmə/" },
      { word: "ферма рядом", stressText: "фе́рма ря́дом", ipa: "/ˈfʲermə ˈrʲadəm/" },
      { word: "шкаф фирмы", stressText: "шкаф фи́рмы", ipa: "/ʂkaf ˈfʲirmɨ/" },
    ],
    difficulty: "medium",
    description:
      "硬 /f/ 与软 /fʲ/ 多见于借词和国际词，但仍需要按俄语硬软系统训练。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-v-vj",
    ipa: "/v vʲ/",
    name: "hard-soft в / вь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "вот / вес",
    keywords: [
      { word: "вот", ipa: "/vot/" },
      { word: "вес", ipa: "/vʲes/" },
      { word: "вал", ipa: "/val/" },
      { word: "вёл", ipa: "/vʲol/" },
      { word: "вы", ipa: "/vɨ/" },
      { word: "вид", ipa: "/vʲit/" },
      { word: "вода", stressText: "вода́", ipa: "/vɐˈda/" },
      { word: "вечер", stressText: "ве́чер", ipa: "/ˈvʲetɕɪr/" },
      { word: "ваш", ipa: "/vaʂ/" },
      { word: "весь", ipa: "/vʲesʲ/" },
      { word: "война", stressText: "война́", ipa: "/vɐjˈna/" },
      { word: "весна", stressText: "весна́", ipa: "/vʲɪsˈna/" },
      { word: "ваза", stressText: "ва́за", ipa: "/ˈvazə/" },
      { word: "ветер", stressText: "ве́тер", ipa: "/ˈvʲetʲɪr/" },
      { word: "время", stressText: "вре́мя", ipa: "/ˈvrʲemʲə/" },
      { word: "вино", stressText: "вино́", ipa: "/vʲɪˈno/" },
      { word: "вот и вес", stressText: "вот и вес", ipa: "/ˈvot i ˈvʲes/" },
      { word: "вал и вёл", stressText: "вал и вёл", ipa: "/ˈval i ˈvʲol/" },
      { word: "вы и вид", stressText: "вы и вид", ipa: "/ˈvɨ i ˈvʲit/" },
      { word: "вода и вечер", stressText: "вода́ и ве́чер", ipa: "/vɐˈda i ˈvʲetɕɪr/" },
      { word: "ваш и весь", stressText: "ваш и весь", ipa: "/ˈvaʂ i ˈvʲesʲ/" },
      { word: "весна в городе", stressText: "весна́ в го́роде", ipa: "/vʲɪsˈna v ˈgorədʲe/" },
      { word: "ветер во дворе", stressText: "ве́тер во дворе́", ipa: "/ˈvʲetʲɪr vɐ dvɐˈrʲe/" },
      { word: "вино вечером", stressText: "вино́ ве́чером", ipa: "/vʲɪˈno ˈvʲetɕɪrəm/" },
    ],
    difficulty: "medium",
    description:
      "硬 /v/ 和软 /vʲ/ 的软化要和词尾清化、跨词清浊同化分开讲，避免混成一个规则。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-k-kj",
    ipa: "/k kʲ/",
    name: "hard-soft к / кь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "кот / кит",
    keywords: [
      { word: "кот", ipa: "/kot/" },
      { word: "кит", ipa: "/kʲit/" },
      { word: "как", ipa: "/kak/" },
      { word: "кино", stressText: "кино́", ipa: "/kʲɪˈno/" },
      { word: "класс", ipa: "/klas/" },
      { word: "кефир", stressText: "кефи́р", ipa: "/kʲɪˈfʲir/" },
      { word: "карта", stressText: "ка́рта", ipa: "/ˈkartə/" },
      { word: "кислый", stressText: "ки́слый", ipa: "/ˈkʲislɨj/" },
      { word: "комната", stressText: "ко́мната", ipa: "/ˈkomnətə/" },
      { word: "кирпич", stressText: "кирпи́ч", ipa: "/kʲɪrˈpʲitɕ/" },
      { word: "курс", ipa: "/kurs/" },
      { word: "кедр", ipa: "/kʲedr/" },
      { word: "камень", stressText: "ка́мень", ipa: "/ˈkamʲɪnʲ/" },
      { word: "книга", stressText: "кни́га", ipa: "/ˈknʲigə/" },
      { word: "кухня", stressText: "ку́хня", ipa: "/ˈkuxnʲə/" },
      { word: "кисть", ipa: "/kʲistʲ/" },
      { word: "кот и кит", stressText: "кот и кит", ipa: "/ˈkot i ˈkʲit/" },
      { word: "как и кино", stressText: "как и кино́", ipa: "/kak i kʲɪˈno/" },
      { word: "класс и кефир", stressText: "класс и кефи́р", ipa: "/klas i kʲɪˈfʲir/" },
      { word: "карта и кит", stressText: "ка́рта и кит", ipa: "/ˈkartə i kʲit/" },
      { word: "книга на кухне", stressText: "кни́га на ку́хне", ipa: "/ˈknʲigə nɐ ˈkuxnʲe/" },
      { word: "кино и класс", stressText: "кино́ и класс", ipa: "/kʲɪˈno i klas/" },
      { word: "кефир в комнате", stressText: "кефи́р в ко́мнате", ipa: "/kʲɪˈfʲir f ˈkomnətʲe/" },
      { word: "тихий кит", stressText: "ти́хий кит", ipa: "/ˈtʲixʲɪj kʲit/" },
    ],
    difficulty: "medium",
    description:
      "硬 /k/ 和软 /kʲ/ 都是软腭塞音；软 кь/ки/ке 的舌面要前抬，不要读成硬 /k/ 后面再加完整 /j/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-g-gj",
    ipa: "/g gʲ/",
    name: "hard-soft г / гь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "газ / герой",
    keywords: [
      { word: "газ", ipa: "/gas/" },
      { word: "герой", stressText: "геро́й", ipa: "/gʲɪˈroj/" },
      { word: "год", ipa: "/got/" },
      { word: "гитара", stressText: "гита́ра", ipa: "/gʲɪˈtarə/" },
      { word: "гора", stressText: "гора́", ipa: "/gɐˈra/" },
      { word: "гений", stressText: "ге́ний", ipa: "/ˈgʲenʲɪj/" },
      { word: "гол", ipa: "/gol/" },
      { word: "гимн", ipa: "/gʲimn/" },
      { word: "группа", stressText: "гру́ппа", ipa: "/ˈgrupə/" },
      { word: "герб", ipa: "/gʲerp/" },
      { word: "гулять", stressText: "гуля́ть", ipa: "/gʊˈlʲatʲ/" },
      { word: "гектар", stressText: "ге́ктар", ipa: "/ˈgʲektər/" },
      { word: "вагон", stressText: "ваго́н", ipa: "/vɐˈgon/" },
      { word: "книга", stressText: "кни́га", ipa: "/ˈknʲigə/" },
      { word: "ноги", stressText: "но́ги", ipa: "/ˈnogʲɪ/" },
      { word: "дорогой", stressText: "дорого́й", ipa: "/dərɐˈgoj/" },
      { word: "газ и герой", stressText: "газ и геро́й", ipa: "/gas i gʲɪˈroj/" },
      { word: "год и гитара", stressText: "год и гита́ра", ipa: "/got i gʲɪˈtarə/" },
      { word: "гора и гений", stressText: "гора́ и ге́ний", ipa: "/gɐˈra i ˈgʲenʲɪj/" },
      { word: "группа и гимн", stressText: "гру́ппа и гимн", ipa: "/ˈgrupə i gʲimn/" },
      { word: "дорогой герой", stressText: "дорого́й геро́й", ipa: "/dərɐˈgoj gʲɪˈroj/" },
      { word: "книга героя", stressText: "кни́га геро́я", ipa: "/ˈknʲigə gʲɪˈrojə/" },
      { word: "гитара в группе", stressText: "гита́ра в гру́ппе", ipa: "/gʲɪˈtarə v ˈgrupʲe/" },
      { word: "город и герой", stressText: "го́род и геро́й", ipa: "/ˈgorət i gʲɪˈroj/" },
    ],
    difficulty: "medium",
    description:
      "硬 /g/ 和软 /gʲ/ 的对立仍属于俄语硬软系统；软 гь/ги/ге 不能用英语 /g/ 加 /j/ 粗略替代。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-x-xj",
    ipa: "/x xʲ/",
    name: "hard-soft х / хь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "хор / хит",
    keywords: [
      { word: "хор", ipa: "/xor/" },
      { word: "хит", ipa: "/xʲit/" },
      { word: "холод", stressText: "хо́лод", ipa: "/ˈxolət/" },
      { word: "химия", stressText: "хи́мия", ipa: "/ˈxʲimʲɪjə/" },
      { word: "хлеб", ipa: "/xlʲep/" },
      { word: "хищник", stressText: "хи́щник", ipa: "/ˈxʲiɕːnʲɪk/" },
      { word: "смех", ipa: "/smʲex/" },
      { word: "тихий", stressText: "ти́хий", ipa: "/ˈtʲixʲɪj/" },
      { word: "ухо", stressText: "у́хо", ipa: "/ˈuxə/" },
      { word: "хитрый", stressText: "хи́трый", ipa: "/ˈxʲitrɨj/" },
      { word: "хата", stressText: "ха́та", ipa: "/ˈxatə/" },
      { word: "хоккей", stressText: "хокке́й", ipa: "/xɐˈkʲej/" },
      { word: "сухой", stressText: "сухо́й", ipa: "/sʊˈxoj/" },
      { word: "архив", stressText: "архи́в", ipa: "/ɐrˈxʲif/" },
      { word: "муха", stressText: "му́ха", ipa: "/ˈmuxə/" },
      { word: "мухи", stressText: "му́хи", ipa: "/ˈmuxʲɪ/" },
      { word: "хор и хит", stressText: "хор и хит", ipa: "/ˈxor i ˈxʲit/" },
      { word: "холод и химия", stressText: "хо́лод и хи́мия", ipa: "/ˈxolət i ˈxʲimʲɪjə/" },
      { word: "смех и тихий", stressText: "смех и ти́хий", ipa: "/smʲex i ˈtʲixʲɪj/" },
      { word: "ухо и мухи", stressText: "у́хо и му́хи", ipa: "/ˈuxə i ˈmuxʲɪ/" },
      { word: "хороший хлеб", stressText: "хоро́ший хлеб", ipa: "/xɐˈroʂɨj xlʲep/" },
      { word: "химия в архиве", stressText: "хи́мия в архи́ве", ipa: "/ˈxʲimʲɪjə v ɐrˈxʲivʲe/" },
      { word: "сухой холод", stressText: "сухо́й хо́лод", ipa: "/sʊˈxoj ˈxolət/" },
      { word: "хитрый ход", stressText: "хи́трый ход", ipa: "/ˈxʲitrɨj xot/" },
    ],
    difficulty: "high",
    description:
      "硬 /x/ 和软 /xʲ/ 都是俄语 х 的核心实现；软化时摩擦位置更前，不能退回英语 /h/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-soft-sign",
    ipa: "/ʲ/",
    name: "soft sign ь",
    category: "consonant",
    soundUnitType: "contrast",
    example: "мать",
    keywords: [
      { word: "мать", ipa: "/matʲ/" },
      { word: "уголь", ipa: "/ˈugəlʲ/", stressText: "у́голь" },
      { word: "день", ipa: "/dʲenʲ/" },
      { word: "письмо", ipa: "/pʲɪsʲˈmo/", stressText: "письмо́" },
      { word: "конь", ipa: "/konʲ/" },
      { word: "мель", ipa: "/mʲelʲ/" },
      { word: "пить", ipa: "/pʲitʲ/" },
      { word: "брать", ipa: "/bratʲ/" },
      { word: "семь", ipa: "/sʲemʲ/" },
      { word: "дверь", ipa: "/dvʲerʲ/" },
      { word: "ночь", ipa: "/notɕ/" },
      { word: "помощь", ipa: "/ˈpoməɕː/", stressText: "по́мощь" },
      { word: "сибирь", ipa: "/sʲɪˈbirʲ/", stressText: "Сиби́рь" },
      { word: "учитель", ipa: "/ʊˈtɕitʲɪlʲ/", stressText: "учи́тель" },
      { word: "любовь", ipa: "/lʲʊˈbofʲ/", stressText: "любо́вь" },
      { word: "июнь", ipa: "/ɪˈjunʲ/", stressText: "ию́нь" },
      { word: "мат и мать", ipa: "/mat i matʲ/" },
      { word: "угол и уголь", ipa: "/ˈugəl i ˈugəlʲ/" },
      { word: "кон и конь", ipa: "/kon i konʲ/" },
      { word: "пить письмо", ipa: "/pʲitʲ pʲɪsʲˈmo/" },
    ],
    difficulty: "high",
    description:
      "软音符号不发独立声音，它改变前一个辅音的软化；训练时要显示出来但不能读成一个额外音节。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ts",
    ipa: "/ts/",
    name: "Russian ц",
    category: "consonant",
    example: "царь",
    keywords: [
      { word: "царь", ipa: "/tsarʲ/" },
      { word: "цена", ipa: "/tsɨˈna/", stressText: "цена́" },
      { word: "центр", ipa: "/tsentr/" },
      { word: "улица", ipa: "/ˈulʲɪtsə/", stressText: "у́лица" },
      { word: "конец", ipa: "/kɐˈnʲets/", stressText: "коне́ц" },
      { word: "цирк", ipa: "/tsɨrk/" },
      { word: "цепь", ipa: "/tsepʲ/" },
      { word: "танец", ipa: "/ˈtanʲɪts/", stressText: "та́нец" },
      { word: "отец", ipa: "/ɐˈtʲets/", stressText: "оте́ц" },
      { word: "птица", ipa: "/ˈptʲitsə/", stressText: "пти́ца" },
      { word: "станция", ipa: "/ˈstantsɨjə/", stressText: "ста́нция" },
      { word: "традиция", ipa: "/trɐˈdʲitsɨjə/", stressText: "тради́ция" },
      { word: "месяц", ipa: "/ˈmʲesʲɪts/", stressText: "ме́сяц" },
      { word: "двадцать", ipa: "/ˈdvatsətʲ/", stressText: "два́дцать" },
      { word: "пятьдесят", ipa: "/pʲɪdʲɪˈsʲat/", stressText: "пятьдеся́т" },
      { word: "процент", ipa: "/prɐˈtsent/", stressText: "проце́нт" },
      { word: "цена центра", ipa: "/tsɨˈna ˈtsentrə/" },
      { word: "улица и центр", ipa: "/ˈulʲɪtsə i tsentr/" },
      { word: "цирк в конце", ipa: "/tsɨrk f kɐˈnʲtse/" },
      { word: "отец танцует", ipa: "/ɐˈtʲets tɐnˈtsujɪt/" },
    ],
    difficulty: "medium",
    description: "ц 是 /ts/，通常偏硬；不要把后面的 и 读成普通 /i/ 的软化环境。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ch",
    ipa: "/tɕ/",
    name: "Russian ч",
    category: "consonant",
    example: "чай",
    keywords: [
      { word: "чай", ipa: "/tɕaj/" },
      { word: "час", ipa: "/tɕas/" },
      { word: "читать", ipa: "/tɕɪˈtatʲ/", stressText: "чита́ть" },
      { word: "человек", ipa: "/tɕɪlɐˈvʲek/", stressText: "челове́к" },
      { word: "ключ", ipa: "/klʲutɕ/" },
      { word: "чашка", ipa: "/ˈtɕaʂkə/", stressText: "ча́шка" },
      { word: "часто", ipa: "/ˈtɕastə/", stressText: "ча́сто" },
      { word: "вечер", ipa: "/ˈvʲetɕɪr/", stressText: "ве́чер" },
      { word: "учить", ipa: "/ʊˈtɕitʲ/", stressText: "учи́ть" },
      { word: "учитель", ipa: "/ʊˈtɕitʲɪlʲ/", stressText: "учи́тель" },
      { word: "дочь", ipa: "/dotɕ/" },
      { word: "ночь", ipa: "/notɕ/" },
      { word: "мяч", ipa: "/mʲatɕ/" },
      { word: "врач", ipa: "/vratɕ/" },
      { word: "почему", ipa: "/pətɕɪˈmu/", stressText: "почему́" },
      { word: "часы", ipa: "/tɕɪˈsɨ/", stressText: "часы́" },
      { word: "чай и час", stressText: "чай и час", ipa: "/ˈtɕaj i ˈtɕas/" },
      { word: "читать вечером", ipa: "/tɕɪˈtatʲ ˈvʲetɕɪrəm/" },
      { word: "учитель читает", ipa: "/ʊˈtɕitʲɪlʲ tɕɪˈtajɪt/" },
      { word: "чашка чая", ipa: "/ˈtɕaʂkə ˈtɕajə/" },
    ],
    difficulty: "high",
    description: "ч 通常偏软，是紧凑的 /tɕ/；不要把它读成硬 /tʃ/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-shch",
    ipa: "/ɕː/",
    name: "Russian щ",
    category: "consonant",
    example: "щи",
    keywords: [
      { word: "щи", ipa: "/ɕːi/" },
      { word: "щука", ipa: "/ˈɕːukə/", stressText: "щу́ка" },
      { word: "ещё", ipa: "/jɪˈɕːo/" },
      { word: "площадь", ipa: "/ˈploɕːətʲ/", stressText: "пло́щадь" },
      { word: "помощь", ipa: "/ˈpoməɕː/", stressText: "по́мощь" },
      { word: "борщ", ipa: "/borɕː/" },
      { word: "товарищ", ipa: "/tɐˈvarʲɪɕː/", stressText: "това́рищ" },
      { word: "щётка", ipa: "/ˈɕːotkə/" },
      { word: "ящик", ipa: "/ˈjaɕːɪk/", stressText: "я́щик" },
      { word: "женщина", ipa: "/ˈʐenɕːɪnə/", stressText: "же́нщина" },
      { word: "будущий", ipa: "/ˈbuduɕːɪj/", stressText: "бу́дущий" },
      { word: "ищу", ipa: "/ɪˈɕːu/", stressText: "ищу́" },
      { word: "защита", ipa: "/zɐˈɕːitə/", stressText: "защи́та" },
      { word: "вещь", ipa: "/vʲeɕː/" },
      { word: "роща", ipa: "/ˈroɕːə/", stressText: "ро́ща" },
      { word: "общий", ipa: "/ˈopɕːɪj/", stressText: "о́бщий" },
      { word: "борщ и щи", stressText: "борщ и щи", ipa: "/ˈborɕː i ˈɕːi/" },
      { word: "помощь нужна", ipa: "/ˈpoməɕː nʊˈʐna/" },
      { word: "ещё щука", ipa: "/jɪˈɕːo ˈɕːukə/" },
      { word: "площадь большая", ipa: "/ˈploɕːətʲ bɐlʲˈʂajə/" },
    ],
    difficulty: "high",
    description: "щ 长而软，接近 /ɕː/；不要简单读成 ш + ч 的硬组合。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-j",
    ipa: "/j/",
    name: "Russian й",
    category: "consonant",
    soundUnitType: "phoneme",
    example: "йогурт",
    keywords: [
      { word: "йогурт", ipa: "/ˈjogʊrt/", stressText: "йо́гурт" },
      { word: "мой", ipa: "/moj/" },
      { word: "твой", ipa: "/tvoj/" },
      { word: "край", ipa: "/kraj/" },
      { word: "чай", ipa: "/tɕaj/" },
      { word: "май", ipa: "/maj/" },
      { word: "свой", ipa: "/svoj/" },
      { word: "герой", ipa: "/gʲɪˈroj/", stressText: "геро́й" },
      { word: "музей", ipa: "/mʊˈzʲej/", stressText: "музе́й" },
      { word: "новый", ipa: "/ˈnovɨj/", stressText: "но́вый" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/", stressText: "си́ний" },
      { word: "язык", ipa: "/jɪˈzɨk/", stressText: "язы́к" },
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "поезд", ipa: "/ˈpojɪst/", stressText: "по́езд" },
      { word: "июнь", ipa: "/ɪˈjunʲ/", stressText: "ию́нь" },
      { word: "июль", ipa: "/ɪˈjulʲ/", stressText: "ию́ль" },
      { word: "мой чай", stressText: "мой чай", ipa: "/ˈmoj ˈtɕaj/" },
      { word: "новый музей", ipa: "/ˈnovɨj mʊˈzʲej/" },
      { word: "семья у моря", ipa: "/sʲɪmʲˈja u ˈmorʲə/" },
      { word: "поезд идёт", ipa: "/ˈpojɪst ɪˈdʲot/" },
    ],
    difficulty: "medium",
    description: "/j/ 是短滑音；和软辅音 [ʲ] 不同，软化不是额外加一个 й。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-iotated-vowels",
    ipa: "/ja je jo ju/",
    name: "iotated vowels я/е/ё/ю",
    category: "prosody",
    soundUnitType: "connected-speech-rule",
    example: "я",
    keywords: [
      { word: "я", ipa: "/ja/" },
      { word: "есть", ipa: "/jesʲtʲ/" },
      { word: "ёж", ipa: "/joʂ/" },
      { word: "юг", ipa: "/juk/" },
      { word: "язык", ipa: "/jɪˈzɨk/", stressText: "язы́к" },
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "мяч", ipa: "/mʲatɕ/" },
      { word: "ёлка", ipa: "/ˈjolkə/" },
      { word: "люк", ipa: "/lʲuk/" },
      { word: "моя семья", ipa: "/mɐˈja sʲɪmʲˈja/" },
      { word: "новая юбка", ipa: "/ˈnovəjə ˈjupkə/" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "земля", ipa: "/zʲɪˈmlʲa/", stressText: "земля́" },
      { word: "Я люблю русский язык.", ipa: "/ja lʲʊˈblʲu ˈruskʲɪj jɪˈzɨk/" },
      { word: "Мой поезд идёт на юг.", ipa: "/moj ˈpojɪst ɪˈdʲot nɐ juk/" },
      { word: "варенье", ipa: "/vɐˈrʲenʲjə/", stressText: "варе́нье" },
      { word: "я люблю", ipa: "/ja lʲʊˈblʲu/" },
      { word: "семья едет", ipa: "/sʲɪmʲˈja ˈjedʲɪt/" },
      { word: "юг и ёж", ipa: "/juk i joʂ/" },
      { word: "песня о семье", ipa: "/ˈpʲesʲnʲə o sʲɪmʲˈje/" },
    ],
    difficulty: "high",
    description:
      "я/е/ё/ю 在词首或元音后常带 /j/，在辅音后常标记前辅音软化；要按位置判断。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-unstressed-o-a",
    ipa: "/ɐ ə/",
    name: "unstressed о/а reduction",
    category: "prosody",
    soundUnitType: "prosody",
    example: "молоко",
    keywords: [
      { word: "молоко", ipa: "/məlɐˈko/", stressText: "молоко́" },
      { word: "хорошо", ipa: "/xərɐˈʂo/", stressText: "хорошо́" },
      { word: "Москва", ipa: "/mɐˈskva/", stressText: "Москва́" },
      { word: "собака", ipa: "/sɐˈbakə/", stressText: "соба́ка" },
      { word: "работа", ipa: "/rɐˈbotə/", stressText: "рабо́та" },
      { word: "дорога", ipa: "/dɐˈrogə/", stressText: "доро́га" },
      { word: "вода", ipa: "/vɐˈda/", stressText: "вода́" },
      { word: "окно", ipa: "/ɐkˈno/", stressText: "окно́" },
      { word: "погода", ipa: "/pɐˈgodə/", stressText: "пого́да" },
      { word: "магазин", ipa: "/məgɐˈzʲin/", stressText: "магази́н" },
      { word: "телефон", ipa: "/tʲɪlʲɪˈfon/", stressText: "телефо́н" },
      { word: "окно открыто", ipa: "/ɐkˈno ɐtˈkrɨtə/" },
      { word: "собака голодная", ipa: "/sɐˈbakə ˈgolədnəjə/" },
      { word: "мама дома", ipa: "/ˈmamə ˈdomə/" },
      { word: "город", ipa: "/ˈgorət/", stressText: "го́род" },
      { word: "Хорошо, спасибо.", ipa: "/xərɐˈʂo spɐˈsʲibə/" },
      { word: "Москва сегодня", ipa: "/mɐˈskva sʲɪˈvodnʲə/" },
      { word: "молоко дома", ipa: "/məlɐˈko ˈdomə/" },
      { word: "собака во дворе", ipa: "/sɐˈbakə vɐ dvɐˈrʲe/" },
      { word: "хорошая погода", ipa: "/xɐˈroʂəjə pɐˈgodə/" },
    ],
    difficulty: "high",
    description:
      "非重读 о/а 常弱化到 [ɐ]/[ə] 附近；先找重音，不要逐字母读。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-unstressed-e-ya",
    ipa: "/ɪ ə/",
    name: "unstressed е/я reduction",
    category: "prosody",
    soundUnitType: "prosody",
    example: "семья",
    keywords: [
      { word: "семья", ipa: "/sʲɪmʲˈja/", stressText: "семья́" },
      { word: "язык", ipa: "/jɪˈzɨk/", stressText: "язы́к" },
      { word: "сегодня", ipa: "/sʲɪˈvodnʲə/", stressText: "сего́дня" },
      { word: "минута", ipa: "/mʲɪˈnutə/", stressText: "мину́та" },
      { word: "директор", ipa: "/dʲɪˈrʲektər/", stressText: "дире́ктор" },
      { word: "билет", ipa: "/bʲɪˈlʲet/", stressText: "биле́т" },
      { word: "земля", ipa: "/zʲɪˈmlʲa/", stressText: "земля́" },
      { word: "письмо", ipa: "/pʲɪsʲˈmo/", stressText: "письмо́" },
      { word: "тетрадь", ipa: "/tʲɪˈtratʲ/", stressText: "тетра́дь" },
      { word: "человек", ipa: "/tɕɪlɐˈvʲek/", stressText: "челове́к" },
      { word: "понедельник", ipa: "/pənʲɪˈdʲelʲnʲɪk/", stressText: "понеде́льник" },
      { word: "интересно", ipa: "/ɪntʲɪˈrʲesnə/", stressText: "интере́сно" },
      { word: "дети идут", ipa: "/ˈdʲetʲɪ ɪˈdut/" },
      { word: "песня", ipa: "/ˈpʲesʲnʲə/", stressText: "пе́сня" },
      { word: "пять билетов", ipa: "/pʲætʲ bʲɪˈlʲetəf/" },
      { word: "Это билет в театр.", ipa: "/ˈetə bʲɪˈlʲet f tʲɪˈatr/" },
      { word: "семья сегодня", ipa: "/sʲɪmʲˈja sʲɪˈvodnʲə/" },
      { word: "билет в театр", ipa: "/bʲɪˈlʲet f tʲɪˈatr/" },
      { word: "язык человека", ipa: "/jɪˈzɨk tɕɪlɐˈvʲekə/" },
      { word: "интересная минута", ipa: "/ɪntʲɪˈrʲesnəjə mʲɪˈnutə/" },
    ],
    difficulty: "high",
    description:
      "非重读 е/я 常趋向 [ɪ]/[ə]，同时前后辅音软化明显；不要把每个字母都读成完整 /e/ 或 /ja/。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-final-devoicing",
    ipa: "final devoicing",
    name: "word-final devoicing",
    category: "prosody",
    soundUnitType: "connected-speech-rule",
    example: "друг",
    keywords: [
      { word: "друг", ipa: "/druk/" },
      { word: "город", ipa: "/ˈgorət/", stressText: "го́род" },
      { word: "нож", ipa: "/noʂ/" },
      { word: "гараж", ipa: "/gɐˈraʂ/", stressText: "гара́ж" },
      { word: "хлеб", ipa: "/xlʲep/" },
      { word: "дуб", ipa: "/dup/" },
      { word: "глаз", ipa: "/glas/" },
      { word: "год", ipa: "/got/" },
      { word: "мёд", ipa: "/mʲot/" },
      { word: "луг", ipa: "/luk/" },
      { word: "сад пустой", ipa: "/sat pʊˈstoj/" },
      { word: "поезд идёт", ipa: "/ˈpojɪst ɪˈdʲot/" },
      { word: "нож тупой", ipa: "/noʂ tʊˈpoj/" },
      { word: "зуб", ipa: "/zup/" },
      { word: "Сад зимой синий.", ipa: "/sad zʲɪˈmoj ˈsʲinʲɪj/" },
      { word: "снег", ipa: "/snʲek/" },
      { word: "друг дома", ipa: "/drug ˈdomə/" },
      { word: "город большой", ipa: "/ˈgorəd bɐlʲˈʂoj/" },
      { word: "нож острый", ipa: "/noʐ ˈostrɨj/" },
      { word: "гараж открыт", ipa: "/gɐˈraʂ ɐtˈkrɨt/" },
    ],
    difficulty: "high",
    description:
      "停顿或清辅音前，词尾 б/д/г/ж/з 常清化；但连到浊辅音、响音或元音前时要按语流处理，不能把每个词都孤立清化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-voicing-assimilation",
    ipa: "voicing assimilation",
    name: "consonant voicing assimilation",
    category: "prosody",
    soundUnitType: "connected-speech-rule",
    example: "встреча",
    keywords: [
      { word: "встреча", ipa: "/ˈfstrʲetɕə/", stressText: "встре́ча" },
      { word: "сделать", ipa: "/ˈzdʲelətʲ/", stressText: "сде́лать" },
      { word: "просьба", ipa: "/ˈprozʲbə/", stressText: "про́сьба" },
      { word: "сдать", ipa: "/zdatʲ/" },
      { word: "вокзал", ipa: "/vɐgˈzal/", stressText: "вокза́л" },
      { word: "подписать", ipa: "/pətpʲɪˈsatʲ/", stressText: "подписа́ть" },
      { word: "отдых", ipa: "/ˈoddɨx/", stressText: "о́тдых" },
      { word: "книга", ipa: "/ˈknʲigə/", stressText: "кни́га" },
      { word: "сбор", ipa: "/zbor/" },
      { word: "к дому", ipa: "/g ˈdomu/" },
      { word: "в школе", ipa: "/f ˈʂkolʲe/" },
      { word: "с братом", ipa: "/z ˈbratəm/" },
      { word: "под столом", ipa: "/pət stɐˈlom/" },
      { word: "над книгой", ipa: "/nat ˈknʲigəj/" },
      { word: "из школы", ipa: "/is ˈʂkolɨ/" },
      { word: "без тебя", ipa: "/bʲɪs tʲɪˈbʲa/" },
      { word: "встреча завтра", ipa: "/ˈfstrʲetɕə ˈzaftrə/" },
      { word: "сделать быстро", ipa: "/ˈzdʲelətʲ ˈbɨstrə/" },
      { word: "просьба друга", ipa: "/ˈprozʲbə ˈdrugə/" },
      { word: "вокзал рядом", ipa: "/vɐgˈzal ˈrʲadəm/" },
    ],
    difficulty: "high",
    description:
      "相邻辅音会影响清浊；例如 встреча 中 в 接清辅音读 [f]，不是按字母逐个读。",
  }),
];
