import type { PhonemeData } from "@/types/phoneme";
import { unit } from "@/lib/language-sound-units/utils";

export const SPANISH_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "es-ES",
    slug: "es-a",
    ipa: "/a/",
    name: "open central vowel",
    category: "vowel",
    example: "casa",
    keywords: [
      { word: "casa", ipa: "/ˈkasa/" },
      { word: "mano", ipa: "/ˈmano/" },
      { word: "agua", ipa: "/ˈaɣwa/" },
      { word: "mapa", ipa: "/ˈmapa/" },
      { word: "nada", ipa: "/ˈnaða/" },
      { word: "sal", ipa: "/sal/" },
    ],
    difficulty: "easy",
    description:
      "嘴巴自然张开，舌位低而居中，保持短、纯、稳定，不滑向英语 /æ/ 或 /ɑː/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-e",
    ipa: "/e/",
    name: "close-mid front vowel",
    category: "vowel",
    example: "mesa",
    keywords: [
      { word: "mesa", ipa: "/ˈmesa/" },
      { word: "leche", ipa: "/ˈletʃe/" },
      { word: "perro", ipa: "/ˈpero/" },
      { word: "verde", ipa: "/ˈbeɾðe/" },
      { word: "tres", ipa: "/tɾes/" },
      { word: "dedo", ipa: "/ˈdeðo/" },
    ],
    difficulty: "easy",
    description: "舌前部抬起，嘴巴半闭；不要读成英语双元音 /eɪ/，结尾不滑。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-i",
    ipa: "/i/",
    name: "close front vowel",
    category: "vowel",
    example: "sí",
    keywords: [
      { word: "sí", ipa: "/si/" },
      { word: "vida", ipa: "/ˈbiða/" },
      { word: "niño", ipa: "/ˈniɲo/" },
      { word: "libro", ipa: "/ˈlibɾo/" },
      { word: "cinco", ipa: "/ˈθinko/" },
      { word: "mira", ipa: "/ˈmiɾa/" },
    ],
    difficulty: "easy",
    description: "嘴角微展，舌前高位；声音短而干净，不拖成长英语 /iː/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-o",
    ipa: "/o/",
    name: "close-mid back rounded vowel",
    category: "vowel",
    example: "sol",
    keywords: [
      { word: "sol", ipa: "/sol/" },
      { word: "hola", ipa: "/ˈola/" },
      { word: "coche", ipa: "/ˈkotʃe/" },
      { word: "rojo", ipa: "/ˈroxo/" },
      { word: "todo", ipa: "/ˈtoðo/" },
      { word: "boca", ipa: "/ˈboka/" },
    ],
    difficulty: "easy",
    description: "双唇收圆，舌后部抬起；保持单元音，不要滑成英语 /oʊ/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-u",
    ipa: "/u/",
    name: "close back rounded vowel",
    category: "vowel",
    example: "luna",
    keywords: [
      { word: "luna", ipa: "/ˈluna/" },
      { word: "uno", ipa: "/ˈuno/" },
      { word: "tú", ipa: "/tu/" },
      { word: "azul", ipa: "/aˈθul/" },
      { word: "mundo", ipa: "/ˈmundo/" },
      { word: "curso", ipa: "/ˈkuɾso/" },
    ],
    difficulty: "easy",
    description: "双唇收圆但声音短，不要按英语长 /uː/ 拉长。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-p",
    ipa: "/p/",
    name: "unaspirated Spanish p",
    category: "consonant",
    example: "pan",
    keywords: [
      { word: "pan", ipa: "/pan/" },
      { word: "papel", ipa: "/paˈpel/" },
      { word: "padre", ipa: "/ˈpaðɾe/" },
      { word: "mapa", ipa: "/ˈmapa/" },
      { word: "poco", ipa: "/ˈpoko/" },
      { word: "puerta", ipa: "/ˈpweɾta/" },
      { word: "plaza", ipa: "/ˈplaθa/" },
      { word: "sopa", ipa: "/ˈsopa/" },
      { word: "campo", ipa: "/ˈkampo/" },
      { word: "rápido", ipa: "/ˈrapiðo/" },
      { word: "España", ipa: "/esˈpaɲa/" },
      { word: "pregunta", ipa: "/pɾeˈɣunta/" },
      { word: "primavera", ipa: "/pɾimaˈβeɾa/" },
      { word: "pelo", ipa: "/ˈpelo/" },
      { word: "pato", ipa: "/ˈpato/" },
      { word: "piso", ipa: "/ˈpiso/" },
      { word: "peso", ipa: "/ˈpeso/" },
      { word: "paquete", ipa: "/paˈkete/" },
      { word: "papel pequeño", ipa: "/paˈpel peˈkeɲo/" },
      { word: "poco a poco", ipa: "/ˈpoko a ˈpoko/" },
      { word: "paz", ipa: "/paθ/" },
      { word: "primero", ipa: "/pɾiˈmeɾo/" },
      { word: "plato", ipa: "/ˈplato/" },
      { word: "ropa", ipa: "/ˈropa/" },
    ],
    difficulty: "easy",
    description:
      "双唇闭合后短促打开；西语 /p/ 不像英语词首 p 那样强送气，要干净但不喷气。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-t",
    ipa: "/t/",
    name: "dental Spanish t",
    category: "consonant",
    example: "tú",
    keywords: [
      { word: "tú", ipa: "/tu/" },
      { word: "té", ipa: "/te/" },
      { word: "toma", ipa: "/ˈtoma/" },
      { word: "todo", ipa: "/ˈtoðo/" },
      { word: "tarde", ipa: "/ˈtaɾðe/" },
      { word: "tres", ipa: "/tɾes/" },
      { word: "cuatro", ipa: "/ˈkwatɾo/" },
      { word: "alto", ipa: "/ˈalto/" },
      { word: "gato", ipa: "/ˈgato/" },
      { word: "patata", ipa: "/paˈtata/" },
      { word: "tiempo", ipa: "/ˈtjempo/" },
      { word: "tren", ipa: "/tɾen/" },
      { word: "trabajo", ipa: "/tɾaˈβaxo/" },
      { word: "tarjeta", ipa: "/taɾˈxeta/" },
      { word: "tomate", ipa: "/toˈmate/" },
      { word: "taza", ipa: "/ˈtaθa/" },
      { word: "tío", ipa: "/ˈtio/" },
      { word: "texto", ipa: "/ˈteksto/" },
      { word: "esta tarde", ipa: "/ˈesta ˈtaɾðe/" },
      { word: "tengo tiempo", ipa: "/ˈtengo ˈtjempo/" },
      { word: "tarde tranquila", ipa: "/ˈtaɾde tɾanˈkila/" },
      { word: "tres tomates", ipa: "/tɾes toˈmates/" },
      { word: "tú también", ipa: "/tu tamˈbjen/" },
      { word: "todo listo", ipa: "/ˈtoðo ˈlisto/" },
    ],
    difficulty: "easy",
    description:
      "舌尖靠近上齿背，位置比英语 /t/ 更靠前；不要强送气，也不要卷到英语齿龈后。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-k",
    ipa: "/k/",
    name: "unaspirated Spanish k",
    category: "consonant",
    example: "casa",
    keywords: [
      { word: "casa", ipa: "/ˈkasa/" },
      { word: "queso", ipa: "/ˈkeso/" },
      { word: "kilo", ipa: "/ˈkilo/" },
      { word: "coche", ipa: "/ˈkotʃe/" },
      { word: "poco", ipa: "/ˈpoko/" },
      { word: "boca", ipa: "/ˈboka/" },
      { word: "escuela", ipa: "/esˈkwela/" },
      { word: "clase", ipa: "/ˈklase/" },
      { word: "claro", ipa: "/ˈklaɾo/" },
      { word: "cantar", ipa: "/kanˈtaɾ/" },
      { word: "camino", ipa: "/kaˈmino/" },
      { word: "café", ipa: "/kaˈfe/" },
      { word: "cuchara", ipa: "/kuˈtʃaɾa/" },
      { word: "cuatro", ipa: "/ˈkwatɾo/" },
      { word: "banco", ipa: "/ˈbanko/" },
      { word: "buscar", ipa: "/busˈkaɾ/" },
      { word: "porque", ipa: "/ˈpoɾke/" },
      { word: "mercado", ipa: "/meɾˈkaðo/" },
      { word: "cada cosa", ipa: "/ˈkaða ˈkosa/" },
      { word: "una casa", ipa: "/ˈuna ˈkasa/" },
      { word: "cosa", ipa: "/ˈkosa/" },
      { word: "quince", ipa: "/ˈkinθe/" },
      { word: "cuenta", ipa: "/ˈkwenta/" },
      { word: "clase corta", ipa: "/ˈklase ˈkoɾta/" },
    ],
    difficulty: "easy",
    description:
      "舌后部短暂贴住软腭后打开；西语 /k/ 要短而不强送气，c/qu/k 拼写都可对应这个目标。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-f",
    ipa: "/f/",
    name: "Spanish f",
    category: "consonant",
    example: "foto",
    keywords: [
      { word: "foto", ipa: "/ˈfoto/" },
      { word: "fácil", ipa: "/ˈfaθil/" },
      { word: "familia", ipa: "/faˈmilja/" },
      { word: "febrero", ipa: "/feˈβɾeɾo/" },
      { word: "flor", ipa: "/floɾ/" },
      { word: "fruta", ipa: "/ˈfɾuta/" },
      { word: "fuerte", ipa: "/ˈfweɾte/" },
      { word: "café", ipa: "/kaˈfe/" },
      { word: "teléfono", ipa: "/teˈlefono/" },
      { word: "oficina", ipa: "/ofiˈθina/" },
      { word: "frío", ipa: "/ˈfɾio/" },
      { word: "fiesta", ipa: "/ˈfjesta/" },
      { word: "feliz", ipa: "/feˈliθ/" },
      { word: "falso", ipa: "/ˈfalso/" },
      { word: "favor", ipa: "/faˈβoɾ/" },
      { word: "fecha", ipa: "/ˈfetʃa/" },
      { word: "falda", ipa: "/ˈfalda/" },
      { word: "fin", ipa: "/fin/" },
      { word: "familia feliz", ipa: "/faˈmilja feˈliθ/" },
      { word: "foto fácil", ipa: "/ˈfoto ˈfaθil/" },
      { word: "forma", ipa: "/ˈfoɾma/" },
      { word: "firma", ipa: "/ˈfiɾma/" },
      { word: "final", ipa: "/fiˈnal/" },
      { word: "flor fresca", ipa: "/floɾ ˈfɾeska/" },
    ],
    difficulty: "easy",
    description:
      "上齿轻触下唇形成持续摩擦；保持清音，不要读成英语 /v/ 或把气流拖得太长。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-m",
    ipa: "/m/",
    name: "Spanish m",
    category: "consonant",
    example: "mano",
    keywords: [
      { word: "mano", ipa: "/ˈmano/" },
      { word: "mesa", ipa: "/ˈmesa/" },
      { word: "amigo", ipa: "/aˈmiɣo/" },
      { word: "mamá", ipa: "/maˈma/" },
      { word: "mundo", ipa: "/ˈmundo/" },
      { word: "mañana", ipa: "/maˈɲana/" },
      { word: "comer", ipa: "/koˈmeɾ/" },
      { word: "cama", ipa: "/ˈkama/" },
      { word: "momento", ipa: "/moˈmento/" },
      { word: "música", ipa: "/ˈmusika/" },
      { word: "mi", ipa: "/mi/" },
      { word: "menos", ipa: "/ˈmenos/" },
      { word: "minuto", ipa: "/miˈnuto/" },
      { word: "museo", ipa: "/muˈseo/" },
      { word: "mismo", ipa: "/ˈmismo/" },
      { word: "nombre", ipa: "/ˈnombɾe/" },
      { word: "camino", ipa: "/kaˈmino/" },
      { word: "mapa", ipa: "/ˈmapa/" },
      { word: "me gusta", ipa: "/me ˈɣusta/" },
      { word: "mi mamá", ipa: "/mi maˈma/" },
      { word: "miel", ipa: "/mjel/" },
      { word: "mar", ipa: "/maɾ/" },
      { word: "médico", ipa: "/ˈmeðiko/" },
      { word: "mucho más", ipa: "/ˈmutʃo mas/" },
    ],
    difficulty: "easy",
    description:
      "双唇闭合，声音从鼻腔出来；保持短而清楚，和鼻音位置同化规则分开练。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-n",
    ipa: "/n/",
    name: "Spanish n",
    category: "consonant",
    example: "no",
    keywords: [
      { word: "no", ipa: "/no/" },
      { word: "nada", ipa: "/ˈnaða/" },
      { word: "noche", ipa: "/ˈnotʃe/" },
      { word: "enero", ipa: "/eˈneɾo/" },
      { word: "una", ipa: "/ˈuna/" },
      { word: "mano", ipa: "/ˈmano/" },
      { word: "pan", ipa: "/pan/" },
      { word: "con", ipa: "/kon/" },
      { word: "antes", ipa: "/ˈantes/" },
      { word: "naranja", ipa: "/naˈɾanxa/" },
      { word: "lunes", ipa: "/ˈlunes/" },
      { word: "tren", ipa: "/tɾen/" },
      { word: "bueno", ipa: "/ˈbweno/" },
      { word: "nombre", ipa: "/ˈnombɾe/" },
      { word: "ventana", ipa: "/benˈtana/" },
      { word: "nuevo", ipa: "/ˈnweβo/" },
      { word: "nunca", ipa: "/ˈnunka/" },
      { word: "niño", ipa: "/ˈniɲo/" },
      { word: "no entiendo", ipa: "/no enˈtjendo/" },
      { word: "una noche", ipa: "/ˈuna ˈnotʃe/" },
      { word: "norte", ipa: "/ˈnoɾte/" },
      { word: "número", ipa: "/ˈnumeɾo/" },
      { word: "normal", ipa: "/noɾˈmal/" },
      { word: "nada nuevo", ipa: "/ˈnaða ˈnweβo/" },
    ],
    difficulty: "easy",
    description:
      "舌尖接近上齿背/齿龈，气流从鼻腔出来；具体位置会随下一个辅音变化，那个变化在鼻音同化单元里训练。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-b-stop",
    ipa: "/b/",
    name: "Spanish /b/ stop-position anchor",
    category: "consonant",
    example: "boca",
    keywords: [
      { word: "boca", ipa: "/ˈboka/" },
      { word: "banco", ipa: "/ˈbanko/" },
      { word: "bueno", ipa: "/ˈbweno/" },
      { word: "bebé", ipa: "/beˈbe/" },
      { word: "vino", ipa: "/ˈbino/" },
      { word: "vaca", ipa: "/ˈbaka/" },
      { word: "barco", ipa: "/ˈbaɾko/" },
      { word: "buscar", ipa: "/busˈkaɾ/" },
      { word: "barrio", ipa: "/ˈbarjo/" },
      { word: "broma", ipa: "/ˈbɾoma/" },
      { word: "blanco", ipa: "/ˈblanko/" },
      { word: "bonito", ipa: "/boˈnito/" },
      { word: "un beso", ipa: "/um ˈbeso/" },
      { word: "un barco", ipa: "/um ˈbaɾko/" },
      { word: "buen día", ipa: "/bwen ˈdia/" },
      { word: "boca bonita", ipa: "/ˈboka boˈnita/" },
      { word: "bebe bien", ipa: "/ˈbebe bjen/" },
      { word: "banco blanco", ipa: "/ˈbanko ˈblanko/" },
      { word: "Beto busca un banco.", ipa: "/ˈbeto ˈbuska un ˈbanko/" },
      { word: "Boca y beso empiezan con /b/.", ipa: "/ˈboka i ˈbeso emˈpjeθan kon be/" },
      { word: "vida", ipa: "/ˈbida/" },
      { word: "volver", ipa: "/bolˈbeɾ/" },
      { word: "bravo", ipa: "/ˈbɾabo/" },
      { word: "bajo", ipa: "/ˈbaxo/" },
    ],
    difficulty: "medium",
    description:
      "这是西语 /b/ 音位的塞音位置锚点：停顿后或鼻音后闭住双唇再打开。它不等于英语 /v/，也不要用元音间 [β] 的小喇叭冒充。",
    notes: [
      "b 和 v 在西语中通常同属 /b/ 音位；本单元只锚定停顿后/鼻音后的塞音实现。",
      "元音间放松的 [β] 继续放在 es-bv 实现层训练。",
    ],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-d-stop",
    ipa: "/d/",
    name: "Spanish /d/ stop-position anchor",
    category: "consonant",
    example: "dos",
    keywords: [
      { word: "dos", ipa: "/dos/" },
      { word: "día", ipa: "/ˈdia/" },
      { word: "dama", ipa: "/ˈdama/" },
      { word: "domingo", ipa: "/doˈmingo/" },
      { word: "doctor", ipa: "/dokˈtoɾ/" },
      { word: "dormir", ipa: "/doɾˈmiɾ/" },
      { word: "dato", ipa: "/ˈdato/" },
      { word: "duda", ipa: "/ˈduda/" },
      { word: "duro", ipa: "/ˈduɾo/" },
      { word: "desde", ipa: "/ˈdesde/" },
      { word: "andar", ipa: "/anˈdaɾ/" },
      { word: "un día", ipa: "/un ˈdia/" },
      { word: "el doctor", ipa: "/el dokˈtoɾ/" },
      { word: "dos datos", ipa: "/dos ˈdatos/" },
      { word: "donde duerme", ipa: "/ˈdonde ˈdweɾme/" },
      { word: "Dora da dos datos.", ipa: "/ˈdoɾa da dos ˈdatos/" },
      { word: "digo", ipa: "/ˈdigo/" },
      { word: "dar", ipa: "/daɾ/" },
      { word: "deporte", ipa: "/deˈpoɾte/" },
      { word: "dental", ipa: "/denˈtal/" },
      { word: "dedo", ipa: "/ˈdedo/" },
      { word: "tarde", ipa: "/ˈtaɾde/" },
      { word: "Madrid", ipa: "/maˈdɾid/" },
      { word: "dulce", ipa: "/ˈdulθe/" },
    ],
    difficulty: "medium",
    description:
      "这是西语 /d/ 音位的塞音位置锚点：舌尖更靠近上齿背，停顿后、/n/ 或 /l/ 后更完整闭塞；不要读成英语强爆破或美式 flap。",
    notes: [
      "元音间的轻擦/近音 [ð] 是同一音位的语流实现，单独在 es-d 实现层训练。",
    ],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-g-stop",
    ipa: "/g/",
    name: "Spanish /g/ stop-position anchor",
    category: "consonant",
    example: "gato",
    keywords: [
      { word: "gato", ipa: "/ˈgato/" },
      { word: "gol", ipa: "/gol/" },
      { word: "goma", ipa: "/ˈgoma/" },
      { word: "gusto", ipa: "/ˈgusto/" },
      { word: "guerra", ipa: "/ˈgera/" },
      { word: "guitarra", ipa: "/giˈtara/" },
      { word: "grande", ipa: "/ˈgɾande/" },
      { word: "gris", ipa: "/gɾis/" },
      { word: "globo", ipa: "/ˈglobo/" },
      { word: "ganar", ipa: "/gaˈnaɾ/" },
      { word: "un gato", ipa: "/un ˈgato/" },
      { word: "un grupo", ipa: "/un ˈgɾupo/" },
      { word: "gato grande", ipa: "/ˈgato ˈgɾande/" },
      { word: "Gabi guarda guantes.", ipa: "/ˈgabi ˈgwaɾda ˈgwantes/" },
      { word: "grupo grande", ipa: "/ˈgɾupo ˈgɾande/" },
      { word: "gana Gonzalo", ipa: "/ˈgana gonˈθalo/" },
      { word: "guapo", ipa: "/ˈgwapo/" },
      { word: "guía", ipa: "/ˈgia/" },
      { word: "gorro", ipa: "/ˈgoro/" },
      { word: "galleta", ipa: "/gaˈʝeta/" },
      { word: "agua", ipa: "/ˈagwa/" },
      { word: "amigo", ipa: "/aˈmigo/" },
      { word: "lago", ipa: "/ˈlago/" },
      { word: "domingo", ipa: "/doˈmingo/" },
    ],
    difficulty: "medium",
    description:
      "这是西语 /g/ 音位的塞音位置锚点：停顿后或鼻音后舌后部短暂闭住软腭。元音间常放松为 [ɣ]，不能用 [ɣ] 音频代表所有 /g/。",
    notes: [
      "g/gu 的硬 g 属于 /g/；j/ge/gi 的 /x/ 是另一个单元。",
      "元音间 [ɣ] 继续放在 es-g 实现层训练。",
    ],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-bv",
    ipa: "/b/ -> [β]",
    name: "Spanish b/v approximant realization",
    category: "consonant",
    soundUnitType: "allophone",
    example: "vida",
    keywords: [
      { word: "vida", ipa: "/ˈbiða/" },
      { word: "vino", ipa: "/ˈbino/" },
      { word: "boca", ipa: "/ˈboka/" },
      { word: "bebé", ipa: "/beˈβe/" },
      { word: "saber", ipa: "/saˈβeɾ/" },
      { word: "uva", ipa: "/ˈuβa/" },
    ],
    difficulty: "high",
    description:
      "本单元讲 /b/ 音位在元音间的放松实现 [β]：双唇接近但不完全闭塞，也不要咬下唇读英语 /v/。停顿后/鼻音后的塞音 /b/ 在 es-b-stop 单独锚定。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-d",
    ipa: "/d/ -> [ð]",
    name: "Spanish d approximant realization",
    category: "consonant",
    soundUnitType: "allophone",
    example: "dedo",
    keywords: [
      { word: "dedo", ipa: "/ˈdeðo/" },
      { word: "día", ipa: "/ˈdia/" },
      { word: "nada", ipa: "/ˈnaða/" },
      { word: "verde", ipa: "/ˈbeɾðe/" },
      { word: "lado", ipa: "/ˈlaðo/" },
      { word: "dos", ipa: "/dos/" },
    ],
    difficulty: "high",
    description:
      "本单元讲 /d/ 音位在元音间的轻擦/近音实现 [ð]；舌尖靠近上齿背，别读成英语强爆破 /d/。停顿后、/n/ 或 /l/ 后的塞音锚点在 es-d-stop。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-g",
    ipa: "/g/ -> [ɣ]",
    name: "Spanish g approximant realization",
    category: "consonant",
    soundUnitType: "allophone",
    example: "gato",
    keywords: [
      { word: "gato", ipa: "/ˈgato/" },
      { word: "agua", ipa: "/ˈaɣwa/" },
      { word: "amigo", ipa: "/aˈmiɣo/" },
      { word: "grande", ipa: "/ˈgɾande/" },
      { word: "juego", ipa: "/ˈxweɣo/" },
      { word: "lago", ipa: "/ˈlaɣo/" },
    ],
    difficulty: "medium",
    description:
      "本单元讲 /g/ 音位在元音间放松为 [ɣ]：舌后部接近软腭但不完全堵住气流。停顿后/鼻音后的塞音 /g/ 在 es-g-stop 单独锚定。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-theta",
    ipa: "/θ/",
    name: "Castilian c/z",
    category: "consonant",
    example: "cielo",
    keywords: [
      { word: "cielo", ipa: "/ˈθjelo/" },
      { word: "zapato", ipa: "/θaˈpato/" },
      { word: "cinco", ipa: "/ˈθinko/" },
      { word: "gracias", ipa: "/ˈgɾaθjas/" },
      { word: "luz", ipa: "/luθ/" },
      { word: "azul", ipa: "/aˈθul/" },
    ],
    difficulty: "medium",
    description:
      "西班牙本土常用；舌尖轻触上下齿间送气。拉美西语常并入 /s/，后续需要做方言开关。",
    notes: ["当前按 es-ES 处理；拉美西语需要单独 profile。"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-x",
    ipa: "/x/",
    name: "voiceless velar fricative",
    category: "consonant",
    example: "jamón",
    keywords: [
      { word: "jamón", ipa: "/xaˈmon/" },
      { word: "juego", ipa: "/ˈxweɣo/" },
      { word: "rojo", ipa: "/ˈroxo/" },
      { word: "gente", ipa: "/ˈxente/" },
      { word: "José", ipa: "/xoˈse/" },
      { word: "México", ipa: "/ˈmexiko/" },
    ],
    difficulty: "high",
    description: "舌后部靠近软腭形成摩擦，像更靠后的“哈”，不要读成英语 /h/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-ny",
    ipa: "/ɲ/",
    name: "palatal nasal",
    category: "consonant",
    example: "niño",
    keywords: [
      { word: "niño", ipa: "/ˈniɲo/" },
      { word: "año", ipa: "/ˈaɲo/" },
      { word: "señor", ipa: "/seˈɲoɾ/" },
      { word: "mañana", ipa: "/maˈɲana/" },
      { word: "sueño", ipa: "/ˈsweɲo/" },
      { word: "España", ipa: "/esˈpaɲa/" },
    ],
    difficulty: "medium",
    description:
      "舌面贴近硬腭，鼻音从硬腭位置出来，不要拆成 /n/ + /j/ 两个音。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-tap-r",
    ipa: "/ɾ/",
    name: "single tap r",
    category: "consonant",
    example: "pero",
    keywords: [
      { word: "pero", ipa: "/ˈpeɾo/" },
      { word: "caro", ipa: "/ˈkaɾo/" },
      { word: "para", ipa: "/ˈpaɾa/" },
      { word: "tarde", ipa: "/ˈtaɾðe/" },
      { word: "verde", ipa: "/ˈbeɾðe/" },
      { word: "libro", ipa: "/ˈlibɾo/" },
    ],
    difficulty: "high",
    description: "舌尖快速弹一下上齿龈，只有一次接触，不要读成英语卷舌 r。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-trill-r",
    ipa: "/r/",
    name: "trilled rr",
    category: "consonant",
    example: "perro",
    keywords: [
      { word: "perro", ipa: "/ˈpero/" },
      { word: "rojo", ipa: "/ˈroxo/" },
      { word: "rápido", ipa: "/ˈrapiðo/" },
      { word: "carro", ipa: "/ˈkaro/" },
      { word: "tierra", ipa: "/ˈtjera/" },
      { word: "río", ipa: "/ˈrio/" },
    ],
    difficulty: "high",
    description:
      "舌尖在上齿龈处连续颤动；先练稳定气流和舌尖放松，再追求多次颤动。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-s",
    ipa: "/s/",
    name: "Spanish s",
    category: "consonant",
    example: "sí",
    keywords: [
      { word: "sí", ipa: "/si/" },
      { word: "sol", ipa: "/sol/" },
      { word: "casa", ipa: "/ˈkasa/" },
      { word: "mesa", ipa: "/ˈmesa/" },
      { word: "sopa", ipa: "/ˈsopa/" },
      { word: "seis", ipa: "/sejs/" },
      { word: "sábado", ipa: "/ˈsaβaðo/" },
      { word: "España", ipa: "/esˈpaɲa/" },
      { word: "saber", ipa: "/saˈβeɾ/" },
      { word: "serie", ipa: "/ˈseɾje/" },
      { word: "silla", ipa: "/ˈsiʝa/" },
      { word: "suerte", ipa: "/ˈsweɾte/" },
      { word: "salud", ipa: "/saˈluð/" },
      { word: "sueño", ipa: "/ˈsweɲo/" },
      { word: "isla", ipa: "/ˈisla/" },
      { word: "mismo", ipa: "/ˈmismo/" },
      { word: "beso", ipa: "/ˈbeso/" },
      { word: "los niños", ipa: "/los ˈniɲos/" },
      { word: "seis casas", ipa: "/sejs ˈkasas/" },
      { word: "solo sé", ipa: "/ˈsolo se/" },
    ],
    difficulty: "medium",
    description:
      "西语 /s/ 清晰、短促，当前 es-ES profile 要和 c/z 的 /θ/ 分开训练。",
    notes: [
      "拉美西语多数使用 seseo，把 c/z 也读成 /s/；这不是错误，而是不同方言目标。",
      "Castilian es-ES 初版把 /s/ 和 /θ/ 作为可对比训练。",
    ],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-ch",
    ipa: "/tʃ/",
    name: "Spanish ch",
    category: "consonant",
    example: "chico",
    keywords: [
      { word: "chico", ipa: "/ˈtʃiko/" },
      { word: "mucho", ipa: "/ˈmutʃo/" },
      { word: "leche", ipa: "/ˈletʃe/" },
      { word: "ocho", ipa: "/ˈotʃo/" },
      { word: "noche", ipa: "/ˈnotʃe/" },
      { word: "coche", ipa: "/ˈkotʃe/" },
      { word: "chocolate", ipa: "/tʃokoˈlate/" },
      { word: "derecho", ipa: "/deˈɾetʃo/" },
      { word: "escuchar", ipa: "/eskuˈtʃaɾ/" },
      { word: "cuchara", ipa: "/kuˈtʃaɾa/" },
      { word: "muchacho", ipa: "/muˈtʃatʃo/" },
      { word: "chaqueta", ipa: "/tʃaˈketa/" },
      { word: "churro", ipa: "/ˈtʃuro/" },
      { word: "hecho", ipa: "/ˈetʃo/" },
      { word: "dicho", ipa: "/ˈditʃo/" },
      { word: "fecha", ipa: "/ˈfetʃa/" },
      { word: "ancho", ipa: "/ˈantʃo/" },
      { word: "chico escucha", ipa: "/ˈtʃiko esˈkutʃa/" },
      { word: "mucha leche", ipa: "/ˈmutʃa ˈletʃe/" },
      { word: "ocho coches", ipa: "/ˈotʃo ˈkotʃes/" },
    ],
    difficulty: "medium",
    description:
      "西语 ch 是一个紧凑的 /tʃ/，不要拖成英语中过度送气或分裂的两个音。",
    notes: ["把 ch 和 j/ge/gi 的 /x/ 分开：chico /tʃ/，juego /x/。"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-y-ll",
    ipa: "/ʝ/",
    name: "y and ll yeísmo",
    category: "consonant",
    soundUnitType: "contrast",
    example: "yo",
    keywords: [
      { word: "yo", ipa: "/ʝo/" },
      { word: "ya", ipa: "/ʝa/" },
      { word: "llave", ipa: "/ˈʝaβe/" },
      { word: "calle", ipa: "/ˈkaʝe/" },
      { word: "ella", ipa: "/ˈeʝa/" },
      { word: "playa", ipa: "/ˈplaʝa/" },
      { word: "mayor", ipa: "/maˈʝoɾ/" },
      { word: "ayuda", ipa: "/aˈʝuða/" },
      { word: "lluvia", ipa: "/ˈʝuβja/" },
      { word: "llegar", ipa: "/ʝeˈɣaɾ/" },
      { word: "yema", ipa: "/ˈʝema/" },
      { word: "yeso", ipa: "/ˈʝeso/" },
      { word: "llamar", ipa: "/ʝaˈmaɾ/" },
      { word: "desayuno", ipa: "/desaˈʝuno/" },
      { word: "ensayo", ipa: "/enˈsaʝo/" },
      { word: "mayo", ipa: "/ˈmaʝo/" },
      { word: "oye", ipa: "/ˈoʝe/" },
      { word: "yo llamo", ipa: "/ʝo ˈʝamo/" },
      { word: "la llave", ipa: "/la ˈʝaβe/" },
      { word: "calle mayor", ipa: "/ˈkaʝe maˈʝoɾ/" },
    ],
    difficulty: "high",
    description:
      "现代西语许多口音中 y 和 ll 合并，常见目标是 /ʝ/ 或较弱的近音。",
    notes: [
      "yeísmo 在西班牙和拉美都很常见；少数地区仍区分 /ʎ/。",
      "当前 es-ES beta 按常见 /ʝ/ 训练，同时把地区变体写进提示，不绝对判错。",
    ],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-l",
    ipa: "/l/",
    name: "clear Spanish l",
    category: "consonant",
    example: "luna",
    keywords: [
      { word: "luna", ipa: "/ˈluna/" },
      { word: "leche", ipa: "/ˈletʃe/" },
      { word: "hola", ipa: "/ˈola/" },
      { word: "sol", ipa: "/sol/" },
      { word: "el", ipa: "/el/" },
      { word: "libro", ipa: "/ˈlibɾo/" },
      { word: "clase", ipa: "/ˈklase/" },
      { word: "plaza", ipa: "/ˈplaθa/" },
      { word: "alma", ipa: "/ˈalma/" },
      { word: "lado", ipa: "/ˈlaðo/" },
      { word: "lago", ipa: "/ˈlaɣo/" },
      { word: "lápiz", ipa: "/ˈlapiθ/" },
      { word: "familia", ipa: "/faˈmilja/" },
      { word: "color", ipa: "/koˈloɾ/" },
      { word: "abril", ipa: "/aˈβɾil/" },
      { word: "pueblo", ipa: "/ˈpweβlo/" },
      { word: "flor", ipa: "/floɾ/" },
      { word: "luna clara", ipa: "/ˈluna ˈklaɾa/" },
      { word: "el libro", ipa: "/el ˈlibɾo/" },
      { word: "la plaza", ipa: "/la ˈplaθa/" },
    ],
    difficulty: "easy",
    description:
      "西语 /l/ 通常清晰，舌尖接近上齿龈；不要像英语词尾 dark L 那样明显舌根化。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-nasal-place",
    ipa: "/m n ɲ ŋ/",
    name: "nasal place assimilation",
    category: "consonant",
    soundUnitType: "connected-speech-rule",
    example: "un gato",
    keywords: [
      { word: "un beso", ipa: "/um ˈbeso/" },
      { word: "un día", ipa: "/un ˈdia/" },
      { word: "un gato", ipa: "/uŋ ˈgato/" },
      { word: "tango", ipa: "/ˈtaŋgo/" },
      { word: "banco", ipa: "/ˈbaŋko/" },
      { word: "conmigo", ipa: "/komˈmiɣo/" },
      { word: "mundo", ipa: "/ˈmundo/" },
      { word: "niño", ipa: "/ˈniɲo/" },
      { word: "antes", ipa: "/ˈantes/" },
      { word: "campo", ipa: "/ˈkampo/" },
      { word: "cinco", ipa: "/ˈθiŋko/" },
      { word: "lengua", ipa: "/ˈleŋgwa/" },
      { word: "también", ipa: "/tamˈbjen/" },
      { word: "un pan", ipa: "/um pan/" },
      { word: "en casa", ipa: "/eŋ ˈkasa/" },
      { word: "con él", ipa: "/kon el/" },
      { word: "mi nombre", ipa: "/mi ˈnombɾe/" },
      { word: "un niño", ipa: "/un ˈniɲo/" },
      { word: "con gusto", ipa: "/koŋ ˈgusto/" },
      { word: "buen viaje", ipa: "/bwem ˈbjaxe/" },
    ],
    difficulty: "high",
    description:
      "鼻音会随下一个辅音调整位置；不要把所有 n 都固定成英语 /n/。",
    notes: ["ñ /ɲ/ 仍是单独目标音，本单元训练语流中的鼻音位置变化。"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-diphthongs-j",
    ipa: "/j/",
    name: "front glide in Spanish diphthongs",
    category: "prosody",
    soundUnitType: "prosody",
    example: "tierra",
    keywords: [
      { word: "tierra", ipa: "/ˈtjera/" },
      { word: "bien", ipa: "/bjen/" },
      { word: "gracias", ipa: "/ˈgɾaθjas/" },
      { word: "familia", ipa: "/faˈmilja/" },
      { word: "aire", ipa: "/ˈajɾe/" },
      { word: "seis", ipa: "/sejs/" },
      { word: "tiempo", ipa: "/ˈtjempo/" },
      { word: "cielo", ipa: "/ˈθjelo/" },
      { word: "ciudad", ipa: "/θjuˈðað/" },
      { word: "viaje", ipa: "/ˈbjaxe/" },
      {
        word: "Tierra y cielo son palabras con diptongos.",
        ipa: "/ˈtjera i ˈθjelo son paˈlabɾas kon dipˈtongos/",
      },
      {
        word: "Mi amigo dice que todo va bien.",
        ipa: "/mi aˈmiɣo ˈdiθe ke ˈtoðo βa βjen/",
      },
      {
        word: "La ciudad tiene cinco universidades.",
        ipa: "/la θjuˈðað ˈtjene ˈθinko uniβeɾsiˈðaðes/",
      },
      { word: "ley", ipa: "/lej/" },
      { word: "limpio", ipa: "/ˈlimpjo/" },
      { word: "familia limpia", ipa: "/faˈmilja ˈlimpja/" },
      { word: "iglesia", ipa: "/iˈɣlesja/" },
      { word: "bien dicho", ipa: "/bjen ˈditʃo/" },
      { word: "seis años", ipa: "/sejs ˈaɲos/" },
      { word: "familia grande", ipa: "/faˈmilja ˈgɾande/" },
      { word: "radio antiguo", ipa: "/ˈraðjo anˈtiɣwo/" },
    ],
    difficulty: "medium",
    description:
      "i/y 在双元音中变成短 /j/ glide；西语元音本身仍保持纯，不滑成英语长元音。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-diphthongs-w",
    ipa: "/w/",
    name: "back rounded glide in Spanish diphthongs",
    category: "prosody",
    soundUnitType: "prosody",
    example: "bueno",
    keywords: [
      { word: "bueno", ipa: "/ˈbweno/" },
      { word: "agua", ipa: "/ˈaɣwa/" },
      { word: "cuatro", ipa: "/ˈkwatɾo/" },
      { word: "fuego", ipa: "/ˈfweɣo/" },
      { word: "puerta", ipa: "/ˈpweɾta/" },
      { word: "ciudad", ipa: "/θjuˈðað/" },
      { word: "jueves", ipa: "/ˈxweβes/" },
      { word: "suerte", ipa: "/ˈsweɾte/" },
      { word: "puente", ipa: "/ˈpwente/" },
      { word: "cuenta", ipa: "/ˈkwenta/" },
      { word: "escuela", ipa: "/esˈkwela/" },
      {
        word: "Bueno, cuatro amigos juegan afuera.",
        ipa: "/ˈbweno ˈkwatɾo aˈmiɣos ˈxweɣan aˈfweɾa/",
      },
      { word: "cuatro huevos", ipa: "/ˈkwatɾo ˈweβos/" },
      { word: "cuando vuelva", ipa: "/ˈkwando ˈbwelβa/" },
      {
        word: "Buenos días, muchas gracias.",
        ipa: "/ˈbwenos ˈdias ˈmutʃas ˈgɾaθjas/",
      },
      { word: "nueve puertas", ipa: "/ˈnweβe ˈpweɾtas/" },
      { word: "cuatro puertas", ipa: "/ˈkwatɾo ˈpweɾtas/" },
      { word: "buena suerte", ipa: "/ˈbwena ˈsweɾte/" },
      { word: "agua fría", ipa: "/ˈaɣwa ˈfɾia/" },
      { word: "buen viaje", ipa: "/bwem ˈbjaxe/" },
      { word: "suelo fuerte", ipa: "/ˈswelo ˈfweɾte/" },
    ],
    difficulty: "medium",
    description:
      "u 在 ue/ua/ui 等组合里形成短 /w/ glide；保持圆唇但不要把前后元音吞掉。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-lexical-stress",
    ipa: "/ˈ/",
    name: "Spanish lexical stress",
    category: "prosody",
    soundUnitType: "prosody",
    example: "papá",
    keywords: [
      { word: "canción", ipa: "/kanˈθjon/" },
      { word: "camión", ipa: "/kaˈmjon/" },
      { word: "difícil", ipa: "/diˈfiθil/" },
      { word: "teléfono", ipa: "/teˈlefono/" },
      { word: "rápido", ipa: "/ˈrapiðo/" },
      { word: "corazón", ipa: "/koɾaˈθon/" },
      { word: "café", ipa: "/kaˈfe/" },
      { word: "jardín", ipa: "/xaɾˈðin/" },
      { word: "sábado", ipa: "/ˈsaβaðo/" },
      { word: "música", ipa: "/ˈmusika/" },
      { word: "mañana", ipa: "/maˈɲana/" },
      { word: "doctor", ipa: "/dokˈtoɾ/" },
      { word: "camino caminó", ipa: "/kaˈmino kamiˈno/" },
      { word: "hablo habló", ipa: "/ˈaβlo aˈβlo/" },
      { word: "medico médico", ipa: "/meˈðiko ˈmeðiko/" },
      { word: "numero número", ipa: "/nuˈmeɾo ˈnumeɾo/" },
      { word: "papa y papá", ipa: "/ˈpapa i paˈpa/" },
      { word: "practico practicó", ipa: "/pɾakˈtiko pɾaktiˈko/" },
      { word: "termino terminó", ipa: "/teɾˈmino teɾmiˈno/" },
      {
        word: "Papá habló con el médico.",
        ipa: "/paˈpa aˈβlo kon el ˈmeðiko/",
      },
      { word: "Buenos días", ipa: "/ˈbwenos ˈdias/" },
      { word: "La música suena bien", ipa: "/la ˈmusika ˈswena bjen/" },
      { word: "Tres palabras cortas", ipa: "/tɾes paˈlaβɾas ˈkoɾtas/" },
    ],
    difficulty: "high",
    description:
      "西语重音较有规律，但重音和重音符号会改变词义；先找重读音节再跟读。",
    notes: ["重音符号不是装饰：papa/papá、hablo/habló 都需要分开训练。"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-syllable-rhythm",
    ipa: "syllable timing",
    name: "Spanish syllable rhythm",
    category: "prosody",
    soundUnitType: "prosody",
    example: "Buenos días",
    keywords: [
      { word: "Buenos días", ipa: "/ˈbwenos ˈdias/" },
      { word: "Muchas gracias", ipa: "/ˈmutʃas ˈgɾaθjas/" },
      { word: "La casa está cerca", ipa: "/la ˈkasa esˈta ˈθeɾka/" },
      { word: "Barcelona", ipa: "/baɾθeˈlona/" },
      { word: "pa-ta-ta", ipa: "/pa ta ta/" },
      { word: "banana", ipa: "/baˈnana/" },
      { word: "minuto", ipa: "/miˈnuto/" },
      { word: "Mi amigo dice hola", ipa: "/mi aˈmiɣo ˈdiθe ˈola/" },
      { word: "La niña come pan", ipa: "/la ˈniɲa ˈkome pan/" },
      { word: "Vivo en Madrid", ipa: "/ˈbiβo en maˈðɾið/" },
      { word: "El perro corre rápido", ipa: "/el ˈpero ˈkore ˈrapiðo/" },
      { word: "Una familia grande", ipa: "/ˈuna faˈmilja ˈgɾande/" },
      { word: "Cinco zapatos azules", ipa: "/ˈθiŋko θaˈpatos aˈθules/" },
      { word: "Tengo una pregunta", ipa: "/ˈteŋgo ˈuna pɾeˈɣunta/" },
      { word: "Escucha y repite", ipa: "/esˈkutʃa i reˈpite/" },
      { word: "Cada sílaba cuenta", ipa: "/ˈkaða ˈsilaβa ˈkwenta/" },
      { word: "No comas deprisa", ipa: "/no ˈkomas deˈpɾisa/" },
      { word: "Habla claro y lento", ipa: "/ˈaβla ˈklaɾo i ˈlento/" },
      { word: "Ritmo de sílabas", ipa: "/ˈritmo de ˈsilaβas/" },
      { word: "Buenos días a todos", ipa: "/ˈbwenos ˈdias a ˈtoðos/" },
    ],
    difficulty: "medium",
    description:
      "西语节奏更接近逐音节推进；不要像英语那样强烈弱读、吞音或把非重读音节压得太短。",
  }),
];
